force-app/main/default/objects/X7S_File_Folder__c/X7S_File_Folder__c.object-meta.xml
<CustomObject>
    <description>Object to support 7S File Folder records as part of the File Folder accelerator from 7Summits.</description>
    <label>7S File Folder</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>7S File Folders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/X7S_File_Folder__c/fields/Parent_Folder__c.field-meta.xml
<CustomField>
    <fullName>Parent_Folder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent folder, null if root folder</description>
    <inlineHelpText>Parent folder, null if root folder</inlineHelpText>
    <label>Parent Folder</label>
    <referenceTo>X7S_File_Folder__c</referenceTo>
    <relationshipLabel>7S File Folders</relationshipLabel>
    <relationshipName>X7S_File_Folders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/X7S_File_Folder__c/fields/Sharing_Setting__c.field-meta.xml
<CustomField>
    <fullName>Sharing_Setting__c</fullName>
    <inlineHelpText>Sharing setting record ID</inlineHelpText>
    <label>Sharing Setting</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/X7S_Files_Icon__mdt/X7S_Files_Icon__mdt.object-meta.xml
<CustomObject>
    <description>Icons  for 7S Files accelerator from 7Summits.</description>
    <label>7S Files Icon</label>
    <pluralLabel>7S Files Icons</pluralLabel>
</CustomObject>

force-app/main/default/objects/X7S_Files_Icon__mdt/fields/File_Type__c.field-meta.xml
<CustomField>
    <fullName>File_Type__c</fullName>
    <description>File type</description>
    <inlineHelpText>File type</inlineHelpText>
    <label>File Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/X7S_Files_Icon__mdt/fields/Icon_Name__c.field-meta.xml
<CustomField>
    <fullName>Icon_Name__c</fullName>
    <description>Enter an SLDS icon using the &quot;type:icon&quot; format (for example, doctype:xml), or enter an image URL.</description>
    <inlineHelpText>Enter an SLDS icon using the &quot;type:icon&quot; format (for example, doctype:xml), or enter an image URL.</inlineHelpText>
    <label>Icon</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/X7S_Files_Icon_Set__mdt/X7S_Files_Icon_Set__mdt.object-meta.xml
<CustomObject>
    <description>Icon set for 7S Files accelerator from 7Summits.</description>
    <label>7S Files Icon Set</label>
    <pluralLabel>7S Files Icon Sets</pluralLabel>
</CustomObject>

force-app/main/default/objects/X7S_Files_Icon_Set__mdt/fields/Show_Preview__c.field-meta.xml
<CustomField>
    <fullName>Show_Preview__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If enabled and the file type is supported, a thumbnail preview is displayed in place of the icon. If no preview is available, an icon is displayed.</description>
    <inlineHelpText>If enabled and the file type is supported, a thumbnail preview is displayed in place of the icon. If no preview is available, an icon is displayed.</inlineHelpText>
    <label>Show Preview</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/X7S_Files_Icon_Set_Assignment__mdt/X7S_Files_Icon_Set_Assignment__mdt.object-meta.xml
<CustomObject>
    <description>Icon set assignment for 7S Files accelerator from 7Summits.</description>
    <label>7S Files Icon Set Assignment</label>
    <pluralLabel>7S Files Icon Set Assignments</pluralLabel>
</CustomObject>

force-app/main/default/objects/X7S_Files_Icon_Set_Assignment__mdt/fields/X7S_Files_Icon__c.field-meta.xml
<CustomField>
    <fullName>X7S_Files_Icon__c</fullName>
    <description>Related file icon</description>
    <inlineHelpText>Related file icon</inlineHelpText>
    <label>7S Files Icon</label>
    <referenceTo>X7S_Files_Icon__mdt</referenceTo>
    <relationshipLabel>7S Files Icon Set Assignments</relationshipLabel>
    <relationshipName>X7S_Files_Icon_Set_Assignments</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/X7S_Files_Icon_Set_Assignment__mdt/fields/X7S_Files_Icon_Set__c.field-meta.xml
<CustomField>
    <fullName>X7S_Files_Icon_Set__c</fullName>
    <description>Related file icon set</description>
    <inlineHelpText>Related file icon set</inlineHelpText>
    <label>7S Files Icon Set</label>
    <referenceTo>X7S_Files_Icon_Set__mdt</referenceTo>
    <relationshipLabel>7S Files Icon Set Assignments</relationshipLabel>
    <relationshipName>X7S_Files_Icon_Set_Assignments</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/X7S_Files_Setting__mdt/X7S_Files_Setting__mdt.object-meta.xml
<CustomObject>
    <description>General settings for 7S Files accelerator from 7Summits.</description>
    <label>7S Files Setting</label>
    <pluralLabel>7S Files Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/X7S_Files_Setting__mdt/fields/X7S_Files_Icon_Set__c.field-meta.xml
<CustomField>
    <fullName>X7S_Files_Icon_Set__c</fullName>
    <description>Icon Set</description>
    <inlineHelpText>Icon Set</inlineHelpText>
    <label>7S Files Icon Set</label>
    <referenceTo>X7S_Files_Icon_Set__mdt</referenceTo>
    <relationshipLabel>7S Files Settings</relationshipLabel>
    <relationshipName>X7S_Files_Settings</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/classes/x7sFilesItemModel.cls
/*
 * Copyright (c) 2021. 7Summits, an IBM Company. All rights reserved.
 */

public with sharing class x7sFilesItemModel {

    @AuraEnabled
    public String Id { get; set; }

    @AuraEnabled
    public String Title { get; set; }

    @AuraEnabled
    public String ContentModifiedById { get; set; }

    @AuraEnabled
    public Datetime ContentModifiedDate { get; set; }

    @AuraEnabled
    public Integer ContentSize { get; set; }

    @AuraEnabled
    public String Description { get; set; }

    @AuraEnabled
    public String FileExtension { get; set; }

    @AuraEnabled
    public String FileType { get; set; }

    @AuraEnabled
    public Datetime LastReferencedDate { get; set; }

    @AuraEnabled
    public Datetime LastViewedDate { get; set; }

    @AuraEnabled
    public String LinkedEntityId { get; set; }

    @AuraEnabled
    public Datetime CreatedDate { get; set; }

    @AuraEnabled
    public String VersionId { get; set; }

    @AuraEnabled
    public String ImageUrl { get; set; }

    @AuraEnabled
    public Boolean IsFolder { get; set; }

    @AuraEnabled
    public String ParentId { get; set; }

    @AuraEnabled
    public List<String> breadcrumbs { get; set; }

    @AuraEnabled
	public x7sFilesIconListModel iconSetSetting { get; set; }

    public x7sFilesItemModel(ContentDocumentLink docLink) {
        this.Id = docLink.ContentDocument.Id;
        this.Title = docLink.ContentDocument.Title;
        this.ContentModifiedById = docLink.ContentDocument.LastModifiedById;
        this.ContentModifiedDate = docLink.ContentDocument.ContentModifiedDate;
        this.ContentSize = docLink.ContentDocument.ContentSize;
        this.Description = docLink.ContentDocument.Description;
        this.FileExtension = docLink.ContentDocument.FileExtension;
        this.FileType = docLink.ContentDocument.FileType;
        this.LastReferencedDate = docLink.ContentDocument.LastReferencedDate;
        this.LastViewedDate = docLink.ContentDocument.LastViewedDate;
        this.CreatedDate = docLink.ContentDocument.CreatedDate;
        this.VersionId = docLink.ContentDocument.LatestPublishedVersionId;
        this.LinkedEntityId = docLink.LinkedEntityId;
        this.IsFolder = false;
        this.iconSetSetting = getIconSettingForFiles(docLink.LinkedEntityId);
    }

    public x7sFilesItemModel(X7S_File_Folder__c record, String communityUrl, Id imageId, List<String> breadcrumbs) {
        this.Id = record.Id;
        this.Title = (String) record.get('Name');
        this.Description = (String) record.get('Description__c');
        this.LinkedEntityId = (String) record.get('Parent_Folder__c');
        this.IsFolder = true;
        this.breadcrumbs = breadcrumbs;
        this.ParentId = record.Parent_Folder__c;
        this.CreatedDate = record.CreatedDate;
        if (imageId != null && String.isNotBlank(communityUrl)) {
            this.ImageUrl = communityUrl + x7sFilesContentDocument.FILE_LOCATION + imageId;
        }
    }

	@TestVisible
	private static x7sFilesIconListModel getIconSettingForFiles(Id Id) {
		X7S_File_Folder__c IconSetId = [SELECT Sharing_Setting__c FROM X7S_File_Folder__c WHERE Id = :Id WITH SECURITY_ENFORCED LIMIT 1];
		X7S_Files_Setting__mdt settings = X7S_Files_Setting__mdt.getInstance((String) IconSetId.get('Sharing_Setting__c'));

		if (settings != null && settings.X7S_Files_Icon_Set__c != null) {
			x7sFilesIconListModel settingModel = getIconListModel(settings);
			return settingModel;
		}
		return null;
	}

    // Icon List
	@TestVisible
	private static x7sFilesIconListModel getIconListModel(X7S_Files_Setting__mdt settings) {

		if (settings != null) {
			try {
				x7sFilesIconListModel iconListModel = new x7sFilesIconListModel();
				List<X7S_Files_Icon_Set_Assignment__mdt> iconSetAssignment = X7S_Files_Icon_Set_Assignment__mdt.getAll().values();

				for (X7S_Files_Icon_Set_Assignment__mdt iconItem : iconSetAssignment) {
					if (iconItem.X7S_Files_Icon_Set__c == settings.X7S_Files_Icon_Set__c) {
						if (iconSetAssignment.size() > 0) {
							List<X7S_Files_Icon_Set__mdt> iconSet = X7S_Files_Icon_Set__mdt.getAll().values();
							for (X7S_Files_Icon_Set__mdt icon : iconSet) {
								if (icon.Id == iconItem.X7S_Files_Icon_Set__c) {
									X7S_Files_Icon__mdt iconField = X7S_Files_Icon__mdt.getInstance(iconItem.X7S_Files_Icon__c);
									if (iconField.Icon_Name__c != null && iconField != null) {
										iconListModel.fileIconList.add(getIconModel(iconField,icon.Show_Preview__c));
									}
								}
							}
						}
					}
				}
				return iconListModel;
			}
			catch (QueryException ex) {
				System.debug('Error occurred getting Icon set assignment: ' + ex.getMessage());
			}
		}
		return null;
	}

    private static x7sFilesIconModel getIconModel(X7S_Files_Icon__mdt iconField, Boolean showPreview) {
		x7sFilesIconModel model = new x7sFilesIconModel();
		if (iconField.Icon_Name__c != null) {
			model.fileType = (String) iconField.File_Type__c;
			model.iconName = (String) iconField.Icon_Name__c;
			model.showPreview = showPreview;
		}
		return model;
	}

}