force-app/main/default/objects/X7S_File_Folder__c/X7S_File_Folder__c.object-meta.xml
<CustomObject>
    <description>Object to support 7S File Folder records as part of the File Folder accelerator from 7Summits.</description>
    <label>7S File Folder</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>7S File Folders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/X7S_File_Folder__c/fields/Sharing_Setting__c.field-meta.xml
<CustomField>
    <fullName>Sharing_Setting__c</fullName>
    <inlineHelpText>Sharing setting record ID</inlineHelpText>
    <label>Sharing Setting</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/x7sFilesShareBatch.cls
/*
 * Copyright (c) 2021. 7Summits, an IBM Company. All rights reserved.
 */

/*
 * To run this in the dev console anonymous window, enter:
 *  Id batchJobId = Database.executeBatch(new x7sFilesShareBatch(), 20);
 *  System.debug('batch job Id: ' + batchJobId);
 * (enable 'open log' to see the output)
 */
@SuppressWarnings('PMD.ApexSharingViolations, PMD.ApexCRUDViolation')
global class x7sFilesShareBatch implements Database.Batchable<SObject>, Database.Stateful {
	global String queryString { get; set; }
	global Integer Count { get; set; }

	global x7sFilesShareBatch() {
		queryString = 'SELECT Id, Name, Sharing_Setting__c FROM X7S_File_Folder__c';
		Count = 0;
	}

	global Database.QueryLocator start(Database.BatchableContext bc) {
		System.debug('start - Batch query: ' + queryString);
		return Database.getQueryLocator(queryString);
	}

	global void execute(Database.BatchableContext bc, List<SObject> scope) {
		List<X7S_File_Folder__c> folderList = (List<X7S_File_Folder__c>) scope;
		System.debug('execute - folders : ' + folderList.size());
		for (X7S_File_Folder__c folder : folderList) {
			x7sFilesShareController.applyFolderShare(folder); Count += 1;
		}
	}

	global void finish(Database.BatchableContext bc) {
		System.debug('finish - Folders processed: ' + Count);
	}
}