force-app/main/default/objects/X7S_Adventure_Step__c/X7S_Adventure_Step__c.object-meta.xml
<CustomObject>
    <description>Object to support Learning Adventure Step records as part of the Learning Adventure accelerator from 7Summits.</description>
    <label>7S Adventure Step</label>
    <nameField>
        <label>7S Adventure Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>7S Adventure Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/X7S_Adventure_Step__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>This is the description of the Adventure Step that will be displayed under the Subtitle</description>
    <inlineHelpText>This is the description of the Adventure Step that will be displayed under the Subtitle</inlineHelpText>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Step__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>The order in which the adventure steps should be displayed</description>
    <label>Order</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Step__c/fields/Subtitle__c.field-meta.xml
<CustomField>
    <fullName>Subtitle__c</fullName>
    <description>Subtitle of the Adventure Step which will be displayed in the header</description>
    <inlineHelpText>This is the subtitle of the Adventure Step which will be displayed in the header</inlineHelpText>
    <label>Subtitle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Task__c/X7S_Adventure_Task__c.object-meta.xml
<CustomObject>
    <description>Object to support Learning Adventure Task records as part of the Learning Adventure accelerator from 7Summits.</description>
    <label>7S Adventure Task</label>
    <nameField>
        <label>7S Adventure Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>7S Adventure Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/X7S_Adventure_Task__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>The order in which to display the Module Task</description>
    <label>Order</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Task__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>X7S_Adventure_Module_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Task__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>The title of this Module Task to be displayed next to icon</description>
    <inlineHelpText>The title of this Module Task to be displayed next to icon</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/x7sAdventureStepWrapperHelper.cls
/*
 * Copyright (c) 2020. 7Summits Inc.
 */

public with sharing class x7sAdventureStepWrapperHelper {

    public static x7sAdventureStepWrapper createWrapper(X7S_Adventure_Step__c theStep, List<x7sAdventureStepModuleWrapper> theStepModuleList, String currentUserId) {

        x7sAdventureStepWrapper stepWrapper = new x7sAdventureStepWrapper();

        stepWrapper.id = theStep.Id;
        stepWrapper.stepName = theStep.Title__c;
        stepWrapper.title = theStep.Title__c;
        stepWrapper.subtitle = theStep.Subtitle__c;
        stepWrapper.description = theStep.Description__c;

        stepWrapper.order = theStep.Order__c;
        stepWrapper.contentDocumentLinks = theStep.ContentDocumentLinks;
        stepWrapper.moduleProgress = theStep.Module_Progress__c;
        stepWrapper.taskProgress = theStep.Task_Progress__c;
        stepWrapper.stepModuleWrapperList = theStepModuleList;
        stepWrapper.userRemainingTaskCount = calculateRemainingTasksForUser(theStepModuleList, currentUserId);

        return stepWrapper;
    }

    /**
     * Iterates through all tasks of each module and calculates total remaining for the current user.
     *
     * @return number of remaining steps for user.
     */
    private static Integer calculateRemainingTasksForUser(List<x7sAdventureStepModuleWrapper> theStepModuleList, String currentUserId) {
        Integer remainingStepTasksForUser = 0;

        if (theStepModuleList != null) {
            for (x7sAdventureStepModuleWrapper eachModule : theStepModuleList) {
                if (eachModule.moduleTasks != null) {
                    for (X7S_Adventure_Task__c eachTask : eachModule.moduleTasks) {
                        Integer totalModuleTasksForUser = 0;
                        Integer completedModuleTasksForUser = 0;
                        Integer remainingModuleTasksForUser = 0;

                        if (eachTask.Owner__c == currentUserId) {
                            totalModuleTasksForUser += 1;

                            if (eachTask.Completed__c) completedModuleTasksForUser += 1;
                            remainingModuleTasksForUser = totalModuleTasksForUser - completedModuleTasksForUser;
                        }

                        remainingStepTasksForUser += remainingModuleTasksForUser;
                    }
                }
            }
        }

        return remainingStepTasksForUser;
    }
}