force-app/main/default/objects/X7S_Files_Global__mdt/X7S_Files_Global__mdt.object-meta.xml
<CustomObject>
    <description>7S Files global settings.</description>
    <label>7S Files Global</label>
    <pluralLabel>7S Files Global</pluralLabel>
</CustomObject>

force-app/main/default/objects/X7S_Files_Global__mdt/fields/Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Batch_Size__c</fullName>
    <defaultValue>20</defaultValue>
    <description>Share process batch size (1 - 200)</description>
    <inlineHelpText>Controls the number of folders that will be processed at one time. The default batch size of 20 will handle most scenarios. If you run into SOQL limit errors on the Sharing batch job, this number will need to be lowered.
            For more details, including a formula that can be used to calculate recommended batch size; please consult the Setup Guide.</inlineHelpText>
    <label>Batch Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/x7sFilesShareBatchSchedule.cls
/*
 * Copyright (c) 2021. 7Summits, an IBM Company. All rights reserved.
 */

/**
 * This class will call the batch process to apply the share settings.
 *
 * In order to avoid hitting the SF SOQL Limit, apply the following to determine the optimal batch size.
 * Find the criteria set with the most criteria assignments.
 * Add 2 for process overhead.
 * Set SHARE_BATCH_SIZE to (200 / (max_criteria + 1)) - 1
 *
 * ex: Max criteria = 5.
 * Use 200 / 7 (rounded down to the nearest Integer), subtract 1
 * set SHARE_BATCH_SIZE = 27
 * (I would round down to 20 for a little more head room)
 */
@SuppressWarnings('PMD.ApexSharingViolations, PMD.ApexCRUDViolation')
global class x7sFilesShareBatchSchedule implements Schedulable {
	private final String DEFAULT_SETTING = 'Default';
	private final Integer SHARE_BATCH_SIZE = 20;

	global void execute(SchedulableContext sc) {
		X7S_Files_Global__mdt setting = X7S_Files_Global__mdt.getInstance(DEFAULT_SETTING);
		Integer batchSize = setting != null && setting.Batch_Size__c != null ? Integer.valueOf(setting.Batch_Size__c) : SHARE_BATCH_SIZE;

		x7sFilesShareBatch sharingBatch = new x7sFilesShareBatch();
		Database.executeBatch(sharingBatch, batchSize);
	}
}