force-app/main/default/objects/SS_Community__c/SS_Community__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is a list of settings used in the Community implementation.</description>
    <label>7Summits Community</label>
</CustomObject>

force-app/main/default/objects/SS_Community__c/fields/Community_Name__c.field-meta.xml
<CustomField>
    <fullName>Community_Name__c</fullName>
    <defaultValue>&quot;A Customer Zone&quot;</defaultValue>
    <description>This should match the label of the Community</description>
    <label>Community Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SS_Community__c/fields/Community_Profile_Name__c.field-meta.xml
<CustomField>
    <fullName>Community_Profile_Name__c</fullName>
    <defaultValue>&quot;Customer Community Login User&quot;</defaultValue>
    <description>Label of the Profile assigned to Community Users</description>
    <label>Community Profile Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SS_Community__c/fields/Default_Community_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Default_Community_Account_Name__c</fullName>
    <defaultValue>&quot;Test Community Customer 01&quot;</defaultValue>
    <description>Name of the Account to assign new Community users to</description>
    <label>Default Community Account Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SS_Community__c/fields/Show_Group_List__c.field-meta.xml
<CustomField>
    <fullName>Show_Group_List__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If the User belongs to an account without a Group associated, whether to show the Chatter Group List or an error page.</description>
    <label>Show Group List</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SS_Community__c/fields/Unauthenticated_Community_Profile_Name__c.field-meta.xml
<CustomField>
    <fullName>Unauthenticated_Community_Profile_Name__c</fullName>
    <defaultValue>&quot;7Summits Customer Community Profile&quot;</defaultValue>
    <description>Label of the Profile assigned to unauthenticated community guest user</description>
    <label>Unauthenticated Community Profile Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SS_Community__c/fields/Username_Suffix__c.field-meta.xml
<CustomField>
    <fullName>Username_Suffix__c</fullName>
    <defaultValue>&quot;@7SummitsCommunity.com&quot;</defaultValue>
    <description>Suffix assigned to create usernames. Ex. @7SummitsCommunity.com</description>
    <label>Username Suffix</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SS_CommunitySiteConstants.cls
public without sharing class SS_CommunitySiteConstants {
    // Constants 

	public static String CUSTOM_LOGIN_PAGE_NAME = 'Login';
    private static String SETTING_NAME = '7Summits Community';

    /*
    private static RecordType PERSON_RECORD_TYPE;
    public static RecordType getPersonRecordType() {
        if (PERSON_RECORD_TYPE == null) {
            PERSON_RECORD_TYPE = [SELECT Id FROM RecordType WHERE sObjectType = 'Account' AND IsPersonType = true AND IsActive = true];
        }
        return PERSON_RECORD_TYPE;
    }
    */

    private static Boolean SHOW_GROUP_LIST;
    public static Boolean getShowGroupList() {
        if (SHOW_GROUP_LIST == null) {
            SHOW_GROUP_LIST = getSetting().Show_Group_List__c;
        }
        return SHOW_GROUP_LIST;
    } 

	private static String COMMUNITY_NAME;
    public static String getCommunityName() {
        if (COMMUNITY_NAME == null) {
            COMMUNITY_NAME = getSetting().Community_Name__c;
        }
        return COMMUNITY_NAME;
    } 

    private static String COMMUNITY_ID;
    public static String getCommunityId() {
        try
        {
            if (COMMUNITY_ID == null) {
                COMMUNITY_ID = [SELECT Id FROM Community WHERE Name =: getCommunityName()][0].Id;
            }
        } catch (Exception e) {
            System.debug('Community does not exist named ' + getCommunityName());
        }
        return COMMUNITY_ID;
    }

    private static String COMMUNITY_PROFILE_NAME; // 'Customer Community Login User';
    public static String getCommunityProfileName() {
        if (COMMUNITY_PROFILE_NAME == null) {
            COMMUNITY_PROFILE_NAME = getSetting().Community_Profile_Name__c;
        }
        return COMMUNITY_PROFILE_NAME;
    } 

    private static String UNAUTHENTICATED_COMMUNITY_PROFILE_NAME; // '7Summits Customer Community Profile';
    public static String getUnauthenticatedCommunityProfileName() {
        if (UNAUTHENTICATED_COMMUNITY_PROFILE_NAME == null) {
            UNAUTHENTICATED_COMMUNITY_PROFILE_NAME = getSetting().Unauthenticated_Community_Profile_Name__c;
        }
        return UNAUTHENTICATED_COMMUNITY_PROFILE_NAME;
    } 

    private static String USERNAME_SUFFIX; //'@7SummitsCommunity.com';
    public static String getUsernameSuffix() {
        if (USERNAME_SUFFIX == null) {
            USERNAME_SUFFIX = getSetting().Username_Suffix__c;
        }
        return USERNAME_SUFFIX;
    } 

    private static String COMMUNITY_ACCOUNT_NAME;
    public static String getDefaultCommunityAccountName() {
        if (COMMUNITY_ACCOUNT_NAME == null) {
            COMMUNITY_ACCOUNT_NAME = getSetting().Default_Community_Account_Name__c;
        }
        return COMMUNITY_ACCOUNT_NAME;
    } 

    private static String COMMUNITY_ACCOUNT_ID;
    public static String getCommunityAccountId() {
        try
        {
            if (COMMUNITY_ACCOUNT_ID == null) {
                COMMUNITY_ACCOUNT_ID = [SELECT Id FROM Account WHERE Name =: getDefaultCommunityAccountName()].Id;
            }
        } catch (Exception e) {
            System.debug('Account does not exist named ' + getDefaultCommunityAccountName());
        }
        return COMMUNITY_ACCOUNT_ID;
    }

    private static SS_Community__c getSetting() {
        SS_Community__c setting = SS_Community__c.getValues(SETTING_NAME);
        if (setting == null) {
            // initialize a setting for test
            setting = new SS_Community__c();
            setting.Community_Name__c = 'A Customer Zone';
            setting.Community_Profile_Name__c = 'Customer Community Login User';
            setting.Username_Suffix__c = '@7SummitsCommunity.com';
            setting.Unauthenticated_Community_Profile_Name__c = '7Summits Customer Community Profile';
            setting.Default_Community_Account_Name__c = 'Test Community Customer 01';
        }
        return setting;
    }

    public static String USER_PROFILE_URL = '/_ui/core/userprofile/UserProfilePage?tab=sfdc.ProfilePlatformFeed';
    public static String GROUP_LIST_URL = '/_ui/core/chatter/groups/GroupListPage';
    public static String GROUP_PROFILE_URL = '/_ui/core/chatter/groups/GroupProfilePage?g=';
}