force-app/main/default/objects/Idea/fields/Idea_Extension_Status__c.field-meta.xml
<CustomField>
    <fullName>Idea_Extension_Status__c</fullName>
    <description>7S Ideas Extension status</description>
    <label>Idea Extension Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Linked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Idea/fields/Status_Comment__c.field-meta.xml
<CustomField>
    <fullName>Status_Comment__c</fullName>
    <description>This field add comments on status change.</description>
    <label>Status Comment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Idea/fields/Status_Summary__c.field-meta.xml
<CustomField>
    <fullName>Status_Summary__c</fullName>
    <description>7S Ideas status summary</description>
    <label>Status Summary</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Idea/fields/X7S_Ideas_Extension__c.field-meta.xml
<CustomField>
    <fullName>X7S_Ideas_Extension__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>7S Ideas related extension object</description>
    <label>7S Ideas Extension</label>
    <referenceTo>X7S_Ideas_Extension__c</referenceTo>
    <relationshipLabel>Ideas</relationshipLabel>
    <relationshipName>Ideas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/X7S_Ideas_Extension__c/X7S_Ideas_Extension__c.object-meta.xml
<CustomObject>
    <description>Object created to extend the standard ideas object. This will essentially have a 1:1 relationship with an Idea.</description>
    <label>7S Idea Extension</label>
    <nameField>
        <label>7S Idea Extension</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>7S Idea Extensions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/X7S_Ideas_Extension__c/fields/Idea__c.field-meta.xml
<CustomField>
    <fullName>Idea__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Idea</label>
    <referenceTo>Idea</referenceTo>
    <relationshipLabel>7S Idea Extensions</relationshipLabel>
    <relationshipName>X7S_Idea_Extensions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/X7S_Ideas_Setting__mdt/fields/Enable_Idea_Extension_Functionality__c.field-meta.xml
<CustomField>
    <fullName>Enable_Idea_Extension_Functionality__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable Idea Extension Functionality</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/x7sIdeasTriggerHelper.cls
/*
 * Copyright (c) 2020. 7Summits Inc.
 */

public with sharing class x7sIdeasTriggerHelper {
	public static void addStatusCommentOnStatusUpdate(List<Idea> listOfIdeas, Map<Id, Idea> oldMapOfIdea) {
		List<x7sIdeasCommentsWrapper.CommentsModel> listOfSummaryWrapper;

		for (Idea ideaUpdate : listOfIdeas) {
			System.debug('Idea trigger - Status check: [' + ideaUpdate.Status + '], [' + oldMapOfIdea.get(ideaUpdate.Id).Status + ']');
			//System.debug('Status comment: [' + ideaUpdate.Status_Comment__c + '] length = ' + ideaUpdate.Status_Comment__c.length());

			if (ideaUpdate.Status != oldMapOfIdea.get(ideaUpdate.Id).Status) {
				if (!String.isEmpty(ideaUpdate.Status_Comment__c)) {
					String statusSummary = (oldMapOfIdea.get(ideaUpdate.Id).Status_Summary__c != null) ? oldMapOfIdea.get(ideaUpdate.Id).Status_Summary__c : '' ;

					if (statusSummary != null && statusSummary != '') {
						listOfSummaryWrapper = (List<x7sIdeasCommentsWrapper.CommentsModel>) JSON.deserialize(statusSummary, List<x7sIdeasCommentsWrapper.CommentsModel>.class);
					}
					else {
						listOfSummaryWrapper = new List<x7sIdeasCommentsWrapper.CommentsModel>();
					}

					x7sIdeasCommentsWrapper.CommentsModel commentsWrapper = new x7sIdeasCommentsWrapper.CommentsModel();

					commentsWrapper.newStatus = ideaUpdate.Status;
					commentsWrapper.changedBy = UserInfo.getFirstName() + ' ' + UserInfo.getLastName();
					commentsWrapper.changedById = UserInfo.getUserId();
					commentsWrapper.changedDate = Date.today();
					commentsWrapper.commentText = ideaUpdate.Status_Comment__c;

					if (listOfSummaryWrapper.size() > 0) {
						listOfSummaryWrapper.add(0, commentsWrapper);
					}
					else {
						listOfSummaryWrapper.add(commentsWrapper);
					}

					ideaUpdate.Status_Summary__c = JSON.serialize(listOfSummaryWrapper);
				}
			}
		}
	}

	public static void createIdeaExtensionRecord(List<Idea> listOfIdeas) {
		if (ideaExtensionEnabled()) {
			List<X7S_Ideas_Extension__c> listOExtensions = new List<X7S_Ideas_Extension__c>();

			List<Id> listOfIdeasIds = new List<Id>();
			List<Id> listOfExtensionIds = new List<Id>();

			//Create Idea Extension
			for (Idea idea : listOfIdeas) {
				if (String.isEmpty(idea.X7S_Ideas_Extension__c)) {
					String extName = idea.Title;

					if (extName.length() > 80) {
						extName = extName.substring(0, 79);
						extName += '…';
					}

					X7S_Ideas_Extension__c ideaExtension = new X7S_Ideas_Extension__c(Idea__c = idea.Id, Name = extName);
					listOExtensions.add(ideaExtension);
					listOfIdeasIds.add(idea.Id);
				}
			}

			try {
				if (!listOExtensions.isEmpty() && X7S_Ideas_Extension__c.SObjectType.getDescribe().isCreateable() ) {
					insert listOExtensions;
				}
			}
			catch (Exception ex) {
				System.debug('ERROR createIdeaExtensionRecord ');
			}

			if (!listOExtensions.isEmpty()) {
				for (X7S_Ideas_Extension__c ids : listOExtensions) {
					listOfExtensionIds.add(ids.Id);
				}
			}

			System.debug('listOfExtensionIds: ' + listOfExtensionIds);
			System.debug('listOExtensions: ' + listOExtensions);

			if (!listOfIdeasIds.isEmpty() && !listOfExtensionIds.isEmpty()) {
				updateIdeaRecord(listOfIdeasIds, listOfExtensionIds);
			}
		}
	}

	public static void updateIdeaRecord(List<Id> listOfIdeasIds, List<Id> listOfExtensionIds) {
		List<Idea> updateIdeaList = new List<Idea>();

		//Update Idea with Extension Id
		if (Schema.SObjectType.Idea.isUpdateable() &&
			Schema.SObjectType.Idea.fields.X7S_Ideas_Extension__c.isUpdateable() &&
			Schema.SObjectType.Idea.fields.Idea_Extension_Status__c.isUpdateable()) {
			for (Idea idea : [SELECT Id,Idea_Extension_Status__c,X7S_Ideas_Extension__c FROM Idea WHERE Id IN :listOfIdeasIds]) {
				for (X7S_Ideas_Extension__c extension : [SELECT Id,Idea__c FROM X7S_Ideas_Extension__c WHERE Id IN :listOfExtensionIds]) {
					if (idea.Id == extension.Idea__c) {
						idea.X7S_Ideas_Extension__c = extension.Id;
						idea.Idea_Extension_Status__c = 'Linked';

						updateIdeaList.add(idea);
					}
				}
			}
		}
		try {
			if (!updateIdeaList.isEmpty() && Idea.SObjectType.getDescribe().isUpdateable()) {
				update updateIdeaList;
			}
		}
		catch (Exception ex) {
			System.debug('ERROR x7sIdeasTriggerHelper.updateIdeaRecord : ' + ex.getMessage());
		}
	}

	public static void createExtensionWhenStatusPending(List<Idea> listOfIdeas) {
		if (ideaExtensionEnabled()) {
			List<Idea> listOfIdeasToUpdate = new List<Idea>();

			for (Idea idea : listOfIdeas) {
				if (idea.Idea_Extension_Status__c != null && idea.Idea_Extension_Status__c == 'Pending') {
					listOfIdeasToUpdate.add(idea);
				}
			}

			if (!listOfIdeasToUpdate.isEmpty()) {
				createIdeaExtensionRecord(listOfIdeasToUpdate);
			}
		}
	}

	private static Boolean ideaExtensionEnabled() {
		String metadataQuery = 'SELECT Id, DeveloperName, Enable_Idea_Extension_Functionality__c FROM X7S_Ideas_Setting__mdt';
		metadataQuery += ' WHERE DeveloperName = \'Default\' LIMIT 1';

		List<X7S_Ideas_Setting__mdt> ideasSettings = (List<X7S_Ideas_Setting__mdt>) Database.query(metadataQuery);

		return
			(!ideasSettings.isEmpty()) &&
				(ideasSettings[0].Enable_Idea_Extension_Functionality__c);
	}
}