force-app/main/default/objects/Idea/fields/Related_Topic_Name__c.field-meta.xml
<CustomField>
    <fullName>Related_Topic_Name__c</fullName>
    <description>7S Ideas related topic name</description>
    <label>Related Topic Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Idea/fields/X7S_Ideas_Extension__c.field-meta.xml
<CustomField>
    <fullName>X7S_Ideas_Extension__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>7S Ideas related extension object</description>
    <label>7S Ideas Extension</label>
    <referenceTo>X7S_Ideas_Extension__c</referenceTo>
    <relationshipLabel>Ideas</relationshipLabel>
    <relationshipName>Ideas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/X7S_Ideas_Extension__c/X7S_Ideas_Extension__c.object-meta.xml
<CustomObject>
    <description>Object created to extend the standard ideas object. This will essentially have a 1:1 relationship with an Idea.</description>
    <label>7S Idea Extension</label>
    <nameField>
        <label>7S Idea Extension</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>7S Idea Extensions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/X7S_Ideas_Extension__c/fields/Idea__c.field-meta.xml
<CustomField>
    <fullName>Idea__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Idea</label>
    <referenceTo>Idea</referenceTo>
    <relationshipLabel>7S Idea Extensions</relationshipLabel>
    <relationshipName>X7S_Idea_Extensions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/X7S_Ideas_Setting__mdt/fields/Enable_Idea_Extension_Functionality__c.field-meta.xml
<CustomField>
    <fullName>Enable_Idea_Extension_Functionality__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable Idea Extension Functionality</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/x7sIdeasTriggerHelperTest.cls
/*
 * Copyright (c) 2020. 7Summits Inc.
 */

@IsTest
public with sharing class x7sIdeasTriggerHelperTest {

	private static final String TEST_IDEA_NAME = 'test_dev_01';


	@IsTest
	static void testCreateIdeaExtensionRecord() {
		List<Idea> ideasToInsert = new List<Idea>();

		String metadataQuery = 'SELECT Id, DeveloperName, MasterLabel,Enable_Idea_Extension_Functionality__c FROM X7S_Ideas_Setting__mdt';
		metadataQuery = metadataQuery + ' WHERE DeveloperName = \'Default\'';
		List<X7S_Ideas_Setting__mdt> listOfIdeaSettings = (List<X7S_Ideas_Setting__mdt>) Database.query(metadataQuery);

		List<Community> community = [SELECT Id FROM Community LIMIT 1];
		if (!community.isEmpty()) {

			Idea currIdea = new Idea(Title = TEST_IDEA_NAME, Related_Topic_Name__c = 'Test 1', CommunityId = community[0].Id);
			ideasToInsert.add(currIdea);
			insert ideasToInsert;

			List<X7S_Ideas_Extension__c> listOfExtIdea = new List<X7S_Ideas_Extension__c>([SELECT Id,Idea__c FROM X7S_Ideas_Extension__c WHERE Idea__c = :ideasToInsert[0].Id]);
			if (listOfIdeaSettings[0].Enable_Idea_Extension_Functionality__c) {
				System.assertEquals(listOfExtIdea.size(), 1, 'Idea extension not inserted');
			}
			else {
				System.assertEquals(listOfExtIdea.size(), 0, 'Idea extension not inserted');
			}
		}
	}
}