force-app/main/default/objects/X7S_Ideas_Custom_Field__mdt/fields/Alignment__c.field-meta.xml
<CustomField>
    <fullName>Alignment__c</fullName>
    <label>Alignment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>left</fullName>
                <default>true</default>
                <label>left</label>
            </value>
            <value>
                <fullName>center</fullName>
            </value>
            <value>
                <fullName>right</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/X7S_Ideas_Custom_Field__mdt/fields/Required__c.field-meta.xml
<CustomField>
    <fullName>Required__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Enable to make this a required field</inlineHelpText>
    <label>Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/X7S_Ideas_Custom_Field__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>Select the custom field data type</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
                <default>true</default>
                <label>Text</label>
            </value>
            <value>
                <fullName>Textarea</fullName>
                <label>Text Area</label>
            </value>
            <value>
                <fullName>Richtext</fullName>
            </value>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>DateTime</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Percent</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Checkbox</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/x7sIdeasCustomFieldTest.cls
/*
 * Copyright (c) 2020. 7Summits Inc.
 */

@IsTest
public class x7sIdeasCustomFieldTest {
	@IsTest
	static void testCustomField() {
		X7S_Ideas_Custom_Field__mdt customRecord = x7sIdeasCustomFieldTest.getCustomFieldCMT();
		x7sIdeasCustomField customField = new x7sIdeasCustomField(customRecord, 1);
		System.assertNotEquals(null, customField);
		customField.dumpModel('testCustomField');

		x7sIdeasCustomField customField2 = new x7sIdeasCustomField(customRecord, 2);
		System.assertNotEquals(null, customField2);
		List<x7sIdeasCustomField> fieldList = new List<x7sIdeasCustomField>();
		fieldList.add(customField);
		fieldList.add(customField2);
		fieldList.sort();
	}

	private static X7S_Ideas_Custom_Field__mdt getCustomFieldCMT() {
		X7S_Ideas_Custom_Field__mdt cmt = new X7S_Ideas_Custom_Field__mdt();
		cmt.DeveloperName = 'Default';
		cmt.Id = null;
		cmt.Label = 'label';
		cmt.Alignment__c = '';
		cmt.API_Name__c = '';
		cmt.Data__c = '';
		cmt.Field_Label__c = '';
		cmt.Info__c = '';
		cmt.Type__c = '';
		cmt.Required__c = true;

		return cmt;
	}
}