force-app/main/default/objects/X7S_Ideas_Custom_Field__mdt/fields/Alignment__c.field-meta.xml
<CustomField>
    <fullName>Alignment__c</fullName>
    <label>Alignment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>left</fullName>
                <default>true</default>
                <label>left</label>
            </value>
            <value>
                <fullName>center</fullName>
            </value>
            <value>
                <fullName>right</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/X7S_Ideas_Custom_Field__mdt/fields/Required__c.field-meta.xml
<CustomField>
    <fullName>Required__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Enable to make this a required field</inlineHelpText>
    <label>Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/X7S_Ideas_Custom_Field__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>Select the custom field data type</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
                <default>true</default>
                <label>Text</label>
            </value>
            <value>
                <fullName>Textarea</fullName>
                <label>Text Area</label>
            </value>
            <value>
                <fullName>Richtext</fullName>
            </value>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>DateTime</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Percent</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Checkbox</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/x7sIdeasCustomField.cls
/*
 * Copyright (c) 2020. 7Summits Inc.
 */

public with sharing class x7sIdeasCustomField implements Comparable {
	@AuraEnabled
	public String id, name, apiName, label, fieldLabel, fieldType, align, info, dataValue;

	@AuraEnabled
	public List<String> dataValues;

	@AuraEnabled
	public Boolean required;

	@AuraEnabled
	public Decimal sequence;

	public x7sIdeasCustomField(X7S_Ideas_Custom_Field__mdt field, Decimal position) {
		id = field.Id;
		name = field.DeveloperName;
		label = field.Label;
		fieldLabel = String.isNotBlank(field.Field_Label__c) ? field.Field_Label__c : field.Label;
		apiName = field.API_Name__c;
		info = field.Info__c;
		fieldType = field.Type__c;
		dataValue = field.Data__c;
		align = field.Alignment__c;
		required = field.Required__c;
		sequence = position;

		if (fieldType == 'Picklist') {
			dataValues = new List<String>();

			dataValues.addAll(dataValue.split(','));
		}
	}

	public void dumpModel(String title) {
		System.debug('Dump Match_Field model   : ' + title);
		System.debug('  id          : ' + this.id);
		System.debug('  name        : ' + this.name);
		System.debug('  label       : ' + this.label);
		System.debug('  field label : ' + this.fieldLabel);
		System.debug('  apiName     : ' + this.apiName);
		System.debug('  info        : ' + this.info);
		System.debug('  type        : ' + this.fieldType);
		System.debug('  data        : ' + this.dataValue);
		System.debug('  align       : ' + this.align);
		System.debug('  sequence    : ' + this.sequence);
		System.debug('  required    : ' + this.required);
	}

	public Integer compareTo(Object param1) {
		x7sIdeasCustomField field = (x7sIdeasCustomField) param1;

		return field.sequence == this.sequence ? 0 : field.sequence > this.sequence ? -1 : 1;
	}
}