force-app/main/default/objects/X7S_News__c/X7S_News__c.object-meta.xml
<CustomObject>
    <description>Object to support News records as part of the News accelerator from 7Summits.</description>
    <label>7S News</label>
    <nameField>
        <label>7S News Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>7S News</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/X7S_News_Like__c/X7S_News_Like__c.object-meta.xml
<CustomObject>
    <description>Object to support News Like records as part of the News accelerator from 7Summits.</description>
    <label>7S News Like</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>News Like Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>7S News Likes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/X7S_News_Like__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>X7S_News_Likes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/X7S_News_Like__c/fields/X7S_News__c.field-meta.xml
<CustomField>
    <fullName>X7S_News__c</fullName>
    <label>News</label>
    <referenceTo>X7S_News__c</referenceTo>
    <relationshipLabel>News Likes</relationshipLabel>
    <relationshipName>X7S_News_Likes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/x7sNewsLikeControllerTest.cls
/*
 * Copyright (c) 2020. 7Summits Inc. All rights reserved.
 */

/*
@Class Name          : x7sNewsLikeControllerTest
@Created by          :
@Description         : Apex Test class for x7sNewsLikeController
*/
@IsTest
private class x7sNewsLikeControllerTest
{

    //Hardcoded Network Id as we can't able to get get Network Id in Test classes.
    //Packaging org
    //public Static String strNetId = '0DB36000000PB5MGAW';

    public static String strNetId {
        get {
            return [SELECT Id FROM Network LIMIT 1][0].Id;
        }
    }

    // Fran Summer 17 org
    //public Static String strNetId = '0DBB0000000CayaOAC';

    @IsTest
    static void test_LikeUnlikeNews(){
        //create News Records
        X7S_News__c newsObj = x7sNewsUtilityTest.createNews(strNetId);
        X7S_News__c newsObj1 = x7sNewsUtilityTest.createNews(strNetId);
        X7S_News__c newsObj2 = x7sNewsUtilityTest.createNews(strNetId);
        X7S_News__c newsObj3 = x7sNewsUtilityTest.createNews(strNetId);
        X7S_News__c newsObj4 = x7sNewsUtilityTest.createNews(strNetId);

        Test.startTest();
        x7sNewsLikeController.likeNews(newsObj.Id);
        x7sNewsLikeController.likeNews(newsObj1.Id);
        x7sNewsLikeController.likeNews(newsObj2.Id);
        x7sNewsLikeController.likeNews(newsObj3.Id);
        x7sNewsLikeController.likeNews(newsObj4.Id);
        System.assert(x7sNewsLikeController.likeNews(null) == false);

        List<X7S_News_Like__c> newsLikes = [
                SELECT Id
                FROM X7S_News_Like__c
                WHERE User__c = :UserInfo.getUserId()
        ];
        System.assert(newsLikes.size() == 5);
        System.assert(x7sNewsLikeController.isLiking(newsObj.Id));

        x7sNewsLikeController.unLikeNews(newsObj.Id);
        x7sNewsLikeController.unLikeNews(newsObj1.Id);
        x7sNewsLikeController.unLikeNews(newsObj2.Id);
        x7sNewsLikeController.unLikeNews(newsObj3.Id);
        x7sNewsLikeController.unLikeNews(newsObj4.Id);
        System.assert(x7sNewsLikeController.unLikeNews(null) == false);

        newsLikes = [
                SELECT Id
                FROM X7S_News_Like__c
                WHERE User__c = :UserInfo.getUserId()
        ];
        System.assert(newsLikes.size() == 0);

        Test.stopTest();
    }

}