force-app/main/default/objects/X7S_Adventure_Module__c/X7S_Adventure_Module__c.object-meta.xml
<CustomObject>
    <description>Object to support Learning Adventure Module records as part of the Learning Adventure accelerator from 7Summits.</description>
    <label>7S Adventure Module</label>
    <nameField>
        <label>7S Adventure Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>7S Adventure Modules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/X7S_Adventure_Module__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>The title of the Step Module that will be displayed above the card</description>
    <inlineHelpText>The title of the Step Module that will be displayed above the card</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Step__c/X7S_Adventure_Step__c.object-meta.xml
<CustomObject>
    <description>Object to support Learning Adventure Step records as part of the Learning Adventure accelerator from 7Summits.</description>
    <label>7S Adventure Step</label>
    <nameField>
        <label>7S Adventure Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>7S Adventure Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/x7sAdventureNavigationWrapperItem.cls
/*
 * Copyright (c) 2020. 7Summits Inc.
 */

public with sharing class x7sAdventureNavigationWrapperItem {
    @AuraEnabled public String title;
    @AuraEnabled public String id;
    @AuraEnabled public Integer userRemainingTaskCount;
    @AuraEnabled public Double progress;

    public x7sAdventureNavigationWrapperItem(X7S_Adventure_Step__c step, Integer tasksRemaining, Double stepProgress) {
        title = step.Title__c;
        id = step.Id;
        userRemainingTaskCount = tasksRemaining;
        progress = stepProgress;
    }

    public x7sAdventureNavigationWrapperItem(X7S_Adventure_Module__c module, Integer tasksRemaining, Double stepProgress) {
        if (module != null) {
            title = module.Title__c;
            id = module.Id;
        }

        userRemainingTaskCount = tasksRemaining;
        progress = stepProgress;
    }

    //for test, delete later
    public x7sAdventureNavigationWrapperItem() {
        title = 'Just a test module';
        id = 'a043h000001V2WfAAK';
        userRemainingTaskCount = 1;
        progress = .50;
    }
}