force-app/main/default/objects/pse__Assignment__c/pse__Assignment__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__AssignmentAndScheduleHelp</customHelpPage>
    <description>Stores information about the allocation of a resource to a project and specifies the bill rate and cost rate for time entered. It references the schedule for a resource and, optionally, a project milestone.</description>
    <label>Assignment</label>
    <nameField>
        <label>Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Assignment__c/fields/ACTIVE_Job_to_Date_Hours__c.field-meta.xml
<CustomField>
    <fullName>ACTIVE_Job_to_Date_Hours__c</fullName>
    <description>Sum of all approved hours logged (active projects).</description>
    <inlineHelpText>Sum of all approved hours logged (active projects).</inlineHelpText>
    <label>ACTIVE_Job to Date (Hours)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/pse__Assignment__c/fields/CLOSED_Job_To_Date_Hours__c.field-meta.xml
<CustomField>
    <fullName>CLOSED_Job_To_Date_Hours__c</fullName>
    <description>Sum of all approved hours logged (closed projects).</description>
    <inlineHelpText>Sum of all approved hours logged (closed projects).</inlineHelpText>
    <label>CLOSED_Job To Date (Hours)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/pse__Assignment__c/fields/pse__Project__c.field-meta.xml
<CustomField>
    <fullName>pse__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>pse__Proj__c</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/pse__Proj__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__ProjectHelp</customHelpPage>
    <description>Represents a collection of business transactions, activities, and related items to be managed over a defined time range, such as timecards, expenses, milestones, and budgets. Typically, people (represented by Resource records) are assigned to projects, though some projects do not require assignments in order to be staffed. Projects may also have a master project (parent) or a sub project (child) in the project hierarchy, supporting roll-ups of revenues, costs, and time to every project and up through the hierarchy.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Proj__c/fields/ACTIVE_JTD_Billable__c.field-meta.xml
<CustomField>
    <fullName>ACTIVE_JTD_Billable__c</fullName>
    <description>Sum of approved billable hours multiplied by Assignment&apos;s bill rate. Calculated from the Resource&apos;s timecards (active projects).</description>
    <inlineHelpText>Sum of approved billable hours multiplied by Assignment&apos;s bill rate. Calculated from the Resource&apos;s timecards (active projects).</inlineHelpText>
    <label>ACTIVE_JTD Billable T&amp;M ($)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/ACTIVE_JTD_Billable_Hours__c.field-meta.xml
<CustomField>
    <fullName>ACTIVE_JTD_Billable_Hours__c</fullName>
    <description>Sum of all approved billable hours from resource&apos;s timecards (active projects).</description>
    <inlineHelpText>Sum of all approved billable hours from resource&apos;s timecards (active projects).</inlineHelpText>
    <label>ACTIVE_JTD Billable (Hours)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/ACTIVE_JTD_Billable_NB_Hours__c.field-meta.xml
<CustomField>
    <fullName>ACTIVE_JTD_Billable_NB_Hours__c</fullName>
    <description>Sum of all approved nonbill and billable hours logged (active project)</description>
    <inlineHelpText>Sum of all approved nonbill and billable hours logged (active project)</inlineHelpText>
    <label>ACTIVE_JTD Billable &amp; NB (Hours)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/ACTIVE_JTD_Nonbill_Hours__c.field-meta.xml
<CustomField>
    <fullName>ACTIVE_JTD_Nonbill_Hours__c</fullName>
    <description>Sum of all approved nonbill hours logged (active projects).</description>
    <inlineHelpText>Sum of all approved nonbill hours logged (active projects).</inlineHelpText>
    <label>ACTIVE_JTD Nonbill (Hours)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/CLOSED_JTD_Billable__c.field-meta.xml
<CustomField>
    <fullName>CLOSED_JTD_Billable__c</fullName>
    <description>Sum of approved billable hours multiplied by Assignment&apos;s bill rate. Calculated from the Resource&apos;s timecards (closed projects).</description>
    <inlineHelpText>Sum of approved billable hours multiplied by Assignment&apos;s bill rate. Calculated from the Resource&apos;s timecards (closed projects).</inlineHelpText>
    <label>CLOSED_JTD Billable T&amp;M ($)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/CLOSED_JTD_Billable_Hours__c.field-meta.xml
<CustomField>
    <fullName>CLOSED_JTD_Billable_Hours__c</fullName>
    <description>Sum of all approved billable hours from resource&apos;s timecards (closed projects).</description>
    <inlineHelpText>Sum of all approved billable hours from resource&apos;s timecards (closed projects).</inlineHelpText>
    <label>CLOSED_JTD Billable (Hours)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/CLOSED_JTD_Billable_NB_Hours__c.field-meta.xml
<CustomField>
    <fullName>CLOSED_JTD_Billable_NB_Hours__c</fullName>
    <description>Sum of all approved nonbill and billable hours logged (closed project)</description>
    <inlineHelpText>Sum of all approved nonbill and billable hours logged (closed project)</inlineHelpText>
    <label>CLOSED_JTD Billable &amp; NB (Hours)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/CLOSED_JTD_Nonbill_Hours__c.field-meta.xml
<CustomField>
    <fullName>CLOSED_JTD_Nonbill_Hours__c</fullName>
    <description>Sum of all approved nonbill hours logged (closed projects).</description>
    <inlineHelpText>Sum of all approved nonbill hours logged (closed projects).</inlineHelpText>
    <label>CLOSED_JTD Nonbill (Hours)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Project_Type__c.field-meta.xml
<CustomField>
    <fullName>pse__Project_Type__c</fullName>
    <description>A descriptive classification of the project</description>
    <label>Project Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Customer Project</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Stage__c.field-meta.xml
<CustomField>
    <fullName>pse__Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Prepare</fullName>
            </value>
            <value>
                <fullName>Define</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Build</fullName>
            </value>
            <value>
                <fullName>Verify</fullName>
            </value>
            <value>
                <fullName>Launch</fullName>
            </value>
            <value>
                <fullName>Close-Out</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/pse__Timecard_Header__c/pse__Timecard_Header__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__TimecardHelp</customHelpPage>
    <description>Records the hours and days worked by a resource in a given week. Timecards are associated with a project and may also be logged against an assignment or milestone, or against one or more project tasks. Resources can submit multiple timecards on the Timecard Entry page, accessed by clicking either “Log a Timecard - New UI” or “Log a Timecard with Task Time” on the PSA Links sidebar (depending on whether your organization logs time against project tasks). This object is named Timecard_Header (API name pse__Timecard_Header__c) and has a master-detail relationship with timecard splits.</description>
    <label>Timecard</label>
    <nameField>
        <displayFormat>TCH-{MM}-{DD}-{YYYY}-{000000}</displayFormat>
        <label>Timecard Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timecards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Timecard_Header__c/fields/pse__Approved__c.field-meta.xml
<CustomField>
    <fullName>pse__Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This checkbox should be checked when the Timecard is approved - typically by a workflow driven by the Status field.</description>
    <inlineHelpText>This checkbox should be checked when the Timecard is approved - typically based on the Status field.</inlineHelpText>
    <label>Approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/pse__Timecard_Header__c/fields/pse__Assignment__c.field-meta.xml
<CustomField>
    <fullName>pse__Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assignment</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>pse__Assignment__c.pse__Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.pse__Project__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>pse__Assignment__c</referenceTo>
    <relationshipLabel>Timecards</relationshipLabel>
    <relationshipName>Timecards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Timecard_Header__c/fields/pse__Billable__c.field-meta.xml
<CustomField>
    <fullName>pse__Billable__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Billable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/pse__Timecard_Header__c/fields/pse__Project__c.field-meta.xml
<CustomField>
    <fullName>pse__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>pse__Proj__c</referenceTo>
    <relationshipLabel>Timecards</relationshipLabel>
    <relationshipName>Timecards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Timecard_Header__c/fields/pse__Total_Billable_Amount__c.field-meta.xml
<CustomField>
    <fullName>pse__Total_Billable_Amount__c</fullName>
    <formula>IF(pse__Billable__c,IF(pse__Daily_Bill_Rate__c,(pse__Total_Days_Worked__c * pse__Bill_Rate__c),(pse__Total_Hours__c * pse__Bill_Rate__c)), 0.00)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Billable Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/TimecardRollupHelper.cls
public class TimecardRollupHelper {
    public static boolean isRunning=false;
    
    public static void calculate(Set<Id> projectIds) {
        List<pse__Timecard_Header__c> timecards = [SELECT Id, pse__Assignment__c, pse__Total_Hours__c, pse__Project__r.pse__Stage__c, pse__Total_Billable_Amount__c, pse__billable__c
                                                   FROM pse__Timecard_Header__c
                                                   WHERE pse__Project__c IN : projectIds AND
                                                   pse__approved__c = TRUE AND 
                                                   pse__project__r.pse__project_type__c = 'Customer Project'];
        
        Map<Id, pse__Proj__c> projectMap = updateProjects(timecards);
        Map<Id, pse__Assignment__c> assignmentMap = updateAssignments(timecards);
        
        if(!assignmentMap.isEmpty()) {
            List<Database.SaveResult> sr = Database.update(assignmentMap.values(), false);
        }
        if(!projectMap.isEmpty()) {
            List<Database.SaveResult> sr = Database.update(projectMap.values(), false);
        }
    }
    
    
    private static Map<Id, pse__Assignment__c> updateAssignments(List<pse__Timecard_Header__c> timecards) {
        
        Map<Id, pse__Assignment__c> assignmentMap = new Map<Id, pse__Assignment__c>();
        
        for(pse__Timecard_Header__c timecard : timecards) {
            
            switch on timecard.pse__Project__r.pse__Stage__c {
                when 'Completed', 'Cancelled' {
                    if(!assignmentMap.containsKey(timecard.pse__Assignment__c)) { assignmentMap.put(timecard.pse__Assignment__c, new pse__Assignment__c(Id=timecard.pse__Assignment__c, CLOSED_Job_To_Date_Hours__c=0)); }
                    try { assignmentMap.get(timecard.pse__Assignment__c).CLOSED_Job_To_Date_Hours__c += timecard.pse__Total_Hours__c; } catch (Exception e) {}
                } when 'Planned' , 'Prepare' , 'Define' , 'Design' , 'Build' , 'Verify' , 'Launch' , 'Close-Out' {
                    if(!assignmentMap.containsKey(timecard.pse__Assignment__c)) { 
                        assignmentMap.put(timecard.pse__Assignment__c, new pse__Assignment__c(Id=timecard.pse__Assignment__c, ACTIVE_Job_to_Date_Hours__c=0)); 
                    }
                    try { assignmentMap.get(timecard.pse__Assignment__c).ACTIVE_Job_to_Date_Hours__c += timecard.pse__Total_Hours__c; } catch (Exception e) {}
                }
            }
        }
        
        return assignmentMap;
    }
    
    private static Map<Id, pse__Proj__c> updateProjects(List<pse__Timecard_Header__c> timecards) {
        
        Map<Id, pse__Proj__c> projectMap = new Map<Id, pse__Proj__c>();
        
        for(pse__Timecard_Header__c timecard : timecards) {
            
            switch on timecard.pse__Project__r.pse__Stage__c {
                when 'Completed', 'Cancelled' {
                    if(!projectMap.containsKey(timecard.pse__Project__c)) { 
                        projectMap.put(timecard.pse__Project__c, new pse__Proj__c(Id=timecard.pse__Project__c, CLOSED_JTD_Billable__c=0, CLOSED_JTD_Billable_Hours__c=0,
                                                                                  CLOSED_JTD_Nonbill_Hours__c=0, CLOSED_JTD_Billable_NB_Hours__c=0));
                    }
                    try { projectMap.get(timecard.pse__Project__c).CLOSED_JTD_Billable__c += timecard.pse__Total_Billable_Amount__c; } catch (Exception e) {}
                    try { projectMap.get(timecard.pse__Project__c).CLOSED_JTD_Billable_NB_Hours__c += timecard.pse__Total_Hours__c; } catch (Exception e) {}
                    if(timecard.pse__billable__c) {
                        try { projectMap.get(timecard.pse__Project__c).CLOSED_JTD_Billable_Hours__c += timecard.pse__Total_Hours__c; } catch (Exception e) {}
                    } else {
                        try { projectMap.get(timecard.pse__Project__c).CLOSED_JTD_Nonbill_Hours__c += timecard.pse__Total_Hours__c; } catch (Exception e) {}
                    }
                } when 'Planned' , 'Prepare' , 'Define' , 'Design' , 'Build' , 'Verify' , 'Launch' , 'Close-Out' {
                    if(!projectMap.containsKey(timecard.pse__Project__c)) { 
                        projectMap.put(timecard.pse__Project__c, new pse__Proj__c(Id=timecard.pse__Project__c, ACTIVE_JTD_Billable_NB_Hours__c=0, ACTIVE_JTD_Nonbill_Hours__c=0,
                                                                                  ACTIVE_JTD_Billable__c=0, ACTIVE_JTD_Billable_Hours__c=0)); 
                    }
                    try { projectMap.get(timecard.pse__Project__c).ACTIVE_JTD_Billable__c += timecard.pse__Total_Billable_Amount__c; } catch (Exception e) {}
                    try { projectMap.get(timecard.pse__Project__c).ACTIVE_JTD_Billable_NB_Hours__c += timecard.pse__Total_Hours__c; } catch (Exception e) {}
                    if(timecard.pse__billable__c) {
                        try { projectMap.get(timecard.pse__Project__c).ACTIVE_JTD_Billable_Hours__c += timecard.pse__Total_Hours__c; } catch (Exception e) {}
                    } else {
                        try { projectMap.get(timecard.pse__Project__c).ACTIVE_JTD_Nonbill_Hours__c += timecard.pse__Total_Hours__c; } catch (Exception e) {}
                    }
                }
            }
        }
        
        return projectMap;
    }
}