force-app/main/default/objects/pse__Assignment__c/pse__Assignment__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__AssignmentAndScheduleHelp</customHelpPage>
    <description>Stores information about the allocation of a resource to a project and specifies the bill rate and cost rate for time entered. It references the schedule for a resource and, optionally, a project milestone.</description>
    <label>Assignment</label>
    <nameField>
        <label>Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Assignment__c/fields/Baseline_Budget__c.field-meta.xml
<CustomField>
    <fullName>Baseline_Budget__c</fullName>
    <formula>pse__Bill_Rate__c*pse__Planned_Hours__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Baseline Budget ($)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/pse__Assignment__c/fields/Estimate_to_Complete_Cost__c.field-meta.xml
<CustomField>
    <fullName>Estimate_to_Complete_Cost__c</fullName>
    <formula>pse__Resource__r.pse__Default_Cost_Rate__c*Estimate_to_Complete_Hours__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Estimate to Complete (Cost)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/pse__Assignment__c/fields/Job_to_Date_Cost__c.field-meta.xml
<CustomField>
    <fullName>Job_to_Date_Cost__c</fullName>
    <formula>Job_to_Date_Hours__c*pse__Resource__r.pse__Default_Cost_Rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Job to Date (Cost)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/pse__Assignment__c/fields/pse__Is_Billable__c.field-meta.xml
<CustomField>
    <fullName>pse__Is_Billable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Billable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/pse__Assignment__c/fields/pse__Planned_Hours__c.field-meta.xml
<CustomField>
    <fullName>pse__Planned_Hours__c</fullName>
    <defaultValue>0</defaultValue>
    <description>User editable number of hours originally planned for this assignment. NOTE: this field is user maintained and will not be updated automatically.</description>
    <inlineHelpText>The number of hours originally planned for this assignment. This value is independent of the actual number of hours scheduled.</inlineHelpText>
    <label>Planned Hours</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/pse__Assignment__c/fields/pse__Project__c.field-meta.xml
<CustomField>
    <fullName>pse__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>pse__Proj__c</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/pse__Proj__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__ProjectHelp</customHelpPage>
    <description>Represents a collection of business transactions, activities, and related items to be managed over a defined time range, such as timecards, expenses, milestones, and budgets. Typically, people (represented by Resource records) are assigned to projects, though some projects do not require assignments in order to be staffed. Projects may also have a master project (parent) or a sub project (child) in the project hierarchy, supporting roll-ups of revenues, costs, and time to every project and up through the hierarchy.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Proj__c/fields/ACTIVE_Baseline_Budget__c.field-meta.xml
<CustomField>
    <fullName>ACTIVE_Baseline_Budget__c</fullName>
    <description>Sum of all assignment&apos;s planned hours multiplied by assignment&apos;s bill rate (active projects).</description>
    <inlineHelpText>Sum of all assignment&apos;s planned hours multiplied by assignment&apos;s bill rate (active projects).</inlineHelpText>
    <label>ACTIVE_Baseline Budget T&amp;M ($)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/ACTIVE_Baseline_Budget_Hours__c.field-meta.xml
<CustomField>
    <fullName>ACTIVE_Baseline_Budget_Hours__c</fullName>
    <description>Sum of all assignment&apos;s billable planned hours (active projects).</description>
    <inlineHelpText>Sum of all assignment&apos;s billable planned hours (active projects).</inlineHelpText>
    <label>ACTIVE_Baseline Budget (Hours)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/ACTIVE_Baseline_Budget_NB_Hours__c.field-meta.xml
<CustomField>
    <fullName>ACTIVE_Baseline_Budget_NB_Hours__c</fullName>
    <description>Sum of Assignment&apos;s nonbill Planned Hours (active projects)</description>
    <inlineHelpText>Sum of Assignment&apos;s nonbill Planned Hours (active projects)</inlineHelpText>
    <label>ACTIVE_Baseline Budget NB (Hours)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/ACTIVE_JTD_Billable_NB_Cost__c.field-meta.xml
<CustomField>
    <fullName>ACTIVE_JTD_Billable_NB_Cost__c</fullName>
    <description>Sum of all assignment&apos;s Job to Date (Cost) on active projects</description>
    <inlineHelpText>Sum of all assignment&apos;s Job to Date (Cost) on active projects</inlineHelpText>
    <label>ACTIVE_JTD Billable &amp; NB (Cost)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/Baseline_Budget__c.field-meta.xml
<CustomField>
    <fullName>Baseline_Budget__c</fullName>
    <description>Sum of all Assignment&apos;s Baseline Budget (Bill Rate * Planned Hours)</description>
    <formula>IF( Opp_Project_Type__c = &quot;Customer Success&quot;,(  ACTIVE_Baseline_Budget_CS__c +  CLOSED_Baseline_Budget_CS__c ),(ACTIVE_Baseline_Budget__c+CLOSED_Baseline_Budget__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Sum of all Assignment&apos;s Baseline Budget (Bill Rate * Planned Hours)</inlineHelpText>
    <label>Baseline Budget ($)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/CLOSED_Baseline_Budget__c.field-meta.xml
<CustomField>
    <fullName>CLOSED_Baseline_Budget__c</fullName>
    <description>Sum of all assignment&apos;s planned hours multiplied by assignment&apos;s bill rate (closed projects).</description>
    <inlineHelpText>Sum of all assignment&apos;s planned hours multiplied by assignment&apos;s bill rate (closed projects).</inlineHelpText>
    <label>CLOSED_Baseline Budget T&amp;M ($)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/CLOSED_Baseline_Budget_Hours__c.field-meta.xml
<CustomField>
    <fullName>CLOSED_Baseline_Budget_Hours__c</fullName>
    <description>Sum of all assignment&apos;s billable planned hours (closed projects).</description>
    <inlineHelpText>Sum of all assignment&apos;s billable planned hours (closed projects).</inlineHelpText>
    <label>CLOSED_Baseline Budget (Hours)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/CLOSED_Baseline_Budget_NB_Hours__c.field-meta.xml
<CustomField>
    <fullName>CLOSED_Baseline_Budget_NB_Hours__c</fullName>
    <description>Sum of Assignment&apos;s nonbill Planned Hours (closed projects)</description>
    <inlineHelpText>Sum of Assignment&apos;s nonbill Planned Hours (closed projects)</inlineHelpText>
    <label>CLOSED_Baseline Budget NB (Hours)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/CLOSED_JTD_Billable_NB_Cost__c.field-meta.xml
<CustomField>
    <fullName>CLOSED_JTD_Billable_NB_Cost__c</fullName>
    <description>Sum of all assignment&apos;s Job to Date (Cost) on closed projects</description>
    <inlineHelpText>Sum of all assignment&apos;s Job to Date (Cost) on closed projects</inlineHelpText>
    <label>CLOSED_JTD Billable &amp; NB (Cost)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/ETC_Billable_NB_Cost_del__c.field-meta.xml
<CustomField>
    <fullName>ETC_Billable_NB_Cost_del__c</fullName>
    <description>Sum of all assignment&apos;s Estimate to Complete (Cost)</description>
    <inlineHelpText>Sum of all assignment&apos;s Estimate to Complete (Cost)</inlineHelpText>
    <label>ETC Billable &amp; NB (Cost)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Is_Billable__c.field-meta.xml
<CustomField>
    <fullName>pse__Is_Billable__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check if this project is billable to a customer.</inlineHelpText>
    <label>Billable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Planned_Hours__c.field-meta.xml
<CustomField>
    <fullName>pse__Planned_Hours__c</fullName>
    <inlineHelpText>The number of hours planned for this project</inlineHelpText>
    <label>Planned Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Project_Type__c.field-meta.xml
<CustomField>
    <fullName>pse__Project_Type__c</fullName>
    <description>A descriptive classification of the project</description>
    <label>Project Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Customer Project</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Stage__c.field-meta.xml
<CustomField>
    <fullName>pse__Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Prepare</fullName>
            </value>
            <value>
                <fullName>Define</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Build</fullName>
            </value>
            <value>
                <fullName>Verify</fullName>
            </value>
            <value>
                <fullName>Launch</fullName>
            </value>
            <value>
                <fullName>Close-Out</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AssignmentRollupHelper.cls
public class AssignmentRollupHelper {
    public static boolean isRunning=false;
    public static void calculate(Set<Id> projectIds) {
        System.debug('******** EXECUTING AssignmentRollupHelper ********');
        List<pse__Proj__c> projects = [SELECT Id, Name, pse__Stage__c,
                                       (SELECT Job_to_Date_Cost__c, Estimate_to_Complete_Cost__c, Baseline_Budget__c, pse__Planned_Hours__c,pse__is_billable__c 
                                        FROM pse__Assignments__r)
                                       FROM pse__Proj__c WHERE Id IN : projectIds AND pse__Project_Type__c='Customer Project'];
        
        List<pse__Proj__c> updatedProjects = new List<pse__Proj__c>();
        for(pse__Proj__c project : projects) {
            System.debug('------ project: ' + project.Id + '    -------- stage: ' + project.pse__Stage__c);
            Decimal closedBaselineBudget = 0.0;
            Decimal closedBaselineBudgetHours = 0.0;
            Decimal closedJTDBillableNBCost = 0.0;
            Decimal closedBaselineBudgetNBHours = 0.0;
            Decimal activeBaselineBudget = 0.0;
            Decimal activeBaselineBudgetHours = 0.0;
            Decimal activeBaselineBudgetNBHours = 0.0;
            Decimal etcBillableNBCost = 0.0;
            Decimal activeJTDBillableNBCost = 0.0;
            for(pse__Assignment__c assignment : project.pse__Assignments__r) {
                
                switch on project.pse__Stage__c {
                    when 'Completed', 'Cancelled' {
                        if(assignment.pse__is_billable__c) {
                            try { closedBaselineBudget += assignment.Baseline_Budget__c; } catch (Exception e) {}
                            try { closedBaselineBudgetHours += assignment.pse__Planned_Hours__c; } catch (Exception e) {}
                        } else {
                            try { closedJTDBillableNBCost += assignment.Job_to_Date_Cost__c; } catch (Exception e) {}
                            try { closedBaselineBudgetNBHours += assignment.pse__Planned_Hours__c; } catch (Exception e) {}
                        }
                    } when 'Planned' , 'Prepare' , 'Define' , 'Design' , 'Build' , 'Verify' , 'Launch' , 'Close-Out' {
                        if(assignment.pse__is_billable__c) {
                            try { activeBaselineBudgetHours += assignment.pse__Planned_Hours__c; } catch (Exception e) {}
                            try { activeBaselineBudget += assignment.Baseline_Budget__c; } catch (Exception e) {}
                        } else {
                            try { activeBaselineBudgetNBHours += assignment.pse__Planned_Hours__c; } catch (Exception e) {}
                        }
                        try { activeJTDBillableNBCost += assignment.Job_to_Date_Cost__c; } catch (Exception e) {}
                        try { etcBillableNBCost += assignment.Estimate_to_Complete_Cost__c; } catch (Exception e) {}
                    }
                }
                
            }
//            switch on project.pse__Stage__c {
//                when 'Completed', 'Cancelled' {
//                    updatedProjects.add(new pse__Proj__c(Id=project.Id, CLOSED_Baseline_Budget__c=closedBaselineBudget,
//                                                         CLOSED_Baseline_Budget_Hours__c=closedBaselineBudgetHours,
//                                                         CLOSED_JTD_Billable_NB_Cost__c=closedJTDBillableNBCost,
//                                                         CLOSED_Baseline_Budget_NB_Hours__c=closedBaselineBudgetNBHours));
//                } when 'Planned' , 'Prepare' , 'Define' , 'Design' , 'Build' , 'Verify' , 'Launch' , 'Close-Out' {
//                    updatedProjects.add(new pse__Proj__c(Id=project.Id, ACTIVE_JTD_Billable_NB_Cost__c=activeJTDBillableNBCost,
//                                                         ACTIVE_Baseline_Budget_Hours__c=activeBaselineBudgetHours,
//                                                         ETC_Billable_NB_Cost_del__c=etcBillableNBCost,
//                                                         ACTIVE_Baseline_Budget__c=activeBaselineBudget,
//                                                         ACTIVE_Baseline_Budget_NB_Hours__c=activeBaselineBudgetNBHours));
//                }
//            }
                    updatedProjects.add(new pse__Proj__c(Id=project.Id, CLOSED_Baseline_Budget__c=closedBaselineBudget,
                                                         CLOSED_Baseline_Budget_Hours__c=closedBaselineBudgetHours,
                                                         CLOSED_JTD_Billable_NB_Cost__c=closedJTDBillableNBCost,
                                                         CLOSED_Baseline_Budget_NB_Hours__c=closedBaselineBudgetNBHours,
                                                         ACTIVE_JTD_Billable_NB_Cost__c=activeJTDBillableNBCost,
                                                         ACTIVE_Baseline_Budget_Hours__c=activeBaselineBudgetHours,
                                                         ETC_Billable_NB_Cost_del__c=etcBillableNBCost,
                                                         ACTIVE_Baseline_Budget__c=activeBaselineBudget,
                                                         ACTIVE_Baseline_Budget_NB_Hours__c=activeBaselineBudgetNBHours));            
        }
        
        if(!updatedProjects.isEmpty()) { 
            List<Database.SaveResult> sr = Database.update(updatedProjects);
        }
        System.debug('******** EXITING AssignmentRollupHelper ********');
    }
}