force-app/main/default/objects/pse__Assignment__c/pse__Assignment__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__AssignmentAndScheduleHelp</customHelpPage>
    <description>Stores information about the allocation of a resource to a project and specifies the bill rate and cost rate for time entered. It references the schedule for a resource and, optionally, a project milestone.</description>
    <label>Assignment</label>
    <nameField>
        <label>Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Assignment__c/fields/Estimate_to_Complete_Hours__c.field-meta.xml
<CustomField>
    <fullName>Estimate_to_Complete_Hours__c</fullName>
    <description>Sum of all forecasted hours (current week forward).</description>
    <inlineHelpText>Sum of all forecasted hours (current week forward).</inlineHelpText>
    <label>Estimate to Complete (Hours)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/pse__Est_Vs_Actuals__c/pse__Est_Vs_Actuals__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__EstimateVsActualsHelp</customHelpPage>
    <description>Compares the estimated and actual hours worked by a resource on an assignment, derived from scheduled hours and entered timecard hours respectively. FinancialForce PSA generates Est Vs Actuals when you create or update assignments and schedules, and when timecard hours are entered for an assignment.</description>
    <label>Est Vs Actuals</label>
    <nameField>
        <label>Est Vs Actuals Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Est Vs Actuals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Est_Vs_Actuals__c/fields/pse__Assignment__c.field-meta.xml
<CustomField>
    <fullName>pse__Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assignment</label>
    <referenceTo>pse__Assignment__c</referenceTo>
    <relationshipLabel>Est Vs Actuals</relationshipLabel>
    <relationshipName>Est_Vs_Actuals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Est_Vs_Actuals__c/fields/pse__Project__c.field-meta.xml
<CustomField>
    <fullName>pse__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>pse__Proj__c</referenceTo>
    <relationshipLabel>Est Vs Actuals</relationshipLabel>
    <relationshipName>Est_Vs_Actuals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Est_Vs_Actuals__c/fields/pse__Time_Period_Type__c.field-meta.xml
<CustomField>
    <fullName>pse__Time_Period_Type__c</fullName>
    <description>The type of time period this time span represents</description>
    <inlineHelpText>The type of time period this time span represents</inlineHelpText>
    <label>Time Period Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Week</fullName>
            </value>
            <value>
                <fullName>Month</fullName>
            </value>
            <value>
                <fullName>Quarter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/pse__Est_Vs_Actuals__c/fields/Scheduled_Billable_Hours__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Billable_Hours__c</fullName>
    <description>Estimated Hours - Only populates if the assignment is billable and EVA record represents a future week. Once the week passes, the value changes to 0</description>
    <formula>IF(AND( pse__End_Date__c  &gt;  TODAY() , Billable__c = True),  pse__Estimated_Hours__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Estimated Hours - Only populates if the assignment is billable and EVA record represents a future week. Once the week passes, the value changes to 0</inlineHelpText>
    <label>Scheduled Billable Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/pse__Est_Vs_Actuals__c/fields/Scheduled_Hours__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Hours__c</fullName>
    <description>Scheduled Billable Hours multiplied by Scheduled Bill Rate</description>
    <formula>Scheduled_Billable_Hours__c*pse__Scheduled_Bill_Rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Scheduled Billable Hours multiplied by Scheduled Bill Rate</inlineHelpText>
    <label>Scheduled Hours ($)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/pse__Est_Vs_Actuals__c/fields/Scheduled_Nonbill_Hours__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Nonbill_Hours__c</fullName>
    <formula>IF(AND( pse__End_Date__c &gt; TODAY() , Billable__c = False), pse__Estimated_Hours__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Scheduled Nonbill Hours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/pse__Est_Vs_Actuals__c/fields/Total_Scheduled_Hours__c.field-meta.xml
<CustomField>
    <fullName>Total_Scheduled_Hours__c</fullName>
    <formula>IF( pse__End_Date__c &gt; TODAY(), pse__Estimated_Hours__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Scheduled Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/pse__Proj__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__ProjectHelp</customHelpPage>
    <description>Represents a collection of business transactions, activities, and related items to be managed over a defined time range, such as timecards, expenses, milestones, and budgets. Typically, people (represented by Resource records) are assigned to projects, though some projects do not require assignments in order to be staffed. Projects may also have a master project (parent) or a sub project (child) in the project hierarchy, supporting roll-ups of revenues, costs, and time to every project and up through the hierarchy.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Proj__c/fields/ETC_Billable_Hours__c.field-meta.xml
<CustomField>
    <fullName>ETC_Billable_Hours__c</fullName>
    <description>Sum of all billable forecasted hours (current week forward). Populated from the field &quot;Scheduled Billable Hours&quot; on all Est vs Actuals records where Time Period = Week.</description>
    <inlineHelpText>Sum of all billable forecasted hours (current week forward)</inlineHelpText>
    <label>ETC Billable (Hours)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/ETC_Billable_NB_Hours__c.field-meta.xml
<CustomField>
    <fullName>ETC_Billable_NB_Hours__c</fullName>
    <description>Sum of all forecasted hours for billable &amp; nonbill assignments (current week forward). Populated from the field &quot;Total Scheduled Hours&quot; on all Est vs Actuals records where Time Period = Week.</description>
    <inlineHelpText>Sum of all forecasted hours for billable &amp; nonbill assignments (current week forward)</inlineHelpText>
    <label>ETC Billable &amp; NB (Hours)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/ETC_Billable_TM__c.field-meta.xml
<CustomField>
    <fullName>ETC_Billable_TM__c</fullName>
    <label>ETC Billable T&amp;M ($)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/ETC_Nonbill_Hours__c.field-meta.xml
<CustomField>
    <fullName>ETC_Nonbill_Hours__c</fullName>
    <description>Sum of all forecasted hours for nonbill assignments (current week forward). Populated from the field &quot;Total Scheduled Hours&quot; on all Est vs Actuals records where Time Period = Week.</description>
    <inlineHelpText>Sum of all forecasted hours for nonbill assignments (current week forward)</inlineHelpText>
    <label>ETC Nonbill (Hours)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Project_Type__c.field-meta.xml
<CustomField>
    <fullName>pse__Project_Type__c</fullName>
    <description>A descriptive classification of the project</description>
    <label>Project Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Customer Project</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Stage__c.field-meta.xml
<CustomField>
    <fullName>pse__Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Prepare</fullName>
            </value>
            <value>
                <fullName>Define</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Build</fullName>
            </value>
            <value>
                <fullName>Verify</fullName>
            </value>
            <value>
                <fullName>Launch</fullName>
            </value>
            <value>
                <fullName>Close-Out</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EstVsActualsRollupHelper.cls
public class EstVsActualsRollupHelper {
    public static boolean isRunning=false;
    
    public static void calculate(Set<Id> projectIds) {
        System.debug('******** EXECUTING EstVsActualsRollupHelper ********');
        List<pse__Proj__c> projects = [SELECT Id, Name, pse__Stage__c,
                                       (SELECT pse__Assignment__c, Total_Scheduled_Hours__c, Scheduled_Nonbill_Hours__c, Scheduled_Hours__c, Scheduled_Billable_Hours__c 
                                        FROM pse__Est_vs_Actuals__r WHERE pse__Time_Period_Type__c='Week')
                                       FROM pse__Proj__c WHERE Id IN : projectIds AND pse__Project_Type__c='Customer Project'];
        
        List<pse__Proj__c> updatedProjects = new List<pse__Proj__c>();
        for(pse__Proj__c project : projects) {
            Decimal etcBillableNBHours = 0.0;
            Decimal etcNonbillHours = 0.0;
            Decimal etcBillableTM = 0.0;
            Decimal etcBillableHours = 0.0;
            for(pse__Est_vs_Actuals__c est : project.pse__Est_vs_Actuals__r) {
                
                switch on project.pse__Stage__c {
                    when 'Completed', 'Cancelled' {

                    } when 'Planned' , 'Prepare' , 'Define' , 'Design' , 'Build' , 'Verify' , 'Launch' , 'Close-Out' {
                        try { etcBillableNBHours += est.Total_Scheduled_Hours__c; } catch (Exception e) {}
                        try { etcNonbillHours += est.Scheduled_Nonbill_Hours__c; } catch (Exception e) {}
                        try { etcBillableTM += est.Scheduled_Hours__c; } catch (Exception e) {}
                        try { etcBillableHours += est.Scheduled_Billable_Hours__c; } catch (Exception e) {}
                    }
                }
                
            }
            switch on project.pse__Stage__c {
                when 'Completed', 'Cancelled' {

                } when 'Planned' , 'Prepare' , 'Define' , 'Design' , 'Build' , 'Verify' , 'Launch' , 'Close-Out' {
					updatedProjects.add(new pse__Proj__c(Id=project.Id, ETC_Billable_NB_Hours__c=etcBillableNBHours,
                                                         ETC_Nonbill_Hours__c=etcNonbillHours,
                                                         ETC_Billable_TM__c=etcBillableTM,
                                                         ETC_Billable_Hours__c=etcBillableHours));
                }
            }
        }
        
        if(!updatedProjects.isEmpty()) { update updatedProjects; }
        updateAssignments(projectIds);
        System.debug('******** EXITING EstVsActualsRollupHelper ********');
    }
    
    @future
    private static void updateAssignments(Set<Id> projectIds) {
        System.debug('******** EXECUTING EstVsActualsRollupHelper-future method ********');
        EstVsActualsRollupHelper.isRunning=true;
        List<pse__Proj__c> projects = [SELECT Id, Name, pse__Stage__c,
                                       (SELECT pse__Assignment__c, Total_Scheduled_Hours__c, Scheduled_Nonbill_Hours__c, Scheduled_Hours__c, Scheduled_Billable_Hours__c 
                                        FROM pse__Est_vs_Actuals__r WHERE pse__Time_Period_Type__c='Week')
                                       FROM pse__Proj__c WHERE Id IN : projectIds AND pse__Project_Type__c='Customer Project'];
        
        Map<Id, pse__Assignment__c> assignmentMap = new Map<Id, pse__Assignment__c>();
        for(pse__Proj__c project : projects) {

            for(pse__Est_vs_Actuals__c est : project.pse__Est_vs_Actuals__r) {
                
                switch on project.pse__Stage__c {
                    when 'Completed', 'Cancelled' {

                    } when 'Planned' , 'Prepare' , 'Define' , 'Design' , 'Build' , 'Verify' , 'Launch' , 'Close-Out' {
                        if(est.pse__Assignment__c != null) {
                            if(!assignmentMap.containsKey(est.pse__Assignment__c)) { 
                                assignmentMap.put(est.pse__Assignment__c, new pse__Assignment__c(Id=est.pse__Assignment__c, Estimate_to_Complete_Hours__c=0.0)); 
                            }
                            try { assignmentMap.get(est.pse__Assignment__c).Estimate_to_Complete_Hours__c += est.Total_Scheduled_Hours__c; } catch (Exception e) {}
                        }
                    }
                }
                
            }

        }
        
        if(!assignmentMap.isEmpty()) { 
            List<Database.SaveResult> sr = Database.update(assignmentMap.values(), false); 
        }
        System.debug('******** EXITING EstVsActualsRollupHelper ********');        
    }
}