force-app/main/default/objects/pse__Budget__c/pse__Budget__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__BudgetHelp</customHelpPage>
    <description>A budgeted amount for a PSA project. Represents, depending on its type, customer purchase orders, internal budgets, outbound vendor purchase orders, or work orders, as well as change requests to these records. It may also contain a separate expense budget amount and specified pre-bill amount.</description>
    <label>Budget</label>
    <nameField>
        <label>Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Budget__c/fields/Budget_Amount__c.field-meta.xml
<CustomField>
    <fullName>Budget_Amount__c</fullName>
    <formula>pse__Opportunity__r.Svcs_Amt_for_NetSuite2__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Budget Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/pse__Budget__c/fields/pse__Project__c.field-meta.xml
<CustomField>
    <fullName>pse__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>pse__Proj__c</referenceTo>
    <relationshipLabel>Budgets</relationshipLabel>
    <relationshipName>Budgets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/pse__Proj__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__ProjectHelp</customHelpPage>
    <description>Represents a collection of business transactions, activities, and related items to be managed over a defined time range, such as timecards, expenses, milestones, and budgets. Typically, people (represented by Resource records) are assigned to projects, though some projects do not require assignments in order to be staffed. Projects may also have a master project (parent) or a sub project (child) in the project hierarchy, supporting roll-ups of revenues, costs, and time to every project and up through the hierarchy.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Proj__c/fields/ACTIVE_SOW_Budget__c.field-meta.xml
<CustomField>
    <fullName>ACTIVE_SOW_Budget__c</fullName>
    <description>Sum of all project budgets (active projects).</description>
    <inlineHelpText>Sum of all project budgets (active projects).</inlineHelpText>
    <label>ACTIVE_SOW Budget ($)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/CLOSED_SOW_Budget__c.field-meta.xml
<CustomField>
    <fullName>CLOSED_SOW_Budget__c</fullName>
    <description>Sum of all project budgets (closed projects).</description>
    <inlineHelpText>Sum of all project budgets (closed projects).</inlineHelpText>
    <label>CLOSED_SOW Budget ($)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Project_Type__c.field-meta.xml
<CustomField>
    <fullName>pse__Project_Type__c</fullName>
    <description>A descriptive classification of the project</description>
    <label>Project Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Customer Project</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Stage__c.field-meta.xml
<CustomField>
    <fullName>pse__Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Prepare</fullName>
            </value>
            <value>
                <fullName>Define</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Build</fullName>
            </value>
            <value>
                <fullName>Verify</fullName>
            </value>
            <value>
                <fullName>Launch</fullName>
            </value>
            <value>
                <fullName>Close-Out</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BudgetRollupHelper.cls
public class BudgetRollupHelper {
    public static void calculate(Set<Id> projectIds) {
        List<pse__Proj__c> projects = [SELECT Id, Name, pse__Stage__c,
                                       (SELECT budget_amount__c , pse__project__c FROM pse__Budgets__r)
                                       FROM pse__Proj__c 
                                       WHERE Id IN : projectIds AND pse__project_type__c = 'Customer Project'];

        List<pse__Proj__c> updatedProjects = new List<pse__Proj__c>();
        for(pse__Proj__c project : projects) {
            Decimal closedSOWBudget = 0.0;
            Decimal activeSOWBudget = 0.0;
            for(pse__Budget__c budget : project.pse__Budgets__r) {
                
                switch on project.pse__Stage__c {
                    when 'Completed', 'Cancelled' {
						closedSOWBudget += budget.Budget_Amount__c;
                    } when 'Planned' , 'Prepare' , 'Define' , 'Design' , 'Build' , 'Verify' , 'Launch' , 'Close-Out' {
						activeSOWBudget +=  budget.Budget_Amount__c;
                    }
                }
                
            }
            switch on project.pse__Stage__c {
                when 'Completed', 'Cancelled' {
                    updatedProjects.add(new pse__Proj__c(Id=project.Id, CLOSED_SOW_Budget__c=closedSOWBudget));
                } when 'Planned' , 'Prepare' , 'Define' , 'Design' , 'Build' , 'Verify' , 'Launch' , 'Close-Out' {
                    updatedProjects.add(new pse__Proj__c(Id=project.Id, ACTIVE_SOW_Budget__c=activeSOWBudget));
                }
            }
        }
        
        if(!updatedProjects.isEmpty()) { update updatedProjects; }
    }
}