force-app/main/default/objects/Community_Task__mdt/Community_Task__mdt.object-meta.xml
<CustomObject>
    <label>Community Task</label>
    <pluralLabel>Community Tasks</pluralLabel>
</CustomObject>

force-app/main/default/objects/Community_Task__mdt/fields/Deactivate__c.field-meta.xml
<CustomField>
    <fullName>Deactivate__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to activate and deactivate a task instead of completely deleting the task. This field helps in displaying only the active Tasks on the component</description>
    <label>Deactivate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Community_Task_Group__mdt/Community_Task_Group__mdt.object-meta.xml
<CustomObject>
    <label>Community Task Group</label>
    <pluralLabel>Community Task Groups</pluralLabel>
</CustomObject>

force-app/main/default/objects/Community_Task_Group__mdt/fields/Deactivate__c.field-meta.xml
<CustomField>
    <fullName>Deactivate__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to activate and deactivate a Task Group instead of completely deleting the group. This field helps in displaying only the active Task Groups on the component</description>
    <label>Deactivate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Community_Task_Group_Assignment__mdt/Community_Task_Group_Assignment__mdt.object-meta.xml
<CustomObject>
    <label>Community Task Group Assignment</label>
    <pluralLabel>Community Task Group Assignments</pluralLabel>
</CustomObject>

force-app/main/default/objects/Community_Task_Group_Assignment__mdt/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <referenceTo>Community_Task_Group__mdt</referenceTo>
    <relationshipLabel>Community Task Group Assignments</relationshipLabel>
    <relationshipName>Community_Task_Group_Assignments</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Community_Task_Group_Assignment__mdt/fields/Task__c.field-meta.xml
<CustomField>
    <fullName>Task__c</fullName>
    <label>Task</label>
    <referenceTo>Community_Task__mdt</referenceTo>
    <relationshipLabel>Community Task Group Assignments</relationshipLabel>
    <relationshipName>Community_Task_Group_Assignments</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <label>Task</label>
</RecordType>

force-app/main/default/classes/Peak_CommunityTaskMDTWrapper.cls
public class Peak_CommunityTaskMDTWrapper {

    /*
        Create Task Wrapper from Task MDTs
    */
    public static List<Peak_CommunityTaskWrapper> getTaskList(){

        List<Peak_CommunityTaskWrapper> returnList = new List<Peak_CommunityTaskWrapper>();

        //Query Task MDTs
        //Included where logic to refresh the component only with the active values
        List<Community_Task__mdt> taskMDTList = [SELECT Id, DeveloperName, Label FROM Community_Task__mdt where Deactivate__c = false];

        //For each MDT create a wrapper
        for(Community_Task__mdt theTaskMDT : taskMDTList){
            returnList.add(formatMDTtoWrapper(theTaskMDT,null));

        }

        return returnList;
    }

    /*
        Create Task Wrapper from Task MDTs queried by Group ID
     */
    public static List<Peak_CommunityTaskWrapper> getTasksForGroupsList(List<Id> groupIds){

        List<Peak_CommunityTaskWrapper> taskList = new List<Peak_CommunityTaskWrapper>();

        //Tasks related to passed in Groups
        List<Id> taskIds = new List<Id>();

        //Query junction MDTs related to Groups
        List<Community_Task_Group_Assignment__mdt> taskGroupAssignments = new List<Community_Task_Group_Assignment__mdt>();
        try {
            taskGroupAssignments = [SELECT Task__r.Id, Order__c
                                    FROM Community_Task_Group_Assignment__mdt
                                    WHERE Group__r.Id in :groupIds];

        } catch(System.QueryException sqe) {
            throw new System.QueryException('Could not find My Custom Metadata Type' + sqe.getMessage());
        }

        //Create Map of the GroupAssignment Task's Id and Order
        Map<Id, Decimal> taskIdAndOrderMap = new Map<Id, Decimal>();
        for(Community_Task_Group_Assignment__mdt theAssignment : taskGroupAssignments){
            taskIdAndOrderMap.put(theAssignment.Task__r.Id, theAssignment.Order__c);
        }

        //Loop through junctions to get Tasks related to Groups
        for (Community_Task_Group_Assignment__mdt taskGroupAssignment : taskGroupAssignments) {
            taskIds.add(taskGroupAssignment.Task__r.Id);
        }

        //Query the Task MDTs in the list
        List<Community_Task__mdt> relatedTasks = new List<Community_Task__mdt>();
        try{
            relatedTasks = [SELECT Id, DeveloperName, Label
                            FROM Community_Task__mdt
                            WHERE Id in :taskIds];

        } catch(System.QueryException sqe) {
            throw new System.QueryException('Could not find My Custom Metadata Type' + sqe.getMessage());
        }

        //Loop through Task MDTs to create wrappers, grabbing Order from Map
        for (Community_Task__mdt thisTask : relatedTasks) {
            //taskList.add(new Peak_CommunityTaskMDTWrapper(true, thisTask));
            taskList.add(formatMDTtoWrapper(thisTask, taskIdAndOrderMap.get(thisTask.Id)));
        }

        return taskList;
    }

    /*
        Format Task MDT into Wrapper
    */
    public static Peak_CommunityTaskWrapper formatMDTtoWrapper(Community_Task__mdt mdtTask, Decimal taskOrder){
        Peak_CommunityTaskWrapper taskWrapper = new Peak_CommunityTaskWrapper();

        taskWrapper.isSelected = false; 
        taskWrapper.label = mdtTask.Label;
        taskWrapper.order = taskOrder;
        taskWrapper.id = mdtTask.id;
        taskWrapper.name = mdtTask.DeveloperName; // Copying Developer name of metadata type record

        return taskWrapper;

    }

    //Inner class to wrap metadata
    public class Peak_CommunityTaskWrapper{

        @AuraEnabled public String name {get;set;} // Developer name of metadata type record
        @AuraEnabled public Boolean isSelected {get;set;}
        @AuraEnabled public String label {get;set;}
        @AuraEnabled public Decimal order {get;set;}
        @AuraEnabled public String id {get;set;}
    }
}