force-app/main/default/objects/Community_Task__mdt/Community_Task__mdt.object-meta.xml
<CustomObject>
    <label>Community Task</label>
    <pluralLabel>Community Tasks</pluralLabel>
</CustomObject>

force-app/main/default/objects/Community_Task__mdt/fields/Deactivate__c.field-meta.xml
<CustomField>
    <fullName>Deactivate__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to activate and deactivate a task instead of completely deleting the task. This field helps in displaying only the active Tasks on the component</description>
    <label>Deactivate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Community_Task_Group__mdt/Community_Task_Group__mdt.object-meta.xml
<CustomObject>
    <label>Community Task Group</label>
    <pluralLabel>Community Task Groups</pluralLabel>
</CustomObject>

force-app/main/default/objects/Community_Task_Group__mdt/fields/Deactivate__c.field-meta.xml
<CustomField>
    <fullName>Deactivate__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to activate and deactivate a Task Group instead of completely deleting the group. This field helps in displaying only the active Task Groups on the component</description>
    <label>Deactivate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Community_Task_Group_Assignment__mdt/Community_Task_Group_Assignment__mdt.object-meta.xml
<CustomObject>
    <label>Community Task Group Assignment</label>
    <pluralLabel>Community Task Group Assignments</pluralLabel>
</CustomObject>

force-app/main/default/objects/Community_Task_Group_Assignment__mdt/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <referenceTo>Community_Task_Group__mdt</referenceTo>
    <relationshipLabel>Community Task Group Assignments</relationshipLabel>
    <relationshipName>Community_Task_Group_Assignments</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Community_Task_Group_Assignment__mdt/fields/Task__c.field-meta.xml
<CustomField>
    <fullName>Task__c</fullName>
    <label>Task</label>
    <referenceTo>Community_Task__mdt</referenceTo>
    <relationshipLabel>Community Task Group Assignments</relationshipLabel>
    <relationshipName>Community_Task_Group_Assignments</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Peak_Metadata_Deploy_Result__c/Peak_Metadata_Deploy_Result__c.object-meta.xml
<CustomObject>
    <label>Peak Metadata Deploy Result</label>
    <nameField>
        <label>Peak Metadata Deploy Result Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Peak Metadata Deploy Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <label>Task</label>
</RecordType>

force-app/main/default/classes/Peak_ChecklistMDTGroupTasksController.cls
/**
 * Created by shashiarrabeli on 5/12/18.
 */

public class Peak_ChecklistMDTGroupTasksController
{
    
    @AuraEnabled
    public static List<Community_Task_Group_Assignment__mdt> getTaskGroupAssignment(){
        List<Community_Task_Group_Assignment__mdt> taskGroupAssignmentList = new List<Community_Task_Group_Assignment__mdt>();
        if(!test.isRunningTest()){
            taskGroupAssignmentList = [select Id, Order__c, Group__c, Task__c from Community_Task_Group_Assignment__mdt where Deactivate__c = false order by Order__c];
        }
        return taskGroupAssignmentList;
    }

    @AuraEnabled
    //Saves the selected group along with tasks selected for that group
    public static Peak_Response saveTaskGroupAssignments (string taskGroupName, List<String> selectedTaskNames)
    {
        Peak_Response peakResponse = new Peak_Response();
        
        //Creating Map to fetch existing task Group Assignments
        Map<String, Community_Task_Group_Assignment__mdt> mapExistingGroupAssignments = new Map<String, Community_Task_Group_Assignment__mdt>();
        
        //Set to contain taskIds to be deactivated
        set<Id> setTasksToDeactivate = new Set<Id>();
        
        //set to contain Task Names to be deactivated
        set<String> setTaskNamesToDeactivate = new Set<String>();

        Community_Task_Group__mdt objTaskGroup = new Community_Task_Group__mdt();
        Map<Id, Community_Task__mdt> mapTasks = new Map<Id, Community_Task__mdt>();
        List<Community_Task_Group_Assignment__mdt> objAssignmentList = new List<Community_Task_Group_Assignment__mdt>();

        if(!test.isRunningTest()){
            //Fetching Selected Group Information(Id)
            objTaskGroup = [select Id, DeveloperName from Community_Task_Group__mdt where DeveloperName = :taskGroupName];

            //Fetching selected Tasks Information(task Ids)
            mapTasks = new Map<Id, Community_Task__mdt>([select Id, DeveloperName from Community_Task__mdt where DeveloperName in:selectedTaskNames]);
            //Fetching existing task-group assignments
            objAssignmentList = [select Id, Group__c, Task__c, DeveloperName, MasterLabel from Community_Task_Group_Assignment__mdt where Group__c = :objTaskGroup.Id];
        }else {

            //Creating a fake assignment for testing -- so we don't rely on querying MDTs
            Community_Task_Group_Assignment__mdt fakeAssignment = new Community_Task_Group_Assignment__mdt();
            objAssignmentList.add(fakeAssignment);
        }

        
        //Fetching existing task-group assignments and adding it to Map
        for(Community_Task_Group_Assignment__mdt objAssignment: objAssignmentList){
            if(!mapTasks.containsKey(objAssignment.Task__c)){
                setTasksToDeactivate.add(objAssignment.Task__c);
                mapExistingGroupAssignments.put(objTaskGroup.DeveloperName + '~' +objAssignment.Task__c, objAssignment);
            }
            else{
                mapExistingGroupAssignments.put(objTaskGroup.DeveloperName + '~' +mapTasks.get(objAssignment.Task__c).DeveloperName, objAssignment);
            }
                
        }
        
        //if there are tasks to be deactivated adding it to the selected task list so it can be processed
        if(!setTasksToDeactivate.isEmpty()){

            if(!test.isRunningTest()) {

                mapTasks = new Map<Id, Community_Task__mdt>([select Id, DeveloperName from Community_Task__mdt where id in:setTasksToDeactivate]);
            }
            
            for(Id taskId: setTasksToDeactivate){
                if(!test.isRunningTest()) {
                    selectedTaskNames.add(mapTasks.get(taskId).DeveloperName);
                    setTaskNamesToDeactivate.add(mapTasks.get(taskId).DeveloperName);
                    mapExistingGroupAssignments.put(objTaskGroup.DeveloperName + '~' + mapTasks.get(taskId).DeveloperName, mapExistingGroupAssignments.get(objTaskGroup.DeveloperName + '~' + taskId));
                    mapExistingGroupAssignments.remove(objTaskGroup.DeveloperName + '~' + taskId);
                }
            }
        }
        
        try{
            Metadata.DeployContainer mdContainer = new Metadata.DeployContainer();
            
            Integer count = 1;
            for(String selectedTaskName : selectedTaskNames){
                // Set up custom metadata to be created in the subscriber org.
                Metadata.CustomMetadata customMetadata =  new Metadata.CustomMetadata();
                
                //if task-group Assignment already exists
                if(mapExistingGroupAssignments.containsKey(taskGroupName + '~' + selectedTaskName)){
                    customMetadata.fullName = 'Community_Task_Group_Assignment.'+mapExistingGroupAssignments.get(taskGroupName + '~' + selectedTaskName).DeveloperName;
                    customMetadata.label = mapExistingGroupAssignments.get(taskGroupName + '~' + selectedTaskName).MasterLabel;
                    
                    Metadata.CustomMetadataValue deactivateField = deactivateField(setTaskNamesToDeactivate,selectedTaskName);
                    customMetadata.values.add(deactivateField);
                }
                else{
                    //Generating a new for new task-group Assignment record
                    String newTaskGroupLabel=taskGroupName+'_'+Integer.valueOf(Math.random()*100000000);

                    customMetadata.fullName = 'Community_Task_Group_Assignment.'+newTaskGroupLabel;
                    customMetadata.label = newTaskGroupLabel;
                }
                
                Metadata.CustomMetadataValue groupField = new Metadata.CustomMetadataValue();

                groupField.field = 'Group__c';
                groupField.value = taskGroupName;

                Metadata.CustomMetadataValue taskField = new Metadata.CustomMetadataValue();

                taskField.field = 'Task__c';
                taskField.value = selectedTaskName;
                
                Metadata.CustomMetadataValue orderField = new Metadata.CustomMetadataValue();

                orderField.field = 'Order__c';
                orderField.value = count;
                
                customMetadata.values.add(groupField);
                customMetadata.values.add(taskField);
                customMetadata.values.add(orderField);
                
                count++; 
                
                mdContainer.addMetadata(customMetadata);
            }

            Peak_CustomMetadataCallback callback = new Peak_CustomMetadataCallback();

            // Enqueue custom metadata deployment
            // jobId is the deployment ID
            
            if(count > 1){
                Id jobId;
                if(!test.isRunningTest()) {
                    jobId = Metadata.Operations.enqueueDeployment(mdContainer, callback);
                }
                peakResponse.messages.add(jobId);
            }
            else{
                peakResponse.success = false;
                peakResponse.messages.add('Nothing to Save');
            }        

            //peakResponse.results.add(checklist);
        } catch (exception e) {
            peakResponse.success = false;
            peakResponse.messages.add(e.getMessage());
        }
        // Return result and possible error messages
        return peakResponse;
    }

    //  A new method to query Peak Metadata Deploy Result by ID
    @AuraEnabled
    public static Peak_Response getDeployGroupResult(String jobId){

        Peak_Response peakResponse = new Peak_Response();
        try{
            peakResponse.results = [Select Success__c, Detailed_Message__c from Peak_Metadata_Deploy_Result__c where Job_ID__c = :jobId];
        } catch (Exception e){
            peakResponse.success = false;
            peakResponse.messages.add(e.getMessage());
        }
        return peakResponse;
    }

    public static Metadata.CustomMetadataValue deactivateField(set<String> setTaskNamesToDeactivate, String selectedTaskName){
        Metadata.CustomMetadataValue deactivateField = new Metadata.CustomMetadataValue();
        deactivateField.field = 'Deactivate__c';

        //setting Deactivate__c field to true
        if(setTaskNamesToDeactivate.contains(selectedTaskName)){
            deactivateField.value = true;
        }
        else
        {
            deactivateField.value = false;
        }
        return deactivateField;
    }

}