force-app/main/default/objects/Adventure__c/Adventure__c.object-meta.xml
<CustomObject>
    <label>Adventure</label>
    <nameField>
        <label>Adventure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Adventures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Adventure__c/fields/Number_of_Completed_Tasks__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Completed_Tasks__c</fullName>
    <label>Number of Completed Tasks</label>
    <summarizedField>Adventure_Step__c.Number_of_Completed_Tasks__c</summarizedField>
    <summaryForeignKey>Adventure_Step__c.Adventure__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Adventure__c/fields/Number_of_Tasks__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Tasks__c</fullName>
    <label>Number of Tasks</label>
    <summarizedField>Adventure_Step__c.Number_of_Tasks__c</summarizedField>
    <summaryForeignKey>Adventure_Step__c.Adventure__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Adventure_Step__c/Adventure_Step__c.object-meta.xml
<CustomObject>
    <label>Adventure Step</label>
    <nameField>
        <label>Adventure Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Adventure Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Adventure_Step__c/fields/Adventure__c.field-meta.xml
<CustomField>
    <fullName>Adventure__c</fullName>
    <description>The Adventure that the Adventure Step belongs to</description>
    <inlineHelpText>This is the Adventure this Adventure Step belongs to</inlineHelpText>
    <label>Adventure</label>
    <referenceTo>Adventure__c</referenceTo>
    <relationshipName>Adventure_Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Adventure_Step__c/fields/Completed__c.field-meta.xml
<CustomField>
    <fullName>Completed__c</fullName>
    <formula>Number_of_Tasks__c =  Number_of_Completed_Tasks__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Adventure_Step__c/fields/Number_of_Completed_Tasks__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Completed_Tasks__c</fullName>
    <label>Number of Completed Tasks</label>
    <summarizedField>Step_Module__c.Number_of_Completed_Tasks__c</summarizedField>
    <summaryForeignKey>Step_Module__c.Adventure_Step__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Adventure_Step__c/fields/Number_of_Tasks__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Tasks__c</fullName>
    <label>Number of Tasks</label>
    <summarizedField>Step_Module__c.Number_of_Tasks__c</summarizedField>
    <summaryForeignKey>Step_Module__c.Adventure_Step__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Adventure_Step__c/fields/Task_Progress__c.field-meta.xml
<CustomField>
    <fullName>Task_Progress__c</fullName>
    <formula>Number_of_Completed_Tasks__c  /  Number_of_Tasks__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>% Task Progress</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <label>Task</label>
</RecordType>

force-app/main/default/objects/X7S_Adventure__c/X7S_Adventure__c.object-meta.xml
<CustomObject>
    <description>Object to support Learning Adventure records as part of the Learning Adventure accelerator from 7Summits.</description>
    <label>7S Adventure</label>
    <nameField>
        <label>7S Adventure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>7S Adventures</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/X7S_Adventure__c/fields/Completed__c.field-meta.xml
<CustomField>
    <fullName>Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure__c/fields/Number_of_Completed_Tasks__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Completed_Tasks__c</fullName>
    <label>Number of Completed Tasks</label>
    <summarizedField>X7S_Adventure_Step__c.Number_of_Completed_Tasks__c</summarizedField>
    <summaryForeignKey>X7S_Adventure_Step__c.Adventure__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure__c/fields/Number_of_Tasks__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Tasks__c</fullName>
    <label>Number of Tasks</label>
    <summarizedField>X7S_Adventure_Step__c.Number_of_Tasks__c</summarizedField>
    <summaryForeignKey>X7S_Adventure_Step__c.Adventure__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure__c/fields/Task_Progress__c.field-meta.xml
<CustomField>
    <fullName>Task_Progress__c</fullName>
    <formula>Number_of_Completed_Tasks__c /  Number_of_Tasks__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>% Task Progress</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Module__c/X7S_Adventure_Module__c.object-meta.xml
<CustomObject>
    <description>Object to support Learning Adventure Module records as part of the Learning Adventure accelerator from 7Summits.</description>
    <label>7S Adventure Module</label>
    <nameField>
        <label>7S Adventure Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>7S Adventure Modules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/X7S_Adventure_Module__c/fields/Adventure__c.field-meta.xml
<CustomField>
    <fullName>Adventure__c</fullName>
    <formula>Adventure_Step__r.Adventure__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Adventure</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Module__c/fields/Adventure_Step__c.field-meta.xml
<CustomField>
    <fullName>Adventure_Step__c</fullName>
    <description>The Adventure Step that contains this Step Module</description>
    <inlineHelpText>The Adventure Step that contains this Step Module</inlineHelpText>
    <label>Adventure Step</label>
    <referenceTo>X7S_Adventure_Step__c</referenceTo>
    <relationshipName>X7S_Step_Modules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Module__c/fields/Completed__c.field-meta.xml
<CustomField>
    <fullName>Completed__c</fullName>
    <formula>IF(Number_of_Tasks__c &gt; 0, Number_of_Tasks__c = Number_of_Completed_Tasks__c,  Completed_Manual__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Completed (Formula)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Module__c/fields/Number_of_Completed_Tasks__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Completed_Tasks__c</fullName>
    <label>Number of Completed Tasks</label>
    <summaryFilterItems>
        <field>X7S_Adventure_Task__c.Completed__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>X7S_Adventure_Task__c.Adventure_Module__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Module__c/fields/Number_of_Tasks__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Tasks__c</fullName>
    <description>Total number of Module Tasks in this Step Module</description>
    <inlineHelpText>Total number of Module Tasks in this Step Module</inlineHelpText>
    <label>Number of Tasks</label>
    <summaryForeignKey>X7S_Adventure_Task__c.Adventure_Module__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Step__c/X7S_Adventure_Step__c.object-meta.xml
<CustomObject>
    <description>Object to support Learning Adventure Step records as part of the Learning Adventure accelerator from 7Summits.</description>
    <label>7S Adventure Step</label>
    <nameField>
        <label>7S Adventure Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>7S Adventure Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/X7S_Adventure_Step__c/fields/Adventure__c.field-meta.xml
<CustomField>
    <fullName>Adventure__c</fullName>
    <description>The Adventure that the Adventure Step belongs to</description>
    <inlineHelpText>This is the Adventure this Adventure Step belongs to</inlineHelpText>
    <label>Adventure</label>
    <referenceTo>X7S_Adventure__c</referenceTo>
    <relationshipName>X7S_Adventure_Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Step__c/fields/Number_of_Completed_Tasks__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Completed_Tasks__c</fullName>
    <label>Number of Completed Tasks</label>
    <summarizedField>X7S_Adventure_Module__c.Number_of_Completed_Tasks__c</summarizedField>
    <summaryForeignKey>X7S_Adventure_Module__c.Adventure_Step__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Step__c/fields/Number_of_Tasks__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Tasks__c</fullName>
    <label>Number of Tasks</label>
    <summarizedField>X7S_Adventure_Module__c.Number_of_Tasks__c</summarizedField>
    <summaryForeignKey>X7S_Adventure_Module__c.Adventure_Step__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Task__c/X7S_Adventure_Task__c.object-meta.xml
<CustomObject>
    <description>Object to support Learning Adventure Task records as part of the Learning Adventure accelerator from 7Summits.</description>
    <label>7S Adventure Task</label>
    <nameField>
        <label>7S Adventure Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>7S Adventure Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/X7S_Adventure_Task__c/fields/Adventure__c.field-meta.xml
<CustomField>
    <fullName>Adventure__c</fullName>
    <formula>Adventure_Module__r.Adventure_Step__r.Adventure__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Adventure</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Task__c/fields/Adventure_Module__c.field-meta.xml
<CustomField>
    <fullName>Adventure_Module__c</fullName>
    <description>The Adventure Module that contains this Module Task</description>
    <inlineHelpText>The Adventure Module that contains this Module Task</inlineHelpText>
    <label>Adventure Module</label>
    <referenceTo>X7S_Adventure_Module__c</referenceTo>
    <relationshipName>X7S_Adventure_Modules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Task__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>X7S_Adventure_Module_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/x7sAdventureModuleTasks.cls
/*
 * Copyright (c) 2020. 7Summits Inc.
 */


public with sharing class x7sAdventureModuleTasks {
    // on 2/06/2020: Task complete/not complete action method (Checkbox action)
    @AuraEnabled
    public static Boolean taskCompleted(Id selectedTaskId, Boolean checkboxFlag) {
        Boolean flagStatus = null;

        if (Schema.SObjectType.X7S_Adventure_Task__c.updateable &&
                Schema.SObjectType.X7S_Adventure_Task__c.fields.Completed__c.isUpdateable()) {
            try {
                if (selectedTaskId != null) {
                    List<X7S_Adventure_Task__c> taskSelectedList = new List<X7S_Adventure_Task__c>([SELECT Id,Completed__c FROM X7S_Adventure_Task__c WHERE Id = :selectedTaskId WITH SECURITY_ENFORCED LIMIT 1]);
                    List<X7S_Adventure_Task__c> updatedTaskList = new List<X7S_Adventure_Task__c>();
                    if (taskSelectedList.size() > 0) {
                        for (X7S_Adventure_Task__c taskRecord : taskSelectedList) {
                            taskRecord.Completed__c = checkboxFlag;
                            updatedTaskList.add(taskRecord);
                        }
                        if (updatedTaskList.size() > 0) {
                            x7sAdventureUtils.throwErrorIfUpdatePermissionMissing(Schema.SObjectType.X7S_Adventure_Task__c);
                            update updatedTaskList; // NOPMD - CRUD permissions validated in previous line

                            flagStatus = checkboxFlag;
                        }
                    }
                }
            } catch (Exception ex) {
                throw new AuraHandledException(ex.getMessage());
            }
        }
        return flagStatus;
    }

    // 19-02-2020 : Module Task Progress (Progress Ring)
    @AuraEnabled
    public static X7S_Adventure_Module__c getModuleTaskProgress(String moduleId) {
        try {
            X7S_Adventure_Module__c queryResult;

            if (moduleId != null) {
                X7S_Adventure_Module__c updatedTaskProgress = [SELECT Number_of_Tasks__c, Task_Progress__c, Completed__c FROM X7S_Adventure_Module__c WHERE Id = :moduleId WITH SECURITY_ENFORCED LIMIT 1];
                queryResult = updatedTaskProgress;
            }
            return queryResult;
        } catch (Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }

    // 26-02-2020 : My Module Task Progress "Filtered tasks" (Progress Ring)
    @AuraEnabled
    public static x7sAdventureMyModuleTaskWrapper getMyModuleTaskProgress(String moduleId, Id ownerId) {
        try {
            x7sAdventureMyModuleTaskWrapper myModule;

            if (moduleId != null && ownerId != null) {

                List<X7S_Adventure_Task__c> tasksList = [SELECT Id,Completed__c FROM X7S_Adventure_Task__c WHERE Adventure_Module__c = :moduleId AND Owner__c = :ownerId WITH SECURITY_ENFORCED];
                myModule = x7sAdventureMyModuleTaskWrapperHelper.createWrapper(tasksList);
            }

            return myModule;
        } catch (Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }

    // 26-02-2020 : My Adventure Progress after "Filtered tasks"
    @AuraEnabled
    public static x7sAdventureMyProgress getMyAdventureProgress(Id adventureId, Id ownerId) {
        try {
            x7sAdventureMyProgress myAdventureProgress = new x7sAdventureMyProgress();
            Integer totalTasks = 0;
            Integer totalCompleteTasks = 0;
            Decimal adventureProgress = 0;
            List<Id> myStepIdList = new List<Id>();
            List<Id> myModuleIdList = new List<Id>();

            if (ownerId != null && adventureId != null) {
                List<X7S_Adventure_Step__c> myAdventure = new List<X7S_Adventure_Step__c>([SELECT Id FROM X7S_Adventure_Step__c WHERE Adventure__c = :adventureId]);

                if (myAdventure.size() > 0) {
                    for (X7S_Adventure_Step__c adve : myAdventure) {
                        myStepIdList.add(adve.Id);
                    }

                    String stepMyModuleQuery = 'SELECT Id FROM X7S_Adventure_Module__c WHERE Adventure_Step__c IN: myStepIdList';
                    List<X7S_Adventure_Module__c> stepModules = Database.query(stepMyModuleQuery);

                    for (X7S_Adventure_Module__c moduleId : stepModules) {
                        myModuleIdList.add(moduleId.Id);
                    }
                    //String 	taskSummary = 'SELECT id,Completed__c FROM X7S_Adventure_Task__c WHERE Adventure_Module__c IN: myModuleIdList AND Owner__c =:OwnerId';

                    String totalTaskSummary = 'SELECT count() FROM X7S_Adventure_Task__c WHERE Adventure_Module__c IN: myModuleIdList AND Owner__c =:ownerId';
                    totalTasks = Database.countQuery(totalTaskSummary);

                    String totalCompleteTaskSummary = 'SELECT count() FROM X7S_Adventure_Task__c WHERE Adventure_Module__c IN: myModuleIdList AND Owner__c =:ownerId AND Completed__c =true';
                    totalCompleteTasks = Database.countQuery(totalCompleteTaskSummary);

                    myAdventureProgress.totalTasksAssigned = totalTasks;
                    myAdventureProgress.totalCompletedTasks = totalCompleteTasks;

                    if (totalTasks > 0) {
                        adventureProgress = (Decimal.valueOf(totalCompleteTasks) / Decimal.valueOf(totalTasks)) * 100;
                    }
                    myAdventureProgress.adventureProgress = adventureProgress.setScale(0);
                }
            }
            return myAdventureProgress;
        } catch (Exception ex) {
            System.debug('Error Line: ' + ex.getLineNumber());
            throw new AuraHandledException(ex.getMessage());
        }
    }

    @AuraEnabled
    public static x7sAdventureMyProgress getAdventureProgress(Id adventureId) {
        try {
            x7sAdventureMyProgress myAdventureProgress = new x7sAdventureMyProgress();
            Integer totalTasks = 0;
            Integer totalCompleteTasks = 0;
            Decimal adventureProgress = 0;

            if (adventureId != null) {
                String getAdventure = 'SELECT Id,Number_of_Completed_Tasks__c,Task_Progress__c,Number_of_Tasks__c From X7S_Adventure__c  WHERE Id =:adventureId LIMIT 1';
                X7S_Adventure__c myAllAdventure = Database.query(getAdventure);

                if (myAllAdventure != null) {
                    totalTasks = Integer.valueOf(myAllAdventure.Number_of_Tasks__c) ;
                    totalCompleteTasks = Integer.valueOf(myAllAdventure.Number_of_Completed_Tasks__c);
                    adventureProgress = myAllAdventure.Task_Progress__c;
                }
                myAdventureProgress.totalTasksAssigned = totalTasks;
                myAdventureProgress.totalCompletedTasks = totalCompleteTasks;
                myAdventureProgress.adventureProgress = adventureProgress.setScale(0);
            }

            return myAdventureProgress;

        } catch (Exception ex) {
            System.debug('Error Line: ' + ex.getLineNumber());
            throw new AuraHandledException(ex.getMessage());
        }
    }
}