force-app/main/default/objects/Adventure__c/Adventure__c.object-meta.xml
<CustomObject>
    <label>Adventure</label>
    <nameField>
        <label>Adventure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Adventures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Adventure__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Title to display in Adventure Header</description>
    <inlineHelpText>This is the title that will be displayed in the Adventure header</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Adventure_Step__c/Adventure_Step__c.object-meta.xml
<CustomObject>
    <label>Adventure Step</label>
    <nameField>
        <label>Adventure Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Adventure Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Adventure_Step__c/fields/Adventure__c.field-meta.xml
<CustomField>
    <fullName>Adventure__c</fullName>
    <description>The Adventure that the Adventure Step belongs to</description>
    <inlineHelpText>This is the Adventure this Adventure Step belongs to</inlineHelpText>
    <label>Adventure</label>
    <referenceTo>Adventure__c</referenceTo>
    <relationshipName>Adventure_Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Adventure_Step__c/fields/Completed__c.field-meta.xml
<CustomField>
    <fullName>Completed__c</fullName>
    <formula>Number_of_Tasks__c =  Number_of_Completed_Tasks__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Adventure_Step__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>This is the description of the Adventure Step that will be displayed under the Subtitle</description>
    <inlineHelpText>This is the description of the Adventure Step that will be displayed under the Subtitle</inlineHelpText>
    <label>Description</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Adventure_Step__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>The order in which the adventure steps should be displayed</description>
    <label>Order</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Adventure_Step__c/fields/Subtitle__c.field-meta.xml
<CustomField>
    <fullName>Subtitle__c</fullName>
    <description>Subtitle of the Adventure Step which will be displayed in the header</description>
    <inlineHelpText>This is the subtitle of the Adventure Step which will be displayed in the header</inlineHelpText>
    <label>Subtitle</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Adventure_Step__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>The title of the Adventure Step</description>
    <inlineHelpText>This is the title that will be displayed in the map for this Adventure Step</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <label>Task</label>
</RecordType>

force-app/main/default/objects/X7S_Adventure__c/X7S_Adventure__c.object-meta.xml
<CustomObject>
    <description>Object to support Learning Adventure records as part of the Learning Adventure accelerator from 7Summits.</description>
    <label>7S Adventure</label>
    <nameField>
        <label>7S Adventure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>7S Adventures</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/X7S_Adventure__c/fields/Completed__c.field-meta.xml
<CustomField>
    <fullName>Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure__c/fields/Subtitle__c.field-meta.xml
<CustomField>
    <fullName>Subtitle__c</fullName>
    <label>Subtitle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Title to display in Adventure Header</description>
    <inlineHelpText>This is the title that will be displayed in the Adventure header</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Module__c/X7S_Adventure_Module__c.object-meta.xml
<CustomObject>
    <description>Object to support Learning Adventure Module records as part of the Learning Adventure accelerator from 7Summits.</description>
    <label>7S Adventure Module</label>
    <nameField>
        <label>7S Adventure Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>7S Adventure Modules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/X7S_Adventure_Module__c/fields/Adventure__c.field-meta.xml
<CustomField>
    <fullName>Adventure__c</fullName>
    <formula>Adventure_Step__r.Adventure__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Adventure</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Module__c/fields/Adventure_Step__c.field-meta.xml
<CustomField>
    <fullName>Adventure_Step__c</fullName>
    <description>The Adventure Step that contains this Step Module</description>
    <inlineHelpText>The Adventure Step that contains this Step Module</inlineHelpText>
    <label>Adventure Step</label>
    <referenceTo>X7S_Adventure_Step__c</referenceTo>
    <relationshipName>X7S_Step_Modules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Module__c/fields/Completed__c.field-meta.xml
<CustomField>
    <fullName>Completed__c</fullName>
    <formula>IF(Number_of_Tasks__c &gt; 0, Number_of_Tasks__c = Number_of_Completed_Tasks__c,  Completed_Manual__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Completed (Formula)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Module__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>The order in which to display the Step Module</description>
    <inlineHelpText>The order in which to display the Step Module</inlineHelpText>
    <label>Order</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Module__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>The title of the Step Module that will be displayed above the card</description>
    <inlineHelpText>The title of the Step Module that will be displayed above the card</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Module__c/fields/Tooltip_Description__c.field-meta.xml
<CustomField>
    <fullName>Tooltip_Description__c</fullName>
    <description>Text to be displayed in the tooltip for this Step Module</description>
    <inlineHelpText>Text to be displayed in the tooltip for this Step Module</inlineHelpText>
    <label>Tooltip Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Step__c/X7S_Adventure_Step__c.object-meta.xml
<CustomObject>
    <description>Object to support Learning Adventure Step records as part of the Learning Adventure accelerator from 7Summits.</description>
    <label>7S Adventure Step</label>
    <nameField>
        <label>7S Adventure Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>7S Adventure Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/X7S_Adventure_Step__c/fields/Adventure__c.field-meta.xml
<CustomField>
    <fullName>Adventure__c</fullName>
    <description>The Adventure that the Adventure Step belongs to</description>
    <inlineHelpText>This is the Adventure this Adventure Step belongs to</inlineHelpText>
    <label>Adventure</label>
    <referenceTo>X7S_Adventure__c</referenceTo>
    <relationshipName>X7S_Adventure_Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Step__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>This is the description of the Adventure Step that will be displayed under the Subtitle</description>
    <inlineHelpText>This is the description of the Adventure Step that will be displayed under the Subtitle</inlineHelpText>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Step__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>The order in which the adventure steps should be displayed</description>
    <label>Order</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Step__c/fields/Subtitle__c.field-meta.xml
<CustomField>
    <fullName>Subtitle__c</fullName>
    <description>Subtitle of the Adventure Step which will be displayed in the header</description>
    <inlineHelpText>This is the subtitle of the Adventure Step which will be displayed in the header</inlineHelpText>
    <label>Subtitle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Task__c/X7S_Adventure_Task__c.object-meta.xml
<CustomObject>
    <description>Object to support Learning Adventure Task records as part of the Learning Adventure accelerator from 7Summits.</description>
    <label>7S Adventure Task</label>
    <nameField>
        <label>7S Adventure Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>7S Adventure Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/X7S_Adventure_Task__c/fields/Adventure__c.field-meta.xml
<CustomField>
    <fullName>Adventure__c</fullName>
    <formula>Adventure_Module__r.Adventure_Step__r.Adventure__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Adventure</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Task__c/fields/Adventure_Module__c.field-meta.xml
<CustomField>
    <fullName>Adventure_Module__c</fullName>
    <description>The Adventure Module that contains this Module Task</description>
    <inlineHelpText>The Adventure Module that contains this Module Task</inlineHelpText>
    <label>Adventure Module</label>
    <referenceTo>X7S_Adventure_Module__c</referenceTo>
    <relationshipName>X7S_Adventure_Modules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Task__c/fields/Content_URL__c.field-meta.xml
<CustomField>
    <fullName>Content_URL__c</fullName>
    <description>The URL linking to the content of this Module Task</description>
    <inlineHelpText>The URL linking to the content of this Module Task</inlineHelpText>
    <label>Content Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Task__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>The order in which to display the Module Task</description>
    <label>Order</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Task__c/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <description>The type of resource this Module Task offers</description>
    <inlineHelpText>The type of resource this Module Task offers</inlineHelpText>
    <label>Resource Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>question_answer</fullName>
                <label>FAQ</label>
            </value>
            <value>
                <fullName>File</fullName>
            </value>
            <value>
                <fullName>Knowledge Base</fullName>
            </value>
            <value>
                <fullName>podcast_webinar</fullName>
                <label>Podcast/Webinar</label>
            </value>
            <value>
                <fullName>Question</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>Trailhead</fullName>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Task__c/fields/Task_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Task_Due_Date__c</fullName>
    <description>The due date for this Task</description>
    <inlineHelpText>The due date for this Task</inlineHelpText>
    <label>Task Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Task__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>The title of this Module Task to be displayed next to icon</description>
    <inlineHelpText>The title of this Module Task to be displayed next to icon</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/x7sAdventureMyStepModuleWrapperTest.cls
/*
 * Copyright (c) 2020. 7Summits Inc.
 */
@IsTest
public with sharing class x7sAdventureMyStepModuleWrapperTest {

    @TestSetup
    public static void testSetup() {

        //Create test adventure
        X7S_Adventure__c testAdventure = new X7S_Adventure__c(Name = x7sAdventureTestConstants.TEST_ADVENTURE_NAME, Title__c = x7sAdventureTestConstants.TEST_ADVENTURE_NAME);
        insert testAdventure;

        //Create test Adventure Step
        X7S_Adventure_Step__c testAdventureStep = new X7S_Adventure_Step__c(Name = x7sAdventureTestConstants.TEST_ADVENTURE_STEP_NAME,
                Title__c = x7sAdventureTestConstants.TEST_ADVENTURE_STEP_NAME, Adventure__c = testAdventure.Id,
                Subtitle__c = x7sAdventureTestConstants.TEST_ADVENTURE_STEP_SUBTITLE, Description__c = x7sAdventureTestConstants.TEST_ADVENTURE_STEP_DESCRIPTION);
        insert testAdventureStep;

        //Create test Step Module
        X7S_Adventure_Module__c testStepModule = new X7S_Adventure_Module__c(Name = x7sAdventureTestConstants.TEST_STEP_MODULE_NAME,
                Title__c = x7sAdventureTestConstants.TEST_STEP_MODULE_NAME, Adventure_Step__c = testAdventureStep.Id);
        insert testStepModule;

        //Create test Module Task
        X7S_Adventure_Task__c testModuleTask = new X7S_Adventure_Task__c(Name = x7sAdventureTestConstants.TEST_MODULE_TASK_NAME,
                Title__c = x7sAdventureTestConstants.TEST_MODULE_TASK_NAME, Content_URL__c = x7sAdventureTestConstants.TEST_URL,
                Resource_Type__c = x7sAdventureTestConstants.TEST_RESOURCE_TYPE, Completed__c = x7sAdventureTestConstants.TEST_MODULE_TASK_Completed,
                Adventure_Module__c = testStepModule.Id);
        insert testModuleTask;
        X7S_Adventure_Task__c testModuleTask_1 = new X7S_Adventure_Task__c(Name = x7sAdventureTestConstants.TEST_MODULE_TASK_NAME,
                Title__c = x7sAdventureTestConstants.TEST_MODULE_TASK_NAME, Content_URL__c = x7sAdventureTestConstants.TEST_URL,
                Resource_Type__c = x7sAdventureTestConstants.TEST_RESOURCE_TYPE, Completed__c = x7sAdventureTestConstants.TEST_MODULE_TASK_Completed,
                Adventure_Module__c = testStepModule.Id);
        insert testModuleTask_1;
        X7S_Adventure_Task__c testModuleTask_2 = new X7S_Adventure_Task__c(Name = x7sAdventureTestConstants.TEST_MODULE_TASK_NAME,
                Title__c = x7sAdventureTestConstants.TEST_MODULE_TASK_NAME, Content_URL__c = x7sAdventureTestConstants.TEST_URL,
                Resource_Type__c = x7sAdventureTestConstants.TEST_RESOURCE_TYPE, Completed__c = x7sAdventureTestConstants.TEST_MODULE_TASK_Completed,
                Adventure_Module__c = testStepModule.Id);
        insert testModuleTask_2;

    }

    @IsTest
    public static void x7s_AdventureMyStepModuleWrapperHelperTest() {

        X7S_Adventure_Module__c testModule = [SELECT Id,Adventure_Step__c,Title__c,Description_Label__c,Description_URL__c,Tooltip_Description__c,Order__c FROM X7S_Adventure_Module__c LIMIT 1];
        List<X7S_Adventure_Task__c> testModuleTask = [SELECT Id,Completed__c,Task_Due_Date__c FROM X7S_Adventure_Task__c WHERE Adventure_Module__c = :testModule.Id];

        x7sAdventureStepModuleWrapper TestStepModule = x7sAdventureMyStepModuleWrapperHelper.createWrapper(testModule, testModuleTask);
        System.assertEquals(TestStepModule.taskProgress, 100);
        System.assertEquals(TestStepModule.completedFlag, true);

    }
}