force-app/main/default/objects/Adventure__c/Adventure__c.object-meta.xml
<CustomObject>
    <label>Adventure</label>
    <nameField>
        <label>Adventure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Adventures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Adventure__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Adventures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Adventure__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Template</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Adventure__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Title to display in Adventure Header</description>
    <inlineHelpText>This is the title that will be displayed in the Adventure header</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Adventure_Step__c/Adventure_Step__c.object-meta.xml
<CustomObject>
    <label>Adventure Step</label>
    <nameField>
        <label>Adventure Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Adventure Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Adventure_Step__c/fields/Adventure__c.field-meta.xml
<CustomField>
    <fullName>Adventure__c</fullName>
    <description>The Adventure that the Adventure Step belongs to</description>
    <inlineHelpText>This is the Adventure this Adventure Step belongs to</inlineHelpText>
    <label>Adventure</label>
    <referenceTo>Adventure__c</referenceTo>
    <relationshipName>Adventure_Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Adventure_Step__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>This is the description of the Adventure Step that will be displayed under the Subtitle</description>
    <inlineHelpText>This is the description of the Adventure Step that will be displayed under the Subtitle</inlineHelpText>
    <label>Description</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Adventure_Step__c/fields/Subtitle__c.field-meta.xml
<CustomField>
    <fullName>Subtitle__c</fullName>
    <description>Subtitle of the Adventure Step which will be displayed in the header</description>
    <inlineHelpText>This is the subtitle of the Adventure Step which will be displayed in the header</inlineHelpText>
    <label>Subtitle</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Adventure_Step__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>The title of the Adventure Step</description>
    <inlineHelpText>This is the title that will be displayed in the map for this Adventure Step</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <label>Task</label>
</RecordType>

force-app/main/default/objects/X7S_Adventure__c/X7S_Adventure__c.object-meta.xml
<CustomObject>
    <description>Object to support Learning Adventure records as part of the Learning Adventure accelerator from 7Summits.</description>
    <label>7S Adventure</label>
    <nameField>
        <label>7S Adventure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>7S Adventures</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/X7S_Adventure__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>X7S_Adventures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure__c/fields/Allow_Cloning__c.field-meta.xml
<CustomField>
    <fullName>Allow_Cloning__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indicate whether this adventure can be cloned.  If set to no, clone button will not be visible.</inlineHelpText>
    <label>Allow Cloning</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure__c/fields/Subtitle__c.field-meta.xml
<CustomField>
    <fullName>Subtitle__c</fullName>
    <label>Subtitle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Title to display in Adventure Header</description>
    <inlineHelpText>This is the title that will be displayed in the Adventure header</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Module__c/X7S_Adventure_Module__c.object-meta.xml
<CustomObject>
    <description>Object to support Learning Adventure Module records as part of the Learning Adventure accelerator from 7Summits.</description>
    <label>7S Adventure Module</label>
    <nameField>
        <label>7S Adventure Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>7S Adventure Modules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/X7S_Adventure_Module__c/fields/Adventure__c.field-meta.xml
<CustomField>
    <fullName>Adventure__c</fullName>
    <formula>Adventure_Step__r.Adventure__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Adventure</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Module__c/fields/Adventure_Step__c.field-meta.xml
<CustomField>
    <fullName>Adventure_Step__c</fullName>
    <description>The Adventure Step that contains this Step Module</description>
    <inlineHelpText>The Adventure Step that contains this Step Module</inlineHelpText>
    <label>Adventure Step</label>
    <referenceTo>X7S_Adventure_Step__c</referenceTo>
    <relationshipName>X7S_Step_Modules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Module__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>The title of the Step Module that will be displayed above the card</description>
    <inlineHelpText>The title of the Step Module that will be displayed above the card</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Step__c/X7S_Adventure_Step__c.object-meta.xml
<CustomObject>
    <description>Object to support Learning Adventure Step records as part of the Learning Adventure accelerator from 7Summits.</description>
    <label>7S Adventure Step</label>
    <nameField>
        <label>7S Adventure Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>7S Adventure Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/X7S_Adventure_Step__c/fields/Adventure__c.field-meta.xml
<CustomField>
    <fullName>Adventure__c</fullName>
    <description>The Adventure that the Adventure Step belongs to</description>
    <inlineHelpText>This is the Adventure this Adventure Step belongs to</inlineHelpText>
    <label>Adventure</label>
    <referenceTo>X7S_Adventure__c</referenceTo>
    <relationshipName>X7S_Adventure_Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Step__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>This is the description of the Adventure Step that will be displayed under the Subtitle</description>
    <inlineHelpText>This is the description of the Adventure Step that will be displayed under the Subtitle</inlineHelpText>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Step__c/fields/Subtitle__c.field-meta.xml
<CustomField>
    <fullName>Subtitle__c</fullName>
    <description>Subtitle of the Adventure Step which will be displayed in the header</description>
    <inlineHelpText>This is the subtitle of the Adventure Step which will be displayed in the header</inlineHelpText>
    <label>Subtitle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Task__c/X7S_Adventure_Task__c.object-meta.xml
<CustomObject>
    <description>Object to support Learning Adventure Task records as part of the Learning Adventure accelerator from 7Summits.</description>
    <label>7S Adventure Task</label>
    <nameField>
        <label>7S Adventure Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>7S Adventure Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/X7S_Adventure_Task__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Adventure_Module__r.Adventure_Step__r.Adventure__r.Account__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Task__c/fields/Adventure__c.field-meta.xml
<CustomField>
    <fullName>Adventure__c</fullName>
    <formula>Adventure_Module__r.Adventure_Step__r.Adventure__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Adventure</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Task__c/fields/Adventure_Module__c.field-meta.xml
<CustomField>
    <fullName>Adventure_Module__c</fullName>
    <description>The Adventure Module that contains this Module Task</description>
    <inlineHelpText>The Adventure Module that contains this Module Task</inlineHelpText>
    <label>Adventure Module</label>
    <referenceTo>X7S_Adventure_Module__c</referenceTo>
    <relationshipName>X7S_Adventure_Modules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Task__c/fields/Content_URL__c.field-meta.xml
<CustomField>
    <fullName>Content_URL__c</fullName>
    <description>The URL linking to the content of this Module Task</description>
    <inlineHelpText>The URL linking to the content of this Module Task</inlineHelpText>
    <label>Content Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Task__c/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <description>The type of resource this Module Task offers</description>
    <inlineHelpText>The type of resource this Module Task offers</inlineHelpText>
    <label>Resource Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>question_answer</fullName>
                <label>FAQ</label>
            </value>
            <value>
                <fullName>File</fullName>
            </value>
            <value>
                <fullName>Knowledge Base</fullName>
            </value>
            <value>
                <fullName>podcast_webinar</fullName>
                <label>Podcast/Webinar</label>
            </value>
            <value>
                <fullName>Question</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>Trailhead</fullName>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Task__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <formula>Adventure_Module__r.Adventure_Step__r.Adventure__r.Template__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Template</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Task__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>The title of this Module Task to be displayed next to icon</description>
    <inlineHelpText>The title of this Module Task to be displayed next to icon</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/x7sAdventureCloneProjectAssignmentTest.cls
/*
 * Copyright (c) 2020. 7Summits Inc.
 */
@IsTest
public with sharing class x7sAdventureCloneProjectAssignmentTest {


    @TestSetup
    public static void TestSetup() {
        //Create test adventure
        Account testAccount = new Account(Name = x7sAdventureCloneTestConstants.ACCOUNT_NAME);
        insert testAccount;


        //Create test adventure
        X7S_Adventure__c testAdventure = new X7S_Adventure__c(Name = x7sAdventureCloneTestConstants.TEST_ADVENTURE_NAME, Title__c = x7sAdventureCloneTestConstants.TEST_ADVENTURE_NAME,
                Account__c = testAccount.Id, Template__c = x7sAdventureCloneTestConstants.TEST_TEMPLATE_NAME, Allow_Cloning__c=true);
        insert testAdventure;

        //Create ContentVersion
        ContentVersion testContentVersion = new ContentVersion(Title = x7sAdventureCloneTestConstants.TEST_CONTENT_VERSION_TITLE, PathOnClient = x7sAdventureCloneTestConstants.TEST_CONTENT_VERSION_PATH_ON_CLIENT, VersionData = x7sAdventureCloneTestConstants.TEST_CONTENT_VERSION_VERSION_DATA, IsMajorVersion = x7sAdventureCloneTestConstants.TEST_CONTENT_VERSION_IS_MAJOR_VERSION);
        insert testContentVersion;

        //Get Content Documents
        Id conDocId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :testContentVersion.Id].ContentDocumentId;
        //Create ContentDocumentLink
        ContentDocumentLink cdl = new ContentDocumentLink(LinkedEntityId = testAdventure.Id, ContentDocumentId = conDocId, ShareType = 'V');
        insert cdl;

        //Create test Adventure Step
        X7S_Adventure_Step__c testAdventureStep = new X7S_Adventure_Step__c(Name = x7sAdventureCloneTestConstants.TEST_ADVENTURE_STEP_NAME,
                Title__c = x7sAdventureCloneTestConstants.TEST_ADVENTURE_STEP_NAME, Adventure__c = testAdventure.Id,
                Subtitle__c = x7sAdventureCloneTestConstants.TEST_ADVENTURE_STEP_SUBTITLE, Description__c = x7sAdventureCloneTestConstants.TEST_ADVENTURE_STEP_DESCRIPTION);
        insert testAdventureStep;

        //Create test Step Module
        X7S_Adventure_Module__c testStepModule = new X7S_Adventure_Module__c(Name = x7sAdventureCloneTestConstants.TEST_STEP_MODULE_NAME,
                Title__c = x7sAdventureCloneTestConstants.TEST_STEP_MODULE_NAME, Adventure_Step__c = testAdventureStep.Id);
        insert testStepModule;

        //Create test Module Task
        X7S_Adventure_Task__c testModuleTaskFirst = new X7S_Adventure_Task__c(Name = x7sAdventureCloneTestConstants.TEST_MODULE_TASK_NAME,
                Title__c = x7sAdventureCloneTestConstants.TEST_MODULE_TASK_NAME, Content_URL__c = x7sAdventureCloneTestConstants.TEST_URL,
                Resource_Type__c = x7sAdventureCloneTestConstants.TEST_RESOURCE_TYPE, Adventure_Module__c = testStepModule.Id, Restrict_to_User__c = x7sAdventureCloneTestConstants.TEST_MODULE_TASK_RESTRICT_TO_USER);
        insert testModuleTaskFirst;

        X7S_Adventure_Task__c testModuleTaskSecond = new X7S_Adventure_Task__c(Name = x7sAdventureCloneTestConstants.TEST_MODULE_TASK_NAME,
                Title__c = x7sAdventureCloneTestConstants.TEST_MODULE_TASK_NAME, Content_URL__c = x7sAdventureCloneTestConstants.TEST_URL,
                Resource_Type__c = x7sAdventureCloneTestConstants.TEST_RESOURCE_TYPE, Adventure_Module__c = testStepModule.Id, Restrict_to_User__c = x7sAdventureCloneTestConstants.TEST_MODULE_TASK_RESTRICT_TO_USER);
        insert testModuleTaskSecond;

        //Create and Associate Topics
        List<Topic> topics = x7sAdventureTestUtils.createTopic(3);  
        List<TopicAssignment> topicAssignmentList = new List<TopicAssignment>();    
        for(Topic topic : topics) {
            topicAssignmentList.add(new TopicAssignment(EntityId = testAdventure.Id, TopicId = topic.Id));      
        }
        if(topicAssignmentList.size() > 0) {
            insert topicAssignmentList;
        }

    }

    @IsTest
    public static void test_AdventureCloneProjectAssignment() {

        X7S_Adventure__c testAdventure = [SELECT Id FROM X7S_Adventure__c WHERE Name = :x7sAdventureCloneTestConstants.TEST_ADVENTURE_NAME];

        X7S_Adventure__c testClone = [SELECT Id,Name,Title__c FROM X7S_Adventure__c WHERE Id = :testAdventure.Id];
        List<X7S_Adventure__c> testAdventures = [SELECT Id, Name FROM X7S_Adventure__c WHERE Id = :testAdventure.Id];
        Integer adventureCount = [SELECT COUNT() FROM X7S_Adventure__c];
        Integer stepsCount = [SELECT COUNT() FROM X7S_Adventure_Step__c];
        Integer moduleCount = [SELECT COUNT() FROM X7S_Adventure_Module__c];
        Integer tasksCount = [SELECT COUNT() FROM X7S_Adventure_Task__c];

        Test.startTest();
        x7sAdventureCloneResponse cloneResponse = x7sAdventureCloneProjectAssignment.getConfiguration(testAdventure.Id);
        System.assertEquals(x7sAdventureCloneTestConstants.TEST_ADVENTURE_NAME + ' Copy', cloneResponse.clonedAdventureName);

        x7sAdventureCloneProjectAssignment.cloneAdventure(testAdventure.Id, x7sAdventureCloneTestConstants.TEST_ADVENTURE_NAME, false, '');
        System.assertEquals([SELECT COUNT() FROM X7S_Adventure__c], adventureCount + 1);
        System.assertEquals([SELECT COUNT() FROM X7S_Adventure_Step__c], stepsCount + 1);
        System.assertEquals([SELECT COUNT() FROM X7S_Adventure_Module__c], moduleCount + 1);
        
        Boolean canClone = x7sAdventureCloneProjectAssignment.checkCanClone(testAdventure.Id);
        System.assertEquals(canClone, true);

        Test.stopTest();
    }

    @IsTest
    public static void testCloneUsers() {
//        String userList = '0055x000008b0I5AAI,005f2000006NCN6AAO,0055x00000BV0ibAAD,005f2000009Na3hAAC,0055x00000BebHOAAZ,0055x00000BedYbAAJ,0055x00000BeeG4AAJ,0055x00000BewdHAAR,005f2000006NCN1AAO,005f2000006ND4PAAW,005f2000007DaUFAA0,005f2000007EtcXAAS,0055x000008b7KJAAY,';

        String              userList        = UserInfo.getUserId();

        X7S_Adventure__c    testAdventure   = [SELECT Id FROM X7S_Adventure__c WHERE Name = :x7sAdventureCloneTestConstants.TEST_ADVENTURE_NAME];
        Integer             adventureCount  = [SELECT COUNT() FROM X7S_Adventure__c];

        Test.startTest();
        x7sAdventureCloneProjectAssignment.CloneUsers(testAdventure.id, true, userList);
        Test.stopTest();

        System.assertEquals(adventureCount + 1, [SELECT COUNT() FROM X7S_Adventure__c]);
    }

//    private static List<User> LoadUsers() {
//        StaticResource  userResource    = [ SELECT Body, ContentType FROM StaticResource WHERE Name = 'TestUsers1'];
//        String          userContent     = userResource.Body.toString();
//        String[]        users           = userContent.split('\n');
//        List<String>    userIds         = new List<String>();
//
//        for (String user : users) {
//            String[] subUsers = user.split(',');
//
//            for (String subUser : subUsers) {
//                userIds.add(subUser.trim());
//            }
//        }
//
//        return [SELECT Id, FirstName, LastName FROM User WHERE Id IN :userIds AND IsActive = TRUE];
//    }
}