force-app/main/default/objects/Community_Asset__c/Community_Asset__c.object-meta.xml
<CustomObject>
    <label>Community Asset</label>
    <nameField>
        <label>Asset</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Community_Asset__c/fields/Asset_Owner__c.field-meta.xml
<CustomField>
    <fullName>Asset_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Community_Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Community_Asset__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Community Assets</relationshipLabel>
    <relationshipName>Community_Assets_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Community_Asset__c/fields/Link__c.field-meta.xml
<CustomField>
    <fullName>Link__c</fullName>
    <label>Link</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/x7S_CommunityAssetsControllerTest.cls
@IsTest
private class x7S_CommunityAssetsControllerTest {
    @testSetup
    static void testSetup() {
        User testUser = Peak_TestUtils.createStandardUserNoContact();
        Account testAccount = Peak_TestUtils.createTestAccount();
        insert testUser;
    }
    @IsTest
    static void testGetObjectAPIName() {
        List<User> testUsers = [SELECT Id FROM User WHERE Email = :Peak_TestConstants.STANDARD_EMAIL AND Username = :Peak_TestConstants.STANDARD_USERNAME];
        Test.startTest();
        String testResponse = x7S_CommunityAssetsController.getObjectAPIName(testUsers[0].Id);
        String actualResponse = testUsers[0].Id.getSObjectType().getDescribe().getName();
        System.assertEquals(testResponse, actualResponse);
        Test.stopTest();
    }
    @IsTest
    static void testGetFieldLabels() {
        List<User> testUsers = [SELECT Id FROM User WHERE Email = :Peak_TestConstants.STANDARD_EMAIL AND Username = :Peak_TestConstants.STANDARD_USERNAME];
        System.runAs(testUsers[0]){
            Test.startTest();
            x7S_AssetResponse testResponse = x7S_CommunityAssetsController.getFieldLabels(new List<String>{'Name'}, false);
            String testLabel = Schema.getGlobalDescribe().get('Community_Asset__c').getDescribe().fields.getMap().get('Name').getDescribe().getLabel();
            System.assertEquals(testResponse.labels[0],testLabel);
            System.assertEquals(testResponse.success,true);
            Test.stopTest();
        }
    }
    @IsTest
    static void testGetFieldLabelsException() {
        List<User> testUsers = [SELECT Id FROM User WHERE Email = :Peak_TestConstants.STANDARD_EMAIL AND Username = :Peak_TestConstants.STANDARD_USERNAME];
        System.runAs(testUsers[0]){
            Test.startTest();
            x7S_AssetResponse testResponse = x7S_CommunityAssetsController.getFieldLabels(new List<String>{'Name'}, true);
            System.assertEquals(testResponse.success,false);
            Test.stopTest();
        }
    }
    @IsTest
    static void testGetAssets() {
        List<Account> testAccounts = [SELECT Id FROM Account WHERE Name = :Peak_TestConstants.ACCOUNT_NAME];
        Community_Asset__c newAsset = new Community_Asset__c();
        newAsset.Name = 'Test Asset';
        newAsset.Client__c = testAccounts[0].Id;
        newAsset.Link__c = 'www.google.com';
        newAsset.Asset_Owner__c=UserInfo.getUserId();
        insert newAsset;
        Test.startTest();
        Peak_Response testResponse = x7S_CommunityAssetsController.getAssets(testAccounts[0].Id, false);
        Community_Asset__c returnedAsset = (Community_Asset__c)testResponse.results[0];
        System.assertEquals(testResponse.success,true);
        System.assertEquals(returnedAsset.Id,newAsset.Id);
        System.assertEquals(returnedAsset.Client__c, testAccounts[0].Id);
        Test.stopTest();
    }
    @IsTest
    static void testGetAssetsException() {
        List<Account> testAccounts = [SELECT Id FROM Account WHERE Name = :Peak_TestConstants.ACCOUNT_NAME];
        Community_Asset__c newAsset = new Community_Asset__c();
        newAsset.Name = 'Test Asset';
        newAsset.Client__c = testAccounts[0].Id;
        newAsset.Link__c = 'www.google.com';
        newAsset.Asset_Owner__c=UserInfo.getUserId();
        insert newAsset;
        Test.startTest();
        Peak_Response testResponse = x7S_CommunityAssetsController.getAssets(testAccounts[0].Id, true);
        System.assertEquals(testResponse.success,false);
        Test.stopTest();
    }
}