force-app/main/default/objects/Community_Asset__c/Community_Asset__c.object-meta.xml
<CustomObject>
    <label>Community Asset</label>
    <nameField>
        <label>Asset</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Community_Asset__c/fields/Asset_Owner__c.field-meta.xml
<CustomField>
    <fullName>Asset_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Community_Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Community_Asset__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Community Assets</relationshipLabel>
    <relationshipName>Community_Assets_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Community_Asset__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>pse__Proj__c</referenceTo>
    <relationshipLabel>Community Assets</relationshipLabel>
    <relationshipName>Community_Assets_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Community_Asset__c/fields/Related_Record__c.field-meta.xml
<CustomField>
    <fullName>Related_Record__c</fullName>
    <label>Related Record</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/pse__Proj__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__ProjectHelp</customHelpPage>
    <description>Represents a collection of business transactions, activities, and related items to be managed over a defined time range, such as timecards, expenses, milestones, and budgets. Typically, people (represented by Resource records) are assigned to projects, though some projects do not require assignments in order to be staffed. Projects may also have a master project (parent) or a sub project (child) in the project hierarchy, supporting roll-ups of revenues, costs, and time to every project and up through the hierarchy.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/x7S_CommunityAssetsController.cls
public with sharing class x7S_CommunityAssetsController {
    @AuraEnabled(cacheable=true)
    public static String getObjectAPIName(Id recordId) {
        return recordId.getSObjectType().getDescribe().getName();
    }
    @AuraEnabled(cacheable=true)
    public static x7S_AssetResponse getFieldLabels(List<String> assetFields, Boolean testThrowException) {
        x7S_AssetResponse assetResponse = new x7S_AssetResponse();
        // Get all of the fields on the object
        try{
            if(Test.isRunningTest() && testThrowException) {
                CalloutException testException = new CalloutException();
                testException.setMessage('This is a constructed exception for testing and code coverage');
                throw testException;
            }
            Map<String,Schema.SObjectField> fieldMap = Schema.getGlobalDescribe().get('Community_Asset__c').getDescribe().fields.getMap();
            for(String currentField : assetFields){
                assetResponse.labels.add(fieldMap.get(currentField) != null ? fieldMap.get(currentField).getDescribe().getLabel() : currentField);
            }
            assetResponse.success = true;
            System.debug(assetResponse);
        }catch (Exception e){
            assetResponse.success = false;
            assetResponse.messages.add(e.getMessage());
        }

        return assetResponse;
    }
    @AuraEnabled
    public static Peak_Response getAssets(String parentId, Boolean testThrowException) {
        Peak_Response peakResponse = new Peak_Response();
        // Get all of the fields on the object
        try{
            if(Test.isRunningTest() && testThrowException) {
                CalloutException testException = new CalloutException();
                testException.setMessage('This is a constructed exception for testing and code coverage');
                throw testException;
            }
            Set<String> fieldNames = Community_Asset__c.sObjectType.getDescribe().fields.getMap().keySet();
            // Build a Dynamic Query String.
            String soqlQuery = 'SELECT ' + String.join(new List<String>(fieldNames), ',') + ',Asset_Owner__r.Name FROM Community_Asset__c WHERE Project__r.Id =:parentId OR Client__r.Id =:parentId OR Related_Record__c =:parentId ORDER BY Order__c ASC, Name ASC NULLS LAST';
            peakResponse.success = true;
            peakResponse.results = Database.query(soqlQuery);
        }catch (Exception e){
            peakResponse.success = false;
            peakResponse.messages.add(e.getMessage());
        }
        System.debug('RESULTS ================= ' + peakResponse.results);
        return peakResponse;
    }
}