force-app/main/default/objects/ALMRecordTypeMapping__mdt/ALMRecordTypeMapping__mdt.object-meta.xml
<CustomObject>
    <description>Record type mapping from ALM to Copado user story</description>
    <label>ALM Record Type Mapping</label>
    <pluralLabel>ALM Record Type Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/ALMRecordTypeMapping__mdt/fields/SalesforceRecordType__c.field-meta.xml
<CustomField>
    <fullName>SalesforceRecordType__c</fullName>
    <label>Salesforce Record Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ALMRecordTypeMapping__mdt/fields/ThirdPartyRecordType__c.field-meta.xml
<CustomField>
    <fullName>ThirdPartyRecordType__c</fullName>
    <label>Third Party Record Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/copado__Project__c/copado__Project__c.object-meta.xml
<CustomObject>
    <description>Overall object for capturing the project details.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/copado__Project__c/fields/copadoccmint__Copado_Integration_Setting__c.field-meta.xml
<CustomField>
    <fullName>copadoccmint__Copado_Integration_Setting__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Copado Integration Setting</label>
    <referenceTo>copadoccmint__Copado_Integration_Setting__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/copado__Project__c/fields/InternalJira__c.field-meta.xml
<CustomField>
    <fullName>InternalJira__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Use 7S Jira instance</description>
    <inlineHelpText>Use 7S Jira instance</inlineHelpText>
    <label>Use 7S Jira</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/copadoccmint__Record_Type_Mapping__c/copadoccmint__Record_Type_Mapping__c.object-meta.xml
<CustomObject>
    <label>Record Type Mapping</label>
    <nameField>
        <displayFormat>RTM-{000000000}</displayFormat>
        <label>Record Type Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Record Type Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Field_Mapping_Template__mdt/Field_Mapping_Template__mdt.object-meta.xml
<CustomObject>
    <description>Field mapping template for Jira integration to Copado (Contains default for 7S Jira Projects)</description>
    <label>Field Mapping Template</label>
    <pluralLabel>Mapping Tempates</pluralLabel>
</CustomObject>

force-app/main/default/objects/Field_Mapping_Template__mdt/fields/Exclude_from_su__c.field-meta.xml
<CustomField>
    <fullName>Exclude_from_su__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Make this checkbox checked if you don&apos;t want this field to be updated from third party platform.</description>
    <inlineHelpText>Make this checkbox checked if you don&apos;t want this field to be updated from third party platform.</inlineHelpText>
    <label>Exclude from Salesforce Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Field_Mapping_Template__mdt/fields/Exclude_from_tpu__c.field-meta.xml
<CustomField>
    <fullName>Exclude_from_tpu__c</fullName>
    <defaultValue>false</defaultValue>
    <description>That field is defined to exclude Mapping records in use on code level for look up purposes(like developer id and project id Mapping) Make it checked for the fields which do not exist on external system.</description>
    <inlineHelpText>That field is defined to exclude Mapping records in use on code level for look up purposes(like developer id and project id Mapping) Make it checked for the fields which do not exist on external system.</inlineHelpText>
    <label>Exclude from Third Part Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Field_Mapping_Template__mdt/fields/Salesforce_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Field_Name__c</fullName>
    <label>Salesforce Field Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Mapping_Template__mdt/fields/Target_Field_Type__c.field-meta.xml
<CustomField>
    <fullName>Target_Field_Type__c</fullName>
    <description>Default value is set to string if not selected.</description>
    <label>Target Field Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>string</fullName>
                <default>true</default>
                <label>string</label>
            </value>
            <value>
                <fullName>object</fullName>
            </value>
            <value>
                <fullName>integer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Field_Mapping_Template__mdt/fields/Third_Party_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Third_Party_Field_Name__c</fullName>
    <label>Third Party Field Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Jira_Status_Mapping_Template__mdt/Jira_Status_Mapping_Template__mdt.object-meta.xml
<CustomObject>
    <label>Jira Status Mapping Template</label>
    <pluralLabel>Jira Status Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Jira_Status_Mapping_Template__mdt/fields/Copado_Status__c.field-meta.xml
<CustomField>
    <fullName>Copado_Status__c</fullName>
    <label>Copado Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Backlog</fullName>
            </value>
            <value>
                <fullName>Backburner</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Ready for Testing</fullName>
            </value>
            <value>
                <fullName>Ready for Dev</fullName>
            </value>
            <value>
                <fullName>Ready for QA</fullName>
            </value>
            <value>
                <fullName>Ready for UAT</fullName>
            </value>
            <value>
                <fullName>Ready for Production</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Jira_Status_Mapping_Template__mdt/fields/ExternalValue__c.field-meta.xml
<CustomField>
    <fullName>ExternalValue__c</fullName>
    <label>External Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Jira_Status_Mapping_Template__mdt/fields/SyncDirection__c.field-meta.xml
<CustomField>
    <fullName>SyncDirection__c</fullName>
    <label>Sync Direction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inbound</fullName>
                <default>true</default>
                <label>Inbound</label>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
            <value>
                <fullName>Ignore</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/JiraStatusMapping__c/JiraStatusMapping__c.object-meta.xml
<CustomObject>
    <label>Jira Status Mapping</label>
    <nameField>
        <displayFormat>JSM-{000000}</displayFormat>
        <label>Mapping Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jira Status Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/JiraStatusMapping__c/fields/CopadoStatus__c.field-meta.xml
<CustomField>
    <fullName>CopadoStatus__c</fullName>
    <description>Copado User Story Status</description>
    <inlineHelpText>Copado User Story Status</inlineHelpText>
    <label>Copado Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>User_Story_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/JiraStatusMapping__c/fields/ExternalValue__c.field-meta.xml
<CustomField>
    <fullName>ExternalValue__c</fullName>
    <description>Value from the external external system</description>
    <inlineHelpText>Value from the external external system</inlineHelpText>
    <label>External Value</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JiraStatusMapping__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>Project associated with the mapping record</description>
    <inlineHelpText>Project associated with the mapping record</inlineHelpText>
    <label>Project</label>
    <referenceTo>copado__Project__c</referenceTo>
    <relationshipLabel>Jira Status Mappings</relationshipLabel>
    <relationshipName>JiraStatusMappings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/JiraStatusMapping__c/fields/SyncDirection__c.field-meta.xml
<CustomField>
    <fullName>SyncDirection__c</fullName>
    <description>Identifies if the record is to be used for inbound synchronizations (External Sync Button), outbound synchronizations or ignored</description>
    <inlineHelpText>Identifies if the record is to be used for inbound synchronizations (External Sync Button), outbound synchronizations or ignored</inlineHelpText>
    <label>Sync Direction</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
            <value>
                <fullName>Ignore</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/User_Story_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Backlog</fullName>
    </customValue>
    <customValue>
        <fullName>Bakcburner</fullName>
    </customValue>
    <customValue>
        <fullName>Awaiting Approval</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Ready for Testing</fullName>
    </customValue>
    <customValue>
        <fullName>Ready for Dev</fullName>
    </customValue>
    <customValue>
        <fullName>Ready for QA</fullName>
    </customValue>
    <customValue>
        <fullName>Ready for UAT</fullName>
    </customValue>
    <customValue>
        <fullName>Ready for Production</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Done</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>To Do</fullName>
    </customValue>
    <masterLabel>User Story Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CopadoProjectTriggerHandler.cls
public class CopadoProjectTriggerHandler {
    public static boolean m_isExecuting = false; 
    public static List<Field_Mapping_Template__mdt> fieldMappings;
    public static List<Jira_Status_Mapping_Template__mdt> statusMappings;
    public static List<ALMRecordTypeMapping__mdt> recordTypeMappings;
    
    //-------------------------------------------------------------------------  
    // On before insert trigger method
    //-------------------------------------------------------------------------
    public static void OnBeforeInsert(List<copado__Project__c> newList) {

    } 
    
    //-------------------------------------------------------------------------
    // On after insert trigger method
    //-------------------------------------------------------------------------
    public static void OnAfterInsert(List<copado__Project__c> newList) {
        System.debug('****** On After Insert *****');
        System.debug('****** newList: ' + newList);
        List<copado__Project__c> newJiraProjects = new List<copado__Project__c>();
        
        for(copado__Project__c project : newList) {
            if(project.InternalJira__c ==true) {
                newJiraProjects.add(project);
            }
        }
        
        if(!newJiraProjects.isEmpty()) { setProjectToUse7SJira(newJiraProjects); }
    }
    
    //-------------------------------------------------------------------------
    // On before update trigger method
    //-------------------------------------------------------------------------
    public static void OnBeforeUpdate(Map<Id, copado__Project__c> oldMap, Map<Id, copado__Project__c> newMap) {
        for(copado__Project__c project : newMap.values()) {
            if(project.InternalJira__c != oldMap.get(project.Id).InternalJira__c) {
                if(project.InternalJira__c==false) {
                    project.copadoccmint__Copado_Integration_Setting__c = null;
                    project.copadoccmint__JQL_Extended_Filter__c = null;
                } else {
                    if(!Test.isRunningTest()) { 
                        project.copadoccmint__Copado_Integration_Setting__c = System.Label.Jira_Integration_Setting;
                        project.copadoccmint__JQL_Extended_Filter__c = System.Label.X7S_Copado_Default_JQL;
                    }
                }
            }
        }
    }
    
    //-------------------------------------------------------------------------
    // On after update trigger method
    //-------------------------------------------------------------------------
    public static void OnAfterUpdate (Map<Id, copado__Project__c> oldMap, Map<Id, copado__Project__c> newMap) {
        List<copado__Project__c> newJiraProjects = new List<copado__Project__c>();
        List<copado__Project__c> cancelledJiraProjects = new List<copado__Project__c>();
        
        for(copado__Project__c project : newMap.values()) {
            System.debug('------ new value: ' + project.InternalJira__c + ' ------- old value: ' + oldMap.get(project.Id).InternalJira__c);
            if(project.InternalJira__c != oldMap.get(project.Id).InternalJira__c) {
                if(project.InternalJira__c==true) {
                    newJiraProjects.add(project);
                } else {
                    cancelledJiraProjects.add(project);
                }
            }
        }
        
        System.debug('------ canceledJiraProjects: ' + cancelledJiraProjects);
        if(!newJiraProjects.isEmpty()) { setProjectToUse7SJira(newJiraProjects); }
        if(!cancelledJiraProjects.isEmpty()) { removeProjectFromJira(cancelledJiraProjects); }
    }
    
    //-------------------------------------------------------------------------
    // On before delete trigger method
    //-------------------------------------------------------------------------
    public static void OnBeforeDelete (List<copado__Project__c> newList) {    
        
    }
    
    //-------------------------------------------------------------------------
    // On after delete trigger method
    //-------------------------------------------------------------------------
    public static void OnAfterDelete (List<copado__Project__c> newList) {    
        
    }
    
    //-------------------------------------------------------------------------
    // Setup project to use 7S Jira
    //-------------------------------------------------------------------------
    private static void setProjectToUse7SJira(List<copado__Project__c> projects) {
        System.debug('****** setProjectToUse7SJira *****');
        List<copadoccmint__Field_Mapping__c> jiraMapping = new List<copadoccmint__Field_Mapping__c>();
        List<JiraStatusMapping__c> statusMapping = new List<JiraStatusMapping__c>();
        List<copadoccmint__Record_Type_Mapping__c> recordTypeMapping = new List<copadoccmint__Record_Type_Mapping__c>();
        
        for(copado__Project__c project : projects) {
            System.debug('****** System.Label.Jira_Integration_Setting: ' + System.Label.Jira_Integration_Setting);
            if(project.InternalJira__c) {
                
                createFieldMappings(project.Id, jiraMapping);
                createStatusMappings(project.Id, statusMapping);
                createRecordTypeMappings(project.Id, recordTypeMapping);
            }
        }
        
        if(!jiraMapping.isEmpty()) { insert jiraMapping; }
        if(!statusMapping.isEmpty()) { insert statusMapping; }
        if(!recordTypeMapping.isEmpty()) { insert recordTypeMapping; }
    }
    
    //-------------------------------------------------------------------------
    // Create field mappings for Jira
    //-------------------------------------------------------------------------
    private static void createFieldMappings(Id projectId, List<copadoccmint__Field_Mapping__c> jiraMapping) {       
        if(fieldMappings==null) { getFieldMappings(); }

        for(Field_Mapping_Template__mdt fieldMap : fieldMappings) {
            jiraMapping.add(new copadoccmint__Field_Mapping__c(copadoccmint__Project__c=projectId, copadoccmint__Exclude_from_su__c=fieldMap.Exclude_from_su__c, 
                                                               copadoccmint__Exclude_from_tpu__c=fieldMap.Exclude_from_tpu__c, copadoccmint__Salesforce_Field_Name__c=fieldMap.Salesforce_Field_Name__c, 
                                                               copadoccmint__Target_Field_Type__c=fieldMap.Target_Field_Type__c, copadoccmint__Third_Party_Field_Name__c=fieldMap.Third_Party_Field_Name__c));
        }
        
    }
    
    //-------------------------------------------------------------------------
    // Create status mappings for Jira
    //-------------------------------------------------------------------------
    private static void createStatusMappings(Id projectId, List<JiraStatusMapping__c> statusMapping) {       
        if(statusMappings==null) { getStatusMappings(); }

        for(Jira_Status_Mapping_Template__mdt fieldMap : statusMappings) {
            statusMapping.add(new JiraStatusMapping__c(Project__c=projectId, CopadoStatus__c=fieldMap.Copado_Status__c, ExternalValue__c=fieldMap.ExternalValue__c,
                                                 SyncDirection__c=fieldMap.SyncDirection__c));
        }
        
    }

    //-------------------------------------------------------------------------
    // Create record type mappings for Jira
    //-------------------------------------------------------------------------
    private static void createRecordTypeMappings(Id projectId, List<copadoccmint__Record_Type_Mapping__c> recordTypeMapping) {       
        if(recordTypeMappings==null) { getRecordTypeMappings(); }

        for(ALMRecordTypeMapping__mdt fieldMap : recordTypeMappings) {
            recordTypeMapping.add(new copadoccmint__Record_Type_Mapping__c(copadoccmint__Project__c=projectId, 
                                                                           copadoccmint__Salesforce_Record_Type_Name__c=fieldMap.SalesforceRecordType__c, 
                                                                           copadoccmint__Third_Party_Record_Type_Name__c=fieldMap.ThirdPartyRecordType__c));
        }
        
    }
    
    
    //-------------------------------------------------------------------------
    // Remove field mappings for Jira
    //-------------------------------------------------------------------------
    private static void removeProjectFromJira(List<copado__Project__c> projects) {
        Set<Id> copadoProjectIds = new Set<Id>();
        for(copado__Project__c project : projects) {
			copadoProjectIds.add(project.Id);
        }
        
        System.debug('******* Removing Field and Status Mappings ********');
        System.debug('-------- copadoProjectIds: ' + copadoProjectIds);
        List<copadoccmint__Field_Mapping__c> f = [SELECT Id FROM copadoccmint__Field_Mapping__c WHERE copadoccmint__Project__c IN : copadoProjectIds];
        List<JiraStatusMapping__c> s = [SELECT Id FROM JiraStatusMapping__c WHERE Project__c IN : copadoProjectIds];
        
        if(!f.isEmpty()) { delete f; }
        if(!s.isEmpty()) { delete s; }
    }
    
    //-------------------------------------------------------------------------
    // Get template field mappings from custom metadata 
    //-------------------------------------------------------------------------
    private static void getFieldMappings() {
        if(Test.isRunningTest()) {
            fieldMappings = new List<Field_Mapping_Template__mdt>();
            fieldMappings.add(new Field_Mapping_Template__mdt(MasterLabel='7S-Test', Salesforce_Field_Name__c='A', Third_Party_Field_Name__c = 'B'));
        } else {
            fieldMappings = [SELECT Exclude_from_su__c, Exclude_from_tpu__c, Salesforce_Field_Name__c, Target_Field_Type__c, Third_Party_Field_Name__c
                             FROM Field_Mapping_Template__mdt
                             WHERE MasterLabel LIKE '7S-%'];
        }
    }
    
    //-------------------------------------------------------------------------
    // Get template status mappings from custom metadata 
    //-------------------------------------------------------------------------
    private static void getStatusMappings() {
        if(Test.isRunningTest()) {
            statusMappings = new List<Jira_Status_Mapping_Template__mdt>();
            statusMappings.add(new Jira_Status_Mapping_Template__mdt(MasterLabel='7S-Test',  Copado_Status__c='Draft', ExternalValue__c = 'B', SyncDirection__c='Inbound'));
        } else {
            statusMappings = [SELECT Copado_Status__c, ExternalValue__c, SyncDirection__c
                             FROM Jira_Status_Mapping_Template__mdt
                             WHERE MasterLabel LIKE '7S-%'];
        }
    }
    
    //-------------------------------------------------------------------------
    // Get template record type mappings from custom metadata 
    //-------------------------------------------------------------------------
    private static void getRecordTypeMappings() {
        if(Test.isRunningTest()) {
            recordTypeMappings = new List<ALMRecordTypeMapping__mdt>();
            recordTypeMappings.add(new ALMRecordTypeMapping__mdt(MasterLabel='7S-Test', SalesforceRecordType__c='A', ThirdPartyRecordType__c = 'B'));
        } else {
            recordTypeMappings = [SELECT SalesforceRecordType__c, ThirdPartyRecordType__c
                                  FROM ALMRecordTypeMapping__mdt];
        }
    }
}