force-app/main/default/objects/Account/fields/CY_Closed_Won_Opps_Products_Only__c.field-meta.xml
<CustomField>
    <fullName>CY_Closed_Won_Opps_Products_Only__c</fullName>
    <description>The products only sum of all opportunities closed/won in the current year. This field is populated via rollup helper.</description>
    <inlineHelpText>The products only sum of all opportunities closed/won in the current year. This field is populated via rollup helper.</inlineHelpText>
    <label>CY Closed/Won Opps - Products Only</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/CY_ClosedWon_Opps_Services_Only__c.field-meta.xml
<CustomField>
    <fullName>CY_ClosedWon_Opps_Services_Only__c</fullName>
    <description>The services only sum of all opportunities closed/won in the current year. This field is populated via rollup helper.</description>
    <inlineHelpText>The services only sum of all opportunities closed/won in the current year. This field is populated via rollup helper.</inlineHelpText>
    <label>CY Closed/Won Opps - Services Only</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Won_Sales_All_Time__c.field-meta.xml
<CustomField>
    <fullName>Won_Sales_All_Time__c</fullName>
    <label>Won Sales - All Time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Month_Won__c.field-meta.xml
<CustomField>
    <fullName>Month_Won__c</fullName>
    <formula>MONTH( CloseDate )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Month Won</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opp_Hierarchy_Status__c.field-meta.xml
<CustomField>
    <fullName>Opp_Hierarchy_Status__c</fullName>
    <formula>IF(
OR(
ISPICKVAL(Project_Type__c,&quot;New Project&quot;),
ISPICKVAL(Project_Type__c,&quot;Customer Success&quot;)), &quot;Parent Opportunity&quot;,
IF(
ISPICKVAL(Project_Type__c, &quot;Change Order&quot;), &quot;Child Opportunity&quot;,
&quot;None&quot;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opp Hierarchy Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Hierarchy__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Hierarchy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Hierarchy</label>
    <referenceTo>Opportunity_Hierarchy__c</referenceTo>
    <relationshipLabel>Opportunities (Opportunity Hierarchy)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Parent_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Parent_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Opportunity_Hierarchy__c.Parent_Opportunity__r.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity_Hierarchy__c</referenceTo>
    <relationshipLabel>Child Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Only_Sub_Total__c.field-meta.xml
<CustomField>
    <fullName>Product_Only_Sub_Total__c</fullName>
    <label>Product Only Sub-Total</label>
    <summarizedField>OpportunityLineItem.TotalPrice</summarizedField>
    <summaryFilterItems>
        <field>OpportunityLineItem.Opp_Prod_Family__c</field>
        <operation>equals</operation>
        <value>Product</value>
    </summaryFilterItems>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project_Type__c.field-meta.xml
<CustomField>
    <fullName>Project_Type__c</fullName>
    <label>Project Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Project</fullName>
            </value>
            <value>
                <fullName>Change Order</fullName>
            </value>
            <value>
                <fullName>IP Only</fullName>
            </value>
            <value>
                <fullName>Customer Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/pse__Primary_Project__c.field-meta.xml
<CustomField>
    <fullName>pse__Primary_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Project</label>
    <referenceTo>pse__Proj__c</referenceTo>
    <relationshipLabel>Primary Project For Opportunities</relationshipLabel>
    <relationshipName>PrimaryProjectForOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Quarter_Won__c.field-meta.xml
<CustomField>
    <fullName>Quarter_Won__c</fullName>
    <formula>CEILING( MONTH (  CloseDate  ) / 3 )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quarter Won</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Quota_Name__c.field-meta.xml
<CustomField>
    <fullName>Quota_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quota Detail</label>
    <referenceTo>Quota_Detail__c</referenceTo>
    <relationshipLabel>Opportunities (Quota Detail)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Svcs_Amt_for_NetSuite2__c.field-meta.xml
<CustomField>
    <fullName>Svcs_Amt_for_NetSuite2__c</fullName>
    <inlineHelpText>This amount is auto-calculated from Products list.</inlineHelpText>
    <label>Svcs Only Sub-Total</label>
    <summarizedField>OpportunityLineItem.TotalPrice</summarizedField>
    <summaryFilterItems>
        <field>OpportunityLineItem.Opp_Prod_Family__c</field>
        <operation>equals</operation>
        <value>Service,, Customer Success</value>
    </summaryFilterItems>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity_Hierarchy__c/Opportunity_Hierarchy__c.object-meta.xml
<CustomObject>
    <label>Opportunity Hierarchy</label>
    <nameField>
        <label>Opportunity Hierarchy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Hierarchy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Hierarchy__c/fields/Child_Opps_Prod_Only_SubTotal__c.field-meta.xml
<CustomField>
    <fullName>Child_Opps_Prod_Only_SubTotal__c</fullName>
    <description>Sum amount of all child opportunity products sold.</description>
    <inlineHelpText>Sum amount of all child opportunity products sold.</inlineHelpText>
    <label>Child Opps Prod Only Sub-Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity_Hierarchy__c/fields/Child_Opps_Svcs_Only_Sub_Total__c.field-meta.xml
<CustomField>
    <fullName>Child_Opps_Svcs_Only_Sub_Total__c</fullName>
    <description>Sum of all child opportunity services sold.</description>
    <inlineHelpText>Sum of all child opportunity services sold.</inlineHelpText>
    <label>Child Opps Svcs Only Sub-Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity_Hierarchy__c/fields/Parent_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Parent_Opportunity__c</fullName>
    <label>Parent Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Parent_Opportunities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Hierarchy__c/fields/SOW_Budget__c.field-meta.xml
<CustomField>
    <fullName>SOW_Budget__c</fullName>
    <formula>Parent_Opportunity__r.Svcs_Amt_for_NetSuite2__c+CO_SOW_Budget__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SOW Budget ($)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/pse__Proj__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__ProjectHelp</customHelpPage>
    <description>Represents a collection of business transactions, activities, and related items to be managed over a defined time range, such as timecards, expenses, milestones, and budgets. Typically, people (represented by Resource records) are assigned to projects, though some projects do not require assignments in order to be staffed. Projects may also have a master project (parent) or a sub project (child) in the project hierarchy, supporting roll-ups of revenues, costs, and time to every project and up through the hierarchy.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Proj__c/fields/SOW_Budget__c.field-meta.xml
<CustomField>
    <fullName>SOW_Budget__c</fullName>
    <description>Sum of the Services amount (i.e. not including IP) for the parent opportunity and its children.</description>
    <inlineHelpText>Sum of the Services amount (i.e. not including IP) for the parent opportunity and its children.</inlineHelpText>
    <label>SOW Budget ($)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quota_Detail__c/Quota_Detail__c.object-meta.xml
<CustomObject>
    <label>Quota Detail</label>
    <nameField>
        <label>Quota Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quota Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quota_Detail__c/fields/April_Attained__c.field-meta.xml
<CustomField>
    <fullName>April_Attained__c</fullName>
    <label>April Attained</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quota_Detail__c/fields/August_Attained__c.field-meta.xml
<CustomField>
    <fullName>August_Attained__c</fullName>
    <label>August Attained</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quota_Detail__c/fields/December_Attained__c.field-meta.xml
<CustomField>
    <fullName>December_Attained__c</fullName>
    <label>December Attained</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quota_Detail__c/fields/February_Attained__c.field-meta.xml
<CustomField>
    <fullName>February_Attained__c</fullName>
    <label>February Attained</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quota_Detail__c/fields/January_Attained__c.field-meta.xml
<CustomField>
    <fullName>January_Attained__c</fullName>
    <label>January Attained</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quota_Detail__c/fields/July_Attained__c.field-meta.xml
<CustomField>
    <fullName>July_Attained__c</fullName>
    <label>July Attained</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quota_Detail__c/fields/June_Attained__c.field-meta.xml
<CustomField>
    <fullName>June_Attained__c</fullName>
    <label>June Attained</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quota_Detail__c/fields/March_Attained__c.field-meta.xml
<CustomField>
    <fullName>March_Attained__c</fullName>
    <label>March Attained</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quota_Detail__c/fields/May_Attained__c.field-meta.xml
<CustomField>
    <fullName>May_Attained__c</fullName>
    <label>May Attained</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quota_Detail__c/fields/November_Attained__c.field-meta.xml
<CustomField>
    <fullName>November_Attained__c</fullName>
    <label>November Attained</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quota_Detail__c/fields/October_Attained__c.field-meta.xml
<CustomField>
    <fullName>October_Attained__c</fullName>
    <label>October Attained</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quota_Detail__c/fields/Q1_Attained__c.field-meta.xml
<CustomField>
    <fullName>Q1_Attained__c</fullName>
    <label>Q1 Attained</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quota_Detail__c/fields/Q2_Attained__c.field-meta.xml
<CustomField>
    <fullName>Q2_Attained__c</fullName>
    <label>Q2 Attained</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quota_Detail__c/fields/Q3_Attained__c.field-meta.xml
<CustomField>
    <fullName>Q3_Attained__c</fullName>
    <label>Q3 Attained</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quota_Detail__c/fields/Q4_Attained__c.field-meta.xml
<CustomField>
    <fullName>Q4_Attained__c</fullName>
    <label>Q4 Attained</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quota_Detail__c/fields/Quota_Attained__c.field-meta.xml
<CustomField>
    <fullName>Quota_Attained__c</fullName>
    <label>Quota Attained</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quota_Detail__c/fields/September_Attained__c.field-meta.xml
<CustomField>
    <fullName>September_Attained__c</fullName>
    <label>September Attained</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/OpportunityRollupHelper.cls
public class OpportunityRollupHelper {
    public static void calculate(Set<Id> projectIds) {
        AggregateResult [] opps = [SELECT pse__Primary_Project__c Id, SUM(Svcs_Amt_for_NetSuite2__c) SvcsAmount 
                                   FROM Opportunity 
                                   WHERE pse__Primary_Project__c IN : ProjectIds 
                                   AND (
                                       (Project_Type__c IN ('New Project', 'Customer Success') AND StageName NOT IN ('9 Closed Lost' , '10 No Opportunity')) 
                                       OR 
                                       (Project_Type__c='Change Order' AND StageName='8 Closed Won')
                                   )
                                   GROUP BY pse__Primary_Project__c];
        
        System.debug('-------- opps: ' + opps);
        
        List<pse__Proj__c> updatedProjects = new List<pse__Proj__c>();
        for(AggregateResult opp : opps) {
            
            if(opp.get('Id') != null) { updatedProjects.add(new pse__Proj__c(Id=(Id)opp.get('Id'), SOW_Budget__c=(Decimal)opp.get('SvcsAmount'))); }
            
        }
        
        System.debug('-------- updatedProjects: ' + updatedProjects);
        if(!updatedProjects.isEmpty()) { update updatedProjects; }
        
    }
    
    public static void calculate(List<Opportunity> opportunities) {
        System.debug('------ IN CALCULATE FOR Accounts & Quotas -----');
        Set<Id> accountIds = new Set<Id>();
        Set<Id> childOppIds = new Set<Id>();
        Set<Id> quotaIds = new Set<Id>();
        for(Opportunity opp : opportunities) {
            if(!opp.isDeleted && opp.isWon) {
                if(!accountIds.contains(opp.AccountId)) { accountIds.add(opp.AccountId); }                
            }
            if(opp.opp_hierarchy_status__c == 'Child Opportunity') {
                if(!childOppIds.contains(opp.Id)) { childOppIds.add(opp.Id); }
            }
            if(!quotaIds.contains(opp.Quota_Name__c)) { quotaIds.add(opp.Quota_Name__c); }
        }
        
        if(!accountIds.isEmpty()) { rollupToAccounts(accountIds); }

        if(!childOppIds.isEmpty()) { rollupHierarchy(childOppIds); }
        
        if(!quotaIds.isEmpty()) { rollupQuotas(quotaIds); }
    }
    
    private static void rollupHierarchy(Set<Id> childOppIds) {
        Map<Id, Opportunity_Hierarchy__c> hierarchyMap = new Map<Id, Opportunity_Hierarchy__c>();
        List<Opportunity> childOpps = [SELECT Parent_Opportunity__c, Svcs_Amt_for_NetSuite2__c, Product_Only_Sub_Total__c, isWon
                                       FROM Opportunity WHERE Id IN : childOppIds];
        System.debug('--------- childOpps: ' + childOpps);
        for(Opportunity childOpp : childOpps) {
            if(childOpp.Parent_Opportunity__c != null) {
                if(!hierarchyMap.containsKey(childOpp.Parent_Opportunity__c)) { 
                    hierarchyMap.put(childOpp.Parent_Opportunity__c, 
                                     new Opportunity_Hierarchy__c(Id=childOpp.Parent_Opportunity__c, 
                                                                  Child_Opps_Svcs_Only_Sub_Total__c=0,
                                                                  Child_Opps_Prod_Only_SubTotal__c=0));
                }
                if(childOpp.isWon) {
                    hierarchyMap.get(childOpp.Parent_Opportunity__c).Child_Opps_Svcs_Only_Sub_Total__c += childOpp.Svcs_Amt_for_NetSuite2__c;
                    hierarchyMap.get(childOpp.Parent_Opportunity__c).Child_Opps_Prod_Only_SubTotal__c += childOpp.Product_Only_Sub_Total__c;
                }
            }
        }
        if(!hierarchyMap.isEmpty()) { update hierarchyMap.values(); }
    }
    
    private static void rollupQuotas(Set<Id> quotaIds) {
        List<Opportunity> opps = [SELECT Amount, Quota_Name__c, Month_Won__c, Quarter_Won__c FROM Opportunity WHERE Quota_Name__c IN : quotaIds];
        Map<Id, Quota_Detail__c> quotaMap = new Map<Id, Quota_Detail__c>();
        for(Opportunity opp : opps) {
            if(opp.Quota_Name__c != null) {
                System.debug('-------- Quota_Name__c: ' + opp.Quota_Name__c);
                if(!quotaMap.containsKey(opp.Quota_Name__c)) { quotaMap.put(opp.Quota_Name__c,
                                                                            new Quota_Detail__c(Id=opp.Quota_Name__c,
                                                                                                January_Attained__c=0,
                                                                                                February_Attained__c=0,
                                                                                                March_Attained__c=0,
                                                                                                April_Attained__c=0,
                                                                                                May_Attained__c=0,
                                                                                                June_Attained__c=0,
                                                                                                July_Attained__c=0,
                                                                                                August_Attained__c=0,
                                                                                                September_Attained__c=0,
                                                                                                October_Attained__c=0,
                                                                                                November_Attained__c=0,
                                                                                                December_Attained__c=0,
                                                                                                Q1_Attained__c=0,
                                                                                                Q2_Attained__c	=0,
                                                                                                Q3_Attained__c=0,
                                                                                                Q4_Attained__c=0,
                                                                                                Quota_Attained__c=0
                                                                                               )); }
                Integer monthWon = Integer.valueOf(opp.Month_Won__c);
                switch on monthWon {
                    when 1 { quotaMap.get(opp.Quota_Name__c).January_Attained__c += opp.Amount; }
                    when 2 { quotaMap.get(opp.Quota_Name__c).February_Attained__c += opp.Amount; }
                    when 3 { quotaMap.get(opp.Quota_Name__c).March_Attained__c += opp.Amount; }
                    when 4 { quotaMap.get(opp.Quota_Name__c).April_Attained__c += opp.Amount; }
                    when 5 { quotaMap.get(opp.Quota_Name__c).May_Attained__c += opp.Amount; }
                    when 6 { quotaMap.get(opp.Quota_Name__c).June_Attained__c += opp.Amount; }
                    when 7 { quotaMap.get(opp.Quota_Name__c).July_Attained__c += opp.Amount; }
                    when 8 { quotaMap.get(opp.Quota_Name__c).August_Attained__c += opp.Amount; }
                    when 9 { quotaMap.get(opp.Quota_Name__c).September_Attained__c += opp.Amount; }
                    when 10 { quotaMap.get(opp.Quota_Name__c).October_Attained__c += opp.Amount; }
                    when 11 { quotaMap.get(opp.Quota_Name__c).November_Attained__c += opp.Amount; }
                    when 12 { quotaMap.get(opp.Quota_Name__c).December_Attained__c += opp.Amount; }
                }
                
                Integer quarterWon = Integer.valueOf(opp.Quarter_Won__c);
                switch on quarterWon {
                    when 1 { quotaMap.get(opp.Quota_Name__c).Q1_Attained__c += opp.Amount; }
                    when 2 { quotaMap.get(opp.Quota_Name__c).Q2_Attained__c += opp.Amount; }
                    when 3 { quotaMap.get(opp.Quota_Name__c).Q3_Attained__c += opp.Amount; }
                    when 4 { quotaMap.get(opp.Quota_Name__c).Q4_Attained__c += opp.Amount; }
                }
                
                quotaMap.get(opp.Quota_Name__c).Quota_Attained__c += opp.Amount;
            }
        }
        
        if(!quotaMap.isEmpty()) { update quotaMap.values(); }
    }
    
    @future
    public static void rollupToAccounts(Set<Id> accountIds) {
        List<Opportunity> opps = [SELECT AccountId, Amount, Svcs_Amt_for_NetSuite2__c,Product_Only_Sub_Total__c, CloseDate 
                                  FROM Opportunity WHERE isDeleted=false and isWon=true AND AccountId IN : accountIds];
        Map<Id, Account> accountMap = new Map<Id, Account>();
        for(Opportunity opp : opps) {
            if(!accountMap.containsKey(opp.AccountId)) { accountMap.put(opp.AccountId, new Account(Id=opp.AccountId, CY_Closed_Won_Opps_Products_Only__c=0, CY_ClosedWon_Opps_Services_Only__c=0, Won_Sales_All_Time__c=0)); }
            if(opp.Amount != null) { accountMap.get(opp.AccountId).Won_Sales_All_Time__c += opp.Amount; }
            if(opp.CloseDate.year() == System.today().year()) {
                if(opp.Product_Only_Sub_Total__c != null) { accountMap.get(opp.AccountId).CY_Closed_Won_Opps_Products_Only__c += opp.Product_Only_Sub_Total__c; }
                if(opp.Svcs_Amt_for_NetSuite2__c != null) { accountMap.get(opp.AccountId).CY_ClosedWon_Opps_Services_Only__c += opp.Svcs_Amt_for_NetSuite2__c; }
            }
        }
        
        if(!accountMap.isEmpty()) { update accountMap.values(); }
    }
    
}