force-app/main/default/objects/Account/fields/Industry_Type__c.field-meta.xml
<CustomField>
    <fullName>Industry_Type__c</fullName>
    <description>The industry associated with the company.</description>
    <inlineHelpText>The industry associated with the company.</inlineHelpText>
    <label>Industry Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Industry_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Industry_Type__c.field-meta.xml
<CustomField>
    <fullName>Industry_Type__c</fullName>
    <label>Industry Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Industry_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>7S Event</label>
    <nameField>
        <label>Events Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>7S Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Details__c.field-meta.xml
<CustomField>
    <fullName>Details__c</fullName>
    <label>Details</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Enable_RSVP__c.field-meta.xml
<CustomField>
    <fullName>Enable_RSVP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable RSVP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/End_DateTime__c.field-meta.xml
<CustomField>
    <fullName>End_DateTime__c</fullName>
    <label>End DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Location_Name__c.field-meta.xml
<CustomField>
    <fullName>Location_Name__c</fullName>
    <label>Location Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Start_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Start_DateTime__c</fullName>
    <label>Start DateTime</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/X7S_Event__c/X7S_Event__c.object-meta.xml
<CustomObject>
    <description>Object to support Events records as part of the Events accelerator from 7Summits.</description>
    <label>7S Event</label>
    <nameField>
        <label>Events Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>7S Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/X7S_Event__c/fields/Details__c.field-meta.xml
<CustomField>
    <fullName>Details__c</fullName>
    <label>Details</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/X7S_Event__c/fields/Enable_RSVP__c.field-meta.xml
<CustomField>
    <fullName>Enable_RSVP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable RSVP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/X7S_Event__c/fields/End_DateTime__c.field-meta.xml
<CustomField>
    <fullName>End_DateTime__c</fullName>
    <label>End DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/X7S_Event__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>en_US</fullName>
                <label>English</label>
            </value>
            <value>
                <fullName>es</fullName>
                <isActive>false</isActive>
                <label>es</label>
            </value>
            <value>
                <fullName>nl_NL</fullName>
                <isActive>false</isActive>
                <label>nl_NL</label>
            </value>
            <value>
                <fullName>zh_CN</fullName>
                <isActive>false</isActive>
                <label>zh_CN</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/X7S_Event__c/fields/Start_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Start_DateTime__c</fullName>
    <label>Start DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/X7S_Event_RSVP__c/X7S_Event_RSVP__c.object-meta.xml
<CustomObject>
    <description>Object to support Event RSVP records as part of the Events accelerator from 7Summits.</description>
    <label>7S Event RSVP</label>
    <nameField>
        <displayFormat>RSVP-{0000}</displayFormat>
        <label>Event RSVP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>7S Event RSVPs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/X7S_Event_RSVP__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>X7S_Event__c</referenceTo>
    <relationshipName>X7S_Event_RSVPs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/X7S_Event_RSVP__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>YES</fullName>
            </value>
            <value>
                <fullName>NO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/X7S_Event_RSVP__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>X7S_Event_RSVPs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/X7S_Event_Translation__c/X7S_Event_Translation__c.object-meta.xml
<CustomObject>
    <description>Object to support Event Translation records as part of the Events accelerator from 7Summits.</description>
    <label>7S Event Translation</label>
    <nameField>
        <label>7S Event Translation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>7S Event Translations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/X7S_Event_Translation__c/fields/Detail__c.field-meta.xml
<CustomField>
    <fullName>Detail__c</fullName>
    <label>Detail</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/X7S_Event_Translation__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <label>Parent Event</label>
    <referenceTo>X7S_Event__c</referenceTo>
    <relationshipLabel>7S Event Translations</relationshipLabel>
    <relationshipName>X7S_Event_Translation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/X7S_Events_Setting__mdt/X7S_Events_Setting__mdt.object-meta.xml
<CustomObject>
    <description>7 Summits Events settings</description>
    <label>7S Events Settings</label>
    <pluralLabel>7S Events Settings</pluralLabel>
</CustomObject>

force-app/main/default/globalValueSets/Industry_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Business Services</fullName>
    </customValue>
    <customValue>
        <fullName>Communications/Media</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer Goods</fullName>
    </customValue>
    <customValue>
        <fullName>Financial Services</fullName>
        <label>Financial  Services</label>
    </customValue>
    <customValue>
        <fullName>Government</fullName>
    </customValue>
    <customValue>
        <fullName>Healthcare</fullName>
    </customValue>
    <customValue>
        <fullName>Higher Education</fullName>
    </customValue>
    <customValue>
        <fullName>High Tech/Software</fullName>
    </customValue>
    <customValue>
        <fullName>Leisure &amp; Hospitality</fullName>
    </customValue>
    <customValue>
        <fullName>Manufacturing &amp; Automotive</fullName>
    </customValue>
    <customValue>
        <fullName>Nonprofit</fullName>
    </customValue>
    <customValue>
        <fullName>Retail</fullName>
    </customValue>
    <customValue>
        <fullName>Transportation</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Legacy</fullName>
        <isActive>false</isActive>
        <label>Legacy</label>
    </customValue>
    <description>Industry type values</description>
    <masterLabel>Industry Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/x7sEventsUtility.cls
/*
 * Copyright (c) 2020. 7Summits Inc.
 */

/*
    Name : x7sEventsUtility
    Description : Utility class for test data creation
    Date : 25/5/2016
*/
@isTest
public with sharing class x7sEventsUtility {

	public static String strNetworkId { get { return [SELECT Id FROM Network LIMIT 1][0].Id;} }

	/*
		 Method Name : createTopic
		 Description : Method for creating topics
	*/
	public static List<Topic> createTopic(Integer noOfEvents)
	{
		List<Topic> topicList = new List<Topic>();

		for (Integer i = 0; i < noOfEvents; i++) {
			Topic topicObj = new Topic(Name = 'Test00' + i, Description = 'Test');
			topicList.add(topicObj);
		}
		insert topicList;

		return topicList;
	}

    /*
         Method Name : createEventsRecords
         Description : Method for creating event records
    */
	public static List<X7S_Event__c> createEventsRecords(Integer noOfEvents)
	{
		List<X7S_Event__c> eventList = new List<X7S_Event__c>();

		for (Integer i = 0; i < noOfEvents; i++) {
			X7S_Event__c objEvent = new X7S_Event__c();

			objEvent.Name = 'event' + i;
			objEvent.Start_DateTime__c = Date.today();
			objEvent.End_DateTime__c = Date.today();
			objEvent.Details__c = 'Event Details is here.';
			objEvent.Location_Name__c = 'Location' + i;
			objEvent.Enable_RSVP__c = false;

			eventList.add(objEvent);
		}
		insert eventList;


		//create 	NewsTranslation__c record
		List<X7S_Event_Translation__c> eventTraslation = new List<X7S_Event_Translation__c>();
		for(X7S_Event__c record:eventList){

			X7S_Event_Translation__c eventTranslationObj = new X7S_Event_Translation__c(
			Name = 'Test Events Translate',
			Detail__c = 'Detail Test',
			Parent__c = record.id,
			Language__c = 'en_US',
			Title__c = 'Test Title');			
			eventTraslation.add(eventTranslationObj);
		}				
		insert eventTraslation; 

		return eventList;
	}

    /*
         Method Name : createTopicAssignment
         Description : Method for creating topic assignments
    */
	public static TopicAssignment createTopicAssignment(String strTopicId, String strEntityId)
	{
		TopicAssignment topicAssignment = new TopicAssignment(EntityId = strEntityId, TopicId = strTopicId);

		insert topicAssignment ;
		return topicAssignment ;
	}

    /*
         Method Name : createRSVPRecords
         Description : Method for creating RSVP records
    */
	public static List<X7S_Event_RSVP__c> createRSVPRecords(Integer noOfEvents, List<X7S_Event__c> eventList)
	{
		List<X7S_Event_RSVP__c> eventRSVPList = new List<X7S_Event_RSVP__c>();

		for (Integer i = 0; i < noOfEvents; i++) {
			X7S_Event_RSVP__c objEvent = new X7S_Event_RSVP__c();

			objEvent.Event__c = eventList[0].Id;
			objEvent.Response__c = 'YES';
			objEvent.User__c = UserInfo.getUserId();

			eventRSVPList.add(objEvent);
		}
		insert eventRSVPList;

		return eventRSVPList;
	}

    /*
         Method Name : deleteRSVPRecords
         Description : Method for deleting RSVP records
    */
	public static List<X7S_Event_RSVP__c> deleteRSVPRecords(Integer noOfEvents, List<X7S_Event_RSVP__c> eventRSVPList)
	{
		delete eventRSVPList;
		return eventRSVPList;
	}

	static final public String COMPANY_COMMUNITY_PROFILE_NAME = x7sEventsTestConstants.CUSTOMER_COMMUNITY_USER;

	static public Id COMPANY_COMMUNITY_PROFILE_Id {
		get {
			if (COMPANY_COMMUNITY_PROFILE_Id == null) {

				List<Profile> profiles = [SELECT Id from Profile where Name = :COMPANY_COMMUNITY_PROFILE_NAME];
				COMPANY_COMMUNITY_PROFILE_Id = profiles[0].Id;
			}
            System.assert(COMPANY_COMMUNITY_PROFILE_Id != null);
			return COMPANY_COMMUNITY_PROFILE_Id;
		}
		set {
			COMPANY_COMMUNITY_PROFILE_Id = value;
			System.assertEquals(value, COMPANY_COMMUNITY_PROFILE_Id);
		}
	}

	static public String THIS_COMMUNITY_NAME {
		get {
			String commName = '';
			commName = [SELECT Id,Name from Network][0].Name;
			System.assertNotEquals(null, commName);
			return commName;
		}
	}

	//by sachin kadian to get profile name from custom metadata
	static public String DEFAULT_PROFILE_NAME{
		get{
			List<X7S_Events_Setting__mdt> eventsSetting = [SELECT Id,Default_Test_Profile__c FROM X7S_Events_Setting__mdt  WHERE DeveloperName='Default'];
			if(eventsSetting != null && eventsSetting.size() >0){
				return eventsSetting[0].Default_Test_Profile__c;
			}
			return null;
		}
	}

	//Create User with given Profile name
	public static List<User> createUsers(Integer howMany, String profileName)
	{
		Account a = new Account(Name = 'TestAccount123', Industry_Type__c = 'Retail') ;
		insert a;

		List<Contact> listOfContacts = new List<Contact>();
		Map<Integer, Contact> mapCont = new Map<Integer, Contact>();

		for (Integer i = 0; i < howMany; i++) {
			Contact c = new Contact(LastName = 'testCon' + i, AccountId = a.Id);
			listOfContacts.add(c);
			mapCont.put(i, c);
		}
		insert listOfContacts;

		// by default bidders
		Id profileId;
		// to make user unique
		String type = 'com';

		Boolean useContact = true;

		if(DEFAULT_PROFILE_NAME != null)
		{
			System.debug('createCommunityUsers - Create user with ' + DEFAULT_PROFILE_NAME + ' profile');
			Profile p  = [SELECT Id, Name FROM Profile WHERE Name = :DEFAULT_PROFILE_NAME];
			profileId  = p.Id;
			useContact = false;
		}
		else if (profileName == COMPANY_COMMUNITY_PROFILE_NAME) {
			System.debug('createCommunityUsers - Create user with ' + COMPANY_COMMUNITY_PROFILE_NAME + ' profile');
			profileId = COMPANY_COMMUNITY_PROFILE_Id;
			type = 'com';
		} else {
			System.debug('createCommunityUsers - Create user with ' + profileName + ' profile');

			Profile p = [SELECT Id, Name FROM Profile WHERE Name = :profileName];
			profileId = p.Id;
		}

		List<User> listOfUsers = new List<User>();
		User usr;

		for (Integer key : mapCont.keySet())
		{
			if (useContact)
			{
				usr = new User(Alias = type + key,
					Email = key + 'testtest@test.com',
					CommunityNickname = key + mapCont.get(key).LastName,
					EmailEncodingKey = 'UTF-8',
					LastName = 'Test' + type + key,
					LanguageLocaleKey = 'en_US',
					LocaleSidKey = 'en_US',
					ProfileId = profileId,
					ContactId = mapCont.get(key).Id,
					TimeZoneSidKey = 'America/Los_Angeles',
					Username = key + type + '@test.com');
			} else {
				usr = new User(Alias = type + key,
					Email = key + 'testtest@test.com',
					CommunityNickname = key + mapCont.get(key).LastName,
					EmailEncodingKey = 'UTF-8',
					LastName = 'Test' + type + key,
					LanguageLocaleKey = 'en_US',
					LocaleSidKey = 'en_US',
					ProfileId = profileId,
					TimeZoneSidKey = 'America/Los_Angeles',
					Username = key + type + '@test.com');
			}
			listOfUsers.add(usr);
		}

		insert listOfUsers;
		return listOfUsers;
	}

	//Create Community User
	//As we are using custom object Events, created a user with the custom Community Profile,
	//As standard community profiles do not allow to give permissions to such custom objects.
	public static User createCommunityUsers(String profileName)
	{
		if(DEFAULT_PROFILE_NAME != null){
			Profile p = [SELECT Id, Name FROM Profile WHERE Name = :DEFAULT_PROFILE_NAME];

			User u = new User(Alias = 'Com',
					Email = 'testtestCommunity@test.com',
					EmailEncodingKey = 'UTF-8',
					LastName = 'Test',
					LanguageLocaleKey = 'en_US',
					LocaleSidKey = 'en_US',
					ProfileId = p.Id,
					TimeZoneSidKey = 'America/Los_Angeles',
					Username = 'testtestCommunity@test.com');

			insert u;
			return u;
		} else {
			Account a = new Account(Name = 'TestAccount123') ;
			insert a;

			Contact c = new Contact(LastName = 'testCon', AccountId = a.Id);
			insert c;


			Profile p = [SELECT Id, Name FROM Profile WHERE Name = :profileName];

			User u = new User(Alias = 'Com',
					Email = 'testtestCommunity@test.com',
					CommunityNickname = c.LastName,
					EmailEncodingKey = 'UTF-8',
					LastName = 'Test',
					LanguageLocaleKey = 'en_US',
					LocaleSidKey = 'en_US',
					ProfileId = p.Id,
					ContactId = c.Id,
					TimeZoneSidKey = 'America/Los_Angeles',
					Username = 'testtestCommunity@test.com');

			insert u;

			return u;
		}
	}

	public static Id createTestGroup(String groupName)
	{
		CollaborationGroup myGroup = new CollaborationGroup();

		myGroup.Name              = groupName;
		myGroup.CollaborationType = 'Public'; //can be 'Public' or 'Private'
		myGroup.NetworkId         = strNetworkId;
		System.assertNotEquals(null, myGroup);

		insert myGroup;
		return myGroup.Id;
	}

	public static void addTestGroupMember(String groupId, String userId)
	{
		CollaborationGroupMember groupMember = new CollaborationGroupMember();

		groupMember.CollaborationGroupId = groupId;
		groupMember.MemberId = userId;
		System.assertNotEquals(null, groupMember);

		insert groupMember;
	}
}