force-app/main/default/objects/Account/fields/Industry_Type__c.field-meta.xml
<CustomField>
    <fullName>Industry_Type__c</fullName>
    <description>The industry associated with the company.</description>
    <inlineHelpText>The industry associated with the company.</inlineHelpText>
    <label>Industry Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Industry_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <description>The source the lead originated from.</description>
    <inlineHelpText>The source the lead originated from.</inlineHelpText>
    <label>Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lead_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Industry_Type__c.field-meta.xml
<CustomField>
    <fullName>Industry_Type__c</fullName>
    <label>Industry Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Industry_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <label>Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lead_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/pse__Is_Resource__c.field-meta.xml
<CustomField>
    <fullName>pse__Is_Resource__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Resource</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/pse__Is_Resource_Active__c.field-meta.xml
<CustomField>
    <fullName>pse__Is_Resource_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Resource Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/pse__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__Start_Date__c</fullName>
    <description>A Resource&apos;s first date of employment.</description>
    <inlineHelpText>A Resource&apos;s first date of employment.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/PSA_Resource.recordType-meta.xml
<RecordType>
    <fullName>PSA_Resource</fullName>
    <active>true</active>
    <label>PSA Resource</label>
</RecordType>

force-app/main/default/objects/pse__Proj__c/pse__Proj__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__ProjectHelp</customHelpPage>
    <description>Represents a collection of business transactions, activities, and related items to be managed over a defined time range, such as timecards, expenses, milestones, and budgets. Typically, people (represented by Resource records) are assigned to projects, though some projects do not require assignments in order to be staffed. Projects may also have a master project (parent) or a sub project (child) in the project hierarchy, supporting roll-ups of revenues, costs, and time to every project and up through the hierarchy.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Proj__c/fields/pse__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/Industry_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Business Services</fullName>
    </customValue>
    <customValue>
        <fullName>Communications/Media</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer Goods</fullName>
    </customValue>
    <customValue>
        <fullName>Financial Services</fullName>
        <label>Financial  Services</label>
    </customValue>
    <customValue>
        <fullName>Government</fullName>
    </customValue>
    <customValue>
        <fullName>Healthcare</fullName>
    </customValue>
    <customValue>
        <fullName>Higher Education</fullName>
    </customValue>
    <customValue>
        <fullName>High Tech/Software</fullName>
    </customValue>
    <customValue>
        <fullName>Leisure &amp; Hospitality</fullName>
    </customValue>
    <customValue>
        <fullName>Manufacturing &amp; Automotive</fullName>
    </customValue>
    <customValue>
        <fullName>Nonprofit</fullName>
    </customValue>
    <customValue>
        <fullName>Retail</fullName>
    </customValue>
    <customValue>
        <fullName>Transportation</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Legacy</fullName>
        <isActive>false</isActive>
        <label>Legacy</label>
    </customValue>
    <description>Industry type values</description>
    <masterLabel>Industry Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lead_Source.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AppExchange</fullName>
    </customValue>
    <customValue>
        <fullName>Digital Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Direct Inbound</fullName>
    </customValue>
    <customValue>
        <fullName>Hosted Event</fullName>
    </customValue>
    <customValue>
        <fullName>Sponsored Event</fullName>
    </customValue>
    <customValue>
        <fullName>Website Conversion</fullName>
    </customValue>
    <customValue>
        <fullName>Channel Inbound</fullName>
    </customValue>
    <customValue>
        <fullName>Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Sales Prospecting</fullName>
    </customValue>
    <customValue>
        <fullName>Zoominfo</fullName>
    </customValue>
    <customValue>
        <fullName>Legacy</fullName>
        <isActive>false</isActive>
        <label>Legacy</label>
    </customValue>
    <description>Lead source values</description>
    <masterLabel>Lead Source</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/x7S_PTODashboardController_Test.cls
@IsTest(SeeAllData=false)
public class x7S_PTODashboardController_Test {
    private static Account account;
    private static Contact contact;
    private static Contact manager;
    private static Contact director;
    private static Contact svp;
    private static Contact evp;
    private static pse__Proj__c PTO_Project;
    
    @isTest static void testController() {
        setup();
        
        Test.startTest();
        
        ApexPages.StandardController standardController = new ApexPages.StandardController(contact);
        x7S_PTODashboardController controller = new x7S_PTODashboardController(standardController);
        
        PageReference pageRef = Page.x7S_PTODashboardContainer;
        pageRef.getParameters().put('id', String.valueOf(contact.Id));
        Test.setCurrentPageReference(pageRef);
        
        Test.stopTest();
        
    }
    
    @isTest static void testManager() {
        setup();
        
        Test.startTest();
        
        ApexPages.StandardController standardController = new ApexPages.StandardController(manager);
        x7S_PTODashboardController controller = new x7S_PTODashboardController(standardController);
        
        PageReference pageRef = Page.x7S_PTODashboardContainer;
        pageRef.getParameters().put('id', String.valueOf(manager.Id));
        Test.setCurrentPageReference(pageRef);
        
        Test.stopTest();
        
    }
    
    @isTest static void testDirector() {
        setup();
        
        Test.startTest();
        
        ApexPages.StandardController standardController = new ApexPages.StandardController(director);
        x7S_PTODashboardController controller = new x7S_PTODashboardController(standardController);
        
        PageReference pageRef = Page.x7S_PTODashboardContainer;
        pageRef.getParameters().put('id', String.valueOf(director.Id));
        Test.setCurrentPageReference(pageRef);
        
        Test.stopTest();
        
    }
    
    @isTest static void setup() {
        RecordType rt = [SELECT Id, DeveloperName FROM RecordType WHERE SObjectType='Contact' AND DeveloperName='PSA_Resource'];
        account = new Account(name='Test Account', Industry_Type__c = 'Other');
        insert account;
        
        evp = new Contact(FirstName='SVP', LastName='Contact', RecordTypeId=rt.Id, AccountId=account.Id, pse__Start_Date__c=System.today().addDays(-60));
        evp.Lead_Source__c=null;
        evp.pse__Is_Resource_Active__c = true;
        evp.pse__Is_Resource__c = true;
        evp.RecordTypeId=rt.Id;
        insert evp;
        
        svp =  new Contact(FirstName='SVP', LastName='Contact', RecordTypeId=rt.Id, AccountId=account.Id, pse__Start_Date__c=System.today());
        svp.pse__Is_Resource_Active__c = true;
        svp.pse__Is_Resource__c = true;
        svp.RecordTypeId=rt.Id;
        svp.ReportsToId=evp.Id;
        insert svp;
        
        director = new Contact(FirstName='Director', LastName='Contact', RecordTypeId=rt.Id, AccountId=account.Id, pse__Start_Date__c=System.today());
        director.pse__Is_Resource_Active__c = true;
        director.pse__Is_Resource__c = true;
        director.RecordTypeId=rt.Id;
        director.ReportsToId=svp.Id;
        insert director;
        
        Date jun1 = Date.newInstance(2021, 06, 01);
        manager = new Contact(FirstName='Manager', LastName='Contact', RecordTypeId=rt.Id, AccountId=account.Id, pse__Start_Date__c=jun1);
        manager.pse__Is_Resource_Active__c = true;
        manager.pse__Is_Resource__c = true;
        manager.ReportsToId=director.Id;
        insert manager;
        
		Date jan1 = Date.newInstance(2020, 01, 01);
        contact = new Contact(FirstName='Test', LastName='Contact', RecordTypeId=rt.Id, AccountId=account.Id, pse__Start_Date__c=jan1);
        contact.pse__Is_Resource_Active__c = true;
        contact.pse__Is_Resource__c = true;
        contact.RecordTypeId=rt.Id;
        contact.ReportsToId=manager.Id;
        insert contact;
        
        PTO_Project = new pse__Proj__c();
        PTO_Project.Name = '7S Internal : Vacation'; 
        insert PTO_Project;

    }
}