force-app/main/default/objects/Account/fields/Industry_Type__c.field-meta.xml
<CustomField>
    <fullName>Industry_Type__c</fullName>
    <description>The industry associated with the company.</description>
    <inlineHelpText>The industry associated with the company.</inlineHelpText>
    <label>Industry Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Industry_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Competency_Group__c.field-meta.xml
<CustomField>
    <fullName>Competency_Group__c</fullName>
    <label>Competency Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Delivery Operations</fullName>
            </value>
            <value>
                <fullName>Sales &amp; Marketing</fullName>
            </value>
            <value>
                <fullName>Executive Management</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>Operations &amp; Finance</fullName>
            </value>
            <value>
                <fullName>Experience Design Studio</fullName>
            </value>
            <value>
                <fullName>Business Consulting</fullName>
            </value>
            <value>
                <fullName>Technology &amp; Accelerators</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Coverage_Participant__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Participant__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Coverage Participant</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Industry_Type__c.field-meta.xml
<CustomField>
    <fullName>Industry_Type__c</fullName>
    <label>Industry Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Industry_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/pse__Is_Resource__c.field-meta.xml
<CustomField>
    <fullName>pse__Is_Resource__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Resource</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/pse__Is_Resource_Active__c.field-meta.xml
<CustomField>
    <fullName>pse__Is_Resource_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Resource Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/pse__Resource_Role__c.field-meta.xml
<CustomField>
    <fullName>pse__Resource_Role__c</fullName>
    <label>Resource Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>Biz Arch</fullName>
            </value>
            <value>
                <fullName>Business Analyst (MTX)</fullName>
            </value>
            <value>
                <fullName>Change Analyst</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Content Marketer</fullName>
            </value>
            <value>
                <fullName>CP</fullName>
            </value>
            <value>
                <fullName>CPQ Arch</fullName>
            </value>
            <value>
                <fullName>CS-BA</fullName>
            </value>
            <value>
                <fullName>CS-FED</fullName>
            </value>
            <value>
                <fullName>CS-Platform Dev</fullName>
            </value>
            <value>
                <fullName>CS-PM</fullName>
            </value>
            <value>
                <fullName>CS-SFDC Dev</fullName>
            </value>
            <value>
                <fullName>CS-TL</fullName>
            </value>
            <value>
                <fullName>Customer Success</fullName>
            </value>
            <value>
                <fullName>DA</fullName>
            </value>
            <value>
                <fullName>Design Engineer</fullName>
            </value>
            <value>
                <fullName>Director, FED</fullName>
            </value>
            <value>
                <fullName>Dir of HR &amp; Recruiting</fullName>
            </value>
            <value>
                <fullName>Employee Bolt Consultant</fullName>
            </value>
            <value>
                <fullName>Exec</fullName>
            </value>
            <value>
                <fullName>Experience Strategist</fullName>
            </value>
            <value>
                <fullName>FED</fullName>
            </value>
            <value>
                <fullName>FED (CG)</fullName>
            </value>
            <value>
                <fullName>FED (CT)</fullName>
            </value>
            <value>
                <fullName>FED (GS Labs)</fullName>
            </value>
            <value>
                <fullName>FED (MTX)</fullName>
            </value>
            <value>
                <fullName>FED (Offshore)</fullName>
            </value>
            <value>
                <fullName>Front Desk Receptionist</fullName>
            </value>
            <value>
                <fullName>PM</fullName>
            </value>
            <value>
                <fullName>SFDC Dev</fullName>
            </value>
            <value>
                <fullName>TA</fullName>
            </value>
            <value>
                <fullName>TL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Record_Type__c</fullName>
    <formula>TEXT(Account.Record_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Record Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <label>Resource Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>External</fullName>
            </value>
            <value>
                <fullName>Generic</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/pse__Assignment__c/pse__Assignment__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__AssignmentAndScheduleHelp</customHelpPage>
    <description>Stores information about the allocation of a resource to a project and specifies the bill rate and cost rate for time entered. It references the schedule for a resource and, optionally, a project milestone.</description>
    <label>Assignment</label>
    <nameField>
        <label>Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Assignment__c/fields/pse__Is_Billable__c.field-meta.xml
<CustomField>
    <fullName>pse__Is_Billable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Billable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/pse__Assignment__c/fields/pse__Schedule__c.field-meta.xml
<CustomField>
    <fullName>pse__Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schedule</label>
    <referenceTo>pse__Schedule__c</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Est_Vs_Actuals__c/pse__Est_Vs_Actuals__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__EstimateVsActualsHelp</customHelpPage>
    <description>Compares the estimated and actual hours worked by a resource on an assignment, derived from scheduled hours and entered timecard hours respectively. FinancialForce PSA generates Est Vs Actuals when you create or update assignments and schedules, and when timecard hours are entered for an assignment.</description>
    <label>Est Vs Actuals</label>
    <nameField>
        <label>Est Vs Actuals Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Est Vs Actuals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Est_Vs_Actuals__c/fields/Competency_Group__c.field-meta.xml
<CustomField>
    <fullName>Competency_Group__c</fullName>
    <formula>TEXT(pse__Resource__r.Competency_Group__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Competency Group</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/pse__Est_Vs_Actuals__c/fields/pse__Assignment__c.field-meta.xml
<CustomField>
    <fullName>pse__Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assignment</label>
    <referenceTo>pse__Assignment__c</referenceTo>
    <relationshipLabel>Est Vs Actuals</relationshipLabel>
    <relationshipName>Est_Vs_Actuals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Est_Vs_Actuals__c/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <formula>TEXT(pse__Resource__r.Resource_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Resource Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/pse__Permission_Control__c/pse__Permission_Control__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__PermissionControlHelp</customHelpPage>
    <description>Grants a set of stand-alone or cascading permissions to a single Salesforce user, with reference to either a resource, region, practice, group, or project. Controls whether the user can carry out specific processes including: logging time on behalf of other resources, entering expenses, staffing, and viewing and editing projects in Project Task Gantt and Gantt.</description>
    <label>Permission Control</label>
    <nameField>
        <displayFormat>PC-{0}</displayFormat>
        <label>Permission Control Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Permission Controls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Permission_Control__c/fields/pse__Region__c.field-meta.xml
<CustomField>
    <fullName>pse__Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Region containing Resources that are the target of the specified action(s) - e.g. delegated Timecard Entry on behalf of Resources in this Region.</description>
    <inlineHelpText>This is the Region containing Resources that are the target of the specified action(s) - e.g. delegated Timecard Entry on behalf of Resources in this Region.</inlineHelpText>
    <label>Region</label>
    <referenceTo>pse__Region__c</referenceTo>
    <relationshipLabel>Permission Controls</relationshipLabel>
    <relationshipName>Permission_Controls</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Permission_Control__c/fields/pse__Staffing__c.field-meta.xml
<CustomField>
    <fullName>pse__Staffing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This checkbox governs the User&apos;s ability to staff Resources from specified Regions/Practices/Groups.</description>
    <inlineHelpText>This checkbox governs the User&apos;s ability to staff Resources from specified Regions/Practices/Groups.</inlineHelpText>
    <label>Staffing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/pse__Permission_Control__c/fields/pse__User__c.field-meta.xml
<CustomField>
    <fullName>pse__User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Permission_Controls</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/pse__Proj__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__ProjectHelp</customHelpPage>
    <description>Represents a collection of business transactions, activities, and related items to be managed over a defined time range, such as timecards, expenses, milestones, and budgets. Typically, people (represented by Resource records) are assigned to projects, though some projects do not require assignments in order to be staffed. Projects may also have a master project (parent) or a sub project (child) in the project hierarchy, supporting roll-ups of revenues, costs, and time to every project and up through the hierarchy.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Proj__c/fields/pse__Account__c.field-meta.xml
<CustomField>
    <fullName>pse__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Is_Active__c.field-meta.xml
<CustomField>
    <fullName>pse__Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Region__c.field-meta.xml
<CustomField>
    <fullName>pse__Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region</label>
    <referenceTo>pse__Region__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Stage__c.field-meta.xml
<CustomField>
    <fullName>pse__Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Prepare</fullName>
            </value>
            <value>
                <fullName>Define</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Build</fullName>
            </value>
            <value>
                <fullName>Verify</fullName>
            </value>
            <value>
                <fullName>Launch</fullName>
            </value>
            <value>
                <fullName>Close-Out</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Industry_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Business Services</fullName>
    </customValue>
    <customValue>
        <fullName>Communications/Media</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer Goods</fullName>
    </customValue>
    <customValue>
        <fullName>Financial Services</fullName>
        <label>Financial  Services</label>
    </customValue>
    <customValue>
        <fullName>Government</fullName>
    </customValue>
    <customValue>
        <fullName>Healthcare</fullName>
    </customValue>
    <customValue>
        <fullName>Higher Education</fullName>
    </customValue>
    <customValue>
        <fullName>High Tech/Software</fullName>
    </customValue>
    <customValue>
        <fullName>Leisure &amp; Hospitality</fullName>
    </customValue>
    <customValue>
        <fullName>Manufacturing &amp; Automotive</fullName>
    </customValue>
    <customValue>
        <fullName>Nonprofit</fullName>
    </customValue>
    <customValue>
        <fullName>Retail</fullName>
    </customValue>
    <customValue>
        <fullName>Transportation</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Legacy</fullName>
        <isActive>false</isActive>
        <label>Legacy</label>
    </customValue>
    <description>Industry type values</description>
    <masterLabel>Industry Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProjectStatisticsExtensionTest.cls
@isTest
public class ProjectStatisticsExtensionTest {

    private static Account svnAccount;
    private static Account custAccount;
    private static List<Contact> contacts;
    private static List<pse__Proj__c> projects;
    private static List<pse__Assignment__c> assignments;
    private static List<pse__Schedule__c> schedules;
    private static List<pse__Assignment__c> setupAssignments;
    private static List<pse__Schedule__c> setupSchedules;
    
    @istest static void testExtension() {
        pse__Proj__c project = [SELECT Id FROM pse__Proj__c LIMIT 1];
        ApexPages.StandardController ctrl = new ApexPages.StandardController(project);
        ProjectStatisticsExtension ext = new ProjectStatisticsExtension(ctrl);
        
        ext.getPhaseSummary();
    }
    
    @testsetup static void setup() {
        pse__Region__c region = new pse__Region__c(Name='Test Region');
        insert region;
        
        pse__Permission_Control__c permissionControl = new pse__Permission_Control__c(pse__User__c=UserINfo.getUserId(), pse__Region__c=region.Id, pse__Staffing__c=true);
        insert permissionControl;
        
        RecordType contactRT = [SELECT ID FROM RecordType WHERE SObjectType='Contact' AND Name='PSA Resource'];
        
        svnAccount = new Account(Name='7Summits', Industry_Type__c='Business Services', Record_Type__c='Vintage - Salesforce');
        custAccount = new Account(Name='Customer Account', Industry_Type__c='Business Services', Record_Type__c='Vintage - Salesforce');
        
        insert svnAccount;
        insert custAccount;
        
        contacts = new List<Contact>();
        contacts.add(new Contact(FirstName='Manager', LastName='Contact', email='test1@abc.com', AccountId=svnAccount.Id, pse__Region__c=region.Id, RecordTypeId=contactRT.Id, Competency_Group__c='Technology & Accelerators', Coverage_Participant__c=true, Active__c=true, pse__Is_Resource__c=true, pse__Is_Resource_Active__c=true, Resource_Type__c='Internal', pse__Resource_Role__c='TA'));
        contacts.add(new Contact(FirstName='Dev1', LastName='Contact', email='test1@abc.com', AccountId=svnAccount.Id, pse__Region__c=region.Id, RecordTypeId=contactRT.Id, Competency_Group__c='Technology & Accelerators', Coverage_Participant__c=False, Active__c=true, pse__Is_Resource__c=true, pse__Is_Resource_Active__c=true, Resource_Type__c='Internal', pse__Resource_Role__c='TL'));
        contacts.add(new Contact(FirstName='OpsManager', LastName='Contact', email='test1@abc.com', AccountId=svnAccount.Id, pse__Region__c=region.Id, RecordTypeId=contactRT.Id, Competency_Group__c='Delivery Operations', Coverage_Participant__c=true, Active__c=true, pse__Is_Resource__c=true, pse__Is_Resource_Active__c=true, Resource_Type__c='Internal', pse__Resource_Role__c='PM'));
        contacts.add(new Contact(FirstName='OpsPM', LastName='Contact', email='test1@abc.com', AccountId=svnAccount.Id, pse__Region__c=region.Id, RecordTypeId=contactRT.Id, Competency_Group__c='Delivery Operations', Coverage_Participant__c=false, Active__c=true, pse__Is_Resource__c=true, pse__Is_Resource_Active__c=true, Resource_Type__c='Internal', pse__Resource_Role__c='PM'));
        contacts.add(new Contact(FirstName='Dev2', LastName='Contact', email='test1@abc.com', AccountId=svnAccount.Id, pse__Region__c=region.Id, RecordTypeId=contactRT.Id, Competency_Group__c='Technology & Accelerators', Coverage_Participant__c=False, Active__c=true, pse__Is_Resource__c=true, pse__Is_Resource_Active__c=true, Resource_Type__c='Internal', pse__Resource_Role__c='TA'));
        contacts.add(new Contact(FirstName='BizMgr', LastName='Contact', email='test1@abc.com', AccountId=svnAccount.Id, pse__Region__c=region.Id, RecordTypeId=contactRT.Id, Competency_Group__c='Business Consulting', Coverage_Participant__c=true, Active__c=true, pse__Is_Resource__c=true, pse__Is_Resource_Active__c=true, Resource_Type__c='Internal', pse__Resource_Role__c='PM'));
        contacts.add(new Contact(FirstName='BA', LastName='Contact', email='test1@abc.com', AccountId=svnAccount.Id, pse__Region__c=region.Id, RecordTypeId=contactRT.Id, Competency_Group__c='Business Consulting', Coverage_Participant__c=false, Active__c=true, pse__Is_Resource__c=true, pse__Is_Resource_Active__c=true, Resource_Type__c='Internal', pse__Resource_Role__c='PM'));
        
        insert contacts;
        
        contacts[1].ReportsToId=contacts[0].Id;
        contacts[3].ReportsToId=contacts[2].Id;
        contacts[4].ReportsToId=contacts[0].Id;
        contacts[6].ReportsToId=contacts[5].Id;
        
        update contacts;
        
        System.debug(contacts[1]);
        
        projects = new List<pse__Proj__c>();
        projects.add(new pse__Proj__c(Name='Project 1', pse__Account__c=custAccount.Id, pse__Region__c=region.id, pse__Is_Active__c=true, pse__Stage__c='Planned', pse__Is_Billable__c=true, pse__Allow_Self_Staffing__c=true, Ops_Staffing_Stage__c='Not Staffed', pse__Start_Date__c=System.today(), pse__End_Date__c=System.today().addDays(30)));
        
        insert projects;
        
        pse__Milestone__c milestone = new pse__Milestone__c(pse__Project__c=projects[0].Id, Name='Prepare', pse__Target_Date__c=System.today());
        insert milestone;
        
        pse__Schedule__c baSchedule = new pse__Schedule__c(pse__Start_Date__c=projects[0].pse__Start_Date__c, pse__End_Date__c=projects[0].pse__End_Date__c, pse__Friday_Hours__c=0);
        pse__Schedule__c baMgrSchedule = new pse__Schedule__c(pse__Start_Date__c=projects[0].pse__Start_Date__c, pse__End_Date__c=projects[0].pse__End_Date__c, pse__Friday_Hours__c=0);
        setupSchedules = new List<pse__Schedule__c>();
        setupSchedules.add(baSchedule);
        setupSchedules.add(baMgrSchedule);
        insert setupSchedules;
        
        assignments = new List<pse__Assignment__c>();
        pse__Assignment__c baAssignment = new pse__Assignment__c(pse__Project__c=projects[0].Id, pse__Resource__c=contacts[6].Id, pse__Schedule__c=baSchedule.Id, pse__Role__c='BA', pse__Is_Billable__c=true, pse__Bill_Rate__c=200.00);
        pse__Assignment__c baMgrAssignment = new pse__Assignment__c(pse__Project__c=projects[0].Id, pse__Resource__c=contacts[5].Id, pse__Schedule__c=baMgrSchedule.Id, pse__Role__c='Coverage', pse__Is_Billable__c=false, pse__Bill_Rate__c=0);
        assignments.add(baAssignment);
        assignments.add(baMgrAssignment);
        
        schedules = new List<pse__Schedule__c>();
        schedules.add(new pse__Schedule__c(pse__Start_Date__c=projects[0].pse__Start_Date__c, pse__End_Date__c=projects[0].pse__End_Date__c, pse__Friday_Hours__c=8));
        schedules.add(new pse__Schedule__c(pse__Start_Date__c=projects[0].pse__Start_Date__c, pse__End_Date__c=projects[0].pse__End_Date__c, pse__Friday_Hours__c=8));
        schedules.add(new pse__Schedule__c(pse__Start_Date__c=projects[0].pse__Start_Date__c, pse__End_Date__c=projects[0].pse__End_Date__c, pse__Friday_Hours__c=8));
        insert schedules;
        
        
        assignments.add(new pse__Assignment__c(pse__Project__c=projects[0].Id, pse__Resource__c=contacts[1].Id, pse__Schedule__c=schedules[0].Id, pse__Role__c='SFDC Dev', pse__Is_Billable__c=true, pse__Bill_Rate__c=200.00));
        assignments.add(new pse__Assignment__c(pse__Project__c=projects[0].Id, pse__Resource__c=contacts[4].Id, pse__Schedule__c=schedules[1].Id, pse__Role__c='TA', pse__Is_Billable__c=true, pse__Bill_Rate__c=200.00));
        assignments.add(new pse__Assignment__c(pse__Project__c=projects[0].Id, pse__Resource__c=contacts[3].Id, pse__Schedule__c=schedules[2].Id, pse__Role__c='PM', pse__Is_Billable__c=true, pse__Bill_Rate__c=200.00));
        
        insert assignments;
        
        pse__Est_vs_Actuals__c est = new pse__Est_vs_Actuals__c(Name='test', pse__Assignment__c=assignments[0].Id, pse__Project__c=projects[0].Id, pse__Resource__c=contacts[6].id, pse__Actual_Hours__c=10.0, pse__Estimated_Hours__c=0.0, pse__Start_Date__c=System.today(), pse__End_Date__c=System.today());
        insert est;
    }
}