force-app/main/default/objects/Account/fields/Industry_Type__c.field-meta.xml
<CustomField>
    <fullName>Industry_Type__c</fullName>
    <description>The industry associated with the company.</description>
    <inlineHelpText>The industry associated with the company.</inlineHelpText>
    <label>Industry Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Industry_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Competency_Group__c.field-meta.xml
<CustomField>
    <fullName>Competency_Group__c</fullName>
    <label>Competency Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Delivery Operations</fullName>
            </value>
            <value>
                <fullName>Sales &amp; Marketing</fullName>
            </value>
            <value>
                <fullName>Executive Management</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>Operations &amp; Finance</fullName>
            </value>
            <value>
                <fullName>Experience Design Studio</fullName>
            </value>
            <value>
                <fullName>Business Consulting</fullName>
            </value>
            <value>
                <fullName>Technology &amp; Accelerators</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Coverage_Participant__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Participant__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Coverage Participant</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Generic_Resource__c.field-meta.xml
<CustomField>
    <fullName>Generic_Resource__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Generic Resource</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Industry_Type__c.field-meta.xml
<CustomField>
    <fullName>Industry_Type__c</fullName>
    <label>Industry Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Industry_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/pse__Is_Resource__c.field-meta.xml
<CustomField>
    <fullName>pse__Is_Resource__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Resource</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/pse__Is_Resource_Active__c.field-meta.xml
<CustomField>
    <fullName>pse__Is_Resource_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Resource Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/pse__Resource_Role__c.field-meta.xml
<CustomField>
    <fullName>pse__Resource_Role__c</fullName>
    <label>Resource Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>Biz Arch</fullName>
            </value>
            <value>
                <fullName>Business Analyst (MTX)</fullName>
            </value>
            <value>
                <fullName>Change Analyst</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Content Marketer</fullName>
            </value>
            <value>
                <fullName>CP</fullName>
            </value>
            <value>
                <fullName>CPQ Arch</fullName>
            </value>
            <value>
                <fullName>CS-BA</fullName>
            </value>
            <value>
                <fullName>CS-FED</fullName>
            </value>
            <value>
                <fullName>CS-Platform Dev</fullName>
            </value>
            <value>
                <fullName>CS-PM</fullName>
            </value>
            <value>
                <fullName>CS-SFDC Dev</fullName>
            </value>
            <value>
                <fullName>CS-TL</fullName>
            </value>
            <value>
                <fullName>Customer Success</fullName>
            </value>
            <value>
                <fullName>DA</fullName>
            </value>
            <value>
                <fullName>Design Engineer</fullName>
            </value>
            <value>
                <fullName>Director, FED</fullName>
            </value>
            <value>
                <fullName>Dir of HR &amp; Recruiting</fullName>
            </value>
            <value>
                <fullName>Employee Bolt Consultant</fullName>
            </value>
            <value>
                <fullName>Exec</fullName>
            </value>
            <value>
                <fullName>Experience Strategist</fullName>
            </value>
            <value>
                <fullName>FED</fullName>
            </value>
            <value>
                <fullName>FED (CG)</fullName>
            </value>
            <value>
                <fullName>FED (CT)</fullName>
            </value>
            <value>
                <fullName>FED (GS Labs)</fullName>
            </value>
            <value>
                <fullName>FED (MTX)</fullName>
            </value>
            <value>
                <fullName>FED (Offshore)</fullName>
            </value>
            <value>
                <fullName>Front Desk Receptionist</fullName>
            </value>
            <value>
                <fullName>PM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/pse__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__Start_Date__c</fullName>
    <description>A Resource&apos;s first date of employment.</description>
    <inlineHelpText>A Resource&apos;s first date of employment.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Record_Type__c</fullName>
    <formula>TEXT(Account.Record_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Record Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <label>Resource Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>External</fullName>
            </value>
            <value>
                <fullName>Generic</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/pse__Region__c.field-meta.xml
<CustomField>
    <fullName>pse__Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region</label>
    <referenceTo>pse__Region__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Permission_Control__c/pse__Permission_Control__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__PermissionControlHelp</customHelpPage>
    <description>Grants a set of stand-alone or cascading permissions to a single Salesforce user, with reference to either a resource, region, practice, group, or project. Controls whether the user can carry out specific processes including: logging time on behalf of other resources, entering expenses, staffing, and viewing and editing projects in Project Task Gantt and Gantt.</description>
    <label>Permission Control</label>
    <nameField>
        <displayFormat>PC-{0}</displayFormat>
        <label>Permission Control Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Permission Controls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Permission_Control__c/fields/pse__Region__c.field-meta.xml
<CustomField>
    <fullName>pse__Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Region containing Resources that are the target of the specified action(s) - e.g. delegated Timecard Entry on behalf of Resources in this Region.</description>
    <inlineHelpText>This is the Region containing Resources that are the target of the specified action(s) - e.g. delegated Timecard Entry on behalf of Resources in this Region.</inlineHelpText>
    <label>Region</label>
    <referenceTo>pse__Region__c</referenceTo>
    <relationshipLabel>Permission Controls</relationshipLabel>
    <relationshipName>Permission_Controls</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Permission_Control__c/fields/pse__Resource_Request_Entry__c.field-meta.xml
<CustomField>
    <fullName>pse__Resource_Request_Entry__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This checkbox governs the User&apos;s ability to enter/edit Resource Requests for specified Regions/Practices/Groups.</description>
    <inlineHelpText>This checkbox governs the User&apos;s ability to enter/edit Resource Requests for specified Regions/Practices/Groups.</inlineHelpText>
    <label>Resource Request Entry</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/pse__Permission_Control__c/fields/pse__Staffing__c.field-meta.xml
<CustomField>
    <fullName>pse__Staffing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This checkbox governs the User&apos;s ability to staff Resources from specified Regions/Practices/Groups.</description>
    <inlineHelpText>This checkbox governs the User&apos;s ability to staff Resources from specified Regions/Practices/Groups.</inlineHelpText>
    <label>Staffing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/pse__Permission_Control__c/fields/pse__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/pse__Permission_Control__c/fields/pse__User__c.field-meta.xml
<CustomField>
    <fullName>pse__User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Permission_Controls</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Region__c/pse__Region__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__RegionHelp</customHelpPage>
    <description>An entity that represents a geographic area in which you do business. Regions are organized as an independent hierarchy determined by the Parent Region field, with parent and child records of the same type. Every region in the hierarchy may contain projects, resources (contacts), and other objects. The hierarchy allows roll-ups of revenue, cost, and time totals.</description>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Industry_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Business Services</fullName>
    </customValue>
    <customValue>
        <fullName>Communications/Media</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer Goods</fullName>
    </customValue>
    <customValue>
        <fullName>Financial Services</fullName>
        <label>Financial  Services</label>
    </customValue>
    <customValue>
        <fullName>Government</fullName>
    </customValue>
    <customValue>
        <fullName>Healthcare</fullName>
    </customValue>
    <customValue>
        <fullName>Higher Education</fullName>
    </customValue>
    <customValue>
        <fullName>High Tech/Software</fullName>
    </customValue>
    <customValue>
        <fullName>Leisure &amp; Hospitality</fullName>
    </customValue>
    <customValue>
        <fullName>Manufacturing &amp; Automotive</fullName>
    </customValue>
    <customValue>
        <fullName>Nonprofit</fullName>
    </customValue>
    <customValue>
        <fullName>Retail</fullName>
    </customValue>
    <customValue>
        <fullName>Transportation</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Legacy</fullName>
        <isActive>false</isActive>
        <label>Legacy</label>
    </customValue>
    <description>Industry type values</description>
    <masterLabel>Industry Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ResourceRequestExtension_Test.cls
@IsTest
public class ResourceRequestExtension_Test {
    
    @istest static void testPage() {
        Opportunity testOpp = [SELECT Id FROM Opportunity LIMIT 1];
        PageReference pageRef = Page.x7s_ResourceRequest;
        pageRef.getParameters().put('id', testOpp.Id);
        
        Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController ctrl = new ApexPages.StandardController(testOpp);
        ResourceRequestExtension ext = new ResourceRequestExtension(ctrl);
        
        ext.resourceRequests[0].pse__Notes__c='test';
        ext.resourceRequests[0].pse__Start_Date__c=System.today();
        ext.resourceRequests[0].pse__End_Date__c=System.today().addDays(90);
        ext.resourceRequests[0].pse__Resource_Role__c='PM';
        ext.resourceRequests[0].Hours_per_Week__c='20';
        ext.resourceRequests[0].Deal_Comments__c='Testing deal comments';
        
        ext.resourceRequests[1].pse__Resource_Role__c='BA';
        ext.resourceRequests[1].Deal_Comments__c='Testing deal comments';
        
        ext.resourceRequests[2].Hours_per_Week__c='20';
        ext.resourceRequests[2].Deal_Comments__c='Testing deal comments';
        
        ext.save();
        
        ext.resourceRequests[0].pse__Notes__c='test';
        ext.resourceRequests[0].pse__Start_Date__c=System.today();
        ext.resourceRequests[0].pse__End_Date__c=System.today().addDays(90);
        ext.resourceRequests[0].pse__Resource_Role__c='PM';
        ext.resourceRequests[0].Hours_per_Week__c='20';
        ext.resourceRequests[0].Deal_Comments__c='Testing deal comments';
        
        ext.resourceRequests[1].Hours_per_Week__c='20';
        ext.resourceRequests[1].pse__Resource_Role__c='PM';
        ext.resourceRequests[1].Deal_Comments__c='Testing deal comments';
        
        ext.resourceRequests[2].pse__Resource_Role__c='PM';
        ext.resourceRequests[2].Hours_per_Week__c='20';
        ext.resourceRequests[2].Deal_Comments__c='Testing deal comments';
        
        ext.save();
    }
    
    @isTest static void testFull() {
        Opportunity testOpp = [SELECT Id FROM Opportunity LIMIT 1];
        PageReference pageRef = Page.x7s_ResourceRequest;
        pageRef.getParameters().put('id', testOpp.Id);
        
        Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController ctrl = new ApexPages.StandardController(testOpp);
        ResourceRequestExtension ext = new ResourceRequestExtension(ctrl);
        
        ext.resourceRequests[0].pse__Notes__c='test';
        ext.resourceRequests[0].pse__Start_Date__c=System.today();
        ext.resourceRequests[0].pse__End_Date__c=System.today().addDays(90);
        ext.resourceRequests[0].pse__Resource_Role__c='PM';
        ext.resourceRequests[0].Hours_per_Week__c='20';
        ext.resourceRequests[0].Deal_Comments__c='Testing deal comments';
        
        ext.save();
    }
    
    @testsetup static void setup() {
        pse__Region__c region = new pse__Region__c(Name='Global Region');
        insert region;
        
        pse__Permission_Control__c permissionControl = new pse__Permission_Control__c(pse__User__c=UserINfo.getUserId(), 
                                                                                      pse__Region__c=region.Id, pse__Staffing__c=true,
                                                                                      pse__Resource_Request_Entry__c=true);
        insert permissionControl;
        
        RecordType resourceRT = [SELECT ID FROM RecordType WHERE SObjectType='Contact' AND Name='PSA Resource'];
        
        Account svnAccount = new Account(Name='7Summits', Industry_Type__c='Business Services', Record_Type__c='Vintage - Salesforce');
        insert svnAccount;
        
        Contact x7sContact = new Contact(FirstName='7S', LastName='Contact', email='test1@7s.com', AccountId=svnAccount.Id, pse__Region__c=region.Id, 
                                         RecordTypeId=resourceRT.Id, Competency_Group__c='Delivery Operations', Coverage_Participant__c=false, 
                                         Active__c=true, pse__Is_Resource__c=true, pse__Is_Resource_Active__c=true, Resource_Type__c='Internal', 
                                         pse__Resource_Role__c='PM', Generic_Resource__c=true);
        insert x7sContact;
        
        Account custAccount = new Account(Name='Customer Account', Industry_Type__c='Business Services', Record_Type__c='Vintage - Salesforce');
        insert custAccount;
        
        Opportunity opp = new Opportunity(Name='Test Opp', AccountId=custAccount.Id, StageName='Prospecting', Amount=0.0, CloseDate=System.today());
        insert opp;
    }
}