force-app/main/default/objects/Account/fields/Industry_Type__c.field-meta.xml
<CustomField>
    <fullName>Industry_Type__c</fullName>
    <description>The industry associated with the company.</description>
    <inlineHelpText>The industry associated with the company.</inlineHelpText>
    <label>Industry Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Industry_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Competency_Group__c.field-meta.xml
<CustomField>
    <fullName>Competency_Group__c</fullName>
    <label>Competency Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Delivery Operations</fullName>
            </value>
            <value>
                <fullName>Sales &amp; Marketing</fullName>
            </value>
            <value>
                <fullName>Executive Management</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>Operations &amp; Finance</fullName>
            </value>
            <value>
                <fullName>Experience Design Studio</fullName>
            </value>
            <value>
                <fullName>Business Consulting</fullName>
            </value>
            <value>
                <fullName>Technology &amp; Accelerators</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Coverage_Participant__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Participant__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Coverage Participant</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Industry_Type__c.field-meta.xml
<CustomField>
    <fullName>Industry_Type__c</fullName>
    <label>Industry Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Industry_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/pse__Is_Resource__c.field-meta.xml
<CustomField>
    <fullName>pse__Is_Resource__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Resource</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/pse__Is_Resource_Active__c.field-meta.xml
<CustomField>
    <fullName>pse__Is_Resource_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Resource Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/pse__Resource_Role__c.field-meta.xml
<CustomField>
    <fullName>pse__Resource_Role__c</fullName>
    <label>Resource Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>Biz Arch</fullName>
            </value>
            <value>
                <fullName>Business Analyst (MTX)</fullName>
            </value>
            <value>
                <fullName>Change Analyst</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Content Marketer</fullName>
            </value>
            <value>
                <fullName>CP</fullName>
            </value>
            <value>
                <fullName>CPQ Arch</fullName>
            </value>
            <value>
                <fullName>CS-BA</fullName>
            </value>
            <value>
                <fullName>CS-FED</fullName>
            </value>
            <value>
                <fullName>CS-Platform Dev</fullName>
            </value>
            <value>
                <fullName>CS-PM</fullName>
            </value>
            <value>
                <fullName>CS-SFDC Dev</fullName>
            </value>
            <value>
                <fullName>CS-TL</fullName>
            </value>
            <value>
                <fullName>Customer Success</fullName>
            </value>
            <value>
                <fullName>DA</fullName>
            </value>
            <value>
                <fullName>Design Engineer</fullName>
            </value>
            <value>
                <fullName>Director, FED</fullName>
            </value>
            <value>
                <fullName>Dir of HR &amp; Recruiting</fullName>
            </value>
            <value>
                <fullName>Employee Bolt Consultant</fullName>
            </value>
            <value>
                <fullName>Exec</fullName>
            </value>
            <value>
                <fullName>Experience Strategist</fullName>
            </value>
            <value>
                <fullName>FED</fullName>
            </value>
            <value>
                <fullName>FED (CG)</fullName>
            </value>
            <value>
                <fullName>FED (CT)</fullName>
            </value>
            <value>
                <fullName>FED (GS Labs)</fullName>
            </value>
            <value>
                <fullName>FED (MTX)</fullName>
            </value>
            <value>
                <fullName>FED (Offshore)</fullName>
            </value>
            <value>
                <fullName>Front Desk Receptionist</fullName>
            </value>
            <value>
                <fullName>PM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Record_Type__c</fullName>
    <formula>TEXT(Account.Record_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Record Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <label>Resource Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>External</fullName>
            </value>
            <value>
                <fullName>Generic</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/GetFeedback_Setting__mdt/GetFeedback_Setting__mdt.object-meta.xml
<CustomObject>
    <label>GetFeedback Setting</label>
    <pluralLabel>GetFeedback Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/GetFeedback_Setting__mdt/fields/ProjectStages__c.field-meta.xml
<CustomField>
    <fullName>ProjectStages__c</fullName>
    <defaultValue>&apos;Define, Design, Build, Verify, Launch&apos;</defaultValue>
    <description>Stages used to determine projects included in surveys</description>
    <inlineHelpText>Project Stages used when selecting Project Survey Contacts separated by a comma (i.e. Define, Design, Build, Verify, Launch</inlineHelpText>
    <label>Project Stages</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project_Type__c.field-meta.xml
<CustomField>
    <fullName>Project_Type__c</fullName>
    <label>Project Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Project</fullName>
            </value>
            <value>
                <fullName>Change Order</fullName>
            </value>
            <value>
                <fullName>IP Only</fullName>
            </value>
            <value>
                <fullName>Customer Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/pse__Region__c.field-meta.xml
<CustomField>
    <fullName>pse__Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region</label>
    <referenceTo>pse__Region__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProjectSurveyContact__c/ProjectSurveyContact__c.object-meta.xml
<CustomObject>
    <label>Project Survey Contact</label>
    <nameField>
        <displayFormat>PSC-{0000000}</displayFormat>
        <label>Survey Contact</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Survey Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectSurveyContact__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Project Survey Contacts</relationshipLabel>
    <relationshipName>Project_Survey_Contacts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/pse__Permission_Control__c/pse__Permission_Control__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__PermissionControlHelp</customHelpPage>
    <description>Grants a set of stand-alone or cascading permissions to a single Salesforce user, with reference to either a resource, region, practice, group, or project. Controls whether the user can carry out specific processes including: logging time on behalf of other resources, entering expenses, staffing, and viewing and editing projects in Project Task Gantt and Gantt.</description>
    <label>Permission Control</label>
    <nameField>
        <displayFormat>PC-{0}</displayFormat>
        <label>Permission Control Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Permission Controls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Permission_Control__c/fields/pse__Region__c.field-meta.xml
<CustomField>
    <fullName>pse__Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Region containing Resources that are the target of the specified action(s) - e.g. delegated Timecard Entry on behalf of Resources in this Region.</description>
    <inlineHelpText>This is the Region containing Resources that are the target of the specified action(s) - e.g. delegated Timecard Entry on behalf of Resources in this Region.</inlineHelpText>
    <label>Region</label>
    <referenceTo>pse__Region__c</referenceTo>
    <relationshipLabel>Permission Controls</relationshipLabel>
    <relationshipName>Permission_Controls</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Permission_Control__c/fields/pse__Staffing__c.field-meta.xml
<CustomField>
    <fullName>pse__Staffing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This checkbox governs the User&apos;s ability to staff Resources from specified Regions/Practices/Groups.</description>
    <inlineHelpText>This checkbox governs the User&apos;s ability to staff Resources from specified Regions/Practices/Groups.</inlineHelpText>
    <label>Staffing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/pse__Permission_Control__c/fields/pse__User__c.field-meta.xml
<CustomField>
    <fullName>pse__User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Permission_Controls</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/pse__Proj__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__ProjectHelp</customHelpPage>
    <description>Represents a collection of business transactions, activities, and related items to be managed over a defined time range, such as timecards, expenses, milestones, and budgets. Typically, people (represented by Resource records) are assigned to projects, though some projects do not require assignments in order to be staffed. Projects may also have a master project (parent) or a sub project (child) in the project hierarchy, supporting roll-ups of revenues, costs, and time to every project and up through the hierarchy.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Proj__c/fields/pse__Account__c.field-meta.xml
<CustomField>
    <fullName>pse__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Allow_Self_Staffing__c.field-meta.xml
<CustomField>
    <fullName>pse__Allow_Self_Staffing__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Whether a resource may create an assignment to this project for his/her own resource. Checking this will allow any and all resources in the system to create assignments to this project.</inlineHelpText>
    <label>Allow Self-Staffing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Is_Active__c.field-meta.xml
<CustomField>
    <fullName>pse__Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Is_Billable__c.field-meta.xml
<CustomField>
    <fullName>pse__Is_Billable__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check if this project is billable to a customer.</inlineHelpText>
    <label>Billable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Region__c.field-meta.xml
<CustomField>
    <fullName>pse__Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region</label>
    <referenceTo>pse__Region__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Stage__c.field-meta.xml
<CustomField>
    <fullName>pse__Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Prepare</fullName>
            </value>
            <value>
                <fullName>Define</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Build</fullName>
            </value>
            <value>
                <fullName>Verify</fullName>
            </value>
            <value>
                <fullName>Launch</fullName>
            </value>
            <value>
                <fullName>Close-Out</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Industry_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Business Services</fullName>
    </customValue>
    <customValue>
        <fullName>Communications/Media</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer Goods</fullName>
    </customValue>
    <customValue>
        <fullName>Financial Services</fullName>
        <label>Financial  Services</label>
    </customValue>
    <customValue>
        <fullName>Government</fullName>
    </customValue>
    <customValue>
        <fullName>Healthcare</fullName>
    </customValue>
    <customValue>
        <fullName>Higher Education</fullName>
    </customValue>
    <customValue>
        <fullName>High Tech/Software</fullName>
    </customValue>
    <customValue>
        <fullName>Leisure &amp; Hospitality</fullName>
    </customValue>
    <customValue>
        <fullName>Manufacturing &amp; Automotive</fullName>
    </customValue>
    <customValue>
        <fullName>Nonprofit</fullName>
    </customValue>
    <customValue>
        <fullName>Retail</fullName>
    </customValue>
    <customValue>
        <fullName>Transportation</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Legacy</fullName>
        <isActive>false</isActive>
        <label>Legacy</label>
    </customValue>
    <description>Industry type values</description>
    <masterLabel>Industry Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ScheduleSendProjectNotifications_Test.cls
@isTest
public class ScheduleSendProjectNotifications_Test {

    @isTest static void testBatchClass() {
        Test.startTest();
        Id batchProcessId = Database.executeBatch( new SendProjectSurveyNotificationsBatch());
        Test.stopTest();
    }
    
    @isTest static void testScheduler() {
        Integer year = System.today().year();
        String cronExpr = '0 0 0 24 2 ? ' + (year+1);
        Test.startTest();
        String jobId = System.schedule('SendSurveyNotifications', cronExpr, new ScheduleSendProjectSurveyNotifications());
        Test.stopTest();
    }
    
    @isTest static void testSchedulerParameter() {
        Integer year = System.today().year();
        String cronExpr = '0 0 0 24 2 ? ' + (year+1);
        Test.startTest();
        String jobId = System.schedule('SendSurveyNotifications', cronExpr, new ScheduleSendProjectSurveyNotifications('Customer Success'));
        Test.stopTest();
    }
    
    @testSetup static void setup() {
        pse__Region__c region = new pse__Region__c(Name='Test Region');
        insert region;
        
        pse__Permission_Control__c permissionControl = new pse__Permission_Control__c(pse__User__c=UserINfo.getUserId(), pse__Region__c=region.Id, pse__Staffing__c=true);
        insert permissionControl;
        
        RecordType resourceRT = [SELECT ID FROM RecordType WHERE SObjectType='Contact' AND Name='PSA Resource'];
        RecordType contactRT = [SELECT ID FROM RecordType WHERE SObjectType='Contact' AND Name='Contact'];
        
        Account svnAccount = new Account(Name='7Summits', Industry_Type__c='Business Services', Record_Type__c='Vintage - Salesforce');
        Account custAccount = new Account(Name='Customer Account', Industry_Type__c='Business Services', Record_Type__c='Vintage - Salesforce');
        
        insert svnAccount;
        insert custAccount;
        
        Contact x7sContact = new Contact(FirstName='7S', LastName='Contact', Title='Test Title', email='test1@7s.com', AccountId=svnAccount.Id, pse__Region__c=region.Id, RecordTypeId=resourceRT.Id, Competency_Group__c='Delivery Operations', Coverage_Participant__c=false, Active__c=true, pse__Is_Resource__c=true, pse__Is_Resource_Active__c=true, Resource_Type__c='Internal', pse__Resource_Role__c='PM');
        insert x7sContact;
        
		Contact custContact = new Contact(FirstName='Cust', LastName='Contact', Title='Test Title', email='test1@customer.com', AccountId=custAccount.Id, RecordTypeId=contactRT.Id);
        insert custContact;
        
        Opportunity opp = new Opportunity(Name='Test Opportunity', StageName='2 Qualified', Amount=10000.0, CloseDate=System.today().addDays(90), Project_Type__c='New Project');
        insert opp;
        
        GetFeedback_Setting__mdt gfSetting = [SELECT ProjectStages__c FROM GetFeedback_Setting__mdt WHERE DeveloperName='Project_Survey'];
        List<String> stages = gfSetting.ProjectStages__c.split(',');
        
        pse__Proj__c project = new pse__Proj__c(Name='Project 1', pse__Account__c=custAccount.Id, pse__Region__c=region.id, pse__Is_Active__c=true, pse__Stage__c=stages[0], pse__Is_Billable__c=true, pse__Allow_Self_Staffing__c=true, Ops_Staffing_Stage__c='Not Staffed', pse__Start_Date__c=System.today(), pse__End_Date__c=System.today().addDays(30), pse__Project_Manager__c=x7sContact.Id, pse__Opportunity__c=opp.Id);
        insert project;
        
        insert new ProjectSurveyContact__c(project__c=project.Id, Account__c=custAccount.Id, Contact__c=custContact.Id, SendSurvey__c=true);
    }
}