force-app/main/default/objects/Account/fields/Industry_Type__c.field-meta.xml
<CustomField>
    <fullName>Industry_Type__c</fullName>
    <description>The industry associated with the company.</description>
    <inlineHelpText>The industry associated with the company.</inlineHelpText>
    <label>Industry Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Industry_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Industry_Type__c.field-meta.xml
<CustomField>
    <fullName>Industry_Type__c</fullName>
    <label>Industry Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Industry_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/pse__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__Start_Date__c</fullName>
    <description>A Resource&apos;s first date of employment.</description>
    <inlineHelpText>A Resource&apos;s first date of employment.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Record_Type__c</fullName>
    <formula>TEXT(Account.Record_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Record Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/GetFeedback_Aut__Answer__c/GetFeedback_Aut__Answer__c.object-meta.xml
<CustomObject>
    <label>Answer</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Answer</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GetFeedback_Aut__Answer__c/fields/GetFeedback_Aut__Contact__c.field-meta.xml
<CustomField>
    <fullName>GetFeedback_Aut__Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Answers</relationshipLabel>
    <relationshipName>Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GetFeedback_Aut__Answer__c/fields/GetFeedback_Aut__GetFeedbackId__c.field-meta.xml
<CustomField>
    <fullName>GetFeedback_Aut__GetFeedbackId__c</fullName>
    <externalId>true</externalId>
    <label>GetFeedbackId</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/GetFeedback_Aut__Answer__c/fields/GetFeedback_Aut__Response__c.field-meta.xml
<CustomField>
    <fullName>GetFeedback_Aut__Response__c</fullName>
    <label>Response</label>
    <referenceTo>GetFeedback_Aut__Response__c</referenceTo>
    <relationshipLabel>Answers</relationshipLabel>
    <relationshipName>Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GetFeedback_Aut__Answer__c/fields/GetFeedback_Aut__Survey__c.field-meta.xml
<CustomField>
    <fullName>GetFeedback_Aut__Survey__c</fullName>
    <formula>HYPERLINK(&quot;/&quot; &amp; GetFeedback_Aut__Response__r.GetFeedback_Aut__Survey__c, GetFeedback_Aut__Response__r.GetFeedback_Aut__Survey__r.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Survey</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GetFeedback_Aut__Response__c/GetFeedback_Aut__Response__c.object-meta.xml
<CustomObject>
    <label>Response</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GetFeedback_Aut__Response__c/fields/GetFeedback_Aut__Account__c.field-meta.xml
<CustomField>
    <fullName>GetFeedback_Aut__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Responses</relationshipLabel>
    <relationshipName>Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GetFeedback_Aut__Response__c/fields/GetFeedback_Aut__GetFeedbackId__c.field-meta.xml
<CustomField>
    <fullName>GetFeedback_Aut__GetFeedbackId__c</fullName>
    <externalId>true</externalId>
    <label>GetFeedback Id</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/GetFeedback_Aut__Response__c/fields/GetFeedback_Aut__Survey__c.field-meta.xml
<CustomField>
    <fullName>GetFeedback_Aut__Survey__c</fullName>
    <label>Survey</label>
    <referenceTo>GetFeedback_Aut__Survey__c</referenceTo>
    <relationshipLabel>Responses</relationshipLabel>
    <relationshipName>Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GetFeedback_Aut__Survey__c/GetFeedback_Aut__Survey__c.object-meta.xml
<CustomObject>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GetFeedback_Aut__Survey__c/fields/GetFeedback_Aut__GetFeedbackId__c.field-meta.xml
<CustomField>
    <fullName>GetFeedback_Aut__GetFeedbackId__c</fullName>
    <externalId>true</externalId>
    <label>GetFeedbackId</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ProjectSurveyContact__c/ProjectSurveyContact__c.object-meta.xml
<CustomObject>
    <label>Project Survey Contact</label>
    <nameField>
        <displayFormat>PSC-{0000000}</displayFormat>
        <label>Survey Contact</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Survey Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectSurveyContact__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Project Survey Contacts</relationshipLabel>
    <relationshipName>Project_Survey_Contacts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ProjectSurveyContact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Project Survey Contacts</relationshipLabel>
    <relationshipName>Project_Survey_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Permission_Control__c/pse__Permission_Control__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__PermissionControlHelp</customHelpPage>
    <description>Grants a set of stand-alone or cascading permissions to a single Salesforce user, with reference to either a resource, region, practice, group, or project. Controls whether the user can carry out specific processes including: logging time on behalf of other resources, entering expenses, staffing, and viewing and editing projects in Project Task Gantt and Gantt.</description>
    <label>Permission Control</label>
    <nameField>
        <displayFormat>PC-{0}</displayFormat>
        <label>Permission Control Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Permission Controls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Permission_Control__c/fields/pse__Region__c.field-meta.xml
<CustomField>
    <fullName>pse__Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Region containing Resources that are the target of the specified action(s) - e.g. delegated Timecard Entry on behalf of Resources in this Region.</description>
    <inlineHelpText>This is the Region containing Resources that are the target of the specified action(s) - e.g. delegated Timecard Entry on behalf of Resources in this Region.</inlineHelpText>
    <label>Region</label>
    <referenceTo>pse__Region__c</referenceTo>
    <relationshipLabel>Permission Controls</relationshipLabel>
    <relationshipName>Permission_Controls</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Permission_Control__c/fields/pse__Staffing__c.field-meta.xml
<CustomField>
    <fullName>pse__Staffing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This checkbox governs the User&apos;s ability to staff Resources from specified Regions/Practices/Groups.</description>
    <inlineHelpText>This checkbox governs the User&apos;s ability to staff Resources from specified Regions/Practices/Groups.</inlineHelpText>
    <label>Staffing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/pse__Permission_Control__c/fields/pse__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/pse__Permission_Control__c/fields/pse__User__c.field-meta.xml
<CustomField>
    <fullName>pse__User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Permission_Controls</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/pse__Proj__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__ProjectHelp</customHelpPage>
    <description>Represents a collection of business transactions, activities, and related items to be managed over a defined time range, such as timecards, expenses, milestones, and budgets. Typically, people (represented by Resource records) are assigned to projects, though some projects do not require assignments in order to be staffed. Projects may also have a master project (parent) or a sub project (child) in the project hierarchy, supporting roll-ups of revenues, costs, and time to every project and up through the hierarchy.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Proj__c/fields/Ops_Staffing_Stage__c.field-meta.xml
<CustomField>
    <fullName>Ops_Staffing_Stage__c</fullName>
    <description>Where we are with staffing new opportunity</description>
    <inlineHelpText>Ops Use Only</inlineHelpText>
    <label>Ops Staffing Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Staffed</fullName>
            </value>
            <value>
                <fullName>Staffing Initiated</fullName>
            </value>
            <value>
                <fullName>Partial Staff - Cannot Start</fullName>
            </value>
            <value>
                <fullName>Partial Staff - Can Start</fullName>
            </value>
            <value>
                <fullName>Fully Staffed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Account__c.field-meta.xml
<CustomField>
    <fullName>pse__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Allow_Self_Staffing__c.field-meta.xml
<CustomField>
    <fullName>pse__Allow_Self_Staffing__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Whether a resource may create an assignment to this project for his/her own resource. Checking this will allow any and all resources in the system to create assignments to this project.</inlineHelpText>
    <label>Allow Self-Staffing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__End_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Is_Active__c.field-meta.xml
<CustomField>
    <fullName>pse__Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Is_Billable__c.field-meta.xml
<CustomField>
    <fullName>pse__Is_Billable__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check if this project is billable to a customer.</inlineHelpText>
    <label>Billable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Region__c.field-meta.xml
<CustomField>
    <fullName>pse__Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region</label>
    <referenceTo>pse__Region__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Stage__c.field-meta.xml
<CustomField>
    <fullName>pse__Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Prepare</fullName>
            </value>
            <value>
                <fullName>Define</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Build</fullName>
            </value>
            <value>
                <fullName>Verify</fullName>
            </value>
            <value>
                <fullName>Launch</fullName>
            </value>
            <value>
                <fullName>Close-Out</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/Industry_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Business Services</fullName>
    </customValue>
    <customValue>
        <fullName>Communications/Media</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer Goods</fullName>
    </customValue>
    <customValue>
        <fullName>Financial Services</fullName>
        <label>Financial  Services</label>
    </customValue>
    <customValue>
        <fullName>Government</fullName>
    </customValue>
    <customValue>
        <fullName>Healthcare</fullName>
    </customValue>
    <customValue>
        <fullName>Higher Education</fullName>
    </customValue>
    <customValue>
        <fullName>High Tech/Software</fullName>
    </customValue>
    <customValue>
        <fullName>Leisure &amp; Hospitality</fullName>
    </customValue>
    <customValue>
        <fullName>Manufacturing &amp; Automotive</fullName>
    </customValue>
    <customValue>
        <fullName>Nonprofit</fullName>
    </customValue>
    <customValue>
        <fullName>Retail</fullName>
    </customValue>
    <customValue>
        <fullName>Transportation</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Legacy</fullName>
        <isActive>false</isActive>
        <label>Legacy</label>
    </customValue>
    <description>Industry type values</description>
    <masterLabel>Industry Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/GetfeedbackAnswerTriggerTest.cls
@isTest
public class GetfeedbackAnswerTriggerTest {

    @testsetup static void setupData() {
        pse__Region__c region = new pse__Region__c(Name='Test Region');
        insert region;
        
        pse__Permission_Control__c permissionControl = new pse__Permission_Control__c(pse__User__c=UserINfo.getUserId(), pse__Region__c=region.Id, pse__Staffing__c=true);
        insert permissionControl;
        
        RecordType contactRT = [SELECT ID FROM RecordType WHERE SObjectType='Contact' AND Name='Contact'];
        
        Account custAccount1 = new Account(Name='Customer Account-1', Industry_Type__c='Business Services', Record_Type__c='Vintage - Salesforce');
        insert custAccount1;

        Account custAccount2 = new Account(Name='Sample Account-2', Industry_Type__c='Business Services', Record_Type__c='Vintage - Salesforce');
        insert custAccount2;
        
        List<Contact> contacts = new List<Contact>();
        contacts.add(new Contact(FirstName='Test', LastName='Contact', email='test1@abc.com', AccountId=custAccount1.Id, RecordTypeId=contactRT.Id));
        contacts.add(new Contact(FirstName='Example', LastName='Contact', email='Example@abc.com', AccountId=custAccount1.Id,  RecordTypeId=contactRT.Id));
        contacts.add(new Contact(FirstName='Sample', LastName='Contact', email='Sample@abc.com', AccountId=custAccount1.Id, RecordTypeId=contactRT.Id));
        contacts.add(new Contact(FirstName='Mobile', LastName='Contact', email='Mobile@abc.com', AccountId=custAccount1.Id, RecordTypeId=contactRT.Id));
        contacts.add(new Contact(FirstName='Local', LastName='Contact', email='Local@abc.com', AccountId=custAccount2.Id, RecordTypeId=contactRT.Id));
        contacts.add(new Contact(FirstName='Work', LastName='Contact', email='Work@abc.com', AccountId=custAccount2.Id, RecordTypeId=contactRT.Id));
        contacts.add(new Contact(FirstName='Last', LastName='Contact', email='Last@abc.com', AccountId=custAccount2.Id, RecordTypeId=contactRT.Id));
        
        insert contacts;
        
        List<pse__Proj__c> projects = New List<pse__Proj__c>();
        projects.add(new pse__Proj__c(Name='Project 1', pse__Account__c=custAccount1.Id, pse__Region__c=region.id, pse__Is_Active__c=true, pse__Stage__c='Define', pse__Is_Billable__c=true, pse__Allow_Self_Staffing__c=true, Ops_Staffing_Stage__c='Not Staffed', pse__Start_Date__c=System.today(), pse__End_Date__c=System.today().addDays(30)));
        projects.add(new pse__Proj__c(Name='Project 2', pse__Account__c=custAccount2.Id, pse__Region__c=region.id, pse__Is_Active__c=true, pse__Stage__c='Design', pse__Is_Billable__c=true, pse__Allow_Self_Staffing__c=true, Ops_Staffing_Stage__c='Not Staffed', pse__Start_Date__c=System.today(), pse__End_Date__c=System.today().addDays(30)));
        insert projects;        
        
        Decimal surveyId = Decimal.valueOf(Math.random()*100000);
        GetFeedback_Aut__Survey__c survey = new GetFeedback_Aut__Survey__c(Name='Test Survey', GetFeedback_Aut__GetFeedbackId__c=surveyId);
        insert survey;

        List<GetFeedback_Aut__Response__c> responses = new List<GetFeedback_Aut__Response__c>();
		List<ProjectSurveyContact__c> projectContacts = new List<ProjectSurveyContact__c>();
        for(pse__Proj__c project : projects) {
            List<Contact> contactList = [SELECT Id, AccountId FROM Contact WHERE AccountId =: project.pse__Account__c];
            for(Contact contact : contactList) {
                Decimal responseId = Decimal.valueOf(Math.random()*100000);
                responses.add(new GetFeedback_Aut__Response__c(GetFeedback_Aut__Survey__c=survey.Id, GetFeedback_Aut__GetFeedbackId__c=responseId,
                                                               GetFeedback_Aut__Account__c=project.pse__Account__c, GetFeedback_Aut__Contact__c=contact.Id, ProjectId__c=project.Id));
                projectContacts.add(new ProjectSurveyContact__c(Project__c=project.Id, Contact__c=contact.Id, Account__c=contact.AccountId));
            }
        }

        insert projectContacts;
        insert responses;
    }
    
    @isTest static void testTriggerAndHandler() {
        List<GetFeedback_Aut__Answer__c> answers = new List<GetFeedback_Aut__Answer__c>();

        List<GetFeedback_Aut__Response__c> responses = [SELECT Id FROM GetFeedback_Aut__Response__c];
        for(GetFeedback_Aut__Response__c response : responses) {
            Decimal answerId = Decimal.valueOf(Math.random()*100000);
            Decimal csat = Decimal.valueOf(Math.random()*10);
            answers.add(new GetFeedback_Aut__Answer__c(GetFeedback_Aut__Response__c=response.Id, GetFeedback_Aut__Number__c=csat, GetFeedback_Aut__QuestionTitle__c='My Question',
                                                       GetFeedback_Aut__GetFeedbackId__c=''+answerId, GetFeedback_Aut__QuestionType__c='NetPromoter'));
        }
        
        answers[0].GetFeedback_Aut__Number__c=10.0;
        answers[1].GetFeedback_Aut__Number__c=7.0;
        answers[2].GetFeedback_Aut__Number__c=3.0;
        
		insert answers;

        delete answers[0];
    }
}