force-app/main/default/objects/Account/fields/Industry_Type__c.field-meta.xml
<CustomField>
    <fullName>Industry_Type__c</fullName>
    <description>The industry associated with the company.</description>
    <inlineHelpText>The industry associated with the company.</inlineHelpText>
    <label>Industry Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Industry_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Competency_Group__c.field-meta.xml
<CustomField>
    <fullName>Competency_Group__c</fullName>
    <label>Competency Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Delivery Operations</fullName>
            </value>
            <value>
                <fullName>Sales &amp; Marketing</fullName>
            </value>
            <value>
                <fullName>Executive Management</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>Operations &amp; Finance</fullName>
            </value>
            <value>
                <fullName>Experience Design Studio</fullName>
            </value>
            <value>
                <fullName>Business Consulting</fullName>
            </value>
            <value>
                <fullName>Technology &amp; Accelerators</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Coverage_Participant__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Participant__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Coverage Participant</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Industry_Type__c.field-meta.xml
<CustomField>
    <fullName>Industry_Type__c</fullName>
    <label>Industry Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Industry_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/pse__Is_Resource__c.field-meta.xml
<CustomField>
    <fullName>pse__Is_Resource__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Resource</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/pse__Is_Resource_Active__c.field-meta.xml
<CustomField>
    <fullName>pse__Is_Resource_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Resource Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/pse__Resource_Role__c.field-meta.xml
<CustomField>
    <fullName>pse__Resource_Role__c</fullName>
    <label>Resource Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>Biz Arch</fullName>
            </value>
            <value>
                <fullName>Business Analyst (MTX)</fullName>
            </value>
            <value>
                <fullName>Change Analyst</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Content Marketer</fullName>
            </value>
            <value>
                <fullName>CP</fullName>
            </value>
            <value>
                <fullName>CPQ Arch</fullName>
            </value>
            <value>
                <fullName>CS-BA</fullName>
            </value>
            <value>
                <fullName>CS-FED</fullName>
            </value>
            <value>
                <fullName>CS-Platform Dev</fullName>
            </value>
            <value>
                <fullName>CS-PM</fullName>
            </value>
            <value>
                <fullName>CS-SFDC Dev</fullName>
            </value>
            <value>
                <fullName>CS-TL</fullName>
            </value>
            <value>
                <fullName>Customer Success</fullName>
            </value>
            <value>
                <fullName>DA</fullName>
            </value>
            <value>
                <fullName>Design Engineer</fullName>
            </value>
            <value>
                <fullName>Director, FED</fullName>
            </value>
            <value>
                <fullName>Dir of HR &amp; Recruiting</fullName>
            </value>
            <value>
                <fullName>Employee Bolt Consultant</fullName>
            </value>
            <value>
                <fullName>Exec</fullName>
            </value>
            <value>
                <fullName>Experience Strategist</fullName>
            </value>
            <value>
                <fullName>FED</fullName>
            </value>
            <value>
                <fullName>FED (CG)</fullName>
            </value>
            <value>
                <fullName>FED (CT)</fullName>
            </value>
            <value>
                <fullName>FED (GS Labs)</fullName>
            </value>
            <value>
                <fullName>FED (MTX)</fullName>
            </value>
            <value>
                <fullName>FED (Offshore)</fullName>
            </value>
            <value>
                <fullName>Front Desk Receptionist</fullName>
            </value>
            <value>
                <fullName>PM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Record_Type__c</fullName>
    <formula>TEXT(Account.Record_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Record Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <label>Resource Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>External</fullName>
            </value>
            <value>
                <fullName>Generic</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/pse__Permission_Control__c/pse__Permission_Control__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__PermissionControlHelp</customHelpPage>
    <description>Grants a set of stand-alone or cascading permissions to a single Salesforce user, with reference to either a resource, region, practice, group, or project. Controls whether the user can carry out specific processes including: logging time on behalf of other resources, entering expenses, staffing, and viewing and editing projects in Project Task Gantt and Gantt.</description>
    <label>Permission Control</label>
    <nameField>
        <displayFormat>PC-{0}</displayFormat>
        <label>Permission Control Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Permission Controls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Permission_Control__c/fields/pse__Region__c.field-meta.xml
<CustomField>
    <fullName>pse__Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Region containing Resources that are the target of the specified action(s) - e.g. delegated Timecard Entry on behalf of Resources in this Region.</description>
    <inlineHelpText>This is the Region containing Resources that are the target of the specified action(s) - e.g. delegated Timecard Entry on behalf of Resources in this Region.</inlineHelpText>
    <label>Region</label>
    <referenceTo>pse__Region__c</referenceTo>
    <relationshipLabel>Permission Controls</relationshipLabel>
    <relationshipName>Permission_Controls</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Permission_Control__c/fields/pse__Staffing__c.field-meta.xml
<CustomField>
    <fullName>pse__Staffing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This checkbox governs the User&apos;s ability to staff Resources from specified Regions/Practices/Groups.</description>
    <inlineHelpText>This checkbox governs the User&apos;s ability to staff Resources from specified Regions/Practices/Groups.</inlineHelpText>
    <label>Staffing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/pse__Permission_Control__c/fields/pse__User__c.field-meta.xml
<CustomField>
    <fullName>pse__User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Permission_Controls</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/pse__Proj__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__ProjectHelp</customHelpPage>
    <description>Represents a collection of business transactions, activities, and related items to be managed over a defined time range, such as timecards, expenses, milestones, and budgets. Typically, people (represented by Resource records) are assigned to projects, though some projects do not require assignments in order to be staffed. Projects may also have a master project (parent) or a sub project (child) in the project hierarchy, supporting roll-ups of revenues, costs, and time to every project and up through the hierarchy.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Proj__c/fields/Forecast_Status__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Status__c</fullName>
    <description>Red/Yellow/Green status for forecasts based on risks &amp; issues</description>
    <label>Forecast Status</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Account__c.field-meta.xml
<CustomField>
    <fullName>pse__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Is_Active__c.field-meta.xml
<CustomField>
    <fullName>pse__Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Region__c.field-meta.xml
<CustomField>
    <fullName>pse__Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region</label>
    <referenceTo>pse__Region__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/Quality_Status__c.field-meta.xml
<CustomField>
    <fullName>Quality_Status__c</fullName>
    <description>Red/Yellow/Green status for overall quality based on Risks &amp; Issues records</description>
    <label>Quality Status</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/Risk_Level_Status__c.field-meta.xml
<CustomField>
    <fullName>Risk_Level_Status__c</fullName>
    <description>Red/Yellow/Green indicator for overall project risk level based on risks and issues</description>
    <label>Risk Level Status</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/Sponsor_Engaged_Status__c.field-meta.xml
<CustomField>
    <fullName>Sponsor_Engaged_Status__c</fullName>
    <description>Red/Yellow/Green status for sponsor engaged</description>
    <label>Sponsor Engaged Status</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Risks_Issues__c/Risks_Issues__c.object-meta.xml
<CustomObject>
    <description>This Object is being used to track Risks &amp; Issues on Projects. This object is not linked to PSA.</description>
    <label>Risk &amp; Issue</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Risks &amp; Issues Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Risks &amp; Issues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Risks_Issues__c/fields/Impact__c.field-meta.xml
<CustomField>
    <fullName>Impact__c</fullName>
    <description>This field is used to determine the impact of the Risk or Issue on the project.</description>
    <inlineHelpText>When choosing an option, please take into account the following areas: Cost, Schedule, Scope &amp; Quality.</inlineHelpText>
    <label>Impact</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Risks_Issues__c/fields/Probability__c.field-meta.xml
<CustomField>
    <fullName>Probability__c</fullName>
    <description>High Probability - 80 -&gt; 100%
Medium-High Probability - 60 -&gt; 80%
Medium-Low Probability - 30 -&gt; 60%
Low Probability - 0 -&gt; 30%</description>
    <inlineHelpText>High Probability - 80 -&gt; 100%
Medium-High Probability - 60 -&gt; 80%
Medium-Low Probability - 30 -&gt; 60%
Low Probability - 0 -&gt; 30%</inlineHelpText>
    <label>Probability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium-High</fullName>
                <isActive>false</isActive>
                <label>Medium-High</label>
            </value>
            <value>
                <fullName>Medium-Low</fullName>
                <isActive>false</isActive>
                <label>Medium-Low</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Risks_Issues__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Risk_Issue_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Risks_Issues__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>This field outlines the Types of Risks &amp; Issues you may choose from.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Risk_Issue_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Risks_Issues__c/recordTypes/Risk.recordType-meta.xml
<RecordType>
    <fullName>Risk</fullName>
    <active>true</active>
    <description>This Record Type is used to track Risks for a project</description>
    <label>Risk</label>
</RecordType>

force-app/main/default/globalValueSets/Industry_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Business Services</fullName>
    </customValue>
    <customValue>
        <fullName>Communications/Media</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer Goods</fullName>
    </customValue>
    <customValue>
        <fullName>Financial Services</fullName>
        <label>Financial  Services</label>
    </customValue>
    <customValue>
        <fullName>Government</fullName>
    </customValue>
    <customValue>
        <fullName>Healthcare</fullName>
    </customValue>
    <customValue>
        <fullName>Higher Education</fullName>
    </customValue>
    <customValue>
        <fullName>High Tech/Software</fullName>
    </customValue>
    <customValue>
        <fullName>Leisure &amp; Hospitality</fullName>
    </customValue>
    <customValue>
        <fullName>Manufacturing &amp; Automotive</fullName>
    </customValue>
    <customValue>
        <fullName>Nonprofit</fullName>
    </customValue>
    <customValue>
        <fullName>Retail</fullName>
    </customValue>
    <customValue>
        <fullName>Transportation</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Legacy</fullName>
        <isActive>false</isActive>
        <label>Legacy</label>
    </customValue>
    <description>Industry type values</description>
    <masterLabel>Industry Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Risk_Issue_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Mitigated</fullName>
    </customValue>
    <customValue>
        <fullName>Eradicated</fullName>
    </customValue>
    <description>Valid Risk &amp; Issue Status</description>
    <masterLabel>Risk &amp; Issue Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Risk_Issue_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Scope</fullName>
    </customValue>
    <customValue>
        <fullName>Resource</fullName>
    </customValue>
    <customValue>
        <fullName>Quality</fullName>
    </customValue>
    <customValue>
        <fullName>DevOps</fullName>
    </customValue>
    <customValue>
        <fullName>Timeline</fullName>
    </customValue>
    <customValue>
        <fullName>Budget</fullName>
    </customValue>
    <customValue>
        <fullName>Client-Specific</fullName>
        <isActive>false</isActive>
        <label>Client-Specific</label>
    </customValue>
    <customValue>
        <fullName>Exec Sponsor</fullName>
        <isActive>false</isActive>
        <label>Exec Sponsor</label>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
        <isActive>false</isActive>
        <label>Other</label>
    </customValue>
    <customValue>
        <fullName>Contracting (SOW, EWB)</fullName>
        <isActive>false</isActive>
        <label>Contracting (SOW, EWB)</label>
    </customValue>
    <customValue>
        <fullName>Schedule</fullName>
        <isActive>false</isActive>
        <label>Schedule</label>
    </customValue>
    <customValue>
        <fullName>Forecast</fullName>
        <isActive>false</isActive>
        <label>Forecast</label>
    </customValue>
    <customValue>
        <fullName>Executive Steering</fullName>
        <isActive>false</isActive>
        <label>Executive Steering</label>
    </customValue>
    <customValue>
        <fullName>Coverage</fullName>
        <isActive>false</isActive>
        <label>Coverage</label>
    </customValue>
    <description>Valid risk &amp; Issue types</description>
    <masterLabel>Risk &amp; Issue Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RiskAndIssuesStatusHandler_Test.cls
@IsTest(SeeAllData=false)
public class RiskAndIssuesStatusHandler_Test {
    private static Account svnAccount;
    private static Contact contact;
    private static Account custAccount;
    private static pse__Proj__c project;
    private static List<Risks_Issues__c> risks;
    
    @isTest static void testHandler() { 
        setup();

        Test.startTest();
        RiskAndIssuesStatusHandler.setProjectRecordStatus(risks);
  
        pse__Proj__c updatedProject = [SELECT Id, Sponsor_Engaged_Status__c, Risk_Level_Status__c, Forecast_Status__c, Quality_Status__c FROM pse__Proj__c WHERE Id =: project.Id];

        Test.stopTest();

    }

    @isTest static void testHighImpact() { 
        setup();

        Test.startTest();
        risks[0].Impact__c='High';
        risks[0].Probability__c='High';
        risks[0].Status__c='Draft';
        risks[1].Impact__c='High';
        risks[1].Probability__c='Medium';
        risks[1].Status__c='Draft';
        risks[2].Impact__c='High';
        risks[2].Probability__c='Low';
        risks[2].Status__c='Draft';
        risks[3].Impact__c='High';
        risks[3].Probability__c='High';
        risks[3].Status__c='Mitigated';
        risks[4].Impact__c='High';
        risks[4].Probability__c='Medium';
        risks[4].Status__c='Mitigated';
        risks[5].Impact__c='High';
        risks[5].Probability__c='High';
        risks[5].Status__c='Eradicated';
        risks[6].Impact__c='High';
        risks[6].Probability__c='Medium';
        risks[6].Status__c='Eradicated';
        risks[7].Impact__c='High';
        risks[7].Probability__c='Low';
        risks[7].Status__c='Eradicated';
        update risks;
        Test.stopTest();

    }
    
    @isTest static void testMediumImpact() { 
        setup();

        Test.startTest();
        risks[0].Impact__c='Medium';
        risks[0].Probability__c='High';
        risks[0].Status__c='Draft';
        risks[1].Impact__c='Medium';
        risks[1].Probability__c='Medium';
        risks[1].Status__c='Draft';
        risks[2].Impact__c='Medium';
        risks[2].Probability__c='Low';
        risks[2].Status__c='Draft';
        risks[3].Impact__c='Medium';
        risks[3].Probability__c='High';
        risks[3].Status__c='Mitigated';
        risks[4].Impact__c='Medium';
        risks[4].Probability__c='Medium';
        risks[4].Status__c='Mitigated';
        risks[5].Impact__c='Medium';
        risks[5].Probability__c='High';
        risks[5].Status__c='Eradicated';
        risks[6].Impact__c='Medium';
        risks[6].Probability__c='Medium';
        risks[6].Status__c='Eradicated';
        risks[7].Impact__c='Medium';
        risks[7].Probability__c='Low';
        risks[7].Status__c='Eradicated';
        update risks;

        Test.stopTest();

    }
    
    public static void setup() {
        pse__Region__c region = new pse__Region__c(Name='Test Region');
        insert region;
        
        pse__Permission_Control__c permissionControl = new pse__Permission_Control__c(pse__User__c=UserINfo.getUserId(), pse__Region__c=region.Id, pse__Staffing__c=true);
        insert permissionControl;
        
        RecordType contactRT = [SELECT ID FROM RecordType WHERE SObjectType='Contact' AND Name='PSA Resource'];
        
        svnAccount = new Account(Name='7Summits', Industry_Type__c='Business Services', Record_Type__c='Vintage - Salesforce');
        custAccount = new Account(Name='Customer Account', Industry_Type__c='Business Services', Record_Type__c='Vintage - Salesforce');
        
        insert svnAccount;
        insert custAccount;
        
        contact=new Contact(FirstName='OpsPM', LastName='Contact', AccountId=svnAccount.Id, pse__Region__c=region.Id, RecordTypeId=contactRT.Id, Competency_Group__c='Delivery Operations', Coverage_Participant__c=false, Active__c=true, pse__Is_Resource__c=true, pse__Is_Resource_Active__c=true, Resource_Type__c='Internal', pse__Resource_Role__c='PM');
        insert contact;
        
        project = new pse__Proj__c(Name='Project 1', pse__Account__c=custAccount.Id, pse__Region__c=region.id, 
                                   pse__Is_Active__c=true, pse__Stage__c='Planned', pse__Is_Billable__c=true, 
                                   pse__Allow_Self_Staffing__c=true, Ops_Staffing_Stage__c='Not Staffed', 
                                   pse__Start_Date__c=System.today(), pse__End_Date__c=System.today().addDays(30),
                                   Sponsor_Engaged_Status__c='', Risk_Level_Status__c='');
        
        insert project;
        
        risks=new List<Risks_Issues__c>();
        RecordType riskRt = [SELECT Id FROM RecordType WHERE SObjectType='Risks_Issues__c' AND Name='Risk'];
        
        risks.add(new Risks_Issues__c(Project__c=project.Id, Type__c='Resource', Impact__c='Low', 
                                      Owner__c=contact.Id, Date_Raised__c=System.today(), RecordTypeId=riskRT.Id,
                                      Expected_Close_Date__c=System.today().addDays(30),
                                      Name__c='Risk 0', Description__c='Description 1'));
        risks.add(new Risks_Issues__c(Project__c=project.Id, Type__c='Resource', Impact__c='Low', 
                                      Owner__c=contact.Id, Date_Raised__c=System.today(), RecordTypeId=riskRT.Id,
                                      Expected_Close_Date__c=System.today().addDays(30), 
                                      Mitigation_Steps__c='These are the steps', Status__c='In Progress',
                                      Name__c='Risk 1', Description__c='Description 2'));
        risks.add(new Risks_Issues__c(Project__c=project.Id, Type__c='Budget', Impact__c='High', Probability__c='Medium',
                                      Owner__c=contact.Id, Date_Raised__c=System.today(), RecordTypeId=riskRT.Id, 
                                      Expected_Close_Date__c=System.today().addDays(30), Status__c='Draft',
                                      Name__c='Risk 2', Description__c='Description 1'));
        risks.add(new Risks_Issues__c(Project__c=project.Id, Type__c='DevOps', Impact__c='Low', Probability__c='Medium',
                                      Owner__c=contact.Id, Date_Raised__c=System.today(), RecordTypeId=riskRT.Id, 
                                      Expected_Close_Date__c=System.today().addDays(30), Status__c='Mitigated',
                                      Name__c='Risk 3', Description__c='Description 1'));
        risks.add(new Risks_Issues__c(Project__c=project.Id, Type__c='Scope', Impact__c='Medium', Probability__c='Low',
                                      Owner__c=contact.Id, Date_Raised__c=System.today(), RecordTypeId=riskRT.Id, 
                                      Expected_Close_Date__c=System.today().addDays(30),
                                      Name__c='Risk 4', Description__c='Description 1'));
        risks.add(new Risks_Issues__c(Project__c=project.Id, Type__c='DevOps', Impact__c='Low', Probability__c='Medium',
                                      Owner__c=contact.Id, Date_Raised__c=System.today(), RecordTypeId=riskRT.Id, 
                                      Expected_Close_Date__c=System.today().addDays(30), Status__c='Mitigated',
                                      Name__c='Risk 5', Description__c='Description 1'));
        risks.add(new Risks_Issues__c(Project__c=project.Id, Type__c='Scope', Impact__c='Medium', Probability__c='Low',
                                      Owner__c=contact.Id, Date_Raised__c=System.today(), RecordTypeId=riskRT.Id, 
                                      Expected_Close_Date__c=System.today().addDays(30),
                                      Name__c='Risk 6', Description__c='Description 1'));
        risks.add(new Risks_Issues__c(Project__c=project.Id, Type__c='Scope', Impact__c='Medium', Probability__c='Low',
                                      Owner__c=contact.Id, Date_Raised__c=System.today(), RecordTypeId=riskRT.Id, 
                                      Expected_Close_Date__c=System.today().addDays(30),
                                      Name__c='Risk 7', Description__c='Description 1'));
        insert risks;
        
    }
}