force-app/main/default/objects/Account/fields/Industry_Type__c.field-meta.xml
<CustomField>
    <fullName>Industry_Type__c</fullName>
    <description>The industry associated with the company.</description>
    <inlineHelpText>The industry associated with the company.</inlineHelpText>
    <label>Industry Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Industry_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <description>The source the lead originated from.</description>
    <inlineHelpText>The source the lead originated from.</inlineHelpText>
    <label>Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lead_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Industry_Type__c.field-meta.xml
<CustomField>
    <fullName>Industry_Type__c</fullName>
    <label>Industry Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Industry_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <label>Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lead_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <description>The source the lead originated.</description>
    <inlineHelpText>The source the lead originated.</inlineHelpText>
    <label>Lead Source (7S)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lead_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Industry_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Business Services</fullName>
    </customValue>
    <customValue>
        <fullName>Communications/Media</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer Goods</fullName>
    </customValue>
    <customValue>
        <fullName>Financial Services</fullName>
        <label>Financial  Services</label>
    </customValue>
    <customValue>
        <fullName>Government</fullName>
    </customValue>
    <customValue>
        <fullName>Healthcare</fullName>
    </customValue>
    <customValue>
        <fullName>Higher Education</fullName>
    </customValue>
    <customValue>
        <fullName>High Tech/Software</fullName>
    </customValue>
    <customValue>
        <fullName>Leisure &amp; Hospitality</fullName>
    </customValue>
    <customValue>
        <fullName>Manufacturing &amp; Automotive</fullName>
    </customValue>
    <customValue>
        <fullName>Nonprofit</fullName>
    </customValue>
    <customValue>
        <fullName>Retail</fullName>
    </customValue>
    <customValue>
        <fullName>Transportation</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Legacy</fullName>
        <isActive>false</isActive>
        <label>Legacy</label>
    </customValue>
    <description>Industry type values</description>
    <masterLabel>Industry Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lead_Source.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AppExchange</fullName>
    </customValue>
    <customValue>
        <fullName>Digital Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Direct Inbound</fullName>
    </customValue>
    <customValue>
        <fullName>Hosted Event</fullName>
    </customValue>
    <customValue>
        <fullName>Sponsored Event</fullName>
    </customValue>
    <customValue>
        <fullName>Website Conversion</fullName>
    </customValue>
    <customValue>
        <fullName>Channel Inbound</fullName>
    </customValue>
    <customValue>
        <fullName>Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Sales Prospecting</fullName>
    </customValue>
    <customValue>
        <fullName>Zoominfo</fullName>
    </customValue>
    <customValue>
        <fullName>Legacy</fullName>
        <isActive>false</isActive>
        <label>Legacy</label>
    </customValue>
    <description>Lead source values</description>
    <masterLabel>Lead Source</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CreateContactRoleTest.cls
@isTest
public class CreateContactRoleTest {
   
    public static testmethod void testSingleOpportunity(){
    	//create data 
    	Account newAccount = new Account();
        newAccount.Industry_Type__c='Retail';
        newAccount.Name = 'Test Account';
        insert newAccount;
        
        Contact testContact = new Contact();
        testContact.AccountId=newAccount.Id;
        testContact.FirstName = 'Bob';
        testContact.LastName = 'LastName';
        testContact.Industry_Type__c = 'Government';
        testContact.Lead_Source__c = 'Sales Prospecting';
        insert testContact;
        
        Campaign campaign = new Campaign(Name='Test Campaign');
        insert campaign;
        
    	//do whatever you need to test
    	Test.startTest();
        Opportunity newOpportunity = new Opportunity();
        newOpportunity.Lead_Source__c='Sales Prospecting';
        newOpportunity.Name ='New Opp';
        newOpportunity.StageName = '1 Prospect';
        newOpportunity.CloseDate = System.today() +1;
        insert newOpportunity;
        
        Test.stopTest();
        
        //check results
    }
}