force-app/main/default/objects/Account/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <description>The source the lead originated from.</description>
    <inlineHelpText>The source the lead originated from.</inlineHelpText>
    <label>Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lead_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Active_Upload__c.field-meta.xml
<CustomField>
    <fullName>Active_Upload__c</fullName>
    <label>Active Upload</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Badges_Upload__c.field-meta.xml
<CustomField>
    <fullName>Badges_Upload__c</fullName>
    <label>Badges Upload</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <label>Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lead_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Points_Check_In__c.field-meta.xml
<CustomField>
    <fullName>Points_Check_In__c</fullName>
    <label>Points Check In</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Retired_Upload__c.field-meta.xml
<CustomField>
    <fullName>Retired_Upload__c</fullName>
    <label>Retired Upload</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Total_Points__c.field-meta.xml
<CustomField>
    <fullName>Total_Points__c</fullName>
    <label>Total Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Trails__c.field-meta.xml
<CustomField>
    <fullName>Trails__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText># of Trails completed.</inlineHelpText>
    <label>Trails</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Trailhead_Leaderboard_Settings__c/Trailhead_Leaderboard_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Trailhead Leaderboard Settings</label>
</CustomObject>

force-app/main/default/objects/Trailhead_Leaderboard_Settings__c/fields/Finish_Message__c.field-meta.xml
<CustomField>
    <fullName>Finish_Message__c</fullName>
    <defaultValue>&apos;Time!&apos;</defaultValue>
    <label>Finish Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trailhead_Leaderboard_Settings__c/fields/Header_Message__c.field-meta.xml
<CustomField>
    <fullName>Header_Message__c</fullName>
    <defaultValue>&apos;Countdown to earn Trailhead Points!&apos;</defaultValue>
    <label>Header Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trailhead_Leaderboard_Settings__c/fields/Target_Time__c.field-meta.xml
<CustomField>
    <fullName>Target_Time__c</fullName>
    <description>The needs to be in format like: 07/25/2015 1:00 PM UTC-0400</description>
    <inlineHelpText>The needs to be in format like: 07/25/2015 1:00 PM UTC-0400</inlineHelpText>
    <label>Target Time</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Lead_Source.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AppExchange</fullName>
    </customValue>
    <customValue>
        <fullName>Digital Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Direct Inbound</fullName>
    </customValue>
    <customValue>
        <fullName>Hosted Event</fullName>
    </customValue>
    <customValue>
        <fullName>Sponsored Event</fullName>
    </customValue>
    <customValue>
        <fullName>Website Conversion</fullName>
    </customValue>
    <customValue>
        <fullName>Channel Inbound</fullName>
    </customValue>
    <customValue>
        <fullName>Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Sales Prospecting</fullName>
    </customValue>
    <customValue>
        <fullName>Zoominfo</fullName>
    </customValue>
    <customValue>
        <fullName>Legacy</fullName>
        <isActive>false</isActive>
        <label>Legacy</label>
    </customValue>
    <description>Lead source values</description>
    <masterLabel>Lead Source</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TrailheadLeaderBoardController_Test.cls
@istest
global with sharing class TrailheadLeaderBoardController_Test{

    @testsetup static void testdata(){
    
        Account a = new Account(Name='Test', Lead_Source__c='Referral');
        insert a;
        
        Contact c = new contact();
        c.LastName = 'test';
        c.Trails__c = 0;
        c.Total_Points__c = 1000;
        c.Active_Upload__c = 200;
        c.Points_check_in__c = 500;
        c.Active__c = true;
        c.AccountId=a.id;
        insert c;
        
        // No active upload
        Contact c2 = new contact();
        c2.LastName = 'test';
        c2.Total_Points__c = 1000;
        c2.Points_check_in__c = 500;
        c2.Badges_Upload__c = 1;
        c2.Retired_Upload__c = 1;
        c2.Trails__c = 0;
        c2.Active__c = true;
        c2.AccountId=a.id;
        insert c2;
        
        Trailhead_Leaderboard_Settings__c ts = new Trailhead_Leaderboard_Settings__c();
        ts.name = 'test';
        ts.Finish_Message__c = 'test';
        ts.Header_Message__c = 'test';
        ts.Target_time__c = '07/26/2015 1:00 PM UTC-0630';
        insert ts;  
    }
    
    @istest static void testController(){
    
        PageReference pageRef = Page.trailheadLeaderboard;
        Test.setCurrentPage(pageRef);

        trailheadLeaderboardController tl = new trailheadleaderboardcontroller();   
    }
}