force-app/main/default/objects/Account/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <description>The source the lead originated from.</description>
    <inlineHelpText>The source the lead originated from.</inlineHelpText>
    <label>Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lead_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/App_Settings__c/App_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>App Settings</label>
</CustomObject>

force-app/main/default/objects/App_Settings__c/fields/Run_Opportunity_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Run_Opportunity_Trigger__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Run Opportunity Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <label>Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lead_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <description>The source the lead originated.</description>
    <inlineHelpText>The source the lead originated.</inlineHelpText>
    <label>Lead Source (7S)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lead_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Link_to_Final_Executed_SOW_PDF__c.field-meta.xml
<CustomField>
    <fullName>Link_to_Final_Executed_SOW_PDF__c</fullName>
    <inlineHelpText>If LOI, please provide the google document to the executed document here. If the client only provides a PO upon signature, please provide a link to google document  here.</inlineHelpText>
    <label>Link to Final Executed SOW (PDF)</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Project_Start_Date__c</fullName>
    <description>Starting date of services or solution project, if known.  Start date is not needed for Software deals</description>
    <inlineHelpText>If known.  Start date not need for Software</inlineHelpText>
    <label>Project Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Solution_Primary_Audience__c.field-meta.xml
<CustomField>
    <fullName>Solution_Primary_Audience__c</fullName>
    <inlineHelpText>Choose the option that reflects the primary audience for this Opportunity</inlineHelpText>
    <label>Solution Primary Audience</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Solution_Offering__c/Solution_Offering__c.object-meta.xml
<CustomObject>
    <label>Solution Offering</label>
    <nameField>
        <label>Solution Offering Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solution Offerings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Solution_Offering__c/fields/Contact_Role__c.field-meta.xml
<CustomField>
    <fullName>Contact_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Role</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Solution Offerings</relationshipLabel>
    <relationshipName>Solution_Offerings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Solution_Offering__c/fields/N_A__c.field-meta.xml
<CustomField>
    <fullName>N_A__c</fullName>
    <defaultValue>false</defaultValue>
    <label>N/A</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Solution_Offering__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Solution Offerings</relationshipLabel>
    <relationshipName>Solution_Offerings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Solution_Offering__c/fields/Sold__c.field-meta.xml
<CustomField>
    <fullName>Sold__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sold</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Solution_Offerring_Names__c/Solution_Offerring_Names__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Solution Offerring Names</label>
</CustomObject>

force-app/main/default/objects/Solution_Offerring_Names__c/fields/Use__c.field-meta.xml
<CustomField>
    <fullName>Use__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Use</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Lead_Source.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AppExchange</fullName>
    </customValue>
    <customValue>
        <fullName>Digital Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Direct Inbound</fullName>
    </customValue>
    <customValue>
        <fullName>Hosted Event</fullName>
    </customValue>
    <customValue>
        <fullName>Sponsored Event</fullName>
    </customValue>
    <customValue>
        <fullName>Website Conversion</fullName>
    </customValue>
    <customValue>
        <fullName>Channel Inbound</fullName>
    </customValue>
    <customValue>
        <fullName>Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Sales Prospecting</fullName>
    </customValue>
    <customValue>
        <fullName>Zoominfo</fullName>
    </customValue>
    <customValue>
        <fullName>Legacy</fullName>
        <isActive>false</isActive>
        <label>Legacy</label>
    </customValue>
    <description>Lead source values</description>
    <masterLabel>Lead Source</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OpportunityTriggerUtilTest.cls
@isTest
private class OpportunityTriggerUtilTest {
	@isTest static void testOpportunityUpdate() {
		App_Settings__c appSettings = new App_Settings__c();
		appSettings.Run_Opportunity_Trigger__c = true;
		insert appSettings;

		Account newAccount = new Account();
		newAccount.Name = 'Test Account';
		insert newAccount;

		Contact newContact = new Contact();
		newContact.FirstName = 'Test';
		newContact.LastName = 'Contact';
		newContact.AccountId = newAccount.Id;
		insert newContact;

		Solution_Offering__c newSolution = new Solution_Offering__c();
		newSolution.Name = 'Jive 7 Upgrade';
		newSolution.Contact_Role__c = newContact.Id;
		newSolution.Appointment_Date__c = Date.today();
		newSolution.Sold__c = false;
		newSolution.N_A__c = false;
		insert newSolution;

		Opportunity newOppty = new Opportunity();
		newOppty.Name = 'New Opportunity';
		newOppty.StageName = 'Identified';
        newOppty.Lead_Source__c='Sales Prospecting';
		newOppty.CloseDate = Date.today().addDays(60);
		newOppty.Project_Start_Date__c = Date.today();
		insert newOppty;

		newSolution.Opportunity__c = newOppty.Id;
		update newSolution;

		newOppty.StageName = 'Closed Won';
        newOppty.Description = 'Test Description';
        newOppty.Link_to_Final_Executed_SOW_PDF__c='https://google.com';
        newOppty.Solution_Primary_Audience__c='Customer';
		update newOppty;
	}

	@isTest static void testCreateSolutionOffering() {
		List<Solution_Offerring_Names__c> solutionRecords = new List<Solution_Offerring_Names__c>();
		solutionRecords.add(new Solution_Offerring_Names__c(Name = 'Jive 7 Upgrade', Use__c = true));
		solutionRecords.add(new Solution_Offerring_Names__c(Name = 'Social Marketing & Outreach', Use__c = true));
		solutionRecords.add(new Solution_Offerring_Names__c(Name = 'Box Resell', Use__c = true));
		solutionRecords.add(new Solution_Offerring_Names__c(Name = 'SFDC Community Workshop', Use__c = true));
		insert solutionRecords;

		Account newAccount = new Account();
		newAccount.Name = 'Test Account';
		insert newAccount;
		OpportunityTriggerUtil.createSolutionOfferingRecords();
	}
}