force-app/main/default/objects/X7S_Ideas_Subscription__c/X7S_Ideas_Subscription__c.object-meta.xml
<CustomObject>
    <description>A custom object to mimic the behavior of EntitySubscription, allowing users to follow Ideas and receive e-mail notifications.</description>
    <label>7S Idea Subscription</label>
    <nameField>
        <displayFormat>IS-{0000}</displayFormat>
        <label>7S Idea Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>7S Idea Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/X7S_Ideas_Subscription__c/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Ideas Subscriptions</description>
    <label>ParentId</label>
    <referenceTo>Idea</referenceTo>
    <relationshipName>X7S_Ideas_Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/X7S_Ideas_Subscription__c/fields/SubscriberId__c.field-meta.xml
<CustomField>
    <fullName>SubscriberId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SubscriberId</label>
    <referenceTo>User</referenceTo>
    <relationshipName>X7S_Ideas_Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/x7sIdeasSubscription.cls
/*
 * Copyright (c) 2020. 7Summits Inc.
 */

public with sharing class x7sIdeasSubscription {
	public static Boolean ideaSubscribe(String userId, String ideaId) {
		Boolean subscribed = false;

		if (String.isNotBlank(ideaId)) {
			List<X7S_Ideas_Subscription__c> ideaSubscriptions = getSubscription(userId, ideaId);

			if (ideaSubscriptions.size() == 0) {
				X7S_Ideas_Subscription__c newIdeaSubscription = new X7S_Ideas_Subscription__c(
					SubscriberId__c = userId,
					ParentId__c = ideaId);
				try {
					if (X7S_Ideas_Subscription__c.SObjectType.getDescribe().isCreateable()) {
						insert newIdeaSubscription;
						subscribed = true;
					}
				}
				catch (DmlException e) {
					System.debug('Failed to insert Idea subscription record: ' + e.getMessage());
				}
			}
		}

		return subscribed;
	}

	public static Boolean ideaUnSubscribe(String userId, String ideaId) {
		Boolean unSubscribed = false;

		if (String.isNotBlank(ideaId) &&
			X7S_Ideas_Subscription__c.SObjectType.getDescribe().isDeletable()) {
			List<X7S_Ideas_Subscription__c> ideaSubscriptions = getSubscription(userId, ideaId);

			if (ideaSubscriptions.size() > 0) {
				try {
					delete ideaSubscriptions;
					unSubscribed = true;
				}
				catch (DmlException e) {
					System.debug('Failed to remove Idea subscription record: ' + e.getMessage());
				}
			}
		}

		return unSubscribed;
	}

	public static Boolean ideaIsSubscribed(String userId, String ideaId) {
		Boolean isFollowing = false;

		if (String.isNotBlank(ideaId)) {
			List<X7S_Ideas_Subscription__c> ideaSubscriptions = getSubscription(userId, ideaId);

			if (ideaSubscriptions.size() > 0) {
				isFollowing = true;
			}
		}

		return isFollowing;
	}

	@TestVisible
	private static List<X7S_Ideas_Subscription__c> getSubscription(String userId, String ideaId) {
		String query = 'SELECT Id' +
			' FROM X7S_Ideas_Subscription__c ' +
			' WHERE ' +
			' SubscriberId__c = ' + '\'' + String.escapeSingleQuotes(userId) + '\'' +
			' AND ParentId__c = ' + '\'' + String.escapeSingleQuotes(ideaId) + '\'' +
			' LIMIT 1';

		// PMD : False positive, All variables are checked
		List<X7S_Ideas_Subscription__c> ideaSubscriptions = (List<X7S_Ideas_Subscription__c>) Database.query(query); //NOPMD

		return ideaSubscriptions;
	}
}