force-app/main/default/objects/pse__Milestone__c/pse__Milestone__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__MilestoneHelp</customHelpPage>
    <description>A target event used to track project progress. In Time and Materials (T&amp;M) projects, individual milestone records are generally not billable, whereas in Fixed Price or mixed projects all or some generally are. You can group together timecards and expenses, submitted by assigned resources, with milestones on the same project, or associate milestones with a fixed external cost. Milestones have a linear (non-hierarchical) relationship with one another.</description>
    <label>Milestone</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Milestone__c/fields/pse__Milestone_Amount__c.field-meta.xml
<CustomField>
    <fullName>pse__Milestone_Amount__c</fullName>
    <defaultValue>0.00</defaultValue>
    <description>Billable Amount associated with the Milestone itself (not including billable amounts from child Timecards/Expenses).  This is primarily intended to be used for fixed-fee Projects. Defaults to and must always be same currency as Project.</description>
    <inlineHelpText>Billable Amount associated with the Milestone itself (not including billable amounts from child Timecards/Expenses).  This is primarily intended to be used for fixed-fee Projects. Defaults to and must always be same currency as Project.</inlineHelpText>
    <label>Milestone Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/pse__Milestone__c/fields/pse__Project__c.field-meta.xml
<CustomField>
    <fullName>pse__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>pse__Proj__c</referenceTo>
    <relationshipLabel>Milestones</relationshipLabel>
    <relationshipName>Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Milestone__c/fields/pse__Target_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__Target_Date__c</fullName>
    <label>Target Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/pse__Proj__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__ProjectHelp</customHelpPage>
    <description>Represents a collection of business transactions, activities, and related items to be managed over a defined time range, such as timecards, expenses, milestones, and budgets. Typically, people (represented by Resource records) are assigned to projects, though some projects do not require assignments in order to be staffed. Projects may also have a master project (parent) or a sub project (child) in the project hierarchy, supporting roll-ups of revenues, costs, and time to every project and up through the hierarchy.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Proj__c/fields/ACTIVE_Baseline_Budget_CS__c.field-meta.xml
<CustomField>
    <fullName>ACTIVE_Baseline_Budget_CS__c</fullName>
    <label>ACTIVE_Baseline Budget CS ($)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/ACTIVE_JTD_Billable_CS__c.field-meta.xml
<CustomField>
    <fullName>ACTIVE_JTD_Billable_CS__c</fullName>
    <label>ACTIVE_JTD Billable CS ($)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/CLOSED_Baseline_Budget_CS__c.field-meta.xml
<CustomField>
    <fullName>CLOSED_Baseline_Budget_CS__c</fullName>
    <label>CLOSED_Baseline Budget CS ($)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/CLOSED_JTD_Billable_CS__c.field-meta.xml
<CustomField>
    <fullName>CLOSED_JTD_Billable_CS__c</fullName>
    <label>CLOSED_JTD Billable CS ($)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/ETC_Billable_CS__c.field-meta.xml
<CustomField>
    <fullName>ETC_Billable_CS__c</fullName>
    <label>ETC Billable CS ($)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/Opp_Project_Type__c.field-meta.xml
<CustomField>
    <fullName>Opp_Project_Type__c</fullName>
    <formula>TEXT(pse__Opportunity__r.Project_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opp Project Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Stage__c.field-meta.xml
<CustomField>
    <fullName>pse__Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Prepare</fullName>
            </value>
            <value>
                <fullName>Define</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Build</fullName>
            </value>
            <value>
                <fullName>Verify</fullName>
            </value>
            <value>
                <fullName>Launch</fullName>
            </value>
            <value>
                <fullName>Close-Out</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MilestoneRollupHelper.cls
public class MilestoneRollupHelper {
    public static boolean isRunning=false;
    public static void calculate(Set<Id> projectIds) {
        System.debug('******** EXECUTING MilestoneRollupHelper ********');
        List<pse__Proj__c> projects = [SELECT Id, Name, pse__Stage__c, (SELECT pse__Milestone_Amount__c, pse__target_date__c FROM pse__Milestones__r)
                                       FROM pse__Proj__c WHERE Id IN : projectIds AND opp_project_type__c = 'Customer Success' ];
        
        List<pse__Proj__c> updatedProjects = new List<pse__Proj__c>();
        for(pse__Proj__c project : projects) {
            Decimal closedBaselineBudget = 0.0;
            Decimal closedJTDBillable = 0.0;
            Decimal activeBaselineBudget = 0.0;
            Decimal	activeJTDBillable = 0.0;
            Decimal etcBillable = 0.0;
            for(pse__Milestone__c milestone : project.pse__Milestones__r) {
                
                if(milestone.pse__Target_Date__c<System.today()) {
                    switch on project.pse__Stage__c {
                        when 'Completed', 'Cancelled' {
                            try { closedBaselineBudget += milestone.pse__Milestone_Amount__c; } catch (Exception e) {}
                            try { closedJTDBillable += milestone.pse__Milestone_Amount__c; } catch (Exception e) {}
                        } when 'Planned' , 'Prepare' , 'Define' , 'Design' , 'Build' , 'Verify' , 'Launch' , 'Close-Out' {
                            try { activeJTDBillable += milestone.pse__Milestone_Amount__c; } catch (Exception e) {}
                        }
                    }
                }
                
                try { activeBaselineBudget += milestone.pse__Milestone_Amount__c; } catch (Exception e) {}
                if(milestone.pse__Target_Date__c>=System.today()) {
                    try { etcBillable += milestone.pse__Milestone_Amount__c; } catch (Exception e) {}
                }
                
            }
            switch on project.pse__Stage__c {
                when 'Completed', 'Cancelled' {
                    updatedProjects.add(new pse__Proj__c(Id=project.Id, CLOSED_Baseline_Budget_CS__c=closedBaselineBudget,
                                                         CLOSED_JTD_Billable_CS__c=closedJTDBillable, ETC_Billable_CS__c=etcBillable));
                } when 'Planned' , 'Prepare' , 'Define' , 'Design' , 'Build' , 'Verify' , 'Launch' , 'Close-Out' {
                    updatedProjects.add(new pse__Proj__c(Id=project.Id, ACTIVE_Baseline_Budget_CS__c=activeBaselineBudget,
                                                         ACTIVE_JTD_Billable_CS__c=activeJTDBillable, ETC_Billable_CS__c=etcBillable));
                }
            }
        }
        
        if(!updatedProjects.isEmpty()) { 
            List<Database.SaveResult> sr = Database.update(updatedProjects);
        }
        System.debug('******** EXITING MilestoneRollupHelper ********');
    }
}