force-app/main/default/objects/copado__Project__c/copado__Project__c.object-meta.xml
<CustomObject>
    <description>Overall object for capturing the project details.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/copado__Project__c/fields/InternalJira__c.field-meta.xml
<CustomField>
    <fullName>InternalJira__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Use 7S Jira instance</description>
    <inlineHelpText>Use 7S Jira instance</inlineHelpText>
    <label>Use 7S Jira</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CopadoProjectTrigger_Test.cls
@isTest (SeeAllData=false)
public class CopadoProjectTrigger_Test {
    public static List<copado__Project__c> projects;
    
    @isTest static void testJiraProject() {
        setup();
        
        Test.startTest();        
        
        projects[0].InternalJira__c = true;
        projects[1].InternalJira__c = false;
        update projects;
        
        List<copadoccmint__Field_Mapping__c> m = [SELECT Id FROM copadoccmint__Field_Mapping__c];
        System.assertEquals(1, m.size());
        
        delete m;
        
        delete projects[0];
        test.stopTest();
    }
    
    @isTest static void setup() {
        projects = new List<copado__Project__c>();
        projects.add(new copado__Project__c(Name='Test-1'));
        projects.add(new copado__Project__c(Name='Test-2', InternalJira__c = true));
        insert projects;
    }
}