force-app/main/default/objects/copado__Project__c/copado__Project__c.object-meta.xml
<CustomObject>
    <description>Overall object for capturing the project details.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/copado__Project__c/fields/Schedule_End__c.field-meta.xml
<CustomField>
    <fullName>Schedule_End__c</fullName>
    <defaultValue>&apos;17&apos;</defaultValue>
    <description>Hour of the day that the scheduled job ends</description>
    <inlineHelpText>Hour of the day that the scheduled job ends</inlineHelpText>
    <label>Schedule End</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Schedule_Hours</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/copado__Project__c/fields/Schedule_Start__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Start__c</fullName>
    <defaultValue>&apos;08&apos;</defaultValue>
    <description>Hour of the day that the scheduled job starts</description>
    <inlineHelpText>Hour of the day that the scheduled job starts</inlineHelpText>
    <label>Schedule Start</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Schedule_Hours</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Schedule_Hours.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>00</fullName>
    </customValue>
    <customValue>
        <fullName>01</fullName>
    </customValue>
    <customValue>
        <fullName>02</fullName>
    </customValue>
    <customValue>
        <fullName>03</fullName>
    </customValue>
    <customValue>
        <fullName>04</fullName>
    </customValue>
    <customValue>
        <fullName>05</fullName>
    </customValue>
    <customValue>
        <fullName>06</fullName>
    </customValue>
    <customValue>
        <fullName>07</fullName>
    </customValue>
    <customValue>
        <fullName>08</fullName>
    </customValue>
    <customValue>
        <fullName>09</fullName>
    </customValue>
    <customValue>
        <fullName>10</fullName>
    </customValue>
    <customValue>
        <fullName>11</fullName>
    </customValue>
    <customValue>
        <fullName>12</fullName>
    </customValue>
    <customValue>
        <fullName>13</fullName>
    </customValue>
    <customValue>
        <fullName>14</fullName>
    </customValue>
    <customValue>
        <fullName>15</fullName>
    </customValue>
    <customValue>
        <fullName>16</fullName>
    </customValue>
    <customValue>
        <fullName>17</fullName>
    </customValue>
    <customValue>
        <fullName>18</fullName>
    </customValue>
    <customValue>
        <fullName>19</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>21</fullName>
    </customValue>
    <customValue>
        <fullName>22</fullName>
    </customValue>
    <customValue>
        <fullName>23</fullName>
    </customValue>
    <masterLabel>Schedule Hours</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/JiraInterationExtension.cls
public class JiraInterationExtension {
    
    public static Id projectId { get; set; }
    public static copado__Project__c project { get; set; }
    private static String jobPrefix = 'Copado project synch - ';
    
    public static void cancelCurrentJob() {
        setProject();
        System.debug('------ Cancelling current jobs -----');
        Set<Id> cronJobIds = new Set<Id>();
        List<CronJobDetail> cronJobs = [SELECT Id, Name FROM CronJobDetail WHERE Name =: jobPrefix + project.copadoccmint__Project_External_Id__c];
        System.debug('-------- cronjobs: ' + cronJobs);
        for(CronJobDetail cronJob : cronJobs) {
            cronJobIds.add(cronJob.Id);
        }
        
        if(!cronJobIds.isEmpty()) {
            List<CronTrigger> abort_job = [SELECT Id FROM CronTrigger WHERE CronJobDetailId IN : cronJobIds];
            
            for (CronTrigger t : abort_job) { 
                System.abortJob(t.Id); 
            }
        }
    }
    
    public static void scheduleJob() {
        cancelCurrentJob();
        Boolean withSprint = true; 
        String scheduledHours=''+project.Schedule_Start__c;
        if(project.Schedule_End__c>project.Schedule_Start__c) { scheduledHours += '-'+project.Schedule_End__c; }
        
        copadoccmint.ScheduleUserStoryFetch scheduledClass = new copadoccmint.ScheduleUserStoryFetch (projectId, withSprint);
        String scheduleJobId = system.schedule(jobPrefix + project.copadoccmint__Project_External_Id__c, '0 0 ' + scheduledHours + ' ? * MON-FRI', scheduledClass);
        System.debug('------- scheduleJobId: ' + scheduleJobId);
    }
    
    private static void setProject() {
        projectId = ApexPages.currentPage().getParameters().get('pid');
        project = [SELECT Id, copadoccmint__Project_External_Id__c, Name, Schedule_Start__c, Schedule_End__c FROM copado__Project__c WHERE Id =: projectId];
        System.debug('-------- project: ' + project);
    }
    
}