force-app/main/default/objects/copado__Project__c/copado__Project__c.object-meta.xml
<CustomObject>
    <description>Overall object for capturing the project details.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/copado__Project__c/fields/Opps_Staffing_Stage__c.field-meta.xml
<CustomField>
    <fullName>Opps_Staffing_Stage__c</fullName>
    <description>Operations Staffing Stage</description>
    <inlineHelpText>Operations Staffing Stage</inlineHelpText>
    <label>Ops Staffing Stage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/copado__Project__c/fields/PSAProject__c.field-meta.xml
<CustomField>
    <fullName>PSAProject__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Associated project in PSA</description>
    <inlineHelpText>Associated project in PSA</inlineHelpText>
    <label>PSA Project</label>
    <referenceTo>pse__Proj__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>CopadoProjects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/pse__Proj__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__ProjectHelp</customHelpPage>
    <description>Represents a collection of business transactions, activities, and related items to be managed over a defined time range, such as timecards, expenses, milestones, and budgets. Typically, people (represented by Resource records) are assigned to projects, though some projects do not require assignments in order to be staffed. Projects may also have a master project (parent) or a sub project (child) in the project hierarchy, supporting roll-ups of revenues, costs, and time to every project and up through the hierarchy.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Proj__c/fields/Copado_Project__c.field-meta.xml
<CustomField>
    <fullName>Copado_Project__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates this project is using Copado and a Copado project record should be created</description>
    <inlineHelpText>Indicates this project is using Copado and a Copado project record should be created</inlineHelpText>
    <label>Copado Project</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/Ops_Staffing_Stage__c.field-meta.xml
<CustomField>
    <fullName>Ops_Staffing_Stage__c</fullName>
    <description>Where we are with staffing new opportunity</description>
    <inlineHelpText>Ops Use Only</inlineHelpText>
    <label>Ops Staffing Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Staffed</fullName>
            </value>
            <value>
                <fullName>Staffing Initiated</fullName>
            </value>
            <value>
                <fullName>Partial Staff - Cannot Start</fullName>
            </value>
            <value>
                <fullName>Partial Staff - Can Start</fullName>
            </value>
            <value>
                <fullName>Fully Staffed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__End_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Stage__c.field-meta.xml
<CustomField>
    <fullName>pse__Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Prepare</fullName>
            </value>
            <value>
                <fullName>Define</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Build</fullName>
            </value>
            <value>
                <fullName>Verify</fullName>
            </value>
            <value>
                <fullName>Launch</fullName>
            </value>
            <value>
                <fullName>Close-Out</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/PSAProjectTriggerHandler.cls
public class PSAProjectTriggerHandler {
    public static boolean m_isExecuting = false;  
    
    //-------------------------------------------------------------------------  
    // On before insert trigger method
    //-------------------------------------------------------------------------
    public static void OnBeforeInsert(List<pse__Proj__c> newList) {
        
    } 
    
    //-------------------------------------------------------------------------
    // On after insert trigger method
    //-------------------------------------------------------------------------
    public static void OnAfterInsert(List<pse__Proj__c> newList) {   
        createCopadoProjects(newList);
    }
    
    //-------------------------------------------------------------------------
    // On before update trigger method
    //-------------------------------------------------------------------------
    public static void OnBeforeUpdate(Map<Id, pse__Proj__c> oldMap, Map<Id, pse__Proj__c> newMap) {
        
    }
    
    //-------------------------------------------------------------------------
    // On after update trigger method
    //-------------------------------------------------------------------------
    public static void OnAfterUpdate (Map<Id, pse__Proj__c> oldMap, Map<Id, pse__Proj__c> newMap) {
        List<pse__Proj__c> projects = new List<pse__Proj__c>();
        for(pse__Proj__c project : newMap.values()) {
            if(project.Copado_Project__c != oldMap.get(project.Id).Copado_Project__c) { projects.add(project); }
        }
        
        if(!projects.isEmpty()) { createCopadoProjects(projects); }
    }
    
    //-------------------------------------------------------------------------
    // On before delete trigger method
    //-------------------------------------------------------------------------
    public static void OnBeforeDelete (List<pse__Proj__c> newList) {    
        
    }
    
    //-------------------------------------------------------------------------
    // Sync Copado projects with PSA Projects
    //-------------------------------------------------------------------------
    private static void createCopadoProjects(List<pse__Proj__c> projects) {
        Set<Id> projectIds = new Set<Id>();
        List<copado__Project__c> copadoProjects = new List<copado__Project__c>();
        
        for(pse__Proj__c project : projects) {
            if(!projectIds.contains(project.Id)) { projectIds.add(project.Id); }
        }
        
        Map<Id, copado__Project__c> copadoProjectMap = new Map<Id, copado__Project__c>();
        List<copado__Project__c> currnetCopadoProjects = [SELECT Id, Name, PSAProject__c, copado__Start_Date__c, copado__End_Date__c FROM copado__Project__c WHERE PSAProject__c IN : projectIds];
        for(copado__Project__c currnetCopadoProject : currnetCopadoProjects) {
            copadoProjectMap.put(currnetCopadoProject.PSAProject__c, currnetCopadoProject);
        }
        
        for(pse__Proj__c project : projects) {
            if(project.Copado_Project__c) {
                copado__Project__c p;
                
                if(copadoProjectMap.containsKey(project.Id)) {
                    p=copadoProjectMap.get(project.Id);
                } else {
                	p = new copado__Project__c(Name=project.Name, PSAProject__c=project.Id, copado__Start_Date__c=project.pse__Start_Date__c, 

                                               copado__End_Date__c=project.pse__End_Date__c, Opps_Staffing_Stage__c=project.Ops_Staffing_Stage__c);

                }
                
                if(project.pse__Stage__c == 'Planned' || project.pse__Stage__c == 'Prepare' || project.pse__Stage__c == 'Define' || project.pse__Stage__c == 'Design') {
                    p.copado__Status__c='Planned';
                } else if (project.pse__Stage__c == 'Build' || project.pse__Stage__c == 'Verify' || project.pse__Stage__c == 'Launch') {
                    p.copado__Status__c='In Progress';
                } else {
                    p.copado__Status__c = 'Completed';
                }
                copadoProjects.add(p);
            }
        }
        
        if(!copadoProjects.isEmpty()) { upsert copadoProjects; }
    }
    
}