force-app/main/default/objects/SS_Product_Action__mdt/SS_Product_Action__mdt.object-meta.xml
<CustomObject>
    <description>Product Action definition - used in an SS Product Action Set</description>
    <label>SS Product Action</label>
    <pluralLabel>SS Product Action</pluralLabel>
</CustomObject>

force-app/main/default/objects/SS_Product_Action__mdt/fields/Action_Title__c.field-meta.xml
<CustomField>
    <fullName>Action_Title__c</fullName>
    <inlineHelpText>Action menu item tooltip</inlineHelpText>
    <label>Action Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SS_Product_Action__mdt/fields/Action_Type__c.field-meta.xml
<CustomField>
    <fullName>Action_Type__c</fullName>
    <inlineHelpText>Select the action type (Lightning Flow or URL redirect)</inlineHelpText>
    <label>Action Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Flow</fullName>
                <default>true</default>
                <label>Flow</label>
            </value>
            <value>
                <fullName>URL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SS_Product_Action__mdt/fields/Action_Value__c.field-meta.xml
<CustomField>
    <fullName>Action_Value__c</fullName>
    <inlineHelpText>Enter the action value for the Action Type Selected - Lightning Flow Name or URL</inlineHelpText>
    <label>Action Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SS_Product_Action__mdt/fields/New_Window__c.field-meta.xml
<CustomField>
    <fullName>New_Window__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check to enable the action in a new Tab or Window</inlineHelpText>
    <label>New Window</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SS_Product_Action_Set__mdt/SS_Product_Action_Set__mdt.object-meta.xml
<CustomObject>
    <description>Define a set of Product Actions to associate with a product catalog item.</description>
    <label>SS Product Action Set</label>
    <pluralLabel>SS Product FlActionow Set</pluralLabel>
</CustomObject>

force-app/main/default/objects/SS_Product_Action_Set__mdt/fields/iconName__c.field-meta.xml
<CustomField>
    <fullName>iconName__c</fullName>
    <inlineHelpText>Menu button icon (SLDS name. e.g. utility:settings)</inlineHelpText>
    <label>iconName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SS_Product_Action_Set__mdt/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <inlineHelpText>Menu button tooltip</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SS_Product_Settings__mdt/SS_Product_Settings__mdt.object-meta.xml
<CustomObject>
    <description>7Summits Product Catalog component settings</description>
    <label>SS Product Setting</label>
    <pluralLabel>SS Product Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/SS_Product_Settings__mdt/fields/Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Id__c</fullName>
    <description>Default account ID for internal users</description>
    <inlineHelpText>Set a default account ID for internal users</inlineHelpText>
    <label>Account Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SS_Product_Settings__mdt/fields/Action_Set__c.field-meta.xml
<CustomField>
    <fullName>Action_Set__c</fullName>
    <inlineHelpText>Associate an action set for this product setting</inlineHelpText>
    <label>Action Set</label>
    <referenceTo>SS_Product_Action_Set__mdt</referenceTo>
    <relationshipLabel>SS Product Settings</relationshipLabel>
    <relationshipName>SS_Product_Settings_Set</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/SS_Product_Settings__mdt/fields/Enable_Discount__c.field-meta.xml
<CustomField>
    <fullName>Enable_Discount__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enable cart summary discount</description>
    <inlineHelpText>Check to enable discount</inlineHelpText>
    <label>Enable Discount</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SS_Product_Settings__mdt/fields/Hide_Add_to_Cart__c.field-meta.xml
<CustomField>
    <fullName>Hide_Add_to_Cart__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Hide product add to cart button</description>
    <inlineHelpText>Check to hide the Add to Cart button in the product catalog.</inlineHelpText>
    <label>Hide Add to Cart</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SS_Product_Settings__mdt/fields/Hide_Images__c.field-meta.xml
<CustomField>
    <fullName>Hide_Images__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Hide product images</description>
    <inlineHelpText>Check to hide all image in the product catalog</inlineHelpText>
    <label>Hide Images</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SS_Product_Settings__mdt/fields/Hide_Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Hide_Unit_Price__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Hide product unit price</description>
    <inlineHelpText>Check to hide the product unit price</inlineHelpText>
    <label>Hide Unit Price</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SS_Product_Settings__mdt/fields/Pricebook_Id__c.field-meta.xml
<CustomField>
    <fullName>Pricebook_Id__c</fullName>
    <description>Pricebook ID to use for the product catalog</description>
    <inlineHelpText>Enter the price book ID to use for the product catalog</inlineHelpText>
    <label>Pricebook Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SS_Product_Settings__mdt/fields/Product_Family_List_IDs__c.field-meta.xml
<CustomField>
    <fullName>Product_Family_List_IDs__c</fullName>
    <description>List of product IDs to use for product family tile view.</description>
    <inlineHelpText>List of product IDs to use for product family tile view images.</inlineHelpText>
    <label>Product Family List IDs</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SS_Product_Settings__mdt/fields/Quantity_List__c.field-meta.xml
<CustomField>
    <fullName>Quantity_List__c</fullName>
    <defaultValue>&quot;1,2,3,4,5,6,7,8,9,10,15,20,30,50&quot;</defaultValue>
    <description>Quantity option list</description>
    <inlineHelpText>CSV list of quantity options</inlineHelpText>
    <label>Quantity List</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SS_Product_Settings__mdt/fields/Suggest_Email__c.field-meta.xml
<CustomField>
    <fullName>Suggest_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Send contact an email when suggesting a product - default is unchecked</description>
    <inlineHelpText>Send an email to a contact when suggesting a product - uncheck for sanbox</inlineHelpText>
    <label>Suggest Send Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SS_Product_Settings__mdt/fields/Use_Points__c.field-meta.xml
<CustomField>
    <fullName>Use_Points__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Use Points rather than Currency when this is checked</description>
    <inlineHelpText>Check to enable points rather than currency for product.</inlineHelpText>
    <label>Use Points</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ss_settings.cls
/*
 * Copyright (c) 2017. 7Summits inc.
 */

/**
 * Created by francois korb on 7/18/17.
 */

public with sharing class ss_settings
{
	private final String    DEFAULT_NAME        = 'Default';
	private final String    SETTINGS_NAME       = 'SS_Product_Settings__mdt';
	private final String    SETTINGS_ACTION     = 'SS_Product_Action__mdt';
	private final String    SETTINGS_ACTION_SET = 'SS_Product_Action_Set__mdt';

	private final Integer   MAX_ACTIONS   = 5;

	static final String FIELD_SEPARATOR   = ',';
	static final String QUANTITY_DEFAULTS = '1,2,3,4,5,6,7,8,9,10,20,30,50,100';

	@AuraEnabled
	public Boolean hideAddToCart {
		get;
		private set;
	}

	@AuraEnabled
	public Boolean hideImages {
		get;
		private set;
	}

	@AuraEnabled
	public Boolean hideUnitPrice {
		get;
		set;
	}

	@AuraEnabled
	public Boolean usePoints {
		get;
		private set;
	}

	@AuraEnabled
	public Boolean enableDiscount {
		get;
		private set;
	}

	@AuraEnabled
	public String pricebookId {
		get;
		private set;
	}

	@AuraEnabled
	public String accountId {
		get;
		private set;
	}

	@AuraEnabled
	public Boolean suggestEmail {
		get;
		private set;
	}

	@AuraEnabled
	public List<String> familyIds {
		get;
		private set;
	}

	@AuraEnabled
	public List<String> quantityList {
		get;
		private set;
	}

	@AuraEnabled
	public ss_actionSet actionSet {
		get;
		private set;
	}

	public ss_settings() {
		getCustomSettings('Default');
	}

	public ss_settings(String name)
	{
		getCustomSettings(String.isBlank(name) ? DEFAULT_NAME : name);
	}

	public ss_settings(String accountId, Boolean usePoints, String priceBookId) {
		this.accountId      = accountId;
		this.hideAddToCart  = false;
		this.hideImages     = false;
		this.hideUnitPrice  = false;
		this.pricebookId    = priceBookId;
		this.usePoints      = usePoints;
		this.enableDiscount = false;
		this.suggestEmail   = false;
		this.familyIds      = null;
		this.quantityList   = null;
	}

	private void getCustomSettings(String name) {
		String query = ss_util_metadata.buildQuery(SETTINGS_NAME, '') + ' WHERE DeveloperName = \'' + name + '\'';

		try
		{
			SS_Product_Settings__mdt  settings = (SS_Product_Settings__mdt) Database.query(query);

			if (settings != null)
			{
				getSettings(settings);
			}
		}
		catch (QueryException ex)
		{
			System.debug('Settings not found for ' + name);
		}
	}

	private void getSettings(SS_Product_Settings__mdt  settings)
	{
		this.accountId      = settings.Account_Id__c;
		this.hideAddToCart  = settings.Hide_Add_to_Cart__c;
		this.hideImages     = settings.Hide_Images__c;
		this.hideUnitPrice  = settings.Hide_Unit_Price__c;
		this.pricebookId    = settings.Pricebook_Id__c;
		this.usePoints      = settings.Use_Points__c;
		this.enableDiscount = settings.Enable_Discount__c;
		this.suggestEmail   = settings.Suggest_Email__c;
		this.familyIds      = String.isNotBlank(settings.Product_Family_List_IDs__c) ? settings.Product_Family_List_IDs__c.split(FIELD_SEPARATOR) : new List<String>();
		this.quantityList   = String.isNotBlank(settings.Quantity_List__c) ? settings.Quantity_List__c.split(FIELD_SEPARATOR) : QUANTITY_DEFAULTS.split(FIELD_SEPARATOR);

		if (settings.Action_Set__c != null)
		{
			this.actionSet      = new ss_actionSet();

			String actionSetQuery = ss_util_metadata.buildQuery(SETTINGS_ACTION_SET, '');
			actionSetQuery       += ' WHERE Id = \'' + settings.Action_Set__c + '\' LIMIT 1';

			SS_Product_Action_Set__mdt actionSet = (SS_Product_Action_Set__mdt)Database.query(actionSetQuery);

			this.actionSet.label    = actionSet.Label;
			this.actionSet.title    = actionSet.Title__c;
			this.actionSet.iconName = actionSet.iconName__c;

			for(Integer actionCount = 1; actionCount <= MAX_ACTIONS; ++actionCount)
			{
				String actionName = 'Action_' + actionCount + '__c';
				Id     actionId   = (Id) actionSet.get(actionName);

				if (actionId != null)
				{
					String actionQuery = ss_util_metadata.buildQuery(SETTINGS_ACTION, '');
					actionQuery += ' WHERE Id =\'' + actionId + '\' LIMIT 1';

					SS_Product_Action__mdt actionItem = (SS_Product_Action__mdt)Database.query(actionQuery);

					if (actionItem != null)
					{
						this.actionSet.items.add(setActionModel(actionItem));
					}
				}
			}
		}
	}

	private static ss_actionModel setActionModel(SS_Product_Action__mdt actionItem)
	{
		ss_actionModel model = new ss_actionModel();

		model.name          = actionItem.DeveloperName;
		model.label         = actionItem.Label;
		model.actionType    = actionItem.Action_Type__c;
		model.actionValue   = actionItem.Action_Value__c;
		model.title         = actionItem.Action_Title__c;
		model.newWindow     = actionItem.New_Window__c;

		return model;
	}
}