force-app/main/default/objects/pse__Proj__c/pse__Proj__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__ProjectHelp</customHelpPage>
    <description>Represents a collection of business transactions, activities, and related items to be managed over a defined time range, such as timecards, expenses, milestones, and budgets. Typically, people (represented by Resource records) are assigned to projects, though some projects do not require assignments in order to be staffed. Projects may also have a master project (parent) or a sub project (child) in the project hierarchy, supporting roll-ups of revenues, costs, and time to every project and up through the hierarchy.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Proj__c/fields/pse__Project_Manager__c.field-meta.xml
<CustomField>
    <fullName>pse__Project_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Person responsible for this project (optional). If not provided, it&apos;s assumed that the record Owner is the project manager.</description>
    <label>Project Manager</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.pse__Is_Resource__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Contact.pse__Is_Resource_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Only active resources are shown. To display all resources, click Show all results.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects Managed</relationshipLabel>
    <relationshipName>ProjectsManaged</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RiskIssueTemplate__c/RiskIssueTemplate__c.object-meta.xml
<CustomObject>
    <description>Template records for Risk &amp; Issue object to be created for each project</description>
    <label>Risk &amp; Issue Template</label>
    <nameField>
        <displayFormat>RIT-{0000000}</displayFormat>
        <label>Template Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Risk &amp; Issue Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RiskIssueTemplate__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of the risk</description>
    <inlineHelpText>Enter the description of the issue</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RiskIssueTemplate__c/fields/Risk_Sequence__c.field-meta.xml
<CustomField>
    <fullName>Risk_Sequence__c</fullName>
    <label>Risk Sequence</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RiskIssueTemplate__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Risk or Issue status</description>
    <inlineHelpText>Risk or Issue status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Risk_Issue_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RiskIssueTemplate__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Risk type</description>
    <inlineHelpText>Risk type</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Risk_Issue_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Risks_Issues__c/Risks_Issues__c.object-meta.xml
<CustomObject>
    <description>This Object is being used to track Risks &amp; Issues on Projects. This object is not linked to PSA.</description>
    <label>Risk &amp; Issue</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Risks &amp; Issues Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Risks &amp; Issues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Risks_Issues__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>The Description of the Risk or Issue being logged</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Risks_Issues__c/fields/Impact__c.field-meta.xml
<CustomField>
    <fullName>Impact__c</fullName>
    <description>This field is used to determine the impact of the Risk or Issue on the project.</description>
    <inlineHelpText>When choosing an option, please take into account the following areas: Cost, Schedule, Scope &amp; Quality.</inlineHelpText>
    <label>Impact</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Risks_Issues__c/fields/Mitigation_Steps__c.field-meta.xml
<CustomField>
    <fullName>Mitigation_Steps__c</fullName>
    <description>Please outline the steps needed to completely mitigate the Risk.</description>
    <inlineHelpText>Please outline the steps needed to completely mitigate the Risk.</inlineHelpText>
    <label>Mitigation Steps</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Risks_Issues__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>The Name of the Risk or Issue being logged</description>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Risks_Issues__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>The Project to which this Risk or Issue is linked</description>
    <label>Project</label>
    <referenceTo>pse__Proj__c</referenceTo>
    <relationshipLabel>Risk &amp; Issue Log</relationshipLabel>
    <relationshipName>Risks_Issues</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Risks_Issues__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Risk_Issue_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Risks_Issues__c/fields/TemplateId__c.field-meta.xml
<CustomField>
    <fullName>TemplateId__c</fullName>
    <label>TemplateId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Risks_Issues__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>This field outlines the Types of Risks &amp; Issues you may choose from.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Risk_Issue_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Risks_Issues__c/recordTypes/Risk.recordType-meta.xml
<RecordType>
    <fullName>Risk</fullName>
    <active>true</active>
    <description>This Record Type is used to track Risks for a project</description>
    <label>Risk</label>
</RecordType>

force-app/main/default/globalValueSets/Risk_Issue_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Mitigated</fullName>
    </customValue>
    <customValue>
        <fullName>Eradicated</fullName>
    </customValue>
    <description>Valid Risk &amp; Issue Status</description>
    <masterLabel>Risk &amp; Issue Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Risk_Issue_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Scope</fullName>
    </customValue>
    <customValue>
        <fullName>Resource</fullName>
    </customValue>
    <customValue>
        <fullName>Quality</fullName>
    </customValue>
    <customValue>
        <fullName>DevOps</fullName>
    </customValue>
    <customValue>
        <fullName>Timeline</fullName>
    </customValue>
    <customValue>
        <fullName>Budget</fullName>
    </customValue>
    <customValue>
        <fullName>Client-Specific</fullName>
        <isActive>false</isActive>
        <label>Client-Specific</label>
    </customValue>
    <customValue>
        <fullName>Exec Sponsor</fullName>
        <isActive>false</isActive>
        <label>Exec Sponsor</label>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
        <isActive>false</isActive>
        <label>Other</label>
    </customValue>
    <customValue>
        <fullName>Contracting (SOW, EWB)</fullName>
        <isActive>false</isActive>
        <label>Contracting (SOW, EWB)</label>
    </customValue>
    <customValue>
        <fullName>Schedule</fullName>
        <isActive>false</isActive>
        <label>Schedule</label>
    </customValue>
    <customValue>
        <fullName>Forecast</fullName>
        <isActive>false</isActive>
        <label>Forecast</label>
    </customValue>
    <customValue>
        <fullName>Executive Steering</fullName>
        <isActive>false</isActive>
        <label>Executive Steering</label>
    </customValue>
    <customValue>
        <fullName>Coverage</fullName>
        <isActive>false</isActive>
        <label>Coverage</label>
    </customValue>
    <description>Valid risk &amp; Issue types</description>
    <masterLabel>Risk &amp; Issue Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PreFlightRisksExtension.cls
public class PreFlightRisksExtension {
    public List<Risks_Issues__c> preflightRisks;
    public Id projectId { get; set; }
    public pse__Proj__c project { get; set; }
    
    public PreflightRisksExtension(ApexPages.standardController controller) {
        projectId = controller.getId();
        project = [SELECT Id, pse__Project_Manager__c, Name FROM pse__Proj__c WHERE Id =: projectId];
    }
    
    public List<Risks_Issues__c> getPreflightRisks() {
        preFlightRisks = new List<Risks_Issues__c>();
        buildPreFlightRisks();
        return preFlightRisks;
    }
    
    public PageReference save() {
		List<Risks_Issues__c> upsertRisks = new List<Risks_Issues__c>();
        System.debug('-------- preflightRisks: ' + preflightRisks);
        for(Risks_Issues__c risk : preflightRisks) {
            if(risk.Impact__c != null) { upsertRisks.add(risk); }  
        }
        
        System.debug('-------- upsertRisks: ' + preflightRisks);
        if(!upsertRisks.isEmpty()) { upsert upsertRisks; }
        return new PageReference('/' + projectId);
    }
    
    private void buildPreflightRisks() {
        RecordType rt = [SELECT Id FROM RecordType WHERE SObjectType='Risks_Issues__c' AND DeveloperName='Risk'];
        List<RiskIssueTemplate__c> templates = [SELECT Name, Description__c, Type__c FROM RiskIssueTemplate__c ORDER BY Type__c, Risk_Sequence__c];
        Map<String, Risks_Issues__c> riskMap = getCurrentRisks();
        
        System.debug('-------- templates: ' + templates);
        for(RiskIssueTemplate__c template : templates) {
            Risks_Issues__c newRisk;
            if(riskMap.containsKey(template.Name)) {
                newRisk = new Risks_Issues__c(Id=riskMap.get(template.Name).Id,
                    						  Impact__c=riskMap.get(template.Name).Impact__c,
                                              Type__c=riskMap.get(template.Name).Type__c,
                                              Mitigation_Steps__c=riskMap.get(template.Name).Mitigation_Steps__c,
                                              Name__c=riskMap.get(template.Name).Name__c,
                                              TemplateId__c=riskMap.get(template.Name).TemplateId__c,
                                              Project__c=projectId);
            } else {
                newRisk = new Risks_Issues__c(Type__c=template.Type__c,
                                              Name__c=template.Description__c,
                                              TemplateId__c=template.Name,
                                              RecordTypeId=rt.Id,
                                              Project__c=projectId);
            }
            preflightRisks.add(newRisk);
        }
    }
    
    private Map<String, Risks_Issues__c> getCurrentRisks() {
        List<Risks_Issues__c> currentRisks = [SELECT Id, Impact__c, Name__c, Status__c, Type__c, TemplateId__c, Mitigation_Steps__c 
                                              FROM Risks_Issues__c 
                                              WHERE Project__c =: projectId];
        Map<String, Risks_Issues__c> riskMap = new Map<String, Risks_Issues__c>();
        
        System.debug('-------- currentRisks: ' + currentRisks);
        for(Risks_Issues__c currentRisk: currentRisks) {
            if(currentRisk.TemplateId__c != null) { riskMap.put(currentRisk.TemplateId__c, currentRisk); }
        }
        
        System.debug('-------- riskMap: ' + riskMap);
        return riskMap;
    }
}