force-app/main/default/objects/pse__Proj__c/pse__Proj__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__ProjectHelp</customHelpPage>
    <description>Represents a collection of business transactions, activities, and related items to be managed over a defined time range, such as timecards, expenses, milestones, and budgets. Typically, people (represented by Resource records) are assigned to projects, though some projects do not require assignments in order to be staffed. Projects may also have a master project (parent) or a sub project (child) in the project hierarchy, supporting roll-ups of revenues, costs, and time to every project and up through the hierarchy.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Proj__c/fields/DevOps_Status__c.field-meta.xml
<CustomField>
    <fullName>DevOps_Status__c</fullName>
    <description>Red/Yellow/Green status for DevOps risks &amp; Issues records</description>
    <label>DevOps Status</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/Forecast_Status__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Status__c</fullName>
    <description>Red/Yellow/Green status for forecasts based on risks &amp; issues</description>
    <label>Forecast Status</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Project_Status__c.field-meta.xml
<CustomField>
    <fullName>pse__Project_Status__c</fullName>
    <description>Select the current project status from the picklist. Alternatively, use Process Builder or workflow rules to use your own logic to control the behavior of the corresponding color indicator field.</description>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Green</fullName>
                <color>#009900</color>
                <default>true</default>
                <label>Green</label>
            </value>
            <value>
                <fullName>Yellow</fullName>
                <color>#FFFF66</color>
                <label>Yellow</label>
            </value>
            <value>
                <fullName>Red</fullName>
                <color>#FF0000</color>
                <label>Red</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/Quality_Status__c.field-meta.xml
<CustomField>
    <fullName>Quality_Status__c</fullName>
    <description>Red/Yellow/Green status for overall quality based on Risks &amp; Issues records</description>
    <label>Quality Status</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/Resourcing_Status__c.field-meta.xml
<CustomField>
    <fullName>Resourcing_Status__c</fullName>
    <description>Red/Yellow/Green status for project resources</description>
    <label>Resourcing Status</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/Risk_Level_Status__c.field-meta.xml
<CustomField>
    <fullName>Risk_Level_Status__c</fullName>
    <description>Red/Yellow/Green indicator for overall project risk level based on risks and issues</description>
    <label>Risk Level Status</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/Scope_Status__c.field-meta.xml
<CustomField>
    <fullName>Scope_Status__c</fullName>
    <label>PCB Scope Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Green</fullName>
                <color>#009900</color>
                <label>Green</label>
            </value>
            <value>
                <fullName>Yellow</fullName>
                <color>#FFFF66</color>
                <label>Yellow</label>
            </value>
            <value>
                <fullName>Red</fullName>
                <color>#FF0000</color>
                <label>Red</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/Sponsor_Engaged_Status__c.field-meta.xml
<CustomField>
    <fullName>Sponsor_Engaged_Status__c</fullName>
    <description>Red/Yellow/Green status for sponsor engaged</description>
    <label>Sponsor Engaged Status</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/Timeline_Status__c.field-meta.xml
<CustomField>
    <fullName>Timeline_Status__c</fullName>
    <label>Timeline Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Risks_Issues__c/Risks_Issues__c.object-meta.xml
<CustomObject>
    <description>This Object is being used to track Risks &amp; Issues on Projects. This object is not linked to PSA.</description>
    <label>Risk &amp; Issue</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Risks &amp; Issues Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Risks &amp; Issues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Risks_Issues__c/fields/Closed_Date__c.field-meta.xml
<CustomField>
    <fullName>Closed_Date__c</fullName>
    <description>The Closed Date of the Risk or Issue</description>
    <inlineHelpText>The Closed Date of the Risk or Issue</inlineHelpText>
    <label>Closed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Risks_Issues__c/fields/Impact__c.field-meta.xml
<CustomField>
    <fullName>Impact__c</fullName>
    <description>This field is used to determine the impact of the Risk or Issue on the project.</description>
    <inlineHelpText>When choosing an option, please take into account the following areas: Cost, Schedule, Scope &amp; Quality.</inlineHelpText>
    <label>Impact</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Risks_Issues__c/fields/Mitigation_Steps__c.field-meta.xml
<CustomField>
    <fullName>Mitigation_Steps__c</fullName>
    <description>Please outline the steps needed to completely mitigate the Risk.</description>
    <inlineHelpText>Please outline the steps needed to completely mitigate the Risk.</inlineHelpText>
    <label>Mitigation Steps</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Risks_Issues__c/fields/Probability__c.field-meta.xml
<CustomField>
    <fullName>Probability__c</fullName>
    <description>High Probability - 80 -&gt; 100%
Medium-High Probability - 60 -&gt; 80%
Medium-Low Probability - 30 -&gt; 60%
Low Probability - 0 -&gt; 30%</description>
    <inlineHelpText>High Probability - 80 -&gt; 100%
Medium-High Probability - 60 -&gt; 80%
Medium-Low Probability - 30 -&gt; 60%
Low Probability - 0 -&gt; 30%</inlineHelpText>
    <label>Probability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium-High</fullName>
                <isActive>false</isActive>
                <label>Medium-High</label>
            </value>
            <value>
                <fullName>Medium-Low</fullName>
                <isActive>false</isActive>
                <label>Medium-Low</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Risks_Issues__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>The Project to which this Risk or Issue is linked</description>
    <label>Project</label>
    <referenceTo>pse__Proj__c</referenceTo>
    <relationshipLabel>Risk &amp; Issue Log</relationshipLabel>
    <relationshipName>Risks_Issues</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Risks_Issues__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Risk_Issue_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Risks_Issues__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>This field outlines the Types of Risks &amp; Issues you may choose from.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Risk_Issue_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Risks_Issues__c/recordTypes/Issue.recordType-meta.xml
<RecordType>
    <fullName>Issue</fullName>
    <active>true</active>
    <description>This Record Type is used to track Issues for a project</description>
    <label>Issue</label>
</RecordType>

force-app/main/default/objects/Risks_Issues__c/recordTypes/Risk.recordType-meta.xml
<RecordType>
    <fullName>Risk</fullName>
    <active>true</active>
    <description>This Record Type is used to track Risks for a project</description>
    <label>Risk</label>
</RecordType>

force-app/main/default/globalValueSets/Risk_Issue_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Mitigated</fullName>
    </customValue>
    <customValue>
        <fullName>Eradicated</fullName>
    </customValue>
    <description>Valid Risk &amp; Issue Status</description>
    <masterLabel>Risk &amp; Issue Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Risk_Issue_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Scope</fullName>
    </customValue>
    <customValue>
        <fullName>Resource</fullName>
    </customValue>
    <customValue>
        <fullName>Quality</fullName>
    </customValue>
    <customValue>
        <fullName>DevOps</fullName>
    </customValue>
    <customValue>
        <fullName>Timeline</fullName>
    </customValue>
    <customValue>
        <fullName>Budget</fullName>
    </customValue>
    <customValue>
        <fullName>Client-Specific</fullName>
        <isActive>false</isActive>
        <label>Client-Specific</label>
    </customValue>
    <customValue>
        <fullName>Exec Sponsor</fullName>
        <isActive>false</isActive>
        <label>Exec Sponsor</label>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
        <isActive>false</isActive>
        <label>Other</label>
    </customValue>
    <customValue>
        <fullName>Contracting (SOW, EWB)</fullName>
        <isActive>false</isActive>
        <label>Contracting (SOW, EWB)</label>
    </customValue>
    <customValue>
        <fullName>Schedule</fullName>
        <isActive>false</isActive>
        <label>Schedule</label>
    </customValue>
    <customValue>
        <fullName>Forecast</fullName>
        <isActive>false</isActive>
        <label>Forecast</label>
    </customValue>
    <customValue>
        <fullName>Executive Steering</fullName>
        <isActive>false</isActive>
        <label>Executive Steering</label>
    </customValue>
    <customValue>
        <fullName>Coverage</fullName>
        <isActive>false</isActive>
        <label>Coverage</label>
    </customValue>
    <description>Valid risk &amp; Issue types</description>
    <masterLabel>Risk &amp; Issue Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RiskAndIssuesStatusHandler.cls
/**
* @description RiskAndIssuesStatusHandler
* Author: Randy Wandell
* Date: 05/22/2020
*/
public with sharing class RiskAndIssuesStatusHandler {
    public static List<pse__Proj__c> setProjectRecordStatus(List<Risks_Issues__c> risks) {
        Set<Id> projectIds = new Set<Id>();
        List<pse__Proj__c> projects = new List<pse__Proj__c>();
        
        for(Risks_Issues__c risk : risks) {
            if(!projectIds.contains(risk.Project__c)) { projectIds.add(risk.Project__c); }
        }
        
        for(Id projectId : projectIds) {
            projects.add(setStatusFieldsForProject(projectId));
        }
        
        System.debug(projects);
        if(!projects.isEmpty()) { update projects; }
        
        return projects;
    }
    
    public static pse__Proj__c setStatusFieldsForProject(Id projectId) {
        String sponsorStatus='Green';
        String coverageStatus='Green';
        String devOpsStatus='Green';
        String riskLevelStatus='Green';
        String forecastStatus='Green';
        String qualityStatus='Green';
        String resourceStatus='Green';
        String scopeStatus='Green';
        String timelineStatus='Green';
        
        List<Risks_Issues__c> projectRisks = [SELECT Id, Type__c, Impact__c, Status__c, Mitigation_Steps__c, Closed_Date__c, Probability__c 
                                              FROM Risks_Issues__c 
                                              WHERE Project__c =: projectId AND RecordType.Name IN('Risk', 'Issue')];
        
        for(Risks_Issues__c projectRisk : projectRisks) {
            if(projectRisk.Type__c=='Exec Sponsor') { sponsorStatus=getRiskStatus(sponsorStatus, projectRisk); }
            else if(projectRisk.Type__c=='Timeline') { timelineStatus=getRiskStatus(timelineStatus, projectRisk); }
            else if(projectRisk.Type__c=='Resource') { resourceStatus=getRiskStatus(resourceStatus, projectRisk); }
            else if(projectRisk.Type__c=='Quality') { qualityStatus=getRiskStatus(qualityStatus, projectRisk); }
            else if(projectRisk.Type__c=='Budget') { forecastStatus=getRiskStatus(forecastStatus, projectRisk); }
            else if(projectRisk.Type__c=='DevOps') { devOpsStatus=getRiskStatus(devOpsStatus, projectRisk); }
            else if(projectRisk.Type__c=='Scope') { scopeStatus=getRiskStatus(scopeStatus, projectRisk); }
            
            System.debug('scopeStatus:  ' + scopeStatus);
            riskLevelStatus=getRiskStatus(riskLevelStatus, projectRisk);
        }
        
        return new pse__Proj__c(Id=projectId, Sponsor_Engaged_Status__c=sponsorStatus, TimeLine_Status__c=timelineStatus, DevOps_Status__c=devOpsStatus, Scope_Status__c=scopeStatus,
                                Risk_Level_Status__c=riskLevelStatus, Forecast_Status__c=forecastStatus, Quality_Status__c=qualityStatus, Resourcing_Status__c=resourceStatus,
                                pse__Project_Status__c=riskLevelStatus);
    }
    
    public static String getRiskStatus(String riskStatus, Risks_Issues__c projectRisk) {
        String thisRiskStatus= 'Green';
        System.debug('----------- projectRisk: ' + projectRisk);
        if(projectRisk.Mitigation_Steps__c=='') { projectRisk.Mitigation_Steps__c=null; }
        
        if(projectRisk.Impact__c == 'High')  {
            if(projectRisk.Probability__c == 'High' || projectRisk.Probability__c == null) {
                if(projectRisk.Status__c == 'Draft' || projectRisk.Status__c == 'In Progress') {
                    thisRiskStatus='Red';
                } else if(projectRisk.Status__c == 'Mitigated') {
                    thisRiskStatus='Yellow';
                } else if(projectRisk.Status__c == 'Eradicated') {
                    thisRiskStatus='Green';
                }
                
            } else if(projectRisk.Probability__c == 'Medium') {
                if(projectRisk.Status__c == 'Draft' || projectRisk.Status__c == 'In Progress') {
                    thisRiskStatus='Red';
                } else if(projectRisk.Status__c == 'Mitigated') {
                    thisRiskStatus='Yellow';
                } else if(projectRisk.Status__c == 'Eradicated') {
                    thisRiskStatus='Green';
                }
            } else if(projectRisk.Probability__c == 'Low') {
                if(projectRisk.Status__c != 'Eradicated') {
                    thisRiskStatus='Yellow';
                } else if(projectRisk.Status__c == 'Eradicated') {
                    thisRiskStatus='Green';
                }
            }
        } else if(projectRisk.Impact__c == 'Medium') {
            if(projectRisk.Probability__c == 'High' || projectRisk.Probability__c == null) {
                if(projectRisk.Status__c == 'Draft' || projectRisk.Status__c == 'In Progress') {
                    thisRiskStatus='Yellow';
                } else if(projectRisk.Status__c == 'Mitigated' || projectRisk.Status__c == 'Eradicated') {
                    thisRiskStatus='Green';
                }
            } else if(projectRisk.Probability__c == 'Medium') {
                if(projectRisk.Status__c == 'Draft' || projectRisk.Status__c == 'In Progress') {
                    thisRiskStatus='Yellow';
                } else if(projectRisk.Status__c == 'Mitigated' || projectRisk.Status__c == 'Eradicated') {
                    thisRiskStatus='Green';
                }
            } else if(projectRisk.Probability__c == 'Low') {
                thisRiskStatus='Green';
            }
        } else if(projectRisk.Impact__c =='Low') {
            thisRiskStatus = 'Green';
        }
        
        System.debug('riskStatus: ' + riskStatus + '       thisRiskStatus: ' + thisRiskStatus);
        if(riskStatus=='Red') { return riskStatus; }
        else if(riskStatus=='Yellow' && thisRiskStatus=='Red') { return thisRiskStatus; }
        else if(riskStatus=='Green' && thisRiskStatus=='Yellow') { return thisRiskStatus; }
        else if(riskStatus=='Green' && thisRiskStatus=='Red') { return thisRiskStatus; }
        else { return riskStatus; }
    }
}