force-app/main/default/objects/Adventure_Step__c/Adventure_Step__c.object-meta.xml
<CustomObject>
    <label>Adventure Step</label>
    <nameField>
        <label>Adventure Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Adventure Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Adventure_Step__c/fields/Completed__c.field-meta.xml
<CustomField>
    <fullName>Completed__c</fullName>
    <formula>Number_of_Tasks__c =  Number_of_Completed_Tasks__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Adventure_Step__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>The order in which the adventure steps should be displayed</description>
    <label>Order</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Adventure_Step__c/fields/Task_Progress__c.field-meta.xml
<CustomField>
    <fullName>Task_Progress__c</fullName>
    <formula>Number_of_Completed_Tasks__c  /  Number_of_Tasks__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>% Task Progress</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Adventure_Step__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>The title of the Adventure Step</description>
    <inlineHelpText>This is the title that will be displayed in the map for this Adventure Step</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Module__c/X7S_Adventure_Module__c.object-meta.xml
<CustomObject>
    <description>Object to support Learning Adventure Module records as part of the Learning Adventure accelerator from 7Summits.</description>
    <label>7S Adventure Module</label>
    <nameField>
        <label>7S Adventure Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>7S Adventure Modules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/X7S_Adventure_Module__c/fields/Adventure_Step__c.field-meta.xml
<CustomField>
    <fullName>Adventure_Step__c</fullName>
    <description>The Adventure Step that contains this Step Module</description>
    <inlineHelpText>The Adventure Step that contains this Step Module</inlineHelpText>
    <label>Adventure Step</label>
    <referenceTo>X7S_Adventure_Step__c</referenceTo>
    <relationshipName>X7S_Step_Modules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Module__c/fields/Completed__c.field-meta.xml
<CustomField>
    <fullName>Completed__c</fullName>
    <formula>IF(Number_of_Tasks__c &gt; 0, Number_of_Tasks__c = Number_of_Completed_Tasks__c,  Completed_Manual__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Completed (Formula)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Module__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>The order in which to display the Step Module</description>
    <inlineHelpText>The order in which to display the Step Module</inlineHelpText>
    <label>Order</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Module__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>The title of the Step Module that will be displayed above the card</description>
    <inlineHelpText>The title of the Step Module that will be displayed above the card</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Module__c/fields/Tooltip_Description__c.field-meta.xml
<CustomField>
    <fullName>Tooltip_Description__c</fullName>
    <description>Text to be displayed in the tooltip for this Step Module</description>
    <inlineHelpText>Text to be displayed in the tooltip for this Step Module</inlineHelpText>
    <label>Tooltip Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Task__c/X7S_Adventure_Task__c.object-meta.xml
<CustomObject>
    <description>Object to support Learning Adventure Task records as part of the Learning Adventure accelerator from 7Summits.</description>
    <label>7S Adventure Task</label>
    <nameField>
        <label>7S Adventure Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>7S Adventure Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/X7S_Adventure_Task__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>The order in which to display the Module Task</description>
    <label>Order</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Task__c/fields/Task_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Task_Due_Date__c</fullName>
    <description>The due date for this Task</description>
    <inlineHelpText>The due date for this Task</inlineHelpText>
    <label>Task Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/X7S_Adventure_Task__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>The title of this Module Task to be displayed next to icon</description>
    <inlineHelpText>The title of this Module Task to be displayed next to icon</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/x7sAdventureStepModuleWrapperHelper.cls
/*
 * Copyright (c) 2020. 7Summits Inc.
 */

public with sharing class x7sAdventureStepModuleWrapperHelper {

    public static x7sAdventureStepModuleWrapper createWrapper(X7S_Adventure_Module__c theStepModule, List<X7S_Adventure_Task__c> moduleTasks) {
        System.debug('Wrapping module tasks');
        System.debug(moduleTasks);

        x7sAdventureStepModuleWrapper stepModule = new x7sAdventureStepModuleWrapper();

        stepModule.id = theStepModule.Id;
        stepModule.Adventure_Step_Id = theStepModule.Adventure_Step__c;
        stepModule.title = theStepModule.Title__c;
        stepModule.moduleTasks = moduleTasks;
        stepModule.order = (Integer) theStepModule.Order__c;
        stepModule.descriptionLabel = theStepModule.Description_Label__c;
        stepModule.descriptionLink = theStepModule.Description_URL__c;
        stepModule.tooltip = theStepModule.Tooltip_Description__c;
        //Module progress
        //stepModule.taskProgress = theStepModule.Task_Progress__c.setScale(0);
        stepModule.completedFlag = theStepModule.Completed__c;
        stepModule.noUserTasks = false;

        for (X7S_Adventure_Task__c each : moduleTasks) {
            if (stepModule.nextModuleTaskDueDate != null && (each.Task_Due_Date__c < stepModule.nextModuleTaskDueDate)) {
                stepModule.nextModuleTaskDueDate = each.Task_Due_Date__c;
                stepModule.nextModuleTaskDueId = each.Id;
            } else if (stepModule.nextModuleTaskDueDate == null) {
                stepModule.nextModuleTaskDueDate = each.Task_Due_Date__c;
                stepModule.nextModuleTaskDueId = each.Id;
            }
        }
        //Need this line to manage  null value for taskProgress
        Decimal taskProgress = 0 ;
        if (moduleTasks.size() > 0) {
            stepModule.taskProgress = theStepModule.Task_Progress__c.setScale(0);
        } else {
            stepModule.taskProgress = taskProgress.setScale(0);
        }

        return stepModule;
    }

}