force-app/main/default/objects/App_Settings__c/App_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>App Settings</label>
</CustomObject>

force-app/main/default/objects/App_Settings__c/fields/Closed_Field__c.field-meta.xml
<CustomField>
    <fullName>Closed_Field__c</fullName>
    <defaultValue>&quot;Closed Won&quot;</defaultValue>
    <label>Closed Field</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solution_Offering__c/Solution_Offering__c.object-meta.xml
<CustomObject>
    <label>Solution Offering</label>
    <nameField>
        <label>Solution Offering Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solution Offerings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Solution_Offering__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Solution Offerings</relationshipLabel>
    <relationshipName>Solution_Offerings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Solution_Offering__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Solution Offerings</relationshipLabel>
    <relationshipName>Solution_Offerings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Solution_Offering__c/fields/Sold__c.field-meta.xml
<CustomField>
    <fullName>Sold__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sold</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Solution_Offerring_Names__c/Solution_Offerring_Names__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Solution Offerring Names</label>
</CustomObject>

force-app/main/default/objects/Solution_Offerring_Names__c/fields/Use__c.field-meta.xml
<CustomField>
    <fullName>Use__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Use</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/OpportunityTriggerUtil.cls
public with sharing class OpportunityTriggerUtil {
    public static void updateSolutionOfferings(List<Opportunity> newOpportunities, Map<Id, Opportunity> oldOpportunityMap) {
        Set<Id> opportunityIds = new Set<Id>();
        for(Opportunity opp : newOpportunities) {
            if(opp.StageName == App_Settings__c.getOrgDefaults().Closed_Field__c && 
                opp.StageName != oldOpportunityMap.get(opp.Id).StageName) {
                opportunityIds.add(opp.Id);
            }
        }
        List<Solution_Offering__c> solutionOfferingsToUpdate = [select Id from Solution_Offering__c where Opportunity__c in: 
            opportunityIds];
        for(Solution_Offering__c offering : solutionOfferingsToUpdate) {
            offering.Sold__c = true;
        }
        update solutionOfferingsToUpdate;
    }

    public static void createSolutionOfferingRecords() {
        List<Solution_Offering__c> solutionsToCreate = new List<Solution_Offering__c>();
        for(Account a : [select Id from Account]) {
            for(Solution_Offerring_Names__c son : Solution_Offerring_Names__c.getall().values()) {
                if(son.Use__c) {
                    solutionsToCreate.add(new Solution_Offering__c(Name = son.Name, Account__c = a.Id));
                }
            }
        }
        insert solutionsToCreate;
    }
}