force-app/main/default/objects/Contact/fields/Active_Upload__c.field-meta.xml
<CustomField>
    <fullName>Active_Upload__c</fullName>
    <label>Active Upload</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Badges__c.field-meta.xml
<CustomField>
    <fullName>Badges__c</fullName>
    <label>Badges</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SF_Dev_User_Id__c.field-meta.xml
<CustomField>
    <fullName>SF_Dev_User_Id__c</fullName>
    <label>SF Dev User Id</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Total_Points__c.field-meta.xml
<CustomField>
    <fullName>Total_Points__c</fullName>
    <label>Total Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Trailhead_URL__c.field-meta.xml
<CustomField>
    <fullName>Trailhead_URL__c</fullName>
    <formula>hyperlink(&quot;https://developer.salesforce.com/forums/ForumsTrailheadProfile?userId=&quot;+ SF_Dev_User_Id__c ,&quot;TrailheadURL&quot;,&quot;_blank&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Trailhead URL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Trails__c.field-meta.xml
<CustomField>
    <fullName>Trails__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText># of Trails completed.</inlineHelpText>
    <label>Trails</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Twitter_URL__c.field-meta.xml
<CustomField>
    <fullName>Twitter_URL__c</fullName>
    <formula>hyperlink(&quot;https://twitter.com/&quot;+  Twitter__c  ,&quot;@&quot;+Twitter__c,&quot;_blank&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Twitter URL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Trailhead_Leaderboard_Settings__c/Trailhead_Leaderboard_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Trailhead Leaderboard Settings</label>
</CustomObject>

force-app/main/default/classes/trailheadLeaderBoardController.cls
public class trailheadLeaderBoardController
{
    public List<ContactWrapper> contacts{get;set;}
    public Trailhead_Leaderboard_Settings__c trailsettings{get;set;}
    
    public trailheadLeaderBoardController()
    {
    
        initdata();
    }

    private void initData()
    {
        trailsettings = Trailhead_Leaderboard_Settings__c.getinstance();
        
        contacts = new List<ContactWrapper>();
        
        Integer x = 0;
        for(Contact c :  [Select Id, Name, Total_Points__c, Active_Upload__c,
                                 Twitter_Url__c, Trailhead_URL__c, SF_Dev_User_Id__c, 
                                 Badges__c, Active__c, Trails__c
                        from Contact 
                        Where Active__c = True
                        Order by Trails__c DESC, Badges__c DESC, Total_Points__c DESC])
        {
            x++;
            contacts.add(new ContactWrapper(c,x));
        
        }
    }
    
    public class ContactWrapper
    {
        public Integer count{get;set;}
        public Contact c {get;set;}
        public Integer badgeTotal {get;set;}
        public Integer pointsToday{get;set;}
        public Integer totalPoints{get;set;}
        public Integer trails{get;set;}
        public String name{get;set;}

        public ContactWrapper(Contact c, Integer x)
        {
            this.c = c;
            this.Name = c.Name;
            count = x;
            if(c.Badges__c == null){
                Integer badgesUpload = 0;
                
                if (c.Badges__c != null){
                    badgesUpload = (Integer)c.Badges__c;
                }        

                this.badgeTotal =  badgesUpload;

            }
            else{
                this.badgeTotal = (Integer)c.Badges__c;
            }
            trails = 0;
            if(c.Trails__c != null){
                trails = (Integer)c.Trails__c;
            }
                
            totalPoints = 0;
             if (c.Total_Points__c != null){
                totalPoints = (Integer)c.Total_Points__c;
            }
   
        }
    
    }


}