force-app/main/default/objects/Contact/fields/Competency_Group__c.field-meta.xml
<CustomField>
    <fullName>Competency_Group__c</fullName>
    <label>Competency Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Delivery Operations</fullName>
            </value>
            <value>
                <fullName>Sales &amp; Marketing</fullName>
            </value>
            <value>
                <fullName>Executive Management</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>Operations &amp; Finance</fullName>
            </value>
            <value>
                <fullName>Experience Design Studio</fullName>
            </value>
            <value>
                <fullName>Business Consulting</fullName>
            </value>
            <value>
                <fullName>Technology &amp; Accelerators</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Coverage_Participant__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Participant__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Coverage Participant</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/pse__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__Start_Date__c</fullName>
    <description>A Resource&apos;s first date of employment.</description>
    <inlineHelpText>A Resource&apos;s first date of employment.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/pse__Assignment__c/pse__Assignment__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__AssignmentAndScheduleHelp</customHelpPage>
    <description>Stores information about the allocation of a resource to a project and specifies the bill rate and cost rate for time entered. It references the schedule for a resource and, optionally, a project milestone.</description>
    <label>Assignment</label>
    <nameField>
        <label>Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Assignment__c/fields/Opp_Project_Type__c.field-meta.xml
<CustomField>
    <fullName>Opp_Project_Type__c</fullName>
    <formula>TEXT(pse__Project__r.pse__Opportunity__r.Project_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opp Project Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/pse__Assignment__c/fields/pse__Bill_Rate__c.field-meta.xml
<CustomField>
    <fullName>pse__Bill_Rate__c</fullName>
    <inlineHelpText>Enter the hourly bill rate for the resource</inlineHelpText>
    <label>Bill Rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/pse__Assignment__c/fields/pse__End_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__End_Date__c</fullName>
    <formula>pse__Schedule__r.pse__End_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/pse__Assignment__c/fields/pse__Exclude_from_Planners__c.field-meta.xml
<CustomField>
    <fullName>pse__Exclude_from_Planners__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>When selected, excludes the assignment from the Resource and Project Planners. Any excluded assignments are not included in totals calculations and color coding in Planners.</inlineHelpText>
    <label>Exclude from Planners</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/pse__Assignment__c/fields/pse__Is_Billable__c.field-meta.xml
<CustomField>
    <fullName>pse__Is_Billable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Billable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/pse__Assignment__c/fields/pse__Project__c.field-meta.xml
<CustomField>
    <fullName>pse__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>pse__Proj__c</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Assignment__c/fields/pse__Resource__c.field-meta.xml
<CustomField>
    <fullName>pse__Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.pse__Is_Resource__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Contact.pse__Is_Resource_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Only active resources are shown. To display all resources, click Show all results.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Assignment__c/fields/pse__Role__c.field-meta.xml
<CustomField>
    <fullName>pse__Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>BA (MTX)</fullName>
            </value>
            <value>
                <fullName>Biz Arch</fullName>
            </value>
            <value>
                <fullName>Change Analyst</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Content Marketer</fullName>
            </value>
            <value>
                <fullName>Coverage</fullName>
            </value>
            <value>
                <fullName>CP</fullName>
            </value>
            <value>
                <fullName>CPQ Arch</fullName>
            </value>
            <value>
                <fullName>CS - BA</fullName>
            </value>
            <value>
                <fullName>CS - FED</fullName>
            </value>
            <value>
                <fullName>CS - Platform Dev</fullName>
                <label>CS - PD</label>
            </value>
            <value>
                <fullName>CS - PM</fullName>
            </value>
            <value>
                <fullName>CS - SFDC Dev</fullName>
                <label>CS-SF Dev</label>
            </value>
            <value>
                <fullName>CS - TL</fullName>
            </value>
            <value>
                <fullName>DA</fullName>
            </value>
            <value>
                <fullName>Design Engineer</fullName>
            </value>
            <value>
                <fullName>Director, FED</fullName>
                <label>Dir FED</label>
            </value>
            <value>
                <fullName>Dir of HR &amp; Recruiting</fullName>
            </value>
            <value>
                <fullName>Exec</fullName>
            </value>
            <value>
                <fullName>Experience Strategist</fullName>
            </value>
            <value>
                <fullName>FED</fullName>
            </value>
            <value>
                <fullName>FED (CG)</fullName>
            </value>
            <value>
                <fullName>FED (CT)</fullName>
            </value>
            <value>
                <fullName>FED (GS)</fullName>
            </value>
            <value>
                <fullName>FED (MTX)</fullName>
            </value>
            <value>
                <fullName>FED (Offshore)</fullName>
                <label>FED (Off)</label>
            </value>
            <value>
                <fullName>Front Desk Receptionist</fullName>
            </value>
            <value>
                <fullName>Integration Architect</fullName>
                <label>IA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/pse__Assignment__c/fields/pse__Schedule__c.field-meta.xml
<CustomField>
    <fullName>pse__Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schedule</label>
    <referenceTo>pse__Schedule__c</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Assignment__c/fields/pse__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__Start_Date__c</fullName>
    <formula>pse__Schedule__r.pse__Start_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/pse__Assignment__c/fields/pse__Status__c.field-meta.xml
<CustomField>
    <fullName>pse__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tentative</fullName>
                <default>true</default>
                <label>Tentative</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/pse__Proj__c/pse__Proj__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__ProjectHelp</customHelpPage>
    <description>Represents a collection of business transactions, activities, and related items to be managed over a defined time range, such as timecards, expenses, milestones, and budgets. Typically, people (represented by Resource records) are assigned to projects, though some projects do not require assignments in order to be staffed. Projects may also have a master project (parent) or a sub project (child) in the project hierarchy, supporting roll-ups of revenues, costs, and time to every project and up through the hierarchy.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Proj__c/fields/InitiateCoverage__c.field-meta.xml
<CustomField>
    <fullName>InitiateCoverage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Initiate Coverage</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/Opp_Project_Type__c.field-meta.xml
<CustomField>
    <fullName>Opp_Project_Type__c</fullName>
    <formula>TEXT(pse__Opportunity__r.Project_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opp Project Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__End_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Is_Billable__c.field-meta.xml
<CustomField>
    <fullName>pse__Is_Billable__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check if this project is billable to a customer.</inlineHelpText>
    <label>Billable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/pse__Schedule__c/pse__Schedule__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__ScheduleHelp</customHelpPage>
    <description>Represents start and end dates and weekly working hours for an assignment. You enter schedule details when you create an assignment, which also creates an associated schedule record. Although schedule records have the fields Scheduled Hours and Scheduled Days, these are not intended for users to enter time directly. Their values are system-generated based on schedule dates, patterns, and exceptions. Specific deviations from schedules are represented as schedule exceptions.</description>
    <label>Schedule</label>
    <nameField>
        <displayFormat>Schedule{000000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Schedule__c/fields/pse__Friday_Hours__c.field-meta.xml
<CustomField>
    <fullName>pse__Friday_Hours__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Friday Hours</label>
    <precision>4</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CoverageAssignmentHandler.cls
/**
* @description CoverageAssignmentHandler
* Author: Randy Wandell
* Date: 05/06/2020
*/
public class CoverageAssignmentHandler {
    
    private static Map<String, List<pse__Assignment__c>> assignmentMap;
    private static Map<String, List<pse__Assignment__c>> coverageAssignmentMap;
    private static Map<String, Set<String>> competencyGroupMap;
    
    public static boolean isFirstTime=true;
    
    public static void makeAssignments(List<Id> projectIds) {
        
        assignmentMap = new Map<String, List<pse__Assignment__c>>();
        coverageAssignmentMap = new Map<String, List<pse__Assignment__c>>();
        Integer assignmentThreshold = Integer.valueOf(System.Label.Coverage_Assignment_Threshold);
        List<String> thresholdCompentencies = ((String)System.Label.Coverage_Assignment_Threshold_Compentencies).split(';');
        Integer thresholdCount=0;
        
        // Get the project
        List<pse__Proj__c> projects = [SELECT Id, pse__Start_Date__c, pse__End_Date__c, Opp_Project_Type__c, InitiateCoverage__c FROM pse__Proj__c WHERE Id IN: projectIds];
        
        // Get a list of resources for each competency group
        List<Contact> coverageResources = [SELECT Id, Name, Competency_Group__c, ReportsToId, 
                                           (SELECT CreatedDate FROM pse__Assignments__r WHERE pse__Role__c='Coverage' ORDER BY CreatedDate DESC LIMIT 1) 
                                           FROM Contact 
                                           WHERE Coverage_Participant__c=true
                                           ORDER BY Competency_Group__c];
        
        // Build out the maps for the projects
        getAssociatedRecords(projectIds);
        
        
        System.debug('assignmentMap: ' + assignmentMap);
        System.debug('coverageAssignmentMap: ' + coverageAssignmentMap);
        
        Integer coverageHours = 0;
        try{
            coverageHours = Integer.valueOf(System.Label.Coverage_Assignment_Default_Hours);
        } catch (Exception converionException) {
            
        }
        
        
        // Loop through the projects and get the lists for each project
        for(pse__Proj__c project : projects) {
            
            // Get assignments for the project
            Set<Id> assignmentIds = new Set<Id>();
            Set<String> competencyGroupSet = new Set<String>();
            
            List<pse__Assignment__c> assignments = assignmentMap.get(project.Id);
            System.debug(assignments);
            
            if(assignments != null) {
                for(pse__Assignment__c assignment : assignments) {
                    if(!assignmentIds.contains(assignment.pse__Resource__c)) {
                        assignmentIds.add(assignment.pse__Resource__c);
                    }
                    if(!competencyGroupSet.contains(assignment.pse__Resource__r.Competency_Group__c)) {
                        competencyGroupSet.add(assignment.pse__Resource__r.Competency_Group__c);
                    }
                }
                
                // Sping through the assignment map and get the total number of assignments for the competencies in the threshold competencies
                for(String compGroup : thresholdCompentencies) {
                    if(assignmentMap.containsKey(compGroup)) { thresholdCount += assignmentMap.get(compGroup).size(); }
                }
                
                // Get current coverage assignments for the project
                Map<String, pse__Assignment__c> currentCoverageAssignmentMap = new Map<String, pse__Assignment__c>();
                
                
                List<pse__Assignment__c> currentCoverageAssignments;
                if(coverageAssignmentMap.containsKey(project.Id)) {
                    currentCoverageAssignments = coverageAssignmentMap.get(project.Id);
                } else {
                    currentCoverageAssignments = new List<pse__Assignment__c>();
                }
                
                
                for(pse__Assignment__c a : currentCoverageAssignments) {
                    if(!currentCoverageAssignmentMap.containsKey(a.pse__Resource__r.Competency_Group__c)) {
                        currentCoverageAssignmentMap.put(a.pse__Resource__r.Competency_Group__c, a);
                    }
                }
                
                Map<String, pse__Assignment__c> coverageAssignmentMap = new Map<String, pse__Assignment__c>();
                Map<String, pse__Schedule__c> coverageScheduleMap = new Map<String, pse__Schedule__c>();
                String compGroup;
                DateTime lastAssignmentDate;
                pse__Assignment__c coverageAssignment = new pse__Assignment__c(pse__Project__c=project.Id, pse__Role__c='Coverage', pse__Status__c='Scheduled', pse__Bill_Rate__c=0, pse__Is_Billable__c=false, pse__Exclude_from_Planners__c=true);
                pse__Schedule__c coverageSchedule = new pse__Schedule__c(pse__Start_Date__c=project.pse__Start_Date__c, pse__End_Date__c=project.pse__End_Date__c, pse__Friday_Hours__c=coverageHours);
                
                for(Contact coverageResource : coverageResources) {
                    if(!currentCoverageAssignmentMap.containsKey(coverageResource.Competency_Group__c)) {
                        if(compGroup==null || compGroup!=coverageResource.Competency_Group__c) { // Check to see if the competency group is null or different from the current contact
                            if(compGroup!=null) { // Add assignment and schedule for competency group
                                System.debug('Competency Group: ' + compGroup);
                                coverageAssignmentMap.put(compGroup, coverageAssignment);
                                coverageScheduleMap.put(compGroup, coverageSchedule);
                            }
                            compGroup=coverageResource.Competency_Group__c;
                            lastAssignmentDate = null;
                            coverageAssignment = new pse__Assignment__c(pse__Project__c=project.Id, pse__Role__c='Coverage', pse__Status__c='Scheduled', pse__Bill_Rate__c=0, pse__Is_Billable__c=false, pse__Exclude_from_Planners__c=true);
                            coverageSchedule = new pse__Schedule__c(pse__Start_Date__c=project.pse__Start_Date__c, pse__End_Date__c=project.pse__End_Date__c, pse__Friday_Hours__c=coverageHours);
                        }
                        if(!coverageAssignmentMap.containsKey(coverageResource.Competency_Group__c)) {
                            compGroup=coverageResource.Competency_Group__c;
                            if(coverageResource.Competency_Group__c=='Delivery Operations') { // Delivery operations uses the manager for coverage
                                coverageAssignment.pse__Resource__c=coverageResource.Id;
                                coverageAssignmentMap.put(compGroup, coverageAssignment);
                            } else {
                                if(!assignmentIds.contains(coverageResource.Id)) { // Coverage participant has an assignment
                                    if(!coverageAssignmentMap.containsKey(compGroup)) {
                                        if(coverageResource.pse__Assignments__r.isEmpty()) { // Coverage participant has not been assigned yet
                                            coverageAssignment.pse__Resource__c=coverageResource.Id;
                                            coverageAssignmentMap.put(compGroup, coverageAssignment);
                                        } else {
                                            if(lastAssignmentDate==null) { // Last assignment date not set and coverage participant not set yet 
                                                coverageAssignment.pse__Resource__c=coverageResource.Id;
                                            } else if(lastAssignmentDate>coverageResource.pse__Assignments__r[0].CreatedDate) { //Last assignment date set and coverage participant assignment date < last assignment
                                                coverageAssignment.pse__Resource__c=coverageResource.Id;
                                                lastAssignmentDate=coverageResource.pse__Assignments__r[0].CreatedDate;
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
                
                if(compGroup!=null) {
                    coverageAssignmentMap.put(compGroup, coverageAssignment);
                    coverageScheduleMap.put(compGroup, coverageSchedule);
                }
                
                if(!coverageAssignmentMap.isEmpty() && (thresholdCount>=assignmentThreshold || project.InitiateCoverage__c==true)) { 
                    insert coverageScheduleMap.values();
                    for(String s: coverageScheduleMap.keySet()) {
                        if(coverageAssignmentMap.get(s).pse__Resource__c==null) {
                            coverageAssignmentMap.remove(s);
                        } else {
                            coverageAssignmentMap.get(s).pse__Schedule__c=coverageScheduleMap.get(s).Id;
                        }
                    }
                    insert coverageAssignmentMap.values();
                    
                    System.debug(coverageAssignmentMap);
                    
                }
            }
        }
    }
    
    
    private static void getAssociatedRecords(List<Id> projectIds) {
        List<pse__Assignment__c> assignments = [SELECT pse__Project__c, pse__Resource__c, pse__Resource__r.Competency_Group__c FROM pse__Assignment__c WHERE pse__Project__r.Id IN: projectIds AND pse__Is_Billable__c = true];
        
        for(pse__Assignment__c assignment : assignments) {
            if(!assignmentMap.containsKey(assignment.pse__Project__c)) {
                assignmentMap.put(assignment.pse__Project__c, new List<pse__Assignment__c>());
            }
            
            assignmentMap.get(assignment.pse__Project__c).add(assignment);
        }
        
        // Get current coverage assignments for the project
        List<pse__Assignment__c> currentCoverageAssignments = [SELECT pse__Project__c, pse__Resource__c, pse__Resource__r.Competency_Group__c 
                                                               FROM pse__Assignment__c 
                                                               WHERE pse__Project__c IN: projectIds AND pse__Role__c='Coverage'];
        for(pse__Assignment__c a : currentCoverageAssignments) {
            if(!coverageAssignmentMap.containsKey(a.pse__Project__c)) {
                coverageAssignmentMap.put(a.pse__Project__c, new List<pse__Assignment__c>());
            }
            coverageAssignmentMap.get(a.pse__Project__c).add(a);
        }
        
    }
}