force-app/main/default/objects/Contact/fields/Competency_Group__c.field-meta.xml
<CustomField>
    <fullName>Competency_Group__c</fullName>
    <label>Competency Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Delivery Operations</fullName>
            </value>
            <value>
                <fullName>Sales &amp; Marketing</fullName>
            </value>
            <value>
                <fullName>Executive Management</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>Operations &amp; Finance</fullName>
            </value>
            <value>
                <fullName>Experience Design Studio</fullName>
            </value>
            <value>
                <fullName>Business Consulting</fullName>
            </value>
            <value>
                <fullName>Technology &amp; Accelerators</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/pse__Is_Resource__c.field-meta.xml
<CustomField>
    <fullName>pse__Is_Resource__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Resource</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/pse__Is_Resource_Active__c.field-meta.xml
<CustomField>
    <fullName>pse__Is_Resource_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Resource Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/pse__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__Start_Date__c</fullName>
    <description>A Resource&apos;s first date of employment.</description>
    <inlineHelpText>A Resource&apos;s first date of employment.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/pse__Permission_Control__c/pse__Permission_Control__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__PermissionControlHelp</customHelpPage>
    <description>Grants a set of stand-alone or cascading permissions to a single Salesforce user, with reference to either a resource, region, practice, group, or project. Controls whether the user can carry out specific processes including: logging time on behalf of other resources, entering expenses, staffing, and viewing and editing projects in Project Task Gantt and Gantt.</description>
    <label>Permission Control</label>
    <nameField>
        <displayFormat>PC-{0}</displayFormat>
        <label>Permission Control Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Permission Controls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Permission_Control__c/fields/pse__Region__c.field-meta.xml
<CustomField>
    <fullName>pse__Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Region containing Resources that are the target of the specified action(s) - e.g. delegated Timecard Entry on behalf of Resources in this Region.</description>
    <inlineHelpText>This is the Region containing Resources that are the target of the specified action(s) - e.g. delegated Timecard Entry on behalf of Resources in this Region.</inlineHelpText>
    <label>Region</label>
    <referenceTo>pse__Region__c</referenceTo>
    <relationshipLabel>Permission Controls</relationshipLabel>
    <relationshipName>Permission_Controls</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Permission_Control__c/fields/pse__Staffing__c.field-meta.xml
<CustomField>
    <fullName>pse__Staffing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This checkbox governs the User&apos;s ability to staff Resources from specified Regions/Practices/Groups.</description>
    <inlineHelpText>This checkbox governs the User&apos;s ability to staff Resources from specified Regions/Practices/Groups.</inlineHelpText>
    <label>Staffing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/pse__Permission_Control__c/fields/pse__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/pse__Permission_Control__c/fields/pse__User__c.field-meta.xml
<CustomField>
    <fullName>pse__User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Permission_Controls</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/pse__Proj__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__ProjectHelp</customHelpPage>
    <description>Represents a collection of business transactions, activities, and related items to be managed over a defined time range, such as timecards, expenses, milestones, and budgets. Typically, people (represented by Resource records) are assigned to projects, though some projects do not require assignments in order to be staffed. Projects may also have a master project (parent) or a sub project (child) in the project hierarchy, supporting roll-ups of revenues, costs, and time to every project and up through the hierarchy.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Proj__c/fields/AutomaticallyCreateAssignment__c.field-meta.xml
<CustomField>
    <fullName>AutomaticallyCreateAssignment__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Automatically create assignment for internal projects</description>
    <inlineHelpText>Automatically create assignment for internal projects</inlineHelpText>
    <label>Automatically Create Assignment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/InitiateCoverage__c.field-meta.xml
<CustomField>
    <fullName>InitiateCoverage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Initiate Coverage</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/Ops_Staffing_Stage__c.field-meta.xml
<CustomField>
    <fullName>Ops_Staffing_Stage__c</fullName>
    <description>Where we are with staffing new opportunity</description>
    <inlineHelpText>Ops Use Only</inlineHelpText>
    <label>Ops Staffing Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Staffed</fullName>
            </value>
            <value>
                <fullName>Staffing Initiated</fullName>
            </value>
            <value>
                <fullName>Partial Staff - Cannot Start</fullName>
            </value>
            <value>
                <fullName>Partial Staff - Can Start</fullName>
            </value>
            <value>
                <fullName>Fully Staffed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Account__c.field-meta.xml
<CustomField>
    <fullName>pse__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Allow_Self_Staffing__c.field-meta.xml
<CustomField>
    <fullName>pse__Allow_Self_Staffing__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Whether a resource may create an assignment to this project for his/her own resource. Checking this will allow any and all resources in the system to create assignments to this project.</inlineHelpText>
    <label>Allow Self-Staffing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__End_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Is_Active__c.field-meta.xml
<CustomField>
    <fullName>pse__Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Is_Billable__c.field-meta.xml
<CustomField>
    <fullName>pse__Is_Billable__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check if this project is billable to a customer.</inlineHelpText>
    <label>Billable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Region__c.field-meta.xml
<CustomField>
    <fullName>pse__Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region</label>
    <referenceTo>pse__Region__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Stage__c.field-meta.xml
<CustomField>
    <fullName>pse__Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Prepare</fullName>
            </value>
            <value>
                <fullName>Define</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Build</fullName>
            </value>
            <value>
                <fullName>Verify</fullName>
            </value>
            <value>
                <fullName>Launch</fullName>
            </value>
            <value>
                <fullName>Close-Out</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/pse__Region__c/pse__Region__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__RegionHelp</customHelpPage>
    <description>An entity that represents a geographic area in which you do business. Regions are organized as an independent hierarchy determined by the Parent Region field, with parent and child records of the same type. Every region in the hierarchy may contain projects, resources (contacts), and other objects. The hierarchy allows roll-ups of revenue, cost, and time totals.</description>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User/fields/Competency_Group__c.field-meta.xml
<CustomField>
    <fullName>Competency_Group__c</fullName>
    <description>User&apos;s competency group populated by the associated contact</description>
    <inlineHelpText>User&apos;s competency group</inlineHelpText>
    <label>Competency Group</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>User&apos;s start date populated by the associated contact</description>
    <inlineHelpText>User&apos;s start date</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/x7S_ContactTriggerHelperTest.cls
@IsTest
private class x7S_ContactTriggerHelperTest {
    private static final List<String> lastNames = new List<String>{'New Manager', 'Old Manager', 'Updated User'};
        
    @TestSetup
    static void testSetup() {
        pse__Region__c region = new pse__Region__c(Name='Test Region');
        insert region;
        
        pse__Permission_Control__c permissionControl = new pse__Permission_Control__c(pse__User__c=UserINfo.getUserId(), pse__Region__c=region.Id, pse__Staffing__c=true);
        insert permissionControl;        
        
        List<User> testUsers = x7S_AdditionalTestUtils.createManyUserNoContact(3, lastNames);
        List<Contact> testContacts = x7S_AdditionalTestUtils.createManyTestContacts(3, lastNames, region.Id);

        pse__Proj__c project = new pse__Proj__c(Name='Test Internal Project', pse__Account__c=testContacts[0].AccountId, pse__Region__c=region.id, pse__Is_Active__c=true, pse__Stage__c='Planned', 
                                      			pse__Is_Billable__c=false, pse__Allow_Self_Staffing__c=true, InitiateCoverage__c=false, Ops_Staffing_Stage__c='Not Staffed', 
                                                pse__Start_Date__c=System.today(), pse__End_Date__c=System.today().addDays(30), AutomaticallyCreateAssignment__c=true);
        
        insert project;

        Map<String, Id> userMap = new Map<String, Id>();
        insert testUsers;
        for(User currentUser : testUsers){
            userMap.put(currentUser.LastName, currentUser.Id);
        }
        for(Contact currentContact : testContacts){
            currentContact.pse__Salesforce_User__c = userMap.get(currentContact.LastName);
            if(currentContact.LastName == 'Updated User'){
                currentContact.ReportsToId = testContacts[1].Id;
            }
        }
        update testContacts;
    }
    
    @IsTest
    static void testManagerSync() {
        Contact testOldContact = [SELECT Id, ReportsToId, pse__Salesforce_User__c, FirstName, LastName, Email, Competency_Group__c, pse__Start_Date__c, AccountId FROM Contact WHERE LastName = :lastNames[2] LIMIT 1];
        Contact testNewManagerContact = [SELECT Id, Name, pse__Salesforce_User__c FROM Contact WHERE LastName = :lastNames[0] LIMIT 1];
        Contact testNewContact = testOldContact;
        testNewContact.ReportsToId = testNewManagerContact.Id;
        update testNewContact;
        Test.startTest();
        x7S_ContactTriggerHelper.handleContactInsertUpdate(new Map<Id, Contact>{testNewContact.Id => testNewContact},new Map<Id, Contact>{testOldContact.Id => testOldContact});
        User testUpdatedUser = [SELECT Id, Name, ManagerId FROM User WHERE LastName = :lastNames[2] LIMIT 1];
        User testNewManagerUser = [SELECT Id, Name FROM User WHERE LastName = :lastNames[0] LIMIT 1];
        System.assertEquals(testUpdatedUser.ManagerId,testNewManagerUser.Id);
        Test.stopTest();
    }
    
    @IsTest
    static void testNameSync() {
        String testLastName = 'Changed Last Name';
        String testFirstName = 'Changed First Name';
        Contact testOldContact = [SELECT Id, ReportsToId, pse__Salesforce_User__c, FirstName, LastName, Email, Competency_Group__c, pse__Start_Date__c, AccountId FROM Contact WHERE LastName = :lastNames[2] LIMIT 1];
        Contact testNewContact = testOldContact;
        testNewContact.LastName = testLastName;
        testNewContact.FirstName = testFirstName;
        update testNewContact;
        Test.startTest();
        x7S_ContactTriggerHelper.handleContactInsertUpdate(new Map<Id, Contact>{testNewContact.Id => testNewContact},new Map<Id, Contact>{testOldContact.Id => testOldContact});
        User testUpdatedUser = [SELECT Id, Name FROM User WHERE LastName = :testLastName LIMIT 1];
        System.assertEquals(testUpdatedUser.Name,testFirstName + ' ' + testLastName);
        Test.stopTest();
    }
    
    @IsTest
    static void testOtherSync() {
        String testComp = Peak_Utils.getPicklistValues('Contact', 'Competency_Group__c')[0];
        Date testStart = Date.newInstance(2016, 5, 31);
        String testEmail = 'changedEmail@test.com';
        Contact testOldContact = [SELECT Id, ReportsToId, pse__Salesforce_User__c, FirstName, LastName, Email, Competency_Group__c, pse__Start_Date__c, AccountId FROM Contact WHERE LastName = :lastNames[2] LIMIT 1];
        Contact testNewContact = testOldContact;
        testNewContact.Competency_Group__c = testComp;
        testNewContact.pse__Start_Date__c = testStart;
        testNewContact.Email = testEmail;
        update testNewContact;
        Test.startTest();
        x7S_ContactTriggerHelper.handleContactInsertUpdate(new Map<Id, Contact>{testNewContact.Id => testNewContact},new Map<Id, Contact>{testOldContact.Id => testOldContact});
        User testUpdatedUser = [SELECT Id, Competency_Group__c, Start_Date__c, Email FROM User WHERE LastName = :lastNames[2] LIMIT 1];
        System.assertEquals(testUpdatedUser.Competency_Group__c,testComp);
        System.assertEquals(testUpdatedUser.Start_Date__c,testStart);
        Test.stopTest();
    }
    
    @IsTest
    static void testInsertNewResource() { 
        RecordType rt = [SELECT Id, Name FROM RecordType WHERE SobjectType='Contact' AND Name='PSA Resource' LIMIT 1];
        Account a = [SELECT Id FROM Account LIMIT 1];
        pse__Region__c region = [SELECT Id FROM pse__Region__c];
		Contact newContact = new Contact(FirstName=Peak_TestConstants.FIRSTNAME + 'NC', LastName='TESTNEW', Email=Peak_TestConstants.STANDARD_EMAIL + 'NC',
                                         AccountId = a.Id, pse__Is_Resource__c=true, pse__Is_Resource_Active__c=true, RecordtypeId=rt.Id, pse__Region__c=region.Id);
        insert newContact;
    }
}