force-app/main/default/objects/Contact/fields/Competency_Group__c.field-meta.xml
<CustomField>
    <fullName>Competency_Group__c</fullName>
    <label>Competency Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Delivery Operations</fullName>
            </value>
            <value>
                <fullName>Sales &amp; Marketing</fullName>
            </value>
            <value>
                <fullName>Executive Management</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>Operations &amp; Finance</fullName>
            </value>
            <value>
                <fullName>Experience Design Studio</fullName>
            </value>
            <value>
                <fullName>Business Consulting</fullName>
            </value>
            <value>
                <fullName>Technology &amp; Accelerators</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/pse__Is_Resource__c.field-meta.xml
<CustomField>
    <fullName>pse__Is_Resource__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Resource</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/pse__Is_Resource_Active__c.field-meta.xml
<CustomField>
    <fullName>pse__Is_Resource_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Resource Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/pse__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__Start_Date__c</fullName>
    <description>A Resource&apos;s first date of employment.</description>
    <inlineHelpText>A Resource&apos;s first date of employment.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/pse__Assignment__c/pse__Assignment__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__AssignmentAndScheduleHelp</customHelpPage>
    <description>Stores information about the allocation of a resource to a project and specifies the bill rate and cost rate for time entered. It references the schedule for a resource and, optionally, a project milestone.</description>
    <label>Assignment</label>
    <nameField>
        <label>Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Assignment__c/fields/pse__End_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__End_Date__c</fullName>
    <formula>pse__Schedule__r.pse__End_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/pse__Assignment__c/fields/pse__Resource__c.field-meta.xml
<CustomField>
    <fullName>pse__Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.pse__Is_Resource__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Contact.pse__Is_Resource_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Only active resources are shown. To display all resources, click Show all results.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Assignment__c/fields/pse__Schedule__c.field-meta.xml
<CustomField>
    <fullName>pse__Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schedule</label>
    <referenceTo>pse__Schedule__c</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Assignment__c/fields/pse__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__Start_Date__c</fullName>
    <formula>pse__Schedule__r.pse__Start_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/pse__Permission_Control__c/pse__Permission_Control__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__PermissionControlHelp</customHelpPage>
    <description>Grants a set of stand-alone or cascading permissions to a single Salesforce user, with reference to either a resource, region, practice, group, or project. Controls whether the user can carry out specific processes including: logging time on behalf of other resources, entering expenses, staffing, and viewing and editing projects in Project Task Gantt and Gantt.</description>
    <label>Permission Control</label>
    <nameField>
        <displayFormat>PC-{0}</displayFormat>
        <label>Permission Control Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Permission Controls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Permission_Control__c/fields/pse__Practice__c.field-meta.xml
<CustomField>
    <fullName>pse__Practice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Practice containing Resources that are the target of the specified action(s) - e.g. delegated Timecard Entry on behalf of Resources in this Practice.</description>
    <inlineHelpText>This is the Practice containing Resources that are the target of the specified action(s) - e.g. delegated Timecard Entry on behalf of Resources in this Practice.</inlineHelpText>
    <label>Practice</label>
    <referenceTo>pse__Practice__c</referenceTo>
    <relationshipLabel>Permission Controls</relationshipLabel>
    <relationshipName>Permission_Controls</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Permission_Control__c/fields/pse__Region__c.field-meta.xml
<CustomField>
    <fullName>pse__Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Region containing Resources that are the target of the specified action(s) - e.g. delegated Timecard Entry on behalf of Resources in this Region.</description>
    <inlineHelpText>This is the Region containing Resources that are the target of the specified action(s) - e.g. delegated Timecard Entry on behalf of Resources in this Region.</inlineHelpText>
    <label>Region</label>
    <referenceTo>pse__Region__c</referenceTo>
    <relationshipLabel>Permission Controls</relationshipLabel>
    <relationshipName>Permission_Controls</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Permission_Control__c/fields/pse__Resource__c.field-meta.xml
<CustomField>
    <fullName>pse__Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Resource who is the target of the specified action(s) - e.g. delegated Timecard Entry on behalf of this Resource.</description>
    <inlineHelpText>This is the Resource who is the target of the specified action(s) - e.g. delegated Timecard Entry on behalf of this Resource.</inlineHelpText>
    <label>Resource</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.pse__Is_Resource__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Contact.pse__Is_Resource_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Only active resources are shown. To display all resources, click Show all results.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Permission Controls</relationshipLabel>
    <relationshipName>Permission_Controls</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Permission_Control__c/fields/pse__Staffing__c.field-meta.xml
<CustomField>
    <fullName>pse__Staffing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This checkbox governs the User&apos;s ability to staff Resources from specified Regions/Practices/Groups.</description>
    <inlineHelpText>This checkbox governs the User&apos;s ability to staff Resources from specified Regions/Practices/Groups.</inlineHelpText>
    <label>Staffing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/pse__Permission_Control__c/fields/pse__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/pse__Permission_Control__c/fields/pse__User__c.field-meta.xml
<CustomField>
    <fullName>pse__User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Permission_Controls</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/pse__Proj__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__ProjectHelp</customHelpPage>
    <description>Represents a collection of business transactions, activities, and related items to be managed over a defined time range, such as timecards, expenses, milestones, and budgets. Typically, people (represented by Resource records) are assigned to projects, though some projects do not require assignments in order to be staffed. Projects may also have a master project (parent) or a sub project (child) in the project hierarchy, supporting roll-ups of revenues, costs, and time to every project and up through the hierarchy.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Proj__c/fields/AutomaticallyCreateAssignment__c.field-meta.xml
<CustomField>
    <fullName>AutomaticallyCreateAssignment__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Automatically create assignment for internal projects</description>
    <inlineHelpText>Automatically create assignment for internal projects</inlineHelpText>
    <label>Automatically Create Assignment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__End_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Is_Active__c.field-meta.xml
<CustomField>
    <fullName>pse__Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Practice__c.field-meta.xml
<CustomField>
    <fullName>pse__Practice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Practice</label>
    <referenceTo>pse__Practice__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Region__c.field-meta.xml
<CustomField>
    <fullName>pse__Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region</label>
    <referenceTo>pse__Region__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/pse__Schedule__c/pse__Schedule__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__ScheduleHelp</customHelpPage>
    <description>Represents start and end dates and weekly working hours for an assignment. You enter schedule details when you create an assignment, which also creates an associated schedule record. Although schedule records have the fields Scheduled Hours and Scheduled Days, these are not intended for users to enter time directly. Their values are system-generated based on schedule dates, patterns, and exceptions. Specific deviations from schedules are represented as schedule exceptions.</description>
    <label>Schedule</label>
    <nameField>
        <displayFormat>Schedule{000000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Schedule__c/fields/pse__Friday_Hours__c.field-meta.xml
<CustomField>
    <fullName>pse__Friday_Hours__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Friday Hours</label>
    <precision>4</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/pse__Schedule__c/fields/pse__Monday_Hours__c.field-meta.xml
<CustomField>
    <fullName>pse__Monday_Hours__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Monday Hours</label>
    <precision>4</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/pse__Schedule__c/fields/pse__Thursday_Hours__c.field-meta.xml
<CustomField>
    <fullName>pse__Thursday_Hours__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Thursday Hours</label>
    <precision>4</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/pse__Schedule__c/fields/pse__Tuesday_Hours__c.field-meta.xml
<CustomField>
    <fullName>pse__Tuesday_Hours__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Tuesday Hours</label>
    <precision>4</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/pse__Schedule__c/fields/pse__Wednesday_Hours__c.field-meta.xml
<CustomField>
    <fullName>pse__Wednesday_Hours__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Wednesday Hours</label>
    <precision>4</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/Apex_Processing__c.field-meta.xml
<CustomField>
    <fullName>Apex_Processing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag set to indicate the user is being processed in an apex context and validation rules can be bypassed</description>
    <inlineHelpText>Flag set to indicate the user is being processed in an apex context and validation rules can be bypassed</inlineHelpText>
    <label>Apex Processing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Competency_Group__c.field-meta.xml
<CustomField>
    <fullName>Competency_Group__c</fullName>
    <description>User&apos;s competency group populated by the associated contact</description>
    <inlineHelpText>User&apos;s competency group</inlineHelpText>
    <label>Competency Group</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>User&apos;s start date populated by the associated contact</description>
    <inlineHelpText>User&apos;s start date</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/x7S_ContactTriggerHelper.cls
public without sharing class x7S_ContactTriggerHelper {
    public static void handleContactInsertUpdate(Map<Id, Contact> newValues, Map<Id, Contact> oldValues) {
        Map<Id,List<String>> changedIdMap = new Map<Id,List<String>>();
        List<User> updatedUsers = new List<User>();
        for(Id key : newValues.keySet()){
            if(newValues.get(key).pse__Salesforce_User__c != null){
                List<String> updatedValues = new List<String>();
                Contact newContact = newValues.get(key);
                Contact oldContact = oldValues != null && !oldValues.isEmpty() ? oldValues.get(key) : new Contact();
                if(newContact.ReportsToId != oldContact.ReportsToId){
                    updatedValues.add('reports');
                }
                if(newContact.FirstName != oldContact.FirstName || newContact.LastName != oldContact.LastName){
                    updatedValues.add('name');
                }
                if(newContact.Email != oldContact.Email){
                    updatedValues.add('email');
                }
                if(newContact.Competency_Group__c != oldContact.Competency_Group__c){
                    updatedValues.add('competency');
                }
                if(newContact.pse__Start_Date__c != oldContact.pse__Start_Date__c){
                    updatedValues.add('start');
                }
                if(newContact.AccountId != oldContact.AccountId){
                    updatedValues.add('company');
                }
                if(!updatedValues.isEmpty()){
                    changedIdMap.put(newContact.Id, updatedValues);
                }
            }
        }
        for(Contact reportsContact : [SELECT Id, FirstName, LastName, Email, ReportsTo.pse__Salesforce_User__c, pse__Salesforce_User__c, Competency_Group__c, pse__Start_Date__c, Account.Name FROM Contact WHERE Id IN :changedIdMap.keySet()]){
            User newUserData = new User(Id=reportsContact.pse__Salesforce_User__c, Apex_Processing__c=true);
            for(String updatedValue : changedIdMap.get(reportsContact.Id)){
                switch on updatedValue {
                    when 'reports' {
                        newUserData.ManagerId = reportsContact.ReportsTo.pse__Salesforce_User__c;
                    }
                    when 'name' {
                        newUserData.FirstName = reportsContact.FirstName;
                        newUserData.LastName = reportsContact.LastName;
                    }
                    when 'email' {
                        newUserData.Email = reportsContact.Email;
                    }
                    when 'competency' {
                        newUserData.Competency_Group__c = reportsContact.Competency_Group__c;
                    }
                    when 'start' {
                        newUserData.Start_Date__c = reportsContact.pse__Start_Date__c;
                    }
                    when 'company' {
                        newUserData.CompanyName = reportsContact.Account.Name;
                    }
                }
            }
            System.debug('handleContactInsertUpdate UPDATED USER ==== ' + newUserData);
            updatedUsers.add(newUserData);
        }
        update updatedUsers;
    }
    
    public static void insertInternalAssignments(Map<Id, Contact> contactMap) {
        List<pse__Permission_Control__c> psaPermissions = [SELECT Id, pse__Region__c, pse__Resource__c, pse__Practice__c 
                                                           FROM pse__Permission_Control__c 
                                                           WHERE pse__User__c =: UserInfo.getUserId() AND pse__Staffing__c=true];
        
        List<pse__Proj__c> projects = [SELECT Id FROM pse__Proj__c WHERE pse__Is_Active__c=true AND AutomaticallyCreateAssignment__c=true];
        List<pse__Assignment__c> newAssignments = new List<pse__Assignment__c>();
        List<pse__Schedule__c> newSchedules = new List<pse__Schedule__c>();
        
        if(!psaPermissions.isEmpty()) {
            Map<Id,Set<Id>> existingAssignments = getExistingAssignmentsForContacts(contactMap.values(), projects);
            System.debug('------ AssignmentMap: ' + existingAssignments);
            System.debug('------ projects: ' + projects);
            for(Contact c : contactMap.values()) {
                boolean assignmentCreated=false;
                for(pse__Permission_Control__c psaPermission : psaPermissions) {
                    if(psaPermission.pse__Region__c == c.pse__Region__c || psaPermission.pse__Practice__c == c.pse__Practice__c) {
                        System.debug('------------ Permissions for Staffing --------------');
                        if(c.pse__Is_Resource_Active__c && c.pse__Is_Resource__c) {
                            for(pse__Proj__c project : projects) {
                                if(!existingAssignments.containsKey(project.Id) || (existingAssignments.containsKey(project.Id) && !existingAssignments.get(project.Id).contains(c.Id))) {
                                    pse__Schedule__c s = new pse__Schedule__c(pse__Start_Date__c=Date.newInstance(2018, 01, 01), 
                                                                              pse__End_Date__c=Date.newInstance(2022, 01, 01),
                                                                              pse__Monday_Hours__c=0,
                                                                              pse__Tuesday_Hours__c=0,
                                                                              pse__Wednesday_Hours__c=0,
                                                                              pse__Thursday_Hours__c=0,
                                                                              pse__Friday_Hours__c=0);
                                    pse__Assignment__c a = new pse__Assignment__c(pse__Project__c=project.Id, pse__Resource__c=c.Id, pse__Use_Resource_Default_Cost_Rate__c	=true,
                                                                                  pse__Bill_Rate__c=0.0);
                                    
                                    newSchedules.add(s);
                                    newAssignments.add(a);
                                    assignmentCreated=true;
                                    
                                }
                            }
                        }
                    }
                    if(assignmentCreated) { break; }
                }
            }            
        }
        
        if(!newSchedules.isEmpty()) {
            System.debug('================= assignments: ' + newAssignments);
            insert newSchedules;
            integer x=0;
            for(pse__Schedule__c s : newSchedules) {
                newAssignments[x].pse__Schedule__c=s.Id;
                x++;
            }
            insert newAssignments;
        }
    }
    
    private static Map<Id, Set<Id>> getExistingAssignmentsForContacts(List<Contact> contacts, List<pse__Proj__c> projects) {
        Map<Id, Set<Id>> existingAssignmentMap = new Map<Id, Set<Id>>();
        Set<Id> resourceIds = new Set<Id>();
        Set<Id> projectIds = new Set<Id>();
        
        for(Contact c : contacts) {
            resourceIds.add(c.Id);
        }
        
        for(pse__Proj__c p : projects) {
            projectIds.add(p.Id);
        }
        
        List<pse__Assignment__c> assignments = [SELECT pse__Project__c, pse__Resource__c 
                                                FROM pse__Assignment__c 
                                                WHERE pse__Project__c IN : projectIds AND pse__Resource__c IN : resourceIds];
        for(pse__Assignment__c assignment : assignments) {
            if(!existingAssignmentMap.containsKey(assignment.pse__Project__c)) { existingAssignmentMap.put(assignment.pse__Project__c, new Set<Id>()); }
            existingAssignmentMap.get(assignment.pse__Project__c).add(assignment.pse__Resource__c);
        }
        
        return existingAssignmentMap;
    }
}