force-app/main/default/objects/Contact/fields/Generic_Resource__c.field-meta.xml
<CustomField>
    <fullName>Generic_Resource__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Generic Resource</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/pse__Resource_Role__c.field-meta.xml
<CustomField>
    <fullName>pse__Resource_Role__c</fullName>
    <label>Resource Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>Biz Arch</fullName>
            </value>
            <value>
                <fullName>Business Analyst (MTX)</fullName>
            </value>
            <value>
                <fullName>Change Analyst</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Content Marketer</fullName>
            </value>
            <value>
                <fullName>CP</fullName>
            </value>
            <value>
                <fullName>CPQ Arch</fullName>
            </value>
            <value>
                <fullName>CS-BA</fullName>
            </value>
            <value>
                <fullName>CS-FED</fullName>
            </value>
            <value>
                <fullName>CS-Platform Dev</fullName>
            </value>
            <value>
                <fullName>CS-PM</fullName>
            </value>
            <value>
                <fullName>CS-SFDC Dev</fullName>
            </value>
            <value>
                <fullName>CS-TL</fullName>
            </value>
            <value>
                <fullName>Customer Success</fullName>
            </value>
            <value>
                <fullName>DA</fullName>
            </value>
            <value>
                <fullName>Design Engineer</fullName>
            </value>
            <value>
                <fullName>Director, FED</fullName>
            </value>
            <value>
                <fullName>Dir of HR &amp; Recruiting</fullName>
            </value>
            <value>
                <fullName>Employee Bolt Consultant</fullName>
            </value>
            <value>
                <fullName>Exec</fullName>
            </value>
            <value>
                <fullName>Experience Strategist</fullName>
            </value>
            <value>
                <fullName>FED</fullName>
            </value>
            <value>
                <fullName>FED (CG)</fullName>
            </value>
            <value>
                <fullName>FED (CT)</fullName>
            </value>
            <value>
                <fullName>FED (GS Labs)</fullName>
            </value>
            <value>
                <fullName>FED (MTX)</fullName>
            </value>
            <value>
                <fullName>FED (Offshore)</fullName>
            </value>
            <value>
                <fullName>Front Desk Receptionist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/pse__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__Start_Date__c</fullName>
    <description>A Resource&apos;s first date of employment.</description>
    <inlineHelpText>A Resource&apos;s first date of employment.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/pse__Region__c.field-meta.xml
<CustomField>
    <fullName>pse__Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region</label>
    <referenceTo>pse__Region__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Region__c/pse__Region__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__RegionHelp</customHelpPage>
    <description>An entity that represents a geographic area in which you do business. Regions are organized as an independent hierarchy determined by the Parent Region field, with parent and child records of the same type. Every region in the hierarchy may contain projects, resources (contacts), and other objects. The hierarchy allows roll-ups of revenue, cost, and time totals.</description>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Resource_Request__c/pse__Resource_Request__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__ResourceRequestHelp</customHelpPage>
    <description>Operating as a means of asking for resources to staff an existing or planned project, resource requests collect information to help users responsible for staffing and assignment creation to choose the right resource. The user requesting the resource (e.g., project manager or sales professional) may create a resource request from an opportunity or project, or generate them based on project tasks and project task assignments. Held resource requests, or “soft bookings”, occur when a named resource has been reserved for a project or opportunity, but not yet assigned to the project.</description>
    <label>Resource Request</label>
    <nameField>
        <displayFormat>RR-{0000000}</displayFormat>
        <label>Resource Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Resource_Request__c/fields/Hours_Per_Week__c.field-meta.xml
<CustomField>
    <fullName>Hours_Per_Week__c</fullName>
    <label>Hours Per Week</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>40</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/pse__Resource_Request__c/fields/pse__End_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/pse__Resource_Request__c/fields/pse__Notes__c.field-meta.xml
<CustomField>
    <fullName>pse__Notes__c</fullName>
    <label>Notes</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/pse__Resource_Request__c/fields/pse__Opportunity__c.field-meta.xml
<CustomField>
    <fullName>pse__Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Resource Requests</relationshipLabel>
    <relationshipName>Resource_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Resource_Request__c/fields/pse__Preferred_Schedule__c.field-meta.xml
<CustomField>
    <fullName>pse__Preferred_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Preferred Schedule</label>
    <referenceTo>pse__Schedule__c</referenceTo>
    <relationshipLabel>Resource Requests</relationshipLabel>
    <relationshipName>Resource_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Resource_Request__c/fields/pse__Region__c.field-meta.xml
<CustomField>
    <fullName>pse__Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region</label>
    <referenceTo>pse__Region__c</referenceTo>
    <relationshipLabel>Resource Requests</relationshipLabel>
    <relationshipName>Resource_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Resource_Request__c/fields/pse__Resource_Role__c.field-meta.xml
<CustomField>
    <fullName>pse__Resource_Role__c</fullName>
    <label>Resource Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>Biz Arch</fullName>
            </value>
            <value>
                <fullName>Business Analyst (MTX)</fullName>
            </value>
            <value>
                <fullName>Change Analyst</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Content Marketer</fullName>
            </value>
            <value>
                <fullName>CP</fullName>
            </value>
            <value>
                <fullName>CPQ Arch</fullName>
            </value>
            <value>
                <fullName>CS - BA</fullName>
            </value>
            <value>
                <fullName>CS - FED</fullName>
            </value>
            <value>
                <fullName>CS - Platform Dev</fullName>
            </value>
            <value>
                <fullName>CS - PM</fullName>
            </value>
            <value>
                <fullName>CS - SFDC Dev</fullName>
            </value>
            <value>
                <fullName>CS - TL</fullName>
            </value>
            <value>
                <fullName>Customer Success</fullName>
            </value>
            <value>
                <fullName>DA</fullName>
            </value>
            <value>
                <fullName>Design Engineer</fullName>
            </value>
            <value>
                <fullName>Director, FED</fullName>
            </value>
            <value>
                <fullName>Dir of HR &amp; Recruiting</fullName>
            </value>
            <value>
                <fullName>Employee Bolt Consultant</fullName>
            </value>
            <value>
                <fullName>Exec</fullName>
            </value>
            <value>
                <fullName>FED</fullName>
            </value>
            <value>
                <fullName>FED (GS Labs)</fullName>
            </value>
            <value>
                <fullName>FED (MTX)</fullName>
            </value>
            <value>
                <fullName>FED (Offshore)</fullName>
            </value>
            <value>
                <fullName>Integration Architect</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>OS Dev</fullName>
            </value>
            <value>
                <fullName>OS Dev (MTX)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/pse__Resource_Request__c/fields/pse__Staffer_Resource__c.field-meta.xml
<CustomField>
    <fullName>pse__Staffer_Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This resource will be picked by Staffer for this resource request.</description>
    <label>Resource</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.pse__Is_Resource__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Contact.pse__Is_Resource_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Only active resources are shown. To display all resources, click Show all results.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Resource Requests (Staffer Resource)</relationshipLabel>
    <relationshipName>Resource_Requests2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Resource_Request__c/fields/pse__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__Start_Date__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/pse__Resource_Request__c/fields/pse__Status__c.field-meta.xml
<CustomField>
    <fullName>pse__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Ready to Staff</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Tentative</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/pse__Schedule__c/pse__Schedule__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__ScheduleHelp</customHelpPage>
    <description>Represents start and end dates and weekly working hours for an assignment. You enter schedule details when you create an assignment, which also creates an associated schedule record. Although schedule records have the fields Scheduled Hours and Scheduled Days, these are not intended for users to enter time directly. Their values are system-generated based on schedule dates, patterns, and exceptions. Specific deviations from schedules are represented as schedule exceptions.</description>
    <label>Schedule</label>
    <nameField>
        <displayFormat>Schedule{000000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Schedule__c/fields/pse__Friday_Hours__c.field-meta.xml
<CustomField>
    <fullName>pse__Friday_Hours__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Friday Hours</label>
    <precision>4</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/pse__Schedule__c/fields/pse__Monday_Hours__c.field-meta.xml
<CustomField>
    <fullName>pse__Monday_Hours__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Monday Hours</label>
    <precision>4</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/pse__Schedule__c/fields/pse__Thursday_Hours__c.field-meta.xml
<CustomField>
    <fullName>pse__Thursday_Hours__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Thursday Hours</label>
    <precision>4</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/pse__Schedule__c/fields/pse__Tuesday_Hours__c.field-meta.xml
<CustomField>
    <fullName>pse__Tuesday_Hours__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Tuesday Hours</label>
    <precision>4</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/pse__Schedule__c/fields/pse__Wednesday_Hours__c.field-meta.xml
<CustomField>
    <fullName>pse__Wednesday_Hours__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Wednesday Hours</label>
    <precision>4</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ResourceRequestExtension.cls
public class ResourceRequestExtension {
    public List<pse__Resource_Request__c> resourceRequests { get {
        if(resourceRequests==null) {
            resourceRequests=new List<pse__Resource_Request__c>();
        }
        return resourceRequests;
    } set; }
    public Id opportunityId { get; set; }
    public Opportunity opp { get; set; }
    /*
    public String scheduleHours { get; set; }
    public List<SelectOption> hours { get {
        if(hours==null) {
            hours=new List<SelectOption>();
            hours.add(new SelectOption('10', '10'));
            hours.add(new SelectOption('20', '20'));
            hours.add(new SelectOption('40', '40'));
        }
        return hours;
    } set; }
	*/
    private pse__Region__c region { get{
        if(region==null) {
            region = [SELECT Id FROM pse__Region__c WHERE Name='Global Region'];
        }
        return region;
    } set; }
    
    private String recordOwner { get{
        if(recordOwner==null) {
            try {
                Group g = [SELECT Id, Name FROM Group WHERE Type='Queue' AND Name='Resource Requests' LIMIT 1];
                recordOwner=g.Id;
            } catch (Exception e) {
                recordOwner=UserInfo.getUserId();
            }
        }
        
        return recordOwner;
    } set; }
    
    private Map<String, Contact> genericResources;
    private Decimal hoursPerDay;
    
    public ResourceRequestExtension(ApexPages.standardController controller) {
        opportunityId = controller.getId();
        initializeReqourceRequests();
        opp = [SELECT Id, Name FROM Opportunity WHERE Id =: opportunityId];
        getGenericResources();
    }
    
    public PageReference save() {
        List<pse__Schedule__c> schedules = new List<pse__Schedule__c>();
        List<pse__Resource_Request__c> newRequests = new List<pse__Resource_Request__c>();
        Integer numberOfWeeks = resourceRequests[0].pse__Start_Date__c.daysBetween(resourceRequests[0].pse__End_Date__c)/7;
        
        for(pse__Resource_Request__c resourceRequest : resourceRequests) {
            System.debug('-----------> resourceRequest: ' + resourceRequest);
            resourceRequest.pse__Notes__c=resourceRequests[0].pse__Notes__c;
            resourceRequest.pse__Start_Date__c=resourceRequests[0].pse__Start_Date__c;
            resourceRequest.pse__End_Date__c=resourceRequests[0].pse__End_Date__c;
            resourceRequest.pse__Status__c='Draft';
            if(resourceRequest.Hours_Per_Week__c!=null && resourceRequest.pse__Resource_Role__c==null) {
                ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, 'If hours are entered then resource role must be entered'));
            }
            if(resourceRequest.pse__Resource_Role__c!=null) {
                try {
                    resourceRequest.pse__SOW_Hours__c=Decimal.valueOf(resourceRequest.Hours_Per_Week__c)*numberOfWeeks;
                    hoursPerDay=Decimal.valueOf(resourceRequest.Hours_Per_Week__c)/5;
                } catch (Exception e) {
                    ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, 'Hours per week must be entered if Resource Role is entered'));
                }
                schedules.add(new pse__Schedule__c(pse__Start_Date__c=resourceRequest.pse__Start_Date__c,
                                                   pse__End_Date__c=resourceRequest.pse__End_Date__c,
                                                   pse__Monday_Hours__c=hoursPerDay,
                                                   pse__Tuesday_Hours__c=hoursPerDay,
                                                   pse__Wednesday_Hours__c=hoursPerDay,
                                                   pse__Thursday_Hours__c=hoursPerDay,
                                                   pse__Friday_Hours__c=hoursPerDay));
                
                resourceRequest.pse__Region__c=region.Id;
                resourceRequest.ownerId=recordOwner;
                if(genericResources.containsKey(resourceRequest.pse__Resource_Role__c)) {
                    resourceRequest.pse__Staffer_Resource__c=genericResources.get(resourceRequest.pse__Resource_Role__c).Id;
                } else {
                    ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, 'A generic resource does not exist for the role'));
                }
                newRequests.add(resourceRequest);
                System.debug('-----------> resourceRequest: ' + resourceRequest);
                
            }
        }
        
        if(ApexPages.hasMessages()) {
            return null;
        } else  {  
            if(!schedules.isEMpty()) { insert schedules; }
            
            Integer x=0;
            
            for(pse__Resource_Request__c resourceRequest : newRequests) {
                if(resourceRequest.pse__Resource_Role__c!=null) {
                    resourceRequest.pse__Preferred_Schedule__c=schedules[x].Id;
                }
                x ++;
            }
            
            if(!newRequests.isEmpty()) { insert newRequests; }
            
            
            return new PageReference('/' + opportunityId);
        }
    }
    
    private void initializeReqourceRequests() {
        for(Integer x=0;x<9;x++) {
            resourceRequests.add(new pse__Resource_Request__c(pse__Opportunity__c=opportunityId));
        }
    }
    
    private void getGenericResources() {
        List<Contact> contacts = [SELECT Id, Name, pse__Resource_Role__c FROM Contact WHERE Generic_Resource__c=true];
        genericResources=new Map<String, Contact>();
        for(Contact c : contacts) {
            genericResources.put(c.pse__Resource_Role__c, c);
        }
    }
}