force-app/main/default/objects/Contact/fields/pse__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__Start_Date__c</fullName>
    <description>A Resource&apos;s first date of employment.</description>
    <inlineHelpText>A Resource&apos;s first date of employment.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/pse__Proj__c/pse__Proj__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__ProjectHelp</customHelpPage>
    <description>Represents a collection of business transactions, activities, and related items to be managed over a defined time range, such as timecards, expenses, milestones, and budgets. Typically, people (represented by Resource records) are assigned to projects, though some projects do not require assignments in order to be staffed. Projects may also have a master project (parent) or a sub project (child) in the project hierarchy, supporting roll-ups of revenues, costs, and time to every project and up through the hierarchy.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Proj__c/fields/pse__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/pse__Timecard_Header__c/pse__Timecard_Header__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__TimecardHelp</customHelpPage>
    <description>Records the hours and days worked by a resource in a given week. Timecards are associated with a project and may also be logged against an assignment or milestone, or against one or more project tasks. Resources can submit multiple timecards on the Timecard Entry page, accessed by clicking either “Log a Timecard - New UI” or “Log a Timecard with Task Time” on the PSA Links sidebar (depending on whether your organization logs time against project tasks). This object is named Timecard_Header (API name pse__Timecard_Header__c) and has a master-detail relationship with timecard splits.</description>
    <label>Timecard</label>
    <nameField>
        <displayFormat>TCH-{MM}-{DD}-{YYYY}-{000000}</displayFormat>
        <label>Timecard Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timecards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Timecard_Header__c/fields/pse__Project__c.field-meta.xml
<CustomField>
    <fullName>pse__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>pse__Proj__c</referenceTo>
    <relationshipLabel>Timecards</relationshipLabel>
    <relationshipName>Timecards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Timecard_Header__c/fields/pse__Resource__c.field-meta.xml
<CustomField>
    <fullName>pse__Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.pse__Is_Resource__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Contact.pse__Is_Resource_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Only active resources are shown. To display all resources, click Show all results.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Timecards</relationshipLabel>
    <relationshipName>Timecards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Timecard_Header__c/fields/pse__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__Start_Date__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/X7STimeOffItem__mdt/X7STimeOffItem__mdt.object-meta.xml
<CustomObject>
    <label>7S Time Off Item</label>
    <pluralLabel>7S Time Off Items</pluralLabel>
</CustomObject>

force-app/main/default/objects/X7STimeOffItem__mdt/fields/Allocation__c.field-meta.xml
<CustomField>
    <fullName>Allocation__c</fullName>
    <label>Allocation</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/x7S_PTODashboardController.cls
public without sharing class x7S_PTODashboardController {
    
    private List<X7STimeOffItem__mdt> timeOffItems {
        get {
            return [SELECT MasterLabel, Allocation__c FROM X7STimeOffItem__mdt ORDER BY Sequence__c];
        }
    }
    
    private Id contactId;
    
    public class TimeOffItem {
        public String itemName { get; set; }
        public Double hoursAllocated { get; set; }
        public Double hoursUsed { get; set; }
        public Double hoursScheduled { get; set; }
        public Double hoursRemaining { get; set; }
    }
    
    public List<TimeOffItem> timeoffItemDetails { get; set; }
    
    public x7S_PTODashboardController(ApexPages.StandardController stdController) {
        contactId=stdController.getId();
        Contact c = [SELECT pse__Start_Date__c FROM Contact WHERE Id=:contactId];
        timeoffItemDetails = new List<TimeOffItem>();
        System.debug(timeOffItems);
        if(!timeOffItems.isEmpty() && c.pse__Start_Date__c != null) {
            for(X7STimeOffItem__mdt toi : timeOffItems) {
                TimeOffItem ti = new TimeOffItem();
                ti.itemName = toi.MasterLabel;
                ti.hoursAllocated=toi.Allocation__c;
                Double startDayOfTheYear=c.pse__Start_Date__c.dayOfYear();
                Date apr1 = Date.newInstance(2021, 04, 01);
                Double divisor=365;
                if(c.pse__Start_Date__c.year()==System.today().year()) { 
                    
                    if(System.today().year()==2021 && c.pse__Start_Date__c>apr1) { 
                        divisor = divisor-apr1.dayOfYear();
                        startDayOfTheYear = startDayOfTheYear-apr1.dayOfYear();
                        
                        System.debug('---------> startDayOfTheYear: ' + startDayOfTheYear + '    ---------> divisor:' + divisor);

                        System.debug('---------> hoursAllocated: ' + ti.hoursAllocated);
                        ti.hoursAllocated=ti.hoursAllocated*(1-(startDayOfTheYear/divisor)); 
                    } else {
                        System.debug('---------> startDayOfTheYear: ' + startDayOfTheYear + '    ---------> divisor:' + divisor);
                        System.debug('---------> hoursAllocated: ' + ti.hoursAllocated);
                        //ti.hoursAllocated=ti.hoursAllocated*((365-startDayOfTheYear)/divisor);
                        ti.hoursAllocated=ti.hoursAllocated;

                    }
                } else {
                    ti.hoursAllocated=ti.hoursAllocated;
                }
                    
                ti.hoursUsed = getHoursForType(toi.MasterLabel, true);
                ti.hoursScheduled = getHoursForType(toi.MasterLabel, false);
                ti.hoursRemaining = ti.hoursAllocated-ti.hoursUsed-ti.hoursScheduled;
                if(ti.hoursRemaining<0.0) { ti.hoursRemaining=0.0; }
                timeoffItemDetails.add(ti);
            }
        }
        System.debug(timeoffItemDetails);
    }
    
    
    private double getHoursForType(String timeOffType, boolean used) {
        double hours=0.0;
        AggregateResult [] hoursForType;
        if(used) {
            Date integrationDate=Date.newInstance(2021, 4, 1);
            hoursForType = [SELECT SUM(pse__Total_Hours__c) TotalHours 
                            FROM pse__Timecard_Header__c 
                            WHERE pse__Resource__c=:contactId 
                            AND pse__Project__r.Name =: timeOffType
                            AND pse__Start_Date__c=THIS_YEAR
                            AND pse__Start_Date__c>=:integrationDate
                            AND pse__Start_Date__c<=TODAY];
        } else {
            hoursForType = [SELECT SUM(pse__Total_Hours__c) TotalHours 
                            FROM pse__Timecard_Header__c 
                            WHERE pse__Resource__c=:contactId 
                            AND pse__Project__r.Name =: timeOffType
                            AND pse__Start_Date__c=THIS_YEAR
                            AND pse__Start_Date__c>TODAY];
        }
        
        if(hoursForType != null && (Double)hoursForType[0].get('TotalHours') != null) { 
            hours = (Double)hoursForType[0].get('TotalHours'); 
        } else {
            hours=0.0;
        }
        
        return hours;
    }
}