force-app/main/default/objects/Contact/fields/pse__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__Start_Date__c</fullName>
    <description>A Resource&apos;s first date of employment.</description>
    <inlineHelpText>A Resource&apos;s first date of employment.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/pse__Assignment__c/pse__Assignment__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__AssignmentAndScheduleHelp</customHelpPage>
    <description>Stores information about the allocation of a resource to a project and specifies the bill rate and cost rate for time entered. It references the schedule for a resource and, optionally, a project milestone.</description>
    <label>Assignment</label>
    <nameField>
        <label>Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Assignment__c/fields/pse__Closed_for_Time_Entry__c.field-meta.xml
<CustomField>
    <fullName>pse__Closed_for_Time_Entry__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, indicates that Timecards may no longer be entered for this Assignment.  Is checked automatically when the Assignment&apos;s Project is Closed for Time Entry.</description>
    <label>Closed for Time Entry</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/pse__Assignment__c/fields/pse__End_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__End_Date__c</fullName>
    <formula>pse__Schedule__r.pse__End_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/pse__Assignment__c/fields/pse__Is_Billable__c.field-meta.xml
<CustomField>
    <fullName>pse__Is_Billable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Billable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/pse__Assignment__c/fields/pse__Project__c.field-meta.xml
<CustomField>
    <fullName>pse__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>pse__Proj__c</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Assignment__c/fields/pse__Resource__c.field-meta.xml
<CustomField>
    <fullName>pse__Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.pse__Is_Resource__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Contact.pse__Is_Resource_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Only active resources are shown. To display all resources, click Show all results.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Assignment__c/fields/pse__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__Start_Date__c</fullName>
    <formula>pse__Schedule__r.pse__Start_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/pse__Assignment__c/fields/pse__Time_Credited__c.field-meta.xml
<CustomField>
    <fullName>pse__Time_Credited__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This checkbox should be checked for non-billable Assignments for which hours are credited towards utilization.</description>
    <inlineHelpText>This checkbox should be checked for non-billable Assignments for which hours are credited towards utilization.</inlineHelpText>
    <label>Time Credited</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/pse__Proj__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__ProjectHelp</customHelpPage>
    <description>Represents a collection of business transactions, activities, and related items to be managed over a defined time range, such as timecards, expenses, milestones, and budgets. Typically, people (represented by Resource records) are assigned to projects, though some projects do not require assignments in order to be staffed. Projects may also have a master project (parent) or a sub project (child) in the project hierarchy, supporting roll-ups of revenues, costs, and time to every project and up through the hierarchy.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Proj__c/fields/pse__Closed_for_Time_Entry__c.field-meta.xml
<CustomField>
    <fullName>pse__Closed_for_Time_Entry__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Closed for Time Entry</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__End_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Is_Billable__c.field-meta.xml
<CustomField>
    <fullName>pse__Is_Billable__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check if this project is billable to a customer.</inlineHelpText>
    <label>Billable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Project_Manager__c.field-meta.xml
<CustomField>
    <fullName>pse__Project_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Person responsible for this project (optional). If not provided, it&apos;s assumed that the record Owner is the project manager.</description>
    <label>Project Manager</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.pse__Is_Resource__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Contact.pse__Is_Resource_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Only active resources are shown. To display all resources, click Show all results.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects Managed</relationshipLabel>
    <relationshipName>ProjectsManaged</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Project_Status__c.field-meta.xml
<CustomField>
    <fullName>pse__Project_Status__c</fullName>
    <description>Select the current project status from the picklist. Alternatively, use Process Builder or workflow rules to use your own logic to control the behavior of the corresponding color indicator field.</description>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Green</fullName>
                <color>#009900</color>
                <default>true</default>
                <label>Green</label>
            </value>
            <value>
                <fullName>Yellow</fullName>
                <color>#FFFF66</color>
                <label>Yellow</label>
            </value>
            <value>
                <fullName>Red</fullName>
                <color>#FF0000</color>
                <label>Red</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Stage__c.field-meta.xml
<CustomField>
    <fullName>pse__Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Prepare</fullName>
            </value>
            <value>
                <fullName>Define</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Build</fullName>
            </value>
            <value>
                <fullName>Verify</fullName>
            </value>
            <value>
                <fullName>Launch</fullName>
            </value>
            <value>
                <fullName>Close-Out</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Time_Credited__c.field-meta.xml
<CustomField>
    <fullName>pse__Time_Credited__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This checkbox should be checked for non-billable projects for which consulting time is credited towards utilization.</description>
    <inlineHelpText>This checkbox should be checked for non-billable projects for which consulting time is credited towards utilization.</inlineHelpText>
    <label>Time Credited</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/x7S_MyProjectsController.cls
public class x7S_MyProjectsController {

    @AuraEnabled
    public static String getContactId(String userId) {
        String contactId = null;

        if (userId == '') {
            userId = UserInfo.getUserId();
        }
        
        contactId = [SELECT ID FROM Contact WHERE pse__Salesforce_User__c = :userId].Id;
        
        return contactId;
    }
    
    @AuraEnabled
    public static List<SObject> getMyProjects(String userId) {

        List<SObject> myProjectsList = new List<SObject>();
        
        String contactId = x7S_MyProjectsController.getContactId(userId);

        
        if (contactId != null) {
        myProjectsList = [SELECT    pse__Project__r.pse__Project_Status__c,
                                    pse__Project__r.Id,
                                    pse__Project__r.Name,
                                    pse__Project__r.pse__Stage__c,
                pse__Project__r.pse__Project_Manager__c,
                pse__Project__r.pse__Project_Manager__r.pse__Salesforce_User__c,
                                    pse__Project__r.pse__Project_Manager__r.FirstName,
                                    pse__Project__r.pse__Project_Manager__r.LastName
                          FROM pse__Assignment__c
                          WHERE pse__Resource__c = :contactId
                            AND Project_Stage__c != 'Closed'
                            AND Project_Stage__c != 'Completed'
                            AND pse__Start_Date__c <= NEXT_N_WEEKS:2
                            AND pse__End_Date__c >= NEXT_N_WEEKS:2
                            AND (pse__Time_Credited__c = TRUE
                                    OR pse__Is_Billable__c = TRUE)
                            AND pse__Closed_for_Time_Entry__c = FALSE
        GROUP BY    pse__Project__r.pse__Project_Status__c,
                                    pse__Project__r.Id,
                                    pse__Project__r.Name,
                                    pse__Project__r.pse__Stage__c,
                                  pse__Project__r.pse__Project_Manager__c,
                                  pse__Project__r.pse__Project_Manager__r.pse__Salesforce_User__c,
                                  pse__Project__r.pse__Project_Manager__r.FirstName,
                                  pse__Project__r.pse__Project_Manager__r.LastName,
                pse__Start_Date__c
        ORDER BY pse__Start_Date__c];
        }

        System.debug(myProjectsList);
        return myProjectsList;
    }
    
}