force-app/main/default/objects/Contact/fields/pse__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__Start_Date__c</fullName>
    <description>A Resource&apos;s first date of employment.</description>
    <inlineHelpText>A Resource&apos;s first date of employment.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/pse__Assignment__c/pse__Assignment__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__AssignmentAndScheduleHelp</customHelpPage>
    <description>Stores information about the allocation of a resource to a project and specifies the bill rate and cost rate for time entered. It references the schedule for a resource and, optionally, a project milestone.</description>
    <label>Assignment</label>
    <nameField>
        <label>Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Assignment__c/fields/pse__Bill_Rate__c.field-meta.xml
<CustomField>
    <fullName>pse__Bill_Rate__c</fullName>
    <inlineHelpText>Enter the hourly bill rate for the resource</inlineHelpText>
    <label>Bill Rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/pse__Assignment__c/fields/pse__End_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__End_Date__c</fullName>
    <formula>pse__Schedule__r.pse__End_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/pse__Assignment__c/fields/pse__Is_Billable__c.field-meta.xml
<CustomField>
    <fullName>pse__Is_Billable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Billable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/pse__Assignment__c/fields/pse__Milestone__c.field-meta.xml
<CustomField>
    <fullName>pse__Milestone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If an Assignment is associated with a Milestone, Timecards logged for that Assignment will, by default, also be associated with the Milestone on the Assignment at the time.</description>
    <inlineHelpText>If an Assignment is associated with a Milestone, Timecards logged for that Assignment will, by default, also be associated with the Milestone on the Assignment at the time.</inlineHelpText>
    <label>Milestone</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>pse__Milestone__c.pse__Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.pse__Project__c</valueField>
        </filterItems>
        <infoMessage>Only milestones for the same project are shown. To display all milestones, click Show all results.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>pse__Milestone__c</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Assignment__c/fields/pse__Project__c.field-meta.xml
<CustomField>
    <fullName>pse__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>pse__Proj__c</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Assignment__c/fields/pse__Resource__c.field-meta.xml
<CustomField>
    <fullName>pse__Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.pse__Is_Resource__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Contact.pse__Is_Resource_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Only active resources are shown. To display all resources, click Show all results.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Assignment__c/fields/pse__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__Start_Date__c</fullName>
    <formula>pse__Schedule__r.pse__Start_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/pse__Est_Vs_Actuals__c/pse__Est_Vs_Actuals__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__EstimateVsActualsHelp</customHelpPage>
    <description>Compares the estimated and actual hours worked by a resource on an assignment, derived from scheduled hours and entered timecard hours respectively. FinancialForce PSA generates Est Vs Actuals when you create or update assignments and schedules, and when timecard hours are entered for an assignment.</description>
    <label>Est Vs Actuals</label>
    <nameField>
        <label>Est Vs Actuals Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Est Vs Actuals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Est_Vs_Actuals__c/fields/Baseline_Estimated_Hours__c.field-meta.xml
<CustomField>
    <fullName>Baseline_Estimated_Hours__c</fullName>
    <label>Baseline Estimated Hours</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/pse__Est_Vs_Actuals__c/fields/pse__Assignment__c.field-meta.xml
<CustomField>
    <fullName>pse__Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assignment</label>
    <referenceTo>pse__Assignment__c</referenceTo>
    <relationshipLabel>Est Vs Actuals</relationshipLabel>
    <relationshipName>Est_Vs_Actuals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Est_Vs_Actuals__c/fields/pse__End_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__End_Date__c</fullName>
    <description>End date of the time period for this record. This should not be confused with the end date of the associated assignment or timecards.</description>
    <inlineHelpText>End date of the time period for this record. This should not be confused with the end date of the associated assignment or timecards.</inlineHelpText>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/pse__Est_Vs_Actuals__c/fields/pse__Project__c.field-meta.xml
<CustomField>
    <fullName>pse__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>pse__Proj__c</referenceTo>
    <relationshipLabel>Est Vs Actuals</relationshipLabel>
    <relationshipName>Est_Vs_Actuals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Est_Vs_Actuals__c/fields/pse__Resource__c.field-meta.xml
<CustomField>
    <fullName>pse__Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Linked to the resource record for the assignment. This allows for easier workflow alerts to be sent</description>
    <label>Resource</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Est Vs Actuals</relationshipLabel>
    <relationshipName>Est_Vs_Actuals_Resource</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Est_Vs_Actuals__c/fields/pse__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__Start_Date__c</fullName>
    <description>Start date of the time period for this record. This should not be confused with the start date of the associated assignment or timecards.</description>
    <inlineHelpText>Start date of the time period for this record. This should not be confused with the start date of the associated assignment or timecards.</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/pse__Est_Vs_Actuals__c/fields/pse__Time_Period_Type__c.field-meta.xml
<CustomField>
    <fullName>pse__Time_Period_Type__c</fullName>
    <description>The type of time period this time span represents</description>
    <inlineHelpText>The type of time period this time span represents</inlineHelpText>
    <label>Time Period Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Week</fullName>
            </value>
            <value>
                <fullName>Month</fullName>
            </value>
            <value>
                <fullName>Quarter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/pse__Expense__c/pse__Expense__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__ExpenseHelp</customHelpPage>
    <description>Sometimes called an expense line or row. Represents a record of an expense incurred by a resource assigned to a project or opportunity. Expenses are grouped into an expense report for submission and approval, and may be subject to limits or rates depending on type (for example, Lodging, Auto Mileage). An expense may be billable or non-billable. Unless marked otherwise, all expenses contain a reimbursable amount for the resource. Expenses have a lookup relationship to expense reports.</description>
    <label>Expense</label>
    <nameField>
        <displayFormat>EXP-{0}</displayFormat>
        <label>Expense Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Expense__c/fields/pse__Amount__c.field-meta.xml
<CustomField>
    <fullName>pse__Amount__c</fullName>
    <description>The amount of this expense (in the expense&apos;s incurred currency)</description>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/pse__Expense__c/fields/pse__Assignment__c.field-meta.xml
<CustomField>
    <fullName>pse__Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assignment</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>pse__Assignment__c.pse__Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.pse__Project__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>pse__Assignment__c</referenceTo>
    <relationshipName>Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Expense__c/fields/pse__Milestone__c.field-meta.xml
<CustomField>
    <fullName>pse__Milestone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Milestone</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>pse__Milestone__c.pse__Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.pse__Project__c</valueField>
        </filterItems>
        <infoMessage>The milestones of the related project are shown initially.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>pse__Milestone__c</referenceTo>
    <relationshipName>Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Expense__c/fields/pse__Project__c.field-meta.xml
<CustomField>
    <fullName>pse__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>pse__Proj__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Expense__c/fields/pse__Resource__c.field-meta.xml
<CustomField>
    <fullName>pse__Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.pse__Is_Resource__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Contact.pse__Is_Resource_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Only active resources are shown. To display all resources, click Show all results.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Milestone__c/pse__Milestone__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__MilestoneHelp</customHelpPage>
    <description>A target event used to track project progress. In Time and Materials (T&amp;M) projects, individual milestone records are generally not billable, whereas in Fixed Price or mixed projects all or some generally are. You can group together timecards and expenses, submitted by assigned resources, with milestones on the same project, or associate milestones with a fixed external cost. Milestones have a linear (non-hierarchical) relationship with one another.</description>
    <label>Milestone</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Milestone__c/fields/pse__Project__c.field-meta.xml
<CustomField>
    <fullName>pse__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>pse__Proj__c</referenceTo>
    <relationshipLabel>Milestones</relationshipLabel>
    <relationshipName>Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Milestone__c/fields/pse__Target_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__Target_Date__c</fullName>
    <label>Target Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/pse__Proj__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__ProjectHelp</customHelpPage>
    <description>Represents a collection of business transactions, activities, and related items to be managed over a defined time range, such as timecards, expenses, milestones, and budgets. Typically, people (represented by Resource records) are assigned to projects, though some projects do not require assignments in order to be staffed. Projects may also have a master project (parent) or a sub project (child) in the project hierarchy, supporting roll-ups of revenues, costs, and time to every project and up through the hierarchy.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Proj__c/fields/pse__End_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Stage__c.field-meta.xml
<CustomField>
    <fullName>pse__Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Prepare</fullName>
            </value>
            <value>
                <fullName>Define</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Build</fullName>
            </value>
            <value>
                <fullName>Verify</fullName>
            </value>
            <value>
                <fullName>Launch</fullName>
            </value>
            <value>
                <fullName>Close-Out</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ProjectStatisticsExtension.cls
public class ProjectStatisticsExtension {
    public class PhaseSummary {
        public String milestone { get; set; }
        public Date startDate { get; set; }
        public Date endDate { get; set; }
        public Decimal sowHours { get; set; }
        public Decimal sowDollars { get; set; }
        public Decimal estHours { get; set; }
        public Decimal estDollars { get; set; }
        public Decimal actualHours { get; set; }
        public Decimal actualDollars { get; set; }
        public Decimal etcHours { get; set; }
        public Decimal etcDollars { get; set; }
        public Decimal eacHours { get; set; }
        public Decimal eacDollars { get; set; }
        public Decimal varianceHours { get; set; }
        public Decimal varianceDollars { get; set; }
        public Decimal expenses { get; set; }
        
        public void init() {
            sowHours=0.0;
            sowDollars=0.0;
            estHours=0.0;
            estDollars=0.0;
            actualHours=0.0;
            actualDollars=0.0;
            etcHours=0.0;
            etcDollars=0.0;
            eacHours=0.0;
            eacDollars=0.0;
            varianceHours=0.0;
            varianceDollars=0.0;
            expenses=0.0;
        }
    }
    
    public pse__Proj__c project { get; set; }
    public List<PhaseSummary> phases { get; set; }
    public PhaseSummary nonBill { get; set; }
    public PhaseSummary projectTotals { get; set; }
    public Id projectId { get; set; }
    public PhaseSummary totals { get; set; }
    
    public ProjectStatisticsExtension(ApexPages.standardController standardController) {
        this.projectId = standardController.getId();
        this.project = [SELECT Id, pse__Start_Date__c, pse__End_Date__c, pse__Project_Id__c, pse__Stage__c FROM pse__Proj__c WHERE Id =: projectId];
        System.debug('-------- projectId: ' + projectId);
    }
    
    public List<PhaseSummary> getPhaseSummary() {
        
        phases = new List<PhaseSummary>();
        totals = new PhaseSummary();
        totals.milestone = 'Billable Totals';
        totals.init();
        
        nonBill = new PhaseSummary();
        nonBill.milestone = 'Non-Billable Totals';
        nonBill.init();
        
        projectTotals = new PhaseSummary();
        projectTotals.milestone = 'Project Totals';
        projectTotals.init();
        
        List<pse__Milestone__c> milestones = [SELECT Id, Name, pse__Target_Date__c FROM pse__Milestone__c WHERE pse__Project__c =: projectId ORDER BY pse__Target_Date__c];
        
        Integer currentRow=0;
        Date targetDate;
        for(pse__Milestone__c milestone : milestones) {
            PhaseSummary ps = new PhaseSummary();
            ps.milestone=milestone.Name;
            if(currentRow == 0) {
                ps.startDate=project.pse__Start_Date__c;
            } else {
                ps.startDate=targetDate;
            }
            targetDate=milestone.pse__Target_Date__c;
            ps.endDate=milestone.pse__Target_Date__c;
            
            ps.init();
            
            phases.add(ps);
            currentRow ++;
        }
        
        phases[phases.size()-1].endDate = project.pse__End_Date__c;
        if(project.pse__Stage__c!='Completed' && project.pse__Stage__c!='Close-Out') {
            phases[phases.size()-1].endDate = project.pse__End_Date__c.addDays(365);
        }
        
        getBillableData();
        getNonBillableData();
        getProjectTotals();
        
        return phases;
    }
    
    private void getBillableData() {
        AggregateResult [] expenses = [SELECT pse__Milestone__r.Name Milestone, SUM(pse__Amount__c) Amount 
                                       FROM pse__Expense__c 
                                       WHERE pse__Project__c =: projectId 
                                       GROUP BY pse__Milestone__r.Name 
                                       ORDER BY pse__Milestone__r.Name];
        
        Map<String, Decimal> expenseMap = new Map<String, Decimal>();
        for(AggregateResult expense : expenses) {
            expenseMap.put((String)expense.get('Milestone'), (Decimal)expense.get('Amount'));
        }
        
        for(PhaseSummary phase : phases){
            System.debug('-------- phase.startDate: ' + phase.startDate + ' - ' + phase.endDate);
            
            AggregateResult [] sowHours = [SELECT pse__Resource__r.Name Resource, MAX(pse__Assignment__r.pse__Bill_Rate__c) BillRate, SUM(Baseline_Estimated_Hours__c) BaselineHours
                                           FROM pse__Est_Vs_Actuals__c 
                                           WHERE pse__Project__c =: projectId AND pse__Start_Date__c >=: phase.startDate AND pse__End_Date__c <=: phase.endDate
                                           AND pse__Time_Period_Type__c='Week' AND pse__Assignment__r.pse__is_Billable__c=true AND Baseline_Estimated_Hours__c != null
                                           GROUP BY pse__Resource__r.Name];
            
            AggregateResult [] estHours = [SELECT pse__Resource__r.Name Resource, MAX(pse__Assignment__r.pse__Bill_Rate__c) BillRate, SUM(pse__Estimated_Hours__c) EstimatedHours
                                           FROM pse__Est_Vs_Actuals__c 
                                           WHERE pse__Project__c =: projectId AND pse__Start_Date__c >=: phase.startDate AND pse__End_Date__c <=: phase.endDate
                                           AND pse__Time_Period_Type__c='Week' AND pse__Assignment__r.pse__is_Billable__c=true
                                           GROUP BY pse__Resource__r.Name];
            
            AggregateResult [] actHours = [SELECT pse__Resource__r.Name Resource, MAX(pse__Assignment__r.pse__Bill_Rate__c) BillRate, SUM(pse__Actual_Hours__c) ActualHours
                                           FROM pse__Est_Vs_Actuals__c 
                                           WHERE pse__Project__c =: projectId AND pse__Start_Date__c >=: phase.startDate AND pse__End_Date__c <=: phase.endDate
                                           AND pse__Time_Period_Type__c='Week' AND pse__Assignment__r.pse__is_Billable__c=true
                                           GROUP BY pse__Resource__r.Name];
            
            System.debug('-------- sow: ' + sowHours);
            System.debug('-------- est: ' + estHours);
            System.debug('-------- act: ' + actHours);
            
            for(AggregateResult sow : sowHours) {
                phase.sowHours += (Decimal)sow.get('BaselineHours'); 
                phase.sowDollars += (Decimal)sow.get('BaselineHours')*(Decimal)sow.get('BillRate');
            }
            for(AggregateResult est : estHours) {
                phase.estHours += (Decimal)est.get('EstimatedHours');
                phase.estDollars += (Decimal)est.get('EstimatedHours')*(Decimal)est.get('BillRate');
            }
            for(AggregateResult act : actHours) {
                phase.actualHours += (Decimal)act.get('ActualHours');
                phase.actualDollars += (Decimal)act.get('ActualHours')*(Decimal)act.get('BillRate');
            }
            if(System.today()<=phase.endDate) {
                phase.etcHours += (phase.estHours-phase.actualHours);
                phase.etcDollars += (phase.estDollars-phase.actualDollars);
            }
            
            phase.eacHours += (phase.actualHours+phase.etcHours);
            phase.eacDollars += (phase.actualDollars+phase.etcDollars);
            
            phase.varianceHours += (phase.eacHours-phase.sowHours);
            phase.varianceDollars += (phase.eacDollars-phase.sowDollars);
            if(expenseMap.containsKey(phase.milestone)) { phase.expenses = expenseMap.get(phase.milestone); }
            
            totals.sowHours += phase.sowHours;
            totals.sowDollars += phase.sowDollars;
            totals.estHours += phase.estHours;
            totals.estDollars += phase.estDollars;
            totals.actualHours += phase.actualHours;
            totals.actualDollars += phase.actualDollars;
            totals.etcHours += phase.etcHours;
            totals.etcDollars += phase.etcDollars;
            totals.eacHours += phase.eacHours;
            totals.eacDollars += phase.eacDollars;
            totals.varianceHours += phase.varianceHours;
            totals.varianceDollars += phase.varianceDollars;
            totals.expenses += phase.expenses;
        }
        
        System.debug(phases);
    }
    
    private void getNonBillableData() {
        Date endDate = project.pse__End_Date__c.addDays(365);
        AggregateResult [] sowHours = [SELECT pse__Resource__r.Name Resource, MAX(pse__Assignment__r.pse__Cost_Rate_Amount__c) BillRate, SUM(Baseline_Estimated_Hours__c) BaselineHours
                                       FROM pse__Est_Vs_Actuals__c 
                                       WHERE pse__Project__c =: projectId AND pse__Start_Date__c >=: project.pse__Start_Date__c AND pse__End_Date__c <=: endDate
                                       AND pse__Time_Period_Type__c='Week' AND pse__Assignment__r.pse__is_Billable__c=false AND Baseline_Estimated_Hours__c != null
                                       GROUP BY pse__Resource__r.Name];
        
        AggregateResult [] estHours = [SELECT pse__Resource__r.Name Resource, MAX(pse__Assignment__r.pse__Cost_Rate_Amount__c) BillRate, SUM(pse__Estimated_Hours__c) EstimatedHours
                                       FROM pse__Est_Vs_Actuals__c 
                                       WHERE pse__Project__c =: projectId AND pse__Start_Date__c >=: project.pse__Start_Date__c AND pse__End_Date__c <=: endDate
                                       AND pse__Time_Period_Type__c='Week' AND pse__Assignment__r.pse__is_Billable__c=false
                                       GROUP BY pse__Resource__r.Name];
        
        AggregateResult [] actHours = [SELECT pse__Resource__r.Name Resource, MAX(pse__Assignment__r.pse__Cost_Rate_Amount__c) BillRate, SUM(pse__Actual_Hours__c) ActualHours
                                       FROM pse__Est_Vs_Actuals__c 
                                       WHERE pse__Project__c =: projectId AND pse__Start_Date__c >=: project.pse__Start_Date__c AND pse__End_Date__c <=: endDate
                                       AND pse__Time_Period_Type__c='Week' AND pse__Assignment__r.pse__is_Billable__c=false
                                       GROUP BY pse__Resource__r.Name];
        
        System.debug('-------- sow: ' + sowHours);
        System.debug('-------- est: ' + estHours);
        System.debug('-------- act: ' + actHours);
        
        for(AggregateResult sow : sowHours) {
            nonBill.sowHours += (Decimal)sow.get('BaselineHours'); 
            nonBill.sowDollars += (Decimal)sow.get('BaselineHours')*(Decimal)sow.get('BillRate');
        }
        for(AggregateResult est : estHours) {
            nonBill.estHours += (Decimal)est.get('EstimatedHours');
            nonBill.estDollars += (Decimal)est.get('EstimatedHours')*(Decimal)est.get('BillRate');
        }
        for(AggregateResult act : actHours) {
            nonBill.actualHours += (Decimal)act.get('ActualHours');
            nonBill.actualDollars += (Decimal)act.get('ActualHours')*(Decimal)act.get('BillRate');
        }
        
        nonBill.etcHours += (nonBill.estHours-nonBill.actualHours);
        nonBill.etcDollars += (nonBill.estDollars-nonBill.actualDollars);
        
        nonBill.eacHours += (nonBill.actualHours+nonBill.etcHours);
        nonBill.eacDollars += (nonBill.actualDollars+nonBill.etcDollars);
        
        nonBill.varianceHours += (nonBill.eacHours-nonBill.sowHours);
        nonBill.varianceDollars += (nonBill.eacDollars-nonBill.sowDollars);
    }
    
    private void getProjectTotals() {
        projectTotals.sowHours += totals.sowHours+nonBill.sowHours;
        projectTotals.sowDollars += totals.sowDollars+nonBill.sowDollars;
        projectTotals.estHours += totals.estHours+nonBill.estHours;
        projectTotals.estDollars += totals.estDollars+nonBill.estDollars;
        projectTotals.actualHours += totals.actualHours+nonBill.actualHours;
        projectTotals.actualDollars += totals.actualDollars+nonBill.actualDollars;
        projectTotals.etcHours += totals.etcHours+nonBill.etcHours;
        projectTotals.etcDollars += totals.etcDollars+nonBill.etcDollars;
        projectTotals.eacHours += totals.eacHours+nonBill.eacHours;
        projectTotals.eacDollars += totals.eacDollars+nonBill.eacDollars;
        projectTotals.varianceHours += totals.varianceHours+nonBill.varianceHours;
        projectTotals.varianceDollars += totals.varianceDollars+nonBill.varianceDollars;
        projectTotals.expenses += totals.expenses+nonBill.expenses;
    }
}