force-app/main/default/objects/Jira_Status_Mapping_Template__mdt/Jira_Status_Mapping_Template__mdt.object-meta.xml
<CustomObject>
    <label>Jira Status Mapping Template</label>
    <pluralLabel>Jira Status Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Jira_Status_Mapping_Template__mdt/fields/Copado_Status__c.field-meta.xml
<CustomField>
    <fullName>Copado_Status__c</fullName>
    <label>Copado Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Backlog</fullName>
            </value>
            <value>
                <fullName>Backburner</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Ready for Testing</fullName>
            </value>
            <value>
                <fullName>Ready for Dev</fullName>
            </value>
            <value>
                <fullName>Ready for QA</fullName>
            </value>
            <value>
                <fullName>Ready for UAT</fullName>
            </value>
            <value>
                <fullName>Ready for Production</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Jira_Status_Mapping_Template__mdt/fields/ExternalValue__c.field-meta.xml
<CustomField>
    <fullName>ExternalValue__c</fullName>
    <label>External Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Jira_Status_Mapping_Template__mdt/fields/SyncDirection__c.field-meta.xml
<CustomField>
    <fullName>SyncDirection__c</fullName>
    <label>Sync Direction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inbound</fullName>
                <default>true</default>
                <label>Inbound</label>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
            <value>
                <fullName>Ignore</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/JiraStatusMapping__c/JiraStatusMapping__c.object-meta.xml
<CustomObject>
    <label>Jira Status Mapping</label>
    <nameField>
        <displayFormat>JSM-{000000}</displayFormat>
        <label>Mapping Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jira Status Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/JiraStatusMapping__c/fields/CopadoStatus__c.field-meta.xml
<CustomField>
    <fullName>CopadoStatus__c</fullName>
    <description>Copado User Story Status</description>
    <inlineHelpText>Copado User Story Status</inlineHelpText>
    <label>Copado Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>User_Story_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/JiraStatusMapping__c/fields/ExternalValue__c.field-meta.xml
<CustomField>
    <fullName>ExternalValue__c</fullName>
    <description>Value from the external external system</description>
    <inlineHelpText>Value from the external external system</inlineHelpText>
    <label>External Value</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JiraStatusMapping__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>Project associated with the mapping record</description>
    <inlineHelpText>Project associated with the mapping record</inlineHelpText>
    <label>Project</label>
    <referenceTo>copado__Project__c</referenceTo>
    <relationshipLabel>Jira Status Mappings</relationshipLabel>
    <relationshipName>JiraStatusMappings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/JiraStatusMapping__c/fields/SyncDirection__c.field-meta.xml
<CustomField>
    <fullName>SyncDirection__c</fullName>
    <description>Identifies if the record is to be used for inbound synchronizations (External Sync Button), outbound synchronizations or ignored</description>
    <inlineHelpText>Identifies if the record is to be used for inbound synchronizations (External Sync Button), outbound synchronizations or ignored</inlineHelpText>
    <label>Sync Direction</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
            <value>
                <fullName>Ignore</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/User_Story_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Backlog</fullName>
    </customValue>
    <customValue>
        <fullName>Bakcburner</fullName>
    </customValue>
    <customValue>
        <fullName>Awaiting Approval</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Ready for Testing</fullName>
    </customValue>
    <customValue>
        <fullName>Ready for Dev</fullName>
    </customValue>
    <customValue>
        <fullName>Ready for QA</fullName>
    </customValue>
    <customValue>
        <fullName>Ready for UAT</fullName>
    </customValue>
    <customValue>
        <fullName>Ready for Production</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Done</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>To Do</fullName>
    </customValue>
    <masterLabel>User Story Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ALMStatusMappingHandler.cls
public abstract class ALMStatusMappingHandler {
    
    public static Map<String, String> statusXRef;
    
    public static String getALMStatus(String statusIn) {
        if(statusXref == null) { getStatusXrefForExternalALM(); }
        return lookupStatus(statusIn);
    }
    
    public static String getALMStatus(String storyId, String statusIn) {
        if(statusXref == null) { getStatusXrefForExternalALM(StoryId); }
        return lookupStatus(statusIn);
    }
    
    public static String getCopadoStatus(String statusIn) {
        if(statusXref == null) { getStatusXrefForCopado(); }
        return lookupStatus(statusIn);
    }
    
    public static String getCopadoStatus(String storyId, String statusIn) {
        if(statusXref == null) { getStatusXrefForCopado(storyId); }
        return lookupStatus(statusIn);
    }
    
    @testvisible
    private static String lookupStatus(String statusIn) {
        if(statusXref.containsKey(statusIn)) {
            return statusXRef.get(statusIn);
        } else {
            return statusIn;
        }
    }
    
    @testvisible
    private static void getStatusXrefForExternalALM() {
        System.debug('building statusXref');
        
        statusXRef = new Map<String, String>();
        List<Jira_Status_Mapping_Template__mdt> statusList = [SELECT Copado_Status__c, ExternalValue__c 
                                                              FROM Jira_Status_Mapping_Template__mdt
                                                              WHERE SyncDirection__c='Outbound'];
        
        if(Test.isRunningTest()) { statusXref.put('Approved', 'To Do'); }
        for(Jira_Status_Mapping_Template__mdt status : statusList) {
            if(!statusXRef.containsKey(status.Copado_Status__c)) { statusXref.put(status.Copado_Status__c, status.ExternalValue__c); }
        }
    }
    
    @testvisible
    private static void getStatusXrefForExternalALM(String storyId) {
        System.debug('building statusXref');
        
        statusXRef = new Map<String, String>();
        List<JiraStatusMapping__c> statusList = [SELECT CopadoStatus__c, ExternalValue__c 
                                                 FROM JiraStatusMapping__c
                                                 WHERE Project__c =: storyId AND SyncDirection__c='Outbound'];
        
        if(Test.isRunningTest()) { statusXref.put('Approved', 'To Do'); }
        for(JiraStatusMapping__c status : statusList) {
            if(!statusXRef.containsKey(status.CopadoStatus__c)) { statusXref.put(status.CopadoStatus__c, status.ExternalValue__c); }
        }
    }
    
    @testvisible
    private static void getStatusXrefForCopado() {
        System.debug('building statusXref');
        statusXRef = new Map<String, String>();
        List<Jira_Status_Mapping_Template__mdt> statusList = [SELECT Copado_Status__c, ExternalValue__c 
                                                              FROM Jira_Status_Mapping_Template__mdt
                                                              WHERE SyncDirection__c='Inbound'];
        
        if(Test.isRunningTest()) { statusXref.put('To Do', 'Approved'); }
        for(Jira_Status_Mapping_Template__mdt status : statusList) {
            if(!statusXRef.containsKey(status.ExternalValue__c)) { statusXref.put(status.ExternalValue__c, status.Copado_Status__c); }
        }
    }
    
    @testvisible
    private static void getStatusXrefForCopado(String storyId) {
        System.debug('building statusXref');
        statusXRef = new Map<String, String>();
        List<JiraStatusMapping__c> statusList = [SELECT CopadoStatus__c, ExternalValue__c 
                                                 FROM JiraStatusMapping__c
                                                 WHERE SyncDirection__c='Inbound'];
        
        if(Test.isRunningTest()) { statusXref.put('To Do', 'Approved'); }
        for(JiraStatusMapping__c status : statusList) {
            if(!statusXRef.containsKey(status.ExternalValue__c)) { statusXref.put(status.ExternalValue__c, status.CopadoStatus__c); }
        }
    }
}