force-app/main/default/objects/X7S_Social_Component_Setting__mdt/X7S_Social_Component_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Settings for the following 7Summits social media applications:  Instagram, Facebook and LinkedIn.</description>
    <label>7S Social Component Setting</label>
    <pluralLabel>7S Social Component Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/X7S_Social_Component_Setting__mdt/fields/Facebook_Featured_Posts__c.field-meta.xml
<CustomField>
    <fullName>Facebook_Featured_Posts__c</fullName>
    <inlineHelpText>Enter comma-separated Facebook post URLs here</inlineHelpText>
    <label>Facebook Featured Posts</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/x7sFacebookFeaturedController.cls
/**
 * Copyright (c) 2020.  7Summits Inc. All rights reserved.
 */

public with sharing class x7sFacebookFeaturedController {

    @AuraEnabled
    public static String getMetaData(String recordLabel){
        System.debug(recordLabel);
        // No PMD for CMT
        X7S_Social_Component_Setting__mdt setting = [SELECT Facebook_Featured_Posts__c FROM X7S_Social_Component_Setting__mdt WHERE DeveloperName = :recordLabel]; //NOPMD
        return setting.Facebook_Featured_Posts__c;
    }
}