force-app/main/default/objects/X7S_Image_Gallery__c/X7S_Image_Gallery__c.object-meta.xml
<CustomObject>
    <description>Object to support Image Gallery records as part of the Expedition Pack accelerator from 7Summits.</description>
    <label>7S Image Gallery</label>
    <nameField>
        <label>7S Image Gallery Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>7S Image Galleries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/X7S_Image_Gallery__c/fields/Default_Image__c.field-meta.xml
<CustomField>
    <fullName>Default_Image__c</fullName>
    <label>Default Image</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/X7S_Image_Gallery_Entry__c/X7S_Image_Gallery_Entry__c.object-meta.xml
<CustomObject>
    <description>Object to support Image Gallery Entry records as part of the Expedition Pack accelerator from 7Summits.</description>
    <label>7S Image Gallery Entry</label>
    <nameField>
        <label>7S Image Gallery Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>7S Image Gallery Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/X7S_Image_Gallery_Entry__c/fields/Image_Description__c.field-meta.xml
<CustomField>
    <fullName>Image_Description__c</fullName>
    <label>Image Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/X7S_Image_Gallery_Entry__c/fields/X7S_Image_Gallery__c.field-meta.xml
<CustomField>
    <fullName>X7S_Image_Gallery__c</fullName>
    <label>X7S Image Gallery</label>
    <referenceTo>X7S_Image_Gallery__c</referenceTo>
    <relationshipLabel>Gallery Entries</relationshipLabel>
    <relationshipName>Gallery_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/x7sExpImageGalleryController.cls
/*
 * Copyright (c) 2020. 7Summits Inc.
 */

public with sharing class x7sExpImageGalleryController {
    public class ExpeditionException extends Exception {}

    @AuraEnabled
    public static x7sExpResponse getImageGallery(String imageGalleryIDString) {
        try {
            List<X7S_Image_Gallery__c> imageGalleries;
            x7sExpResponse response = new x7sExpResponse();

            if (!String.isEmpty(imageGalleryIDString)) {
                imageGalleries = [
                        SELECT Id, Default_Image__c, Description__c,
                            (SELECT Image_URL__c, Sort_Order__c, Image_Description__c
                             FROM Gallery_Entries__r
                             ORDER BY Sort_Order__c ASC)
                        FROM X7S_Image_Gallery__c
                        WHERE Id = :imageGalleryIDString
                        WITH SECURITY_ENFORCED ];
            }

            response.results = imageGalleries;
            return response;
        }
        catch (System.QueryException ex)
        {
            System.debug('getImageGallery()-- EXCEPTION:  ' + ex);
            throw new ExpeditionException(System.Label.x7sExpCRUDAccessDenied);
        }
    }
}