force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/pse__Assignment__c/pse__Assignment__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__AssignmentAndScheduleHelp</customHelpPage>
    <description>Stores information about the allocation of a resource to a project and specifies the bill rate and cost rate for time entered. It references the schedule for a resource and, optionally, a project milestone.</description>
    <label>Assignment</label>
    <nameField>
        <label>Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Assignment__c/fields/pse__Bill_Rate__c.field-meta.xml
<CustomField>
    <fullName>pse__Bill_Rate__c</fullName>
    <inlineHelpText>Enter the hourly bill rate for the resource</inlineHelpText>
    <label>Bill Rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/pse__Assignment__c/fields/pse__Is_Billable__c.field-meta.xml
<CustomField>
    <fullName>pse__Is_Billable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Billable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/pse__Assignment__c/fields/pse__Project__c.field-meta.xml
<CustomField>
    <fullName>pse__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>pse__Proj__c</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Est_Vs_Actuals__c/pse__Est_Vs_Actuals__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__EstimateVsActualsHelp</customHelpPage>
    <description>Compares the estimated and actual hours worked by a resource on an assignment, derived from scheduled hours and entered timecard hours respectively. FinancialForce PSA generates Est Vs Actuals when you create or update assignments and schedules, and when timecard hours are entered for an assignment.</description>
    <label>Est Vs Actuals</label>
    <nameField>
        <label>Est Vs Actuals Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Est Vs Actuals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Est_Vs_Actuals__c/fields/pse__Assignment__c.field-meta.xml
<CustomField>
    <fullName>pse__Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assignment</label>
    <referenceTo>pse__Assignment__c</referenceTo>
    <relationshipLabel>Est Vs Actuals</relationshipLabel>
    <relationshipName>Est_Vs_Actuals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Est_Vs_Actuals__c/fields/pse__Project__c.field-meta.xml
<CustomField>
    <fullName>pse__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>pse__Proj__c</referenceTo>
    <relationshipLabel>Est Vs Actuals</relationshipLabel>
    <relationshipName>Est_Vs_Actuals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/pse__Proj__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__ProjectHelp</customHelpPage>
    <description>Represents a collection of business transactions, activities, and related items to be managed over a defined time range, such as timecards, expenses, milestones, and budgets. Typically, people (represented by Resource records) are assigned to projects, though some projects do not require assignments in order to be staffed. Projects may also have a master project (parent) or a sub project (child) in the project hierarchy, supporting roll-ups of revenues, costs, and time to every project and up through the hierarchy.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Proj__c/fields/pse__Is_Billable__c.field-meta.xml
<CustomField>
    <fullName>pse__Is_Billable__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check if this project is billable to a customer.</inlineHelpText>
    <label>Billable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Stage__c.field-meta.xml
<CustomField>
    <fullName>pse__Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Prepare</fullName>
            </value>
            <value>
                <fullName>Define</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Build</fullName>
            </value>
            <value>
                <fullName>Verify</fullName>
            </value>
            <value>
                <fullName>Launch</fullName>
            </value>
            <value>
                <fullName>Close-Out</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AssignmentRollupHelper_Test.cls
@isTest (SeeAllData=false)
public class AssignmentRollupHelper_Test {
    @testSetup static void setup() {
        ProjectRollupHelpers_Test.setupTestData(new List<String>{'Contact', 'pse__Est_vs_Actuals__c'});
        
    }
    
    @isTest static void testDelete() {
        System.debug('---------------- STARTING testDelete METHOD ----------------');
        AssignmentRollupHelper.isRunning=false;
        TriggerState.resetThisTrigger('x7sAssignmentTrigger');
        TriggerState.resetThisTrigger('pse__Assignment__c');
        pse__Assignment__c assignment = [SELECT Id, pse__Project__c, pse__is_billable__c, pse__Bill_Rate__c FROM pse__Assignment__c LIMIT 1];
        pse__Proj__c project = [SELECT Id, pse__Stage__c FROM pse__Proj__c WHERE Id =: assignment.pse__Project__c];
        
        Test.startTest();
        delete assignment;
        Test.stopTest();
    }
   
    @isTest static void testCompleted() {  
        System.debug('---------------- STARTING testCompleted METHOD ----------------');
        EstVsActualsRollupHelper.isRunning=true;
        
        pse__Assignment__c assignment = [SELECT Id, pse__Project__c, pse__is_billable__c, pse__Bill_Rate__c FROM pse__Assignment__c LIMIT 1];
        pse__Proj__c project = [SELECT Id, pse__Stage__c FROM pse__Proj__c WHERE Id =: assignment.pse__Project__c];
        
        System.debug('---------------- ENTERING INTO TEST ----------------');
        Test.startTest();
        project.pse__Stage__c='Completed';
        update project;
        System.debug('------ updated project: ' + project.Id + '    -------- stage: ' + project.pse__Stage__c);
        AssignmentRollupHelper.isRunning=false;
        TriggerState.resetThisTrigger('x7sAssignmentTrigger');
        update assignment;
        Test.stopTest();
        System.debug('---------------- TEST COMPLETED ----------------');
    } 
   
    @isTest static void testCompletedNB() {
        EstVsActualsRollupHelper.isRunning=true;
        pse__Assignment__c assignment = [SELECT Id, pse__Project__c, pse__is_billable__c, pse__Bill_Rate__c FROM pse__Assignment__c LIMIT 1];
        pse__Proj__c project = [SELECT Id, pse__Stage__c FROM pse__Proj__c WHERE Id =: assignment.pse__Project__c];
        Test.startTest();
        project.pse__Stage__c='Completed';
        update project;
        assignment.pse__is_billable__c=false;
        assignment.pse__Bill_Rate__c=0.0;
        update assignment;
        Test.stopTest();
    } 
    
    @isTest static void testBuildNB() {
        EstVsActualsRollupHelper.isRunning=true;
        pse__Assignment__c assignment = [SELECT Id, pse__Project__c, pse__is_billable__c, pse__Bill_Rate__c FROM pse__Assignment__c LIMIT 1];
        pse__Proj__c project = [SELECT Id, pse__Stage__c FROM pse__Proj__c WHERE Id =: assignment.pse__Project__c];
        Test.startTest();
        project.pse__Stage__c='Build';
        update project;
        assignment.pse__is_billable__c=false;
        assignment.pse__Bill_Rate__c=0.0;
        update assignment;
        Test.stopTest();
    } 

}