force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/GetFeedback_Setting__mdt/GetFeedback_Setting__mdt.object-meta.xml
<CustomObject>
    <label>GetFeedback Setting</label>
    <pluralLabel>GetFeedback Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/GetFeedback_Setting__mdt/fields/EmailFromAddress__c.field-meta.xml
<CustomField>
    <fullName>EmailFromAddress__c</fullName>
    <label>Email From Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/GetFeedback_Setting__mdt/fields/ProjectStages__c.field-meta.xml
<CustomField>
    <fullName>ProjectStages__c</fullName>
    <defaultValue>&apos;Define, Design, Build, Verify, Launch&apos;</defaultValue>
    <description>Stages used to determine projects included in surveys</description>
    <inlineHelpText>Project Stages used when selecting Project Survey Contacts separated by a comma (i.e. Define, Design, Build, Verify, Launch</inlineHelpText>
    <label>Project Stages</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GetFeedback_Setting__mdt/fields/SubjectPrefix__c.field-meta.xml
<CustomField>
    <fullName>SubjectPrefix__c</fullName>
    <label>Subject Prefix</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GetFeedback_Setting__mdt/fields/SurveyLink__c.field-meta.xml
<CustomField>
    <fullName>SurveyLink__c</fullName>
    <label>Survey Link</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/GetFeedback_Setting__mdt/fields/SurveyLinkHTML__c.field-meta.xml
<CustomField>
    <fullName>SurveyLinkHTML__c</fullName>
    <label>Survey Link HTML</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GetFeedback_Setting__mdt/fields/SurveyLinkText__c.field-meta.xml
<CustomField>
    <fullName>SurveyLinkText__c</fullName>
    <label>Survey Link Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProjectSurveyContact__c/ProjectSurveyContact__c.object-meta.xml
<CustomObject>
    <label>Project Survey Contact</label>
    <nameField>
        <displayFormat>PSC-{0000000}</displayFormat>
        <label>Survey Contact</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Survey Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectSurveyContact__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Project Survey Contacts</relationshipLabel>
    <relationshipName>Project_Survey_Contacts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ProjectSurveyContact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Project Survey Contacts</relationshipLabel>
    <relationshipName>Project_Survey_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProjectSurveyContact__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>pse__Proj__c</referenceTo>
    <relationshipLabel>Project Survey Contacts</relationshipLabel>
    <relationshipName>ProjectSurveyContacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ProjectSurveyContact__c/fields/SendSurvey__c.field-meta.xml
<CustomField>
    <fullName>SendSurvey__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Send Survey flag - indicates that the contact is to receive a survey for the project</description>
    <inlineHelpText>Checked: Send a survey for the project to the contact   Unchecked: Do not send a survey for the project to the contact</inlineHelpText>
    <label>Send Survey</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/pse__Proj__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__ProjectHelp</customHelpPage>
    <description>Represents a collection of business transactions, activities, and related items to be managed over a defined time range, such as timecards, expenses, milestones, and budgets. Typically, people (represented by Resource records) are assigned to projects, though some projects do not require assignments in order to be staffed. Projects may also have a master project (parent) or a sub project (child) in the project hierarchy, supporting roll-ups of revenues, costs, and time to every project and up through the hierarchy.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Proj__c/fields/Opp_Project_Type__c.field-meta.xml
<CustomField>
    <fullName>Opp_Project_Type__c</fullName>
    <formula>TEXT(pse__Opportunity__r.Project_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opp Project Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Project_Manager__c.field-meta.xml
<CustomField>
    <fullName>pse__Project_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Person responsible for this project (optional). If not provided, it&apos;s assumed that the record Owner is the project manager.</description>
    <label>Project Manager</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.pse__Is_Resource__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Contact.pse__Is_Resource_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Only active resources are shown. To display all resources, click Show all results.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects Managed</relationshipLabel>
    <relationshipName>ProjectsManaged</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Stage__c.field-meta.xml
<CustomField>
    <fullName>pse__Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Prepare</fullName>
            </value>
            <value>
                <fullName>Define</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Build</fullName>
            </value>
            <value>
                <fullName>Verify</fullName>
            </value>
            <value>
                <fullName>Launch</fullName>
            </value>
            <value>
                <fullName>Close-Out</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SendProjectSurveyNotificationsBatch.cls
global class SendProjectSurveyNotificationsBatch implements Database.batchable<sObject>, Database.Stateful {

    private String projectType;
    
    global SendProjectSurveyNotificationsBatch () {
        this.projectType='New Project';
    }
    
    global SendProjectSurveyNotificationsBatch (String projectType) {
        this.projectType = projectType;
    }
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        GetFeedback_Setting__mdt gfSetting = [SELECT ProjectStages__c FROM GetFeedback_Setting__mdt WHERE DeveloperName='Project_Survey'];
        
        System.debug('--------> projectType: ' + projectType);
        
        List<String> stages = gfSetting.ProjectStages__c.split(',');
        String query = 'SELECT Id, Project__c, Account__c, Contact__c, Contact__r.Email, Contact__r.FirstName, Project__r.pse__Project_Manager__r.Title, ' +

            'Contact__r.Lastname, Project__r.pse__Project_Manager__r.Name, Project__r.Name, Project__r.pse__Project_Manager__c, Project__r.pse__Project_Manager__r.Email ' +

            'FROM ProjectSurveyContact__c WHERE SendSurvey__c = true AND Project__r.pse__Stage__c IN : stages AND Project__r.Opp_Project_Type__c =: projectType';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bc, List<ProjectSurveyContact__c> contacts) {
        List<Messaging.SingleEmailMessage> allMsg = new List<Messaging.SingleEmailMessage>();
        GetFeedback_Setting__mdt gfSetting = [SELECT EmailTemplateName__c, SurveyLink__c, EmailFromAddress__c, SurveyLinkText__c, SurveyLinkHTML__c, SubjectPrefix__c 
                                              FROM GetFeedback_Setting__mdt WHERE DeveloperName='Project_Survey'];
        
        OrgWideEmailAddress[] owea = [select Id from OrgWideEmailAddress where Address =: gfSetting.EmailFromAddress__c];
        
        EmailTemplate et = [SELECT Id, Subject, Body, HTMLValue FROM EmailTemplate WHERE DeveloperName =: gfSetting.EmailTemplateName__c];
        
        for(ProjectSurveyContact__c contact : contacts) {
            List<string> toAddress = new List<string>();
            toAddress.add(contact.Contact__r.Email);
            
            String surveyLink = gfSetting.SurveyLink__c.replace('###ACCOUNT###', contact.Account__c);
            surveyLink = surveyLink.replace('###CONTACT###', contact.Contact__c);
            surveyLink = surveyLink.replace('###PROJECT###', contact.Project__c);
            
            String body = et.Body;

            body = body.replace('###SURVEYLINK###', surveyLink);
            body = body.replace('###FIRSTNAME###', contact.Contact__r.FirstName);
            body = body.replace('###PROJECTMANAGER###', contact.Project__r.pse__Project_Manager__r.Name);
            body = body.replace('###PMCONTACTID###', contact.Project__r.pse__Project_Manager__c);
            
            String htmlBody = et.HTMLValue;

            htmlBody = et.HTMLValue.replace('###SURVEYLINKTEXT###', '<a href=\'' + surveyLink + '\'>' + gfSetting.SurveyLinkText__c + '</a>');
            
            htmlBody = htmlBody.replace('###SURVEYBUTTONIMAGE###', '<a href=\'' + surveyLink + '\'>' + gfSetting.SurveyLinkHTML__c + '</a>');
			htmlBody = htmlBody.replace('###FIRSTNAME###', contact.Contact__r.FirstName);            
            htmlBody = htmlBody.replace('###PROJECTMANAGER###', contact.Project__r.pse__Project_Manager__r.Name);
            htmlBody = htmlBody.replace('###PMTITLE###', contact.Project__r.pse__Project_Manager__r.Title);
            htmlBody = htmlBody.replace('###PMCONTACTID###', contact.Project__r.pse__Project_Manager__c);
            htmlBody = htmlBody.replace('<![CDATA[','');
            htmlBody = htmlBody.replace(']]>','');
            
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            if ( owea.size() > 0 ) {
                mail.setOrgWideEmailAddressId(owea.get(0).Id);
            }
            mail.setTemplateId(et.Id);
            mail.setToAddresses(toAddress);

            mail.setReplyTo(contact.Project__r.pse__Project_Manager__r.Email);

            mail.setHtmlBody(htmlBody);
            mail.setPlainTextBody(body);
            mail.setSubject(gfSetting.SubjectPrefix__c + contact.Project__r.Name.replace('-Pr',''));
            mail.setTargetObjectId(contact.Contact__c);
            mail.setWhatId(contact.Contact__c);
            mail.setSaveAsActivity(false);
            mail.setUseSignature(false);
            
            allMsg.add(mail);
        }
        
        if(!allMsg.isEmpty()) { Messaging.sendEmail(allMsg); }
    }
    
    global void finish(Database.BatchableContext BC) {
    }
}