force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/ProjectSurveyContact__c/ProjectSurveyContact__c.object-meta.xml
<CustomObject>
    <label>Project Survey Contact</label>
    <nameField>
        <displayFormat>PSC-{0000000}</displayFormat>
        <label>Survey Contact</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Survey Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectSurveyContact__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Project Survey Contacts</relationshipLabel>
    <relationshipName>Project_Survey_Contacts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ProjectSurveyContact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Project Survey Contacts</relationshipLabel>
    <relationshipName>Project_Survey_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProjectSurveyContact__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>pse__Proj__c</referenceTo>
    <relationshipLabel>Project Survey Contacts</relationshipLabel>
    <relationshipName>ProjectSurveyContacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ProjectSurveyContact__c/fields/SendSurvey__c.field-meta.xml
<CustomField>
    <fullName>SendSurvey__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Send Survey flag - indicates that the contact is to receive a survey for the project</description>
    <inlineHelpText>Checked: Send a survey for the project to the contact   Unchecked: Do not send a survey for the project to the contact</inlineHelpText>
    <label>Send Survey</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/pse__Proj__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__ProjectHelp</customHelpPage>
    <description>Represents a collection of business transactions, activities, and related items to be managed over a defined time range, such as timecards, expenses, milestones, and budgets. Typically, people (represented by Resource records) are assigned to projects, though some projects do not require assignments in order to be staffed. Projects may also have a master project (parent) or a sub project (child) in the project hierarchy, supporting roll-ups of revenues, costs, and time to every project and up through the hierarchy.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Proj__c/fields/pse__Account__c.field-meta.xml
<CustomField>
    <fullName>pse__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProjectSurveyContactController.cls
public class ProjectSurveyContactController {

    public class ProjectSurveyContact {
        public String recId { get; set; }
        public String project { get; set; }
        public String account { get; set; }
        public String contact { get; set; }
        public String contactName { get; set; }
        public boolean sendSurvey { get; set; }
    }
    public List<ProjectSurveyContact> contacts { get; set; }
    public pse__Proj__c currentProject { get; set; }
    private String projectRecordId;
    
    public ProjectSurveyContactController(ApexPages.standardController controller) {
        ProjectSurveyContact__c projectIn = (ProjectSurveyContact__c)controller.getRecord();
        projectRecordId = projectIn.Project__c;
        if(projectRecordId == null) { projectRecordId=ApexPages.currentPage().getParameters().get('projectId'); }
        System.debug('ProjectId: ' + projectRecordId);
        
        currentProject = [SELECT Id, pse__Account__c, Name, pse__Account__r.Name FROM pse__Proj__c WHERE Id =: projectRecordId];
        List<Contact> accountContacts = [SELECT Id, Name FROM Contact WHERE AccountId =: currentProject.pse__Account__c ORDER By Name];
        List<ProjectSurveyContact__c> existingContacts = [SELECT Id, Project__c, Account__c, Contact__c, SendSurvey__c 
                                                  FROM ProjectSurveyContact__c WHERE Project__c = : currentProject.Id];
        
        System.debug('accountContacts: ' + accountContacts);
        System.debug('existingContacts: ' + existingContacts);
        
        Map<Id, ProjectSurveyContact__c> contactMap = new Map<Id, ProjectSurveyContact__c>();
        for(ProjectSurveyContact__c psc : existingContacts) {
            if(!contactMap.containsKey(psc.Contact__c)) { contactMap.put(psc.Contact__c, psc); }
        }
        
		contacts = new List<ProjectSurveyContact>();
        for(Contact c : accountContacts) {
            ProjectSurveyContact newPSC = new ProjectSurveyContact();
            newPsc.project=projectRecordId;
            newPsc.account=currentProject.pse__Account__c;
            newPsc.contact=c.Id;
            newPsc.contactName=c.Name;
            if(contactMap.containsKey(c.Id)) { 
                newPsc.recId = contactMap.get(c.Id).Id;
                newPsc.sendSurvey = contactMap.get(c.Id).SendSurvey__c;
            }
            contacts.add(newPSC);
        }
        
        System.debug('contacts: ' + contacts);
        
    }
    
    public PageReference save() {
        List<ProjectSurveyContact__c> projectContacts = new List<ProjectSurveyContact__c>();
        for(ProjectSurveyContact pscContact : contacts) {
            if(pscContact.sendSurvey == true || pscContact.RecId != null) {
                projectContacts.add(new ProjectSurveyContact__c (Id=pscContact.recId,
                                                                 Project__c=pscContact.project,
                                                                 Account__c=pscContact.account,
                                                                 Contact__c=pscContact.contact,
                                                                 SendSurvey__c=pscContact.sendSurvey));
            } 
        }
        
        System.debug(projectContacts);
        upsert projectContacts;
        
        return new PageReference('/' + projectRecordId);
    }
    
    public PageReference cancel() {
        return new PageReference('/' + projectRecordId);
    }
}