force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Project_Type__c.field-meta.xml
<CustomField>
    <fullName>Project_Type__c</fullName>
    <label>Project Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Project</fullName>
            </value>
            <value>
                <fullName>Change Order</fullName>
            </value>
            <value>
                <fullName>IP Only</fullName>
            </value>
            <value>
                <fullName>Customer Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/pse__Parent_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>pse__Parent_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Child Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Quota_Name__c.field-meta.xml
<CustomField>
    <fullName>Quota_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quota Detail</label>
    <referenceTo>Quota_Detail__c</referenceTo>
    <relationshipLabel>Opportunities (Quota Detail)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Solution_Primary_Audience__c.field-meta.xml
<CustomField>
    <fullName>Solution_Primary_Audience__c</fullName>
    <inlineHelpText>Choose the option that reflects the primary audience for this Opportunity</inlineHelpText>
    <label>Solution Primary Audience</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Team_Recognition__c.field-meta.xml
<CustomField>
    <fullName>Team_Recognition__c</fullName>
    <description>Recognition of those who helped close the opportunity.</description>
    <inlineHelpText>Provide recognition for the team, calling out specific team players, client expectations exceeded, etc.</inlineHelpText>
    <label>Team Recognition</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/OpportunityRollupHelper_Test.cls
@isTest
public class OpportunityRollupHelper_Test {
    @testSetup static void setup() {
        ProjectRollupHelpers_Test.setupTestData(new List<String>{'Contact'});
    }

    @isTest static void testOpportunityTrigger() {
        Opportunity opp = [SELECT Id, Quota_Name__c, AccountId FROM Opportunity WHERE Name='test opp' LIMIT 1];
        System.debug('-------- opp: ' + opp);
        List<Opportunity> monthlyOpps = new List<Opportunity>();
        for(integer x=1;x<=12;x++) {
            Date closedDate=Date.newInstance(System.today().year(), x, 1);
            monthlyOpps.add(new Opportunity(Name='test opp-'+x, AccountId=opp.AccountId, Amount=100.0, StageName='Closed Won', CloseDate=closedDate, Description='Opportunity',
                                          Solution_Primary_Audience__c='Customer', Quota_Name__c=opp.Quota_Name__c, pse__Parent_Opportunity__c=opp.Id, Project_Type__c='Change Order',
                                           Team_Recognition__c='Amazing Job!'));
        }
        
        Test.startTest();
        insert monthlyOpps;
        Test.stopTest();
    }    
}