force-app/main/default/objects/X7S_Files_Criteria__mdt/X7S_Files_Criteria__mdt.object-meta.xml
<CustomObject>
    <description>Criteria for 7S Files accelerator from 7Summits.</description>
    <label>7S Files Criteria</label>
    <pluralLabel>7S Files Criteria</pluralLabel>
</CustomObject>

force-app/main/default/objects/X7S_Files_Criteria__mdt/fields/API_Name__c.field-meta.xml
<CustomField>
    <fullName>API_Name__c</fullName>
    <description>Criteria field api name (object.field)</description>
    <inlineHelpText>Criteria field api name (object.field)</inlineHelpText>
    <label>API Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/X7S_Files_Criteria__mdt/fields/Field_Type__c.field-meta.xml
<CustomField>
    <fullName>Field_Type__c</fullName>
    <label>Field Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>text</fullName>
                <default>true</default>
                <label>text</label>
            </value>
            <value>
                <fullName>number</fullName>
            </value>
            <value>
                <fullName>date</fullName>
            </value>
            <value>
                <fullName>picklist</fullName>
            </value>
            <value>
                <fullName>checkbox</fullName>
            </value>
            <value>
                <fullName>multi-picklist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/X7S_Files_Criteria__mdt/fields/Field_Value__c.field-meta.xml
<CustomField>
    <fullName>Field_Value__c</fullName>
    <description>Field value to use as the second operand to evaluate the visibility expression. Use TODAY in a date
			type expression.</description>
    <inlineHelpText>Field value to use as the second operand to evaluate the visibility expression. Use TODAY in a
			date type expression.</inlineHelpText>
    <label>Field Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/X7S_Files_Criteria__mdt/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <label>Operator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Equals</fullName>
                <default>true</default>
                <label>Equals</label>
            </value>
            <value>
                <fullName>NotEquals</fullName>
            </value>
            <value>
                <fullName>GreaterThan</fullName>
            </value>
            <value>
                <fullName>GreaterEqual</fullName>
            </value>
            <value>
                <fullName>LessThan</fullName>
            </value>
            <value>
                <fullName>LessEqual</fullName>
            </value>
            <value>
                <fullName>Includes</fullName>
            </value>
            <value>
                <fullName>Excludes</fullName>
            </value>
            <value>
                <fullName>Contains</fullName>
            </value>
            <value>
                <fullName>NotContains</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/X7S_Files_Criteria_Set__mdt/X7S_Files_Criteria_Set__mdt.object-meta.xml
<CustomObject>
    <description>Criteria set for 7S Files accelerator from 7Summits.</description>
    <label>7S Files Criteria Set</label>
    <pluralLabel>7S Files Criteria Sets</pluralLabel>
</CustomObject>

force-app/main/default/objects/X7S_Files_Criteria_Set__mdt/fields/Custom_Logic__c.field-meta.xml
<CustomField>
    <fullName>Custom_Logic__c</fullName>
    <description>Specify share logic. Eg. 1 OR 2</description>
    <inlineHelpText>Specify the share logic to apply to the assigned sharing criteria for this criteria set.</inlineHelpText>
    <label>Custom Logic</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/X7S_Files_Criteria_Set__mdt/fields/Default_Logic__c.field-meta.xml
<CustomField>
    <fullName>Default_Logic__c</fullName>
    <defaultValue>&quot;AND&quot;</defaultValue>
    <inlineHelpText>Default Logic:
All of the conditions are met (AND)
Any of the conditions are met (OR)
Customize the logic</inlineHelpText>
    <label>Default Logic</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AND</fullName>
                <default>true</default>
                <label>AND</label>
            </value>
            <value>
                <fullName>OR</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/X7S_Files_Criteria_Set_Assignment__mdt/X7S_Files_Criteria_Set_Assignment__mdt.object-meta.xml
<CustomObject>
    <description>Criteria set assignment for 7S Files accelerator from 7Summits.</description>
    <label>7S Files Criteria Set Assignment</label>
    <pluralLabel>7S Files Criteria Set Assignments</pluralLabel>
</CustomObject>

force-app/main/default/objects/X7S_Files_Criteria_Set_Assignment__mdt/fields/Logic_Id__c.field-meta.xml
<CustomField>
    <fullName>Logic_Id__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Assignment ID for Share Logic configuration</inlineHelpText>
    <label>Logic Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/X7S_Files_Criteria_Set_Assignment__mdt/fields/X7S_Files_Criteria__c.field-meta.xml
<CustomField>
    <fullName>X7S_Files_Criteria__c</fullName>
    <description>Related criteria field</description>
    <inlineHelpText>Related criteria field</inlineHelpText>
    <label>7S Files Criteria</label>
    <referenceTo>X7S_Files_Criteria__mdt</referenceTo>
    <relationshipLabel>7S Files Criteria Set Assignments</relationshipLabel>
    <relationshipName>X7S_Files_Criteria_Set_Assignments</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/X7S_Files_Criteria_Set_Assignment__mdt/fields/X7S_Files_Criteria_Set__c.field-meta.xml
<CustomField>
    <fullName>X7S_Files_Criteria_Set__c</fullName>
    <description>Related criteria set</description>
    <inlineHelpText>Related criteria set</inlineHelpText>
    <label>7S Files Criteria Set</label>
    <referenceTo>X7S_Files_Criteria_Set__mdt</referenceTo>
    <relationshipLabel>7S Files Criteria Set Assignments</relationshipLabel>
    <relationshipName>X7S_Files_Criteria_Set_Assignments</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/classes/x7sFilesCriteriaController.cls
/*
 * Copyright (c) 2021. 7Summits, an IBM Company. All rights reserved.
 */

public with sharing class x7sFilesCriteriaController {
	private static final String DEFAULT_LOGIC = 'AND';

	public static x7sFilesCriteriaListModel getCriteriaListModel(String fileCriteriaSet) {
		if (String.isNotBlank(fileCriteriaSet)) {
			try {
				x7sFilesCriteriaListModel criteriaListModel = new x7sFilesCriteriaListModel();
				criteriaListModel.id = fileCriteriaSet;

				X7S_Files_Criteria_Set__mdt criteriaAssignment =  X7S_Files_Criteria_Set__mdt.getInstance(fileCriteriaSet);
				criteriaListModel.defaultLogic = criteriaAssignment.Default_Logic__c != null ? criteriaAssignment.Default_Logic__c : DEFAULT_LOGIC;
				criteriaListModel.customLogic = criteriaAssignment.Custom_Logic__c;

				List<X7S_Files_Criteria_Set_Assignment__mdt> criteriaSetAssignment = X7S_Files_Criteria_Set_Assignment__mdt.getAll().values();

				for (X7S_Files_Criteria_Set_Assignment__mdt criteriaItem : criteriaSetAssignment) {

					if (criteriaItem.X7S_Files_Criteria_Set__c == fileCriteriaSet) {
						if (criteriaSetAssignment.size() > 0) {
							List<X7S_Files_Criteria_Set__mdt> criteriaSet = X7S_Files_Criteria_Set__mdt.getAll().values();

							for (X7S_Files_Criteria_Set__mdt criteria : criteriaSet) {
								if (criteria.Id == criteriaItem.X7S_Files_Criteria_Set__c) {
									X7S_Files_Criteria__mdt criteriaField = X7S_Files_Criteria__mdt.getInstance(criteriaItem.X7S_Files_Criteria__c);

									if (criteriaField != null && String.isNotBlank(criteriaField.API_Name__c)) {
										criteriaListModel.criteriaFieldList.add(setCriteriaFieldModel(criteriaItem.X7S_Files_Criteria__c, criteriaItem.Logic_Id__c, criteriaField));
									}
								}
							}
						}
					}
				}

				criteriaListModel.criteriaFieldList.sort();
				//System.debug('criteriaListModel----' + criteriaListModel);
				return criteriaListModel;
			}
			catch (QueryException ex) {
				System.debug('Error getting Criteria set assignment: ' + ex.getMessage());
			}
		}

		return null;
	}

	private static x7sFilesCriteriaFieldModel setCriteriaFieldModel(String id, Decimal logicId, X7S_Files_Criteria__mdt criteriaField) {
		x7sFilesCriteriaFieldModel model = new x7sFilesCriteriaFieldModel();

		if (criteriaField.API_Name__c != null) {
			model.id = id;
			model.logicId = logicId;
			model.fieldName = criteriaField.API_Name__c;
			model.fieldValue = criteriaField.Field_Value__c;
			model.operator = criteriaField.Operator__c;
			model.type = criteriaField.Field_Type__c;
		}

		return model;
	}
}